srsgnb::dmrs_pdcch_processor_impl
constexpr unsigned srsgnb::dmrs_pdcch_processor_impl::STRIDE
Defines the DMRS index increment in frequency domain.
constexpr unsigned srsgnb::dmrs_pdcch_processor_impl::OFFSET
Defines the DMRS index offset in a resource block.
constexpr unsigned srsgnb::dmrs_pdcch_processor_impl::NOF_DMRS_PER_RB
Defines the number of DMRS per active resource block.
Referenced by sequence_generation, map.
constexpr unsigned srsgnb::dmrs_pdcch_processor_impl::MAX_NOF_DMRS_PER_SYMBOL
Defines the maximum number of DMRS for PDCCH that can be found in a symbol.
std::unique_ptr<pseudo_random_generator> srsgnb::dmrs_pdcch_processor_impl::prg
Pseudo-random sequence generator instance.
Referenced by sequence_generation.
unsigned dmrs_pdcch_processor_impl::c_init(unsigned symbol, const config_t &config)
Computes the initial pseudo-random state.
symbol Denotes the symbol index. config Provides the required parameters. The initial pseudo-random state.
References srsgnb::dmrs_pdcch_processor::config_t::slot, srsgnb::slot_point::slot_index, srsgnb::dmrs_pdcch_processor::config_t::n_id, srsgnb::get_nsymb_per_slot, srsgnb::dmrs_pdcch_processor::config_t::cp, srsgnb::pow2.
Referenced by sequence_generation.
void dmrs_pdcch_processor_impl::sequence_generation(span< cf_t > sequence, unsigned symbol, const config_t &config) const
Sequence generation as per TS 38.211 Section 7.4.1.3.1.
This method generates the sequence described in TS 38.211 Section 7.4.1.3.1, considering the only values required to fill the resource blocks according to TS 38.211 Section 7.3.2. sequence Provides the sequence destination. symbol Denotes the symbol index. config Provides the required parameters to calculate the sequences.
References prg, c_init, srsgnb::dmrs_sequence_generate, srsgnb::dmrs_pdcch_processor::config_t::amplitude, srsgnb::dmrs_pdcch_processor::config_t::reference_point_k_rb, NOF_DMRS_PER_RB, srsgnb::dmrs_pdcch_processor::config_t::rb_mask.
Referenced by map.
void dmrs_pdcch_processor_impl::mapping(resource_grid_writer &grid, span< const cf_t > sequence, unsigned rg_subc_mask_ref, span< const bool > rg_subc_mask, unsigned symbol, const static_vector< uint8_t, MAX_PORTS > &ports)
Mapping to physical resources as per TS 38.211 Section 7.4.1.3.2.
This method implements the signal mapping as described in TS 38.211 Section 7.4.1.3.2. grid Destination resource grid. sequence Sequence to write in the resource grid. rg_subc_mask_ref Subcarrier index in the resource grid of the mask first element. rg_subc_mask Indicates the subcarriers where sequence is mapped onto. symbol Denotes the OFDM symbol index within the slot. ports Port list.
References srsgnb::resource_grid_writer::put.
Referenced by map.
srsgnb::dmrs_pdcch_processor_impl::dmrs_pdcch_processor_impl(std::unique_ptr< pseudo_random_generator > prg_)
void dmrs_pdcch_processor_impl::map(resource_grid_writer &grid, const config_t &config) override
Generates and maps DMRS for PDCCH according to TS 38.211 section 7.4.1.3.
grid Provides the destination resource grid. config Provides the required configuration to generate and map the signal.
References srsgnb::dmrs_pdcch_processor::config_t::rb_mask, srsgnb::bounded_bitset< N, reversed >::count, NOF_DMRS_PER_RB, srsgnb::get_rg_subc_mask_reference, srsgnb::get_rg_subc_mask, srsgnb::dmrs_pdcch_processor::config_t::start_symbol_index, srsgnb::dmrs_pdcch_processor::config_t::duration, sequence_generation, mapping, srsgnb::dmrs_pdcch_processor::config_t::ports.