srsgnb::channel_estimate
float srsgnb::channel_estimate::get_noise_variance(unsigned rx_port, unsigned tx_layer=0) const
Returns the estimated noise variance for the path between the given Rx port and Tx layer (dB scale).
References noise_variance, path_to_index.
Referenced by get_noise_variance_dB.
float srsgnb::channel_estimate::get_noise_variance_dB(unsigned rx_port, unsigned tx_layer=0) const
Returns the estimated noise variance for the path between the given Rx port and Tx layer (dB scale).
References srsgnb::convert_power_to_dB, get_noise_variance.
float srsgnb::channel_estimate::get_rsrp(unsigned rx_port, unsigned tx_layer=0) const
Returns the estimated RSRP for the path between the given Rx port and Tx layer (linear scale).
References rsrp, path_to_index.
Referenced by get_rsrp_dB.
float srsgnb::channel_estimate::get_rsrp_dB(unsigned rx_port, unsigned tx_layer=0) const
Returns the estimated RSRP for the path between the given Rx port and Tx layer (dB scale).
References srsgnb::convert_power_to_dB, get_rsrp.
float srsgnb::channel_estimate::get_epre(unsigned rx_port, unsigned tx_layer=0) const
Returns the average EPRE for the path between the given Rx port and Tx layer (linear scale).
References epre, path_to_index.
Referenced by get_epre_dB.
float srsgnb::channel_estimate::get_epre_dB(unsigned rx_port, unsigned tx_layer=0) const
Returns the average EPRE for the path between the given Rx port and Tx layer (dB scale).
References srsgnb::convert_power_to_dB, get_epre.
float srsgnb::channel_estimate::get_snr(unsigned rx_port, unsigned tx_layer=0) const
Returns the estimated SNR for the path between the given Rx port and Tx layer (linear scale).
References snr, path_to_index.
Referenced by get_snr_dB.
float srsgnb::channel_estimate::get_snr_dB(unsigned rx_port, unsigned tx_layer=0) const
Returns the estimated SNR for the path between the given Rx port and Tx layer (dB scale).
References srsgnb::convert_power_to_dB, get_snr.
span<cf_t> srsgnb::channel_estimate::get_path_ch_estimate(unsigned rx_port, unsigned tx_layer=0)
Returns a read-write view to the RE channel estimates of the path between the given Rx port and Tx layer.
The view is represented as a vector indexed by i) subcarriers and ii) OFDM symbols.
References nof_subcarriers, nof_symbols, nof_rx_ports, ce, srsgnb::span< T >::subspan.
span<const cf_t> srsgnb::channel_estimate::get_path_ch_estimate(unsigned rx_port, unsigned tx_layer=0) const
Returns a read-only view to the RE channel estimates of the path between the given Rx port and Tx layer.
The view is represented as a vector indexed by i) subcarriers and ii) OFDM symbols.
References nof_subcarriers, nof_symbols, nof_rx_ports, ce, srsgnb::span< T >::subspan.
void srsgnb::channel_estimate::set_noise_variance(float var_val, unsigned rx_port, unsigned tx_layer=0)
Sets the estimated RSRP for the path between the given Rx port and Tx layer (linear scale).
References noise_variance, path_to_index.
void srsgnb::channel_estimate::set_rsrp(float rsrp_val, unsigned rx_port, unsigned tx_layer=0)
Sets the estimated RSRP for the path between the given Rx port and Tx layer (linear scale).
References rsrp, path_to_index.
void srsgnb::channel_estimate::set_epre(float epre_val, unsigned rx_port, unsigned tx_layer=0)
Sets the average EPRE for the path between the given Rx port and Tx layer (linear scale).
References epre, path_to_index.
void srsgnb::channel_estimate::set_snr(float snr_val, unsigned rx_port, unsigned tx_layer=0)
Sets the estimated SNR for the path between the given Rx port and Tx layer (linear scale).
References snr, path_to_index.
void srsgnb::channel_estimate::set_ch_estimate(float ce_val, unsigned subcarrier, unsigned symbol, unsigned rx_port=0, unsigned tx_layer=0)
Sets the channel estimate for the resource element at the given coordinates.
References coords_to_index, ce.
std::vector<float> srsgnb::channel_estimate::noise_variance
Estimated reference signal received powers (linear scale).
Referenced by channel_estimate, get_noise_variance, set_noise_variance.
std::vector<float> srsgnb::channel_estimate::rsrp
Estimated reference signal received powers (linear scale).
Referenced by channel_estimate, get_rsrp, set_rsrp.
std::vector<float> srsgnb::channel_estimate::epre
Average energies per resource element (linear scale).
Referenced by channel_estimate, get_epre, set_epre.
std::vector<float> srsgnb::channel_estimate::snr
Estimated signal-to-noise ratios (linear scale).
Referenced by channel_estimate, get_snr, set_snr.
constexpr unsigned srsgnb::channel_estimate::MAX_RX_PORTS
Maximum supported number of receive ports.
Referenced by channel_estimate.
constexpr unsigned srsgnb::channel_estimate::MAX_TX_LAYERS
Maximum supported number of transmission layers.
Referenced by channel_estimate.
constexpr unsigned srsgnb::channel_estimate::MAX_TX_RX_PATHS
Maximum number of transmitreceive paths.
Referenced by channel_estimate.
constexpr unsigned srsgnb::channel_estimate::MAX_BUFFER_SIZE
Maximum total number of REs in a channel estimate.
Referenced by channel_estimate.
unsigned srsgnb::channel_estimate::nof_subcarriers
Number of subcarriers considered for channel estimation.
Referenced by get_path_ch_estimate, coords_to_index.
unsigned srsgnb::channel_estimate::nof_symbols
Number of OFDM symbols considered for channel estimation.
Referenced by get_path_ch_estimate, coords_to_index.
unsigned srsgnb::channel_estimate::nof_rx_ports
Number of receive ports.
Referenced by get_path_ch_estimate, path_to_index, coords_to_index.
std::vector<cf_t> srsgnb::channel_estimate::ce
Container for channel estimates.
The channel estimate should be thought as four-dimensional tensor with dimensions representing, in order, subcarriers, OFDM symbols, receive ports and, finally, transmit layers. However, it is represented as a single vector, indexed in the same order: i) subcarriers, ii) OFDM symbols, iii) Rx ports, and iv) Tx layers.
Referenced by channel_estimate, get_path_ch_estimate, set_ch_estimate.
srsgnb::channel_estimate::channel_estimate(const channel_estimate_dimensions &dims)
Constructor: sets the size of the internal buffers.
References srsgnb::channel_estimate::channel_estimate_dimensions::nof_prb, srsgnb::MAX_RB, srsgnb::channel_estimate::channel_estimate_dimensions::nof_symbols, srsgnb::MAX_NSYMB_PER_SLOT, srsgnb::channel_estimate::channel_estimate_dimensions::nof_rx_ports, MAX_RX_PORTS, srsgnb::channel_estimate::channel_estimate_dimensions::nof_tx_layers, MAX_TX_LAYERS, srsgnb::NRE, ce, MAX_BUFFER_SIZE, noise_variance, MAX_TX_RX_PATHS, epre, rsrp, snr.
srsgnb::channel_estimate::~channel_estimate()=default
Default destructor.
void srsgnb::channel_estimate::resize(const channel_estimate_dimensions &dims)
unsigned srsgnb::channel_estimate::path_to_index(unsigned rx_port, unsigned tx_layer=0) const
Transforms a port-layer pair into a linear index.
References nof_rx_ports.
Referenced by get_noise_variance, get_rsrp, get_epre, get_snr, set_noise_variance, set_rsrp, set_epre, set_snr.
unsigned srsgnb::channel_estimate::coords_to_index(unsigned subcarrier, unsigned symbol, unsigned rx_port=0, unsigned tx_layer=0) const
Transforms a four-dimensional coordinate into a linear index.
References nof_subcarriers, nof_symbols, nof_rx_ports.
Referenced by set_ch_estimate.