srsgnb::byte_buffer_writer
byte_buffer* srsgnb::byte_buffer_writer::buffer
srsgnb::byte_buffer_writer::byte_buffer_writer(byte_buffer &other)
byte_buffer_view srsgnb::byte_buffer_writer::view() const
Obtain a range view to the bytes pointed by the reader.
Referenced by srsgnb::bit_encoder::data.
void srsgnb::byte_buffer_writer::append(byte_buffer_view bytes)
Appends bytes.
References srsgnb::byte_buffer::append.
Referenced by srsgnb::bit_encoder::pack, srsgnb::bit_encoder::pack_bytes.
void srsgnb::byte_buffer_writer::append(const std::initializer_list< uint8_t > &bytes)
Appends initializer list of bytes.
References srsgnb::byte_buffer::append.
void srsgnb::byte_buffer_writer::append(span< const uint8_t > bytes)
Appends span of bytes.
References srsgnb::byte_buffer::append.
void srsgnb::byte_buffer_writer::append(uint8_t byte)
Appends single byte.
References srsgnb::byte_buffer::append.
void srsgnb::byte_buffer_writer::append_zeros(size_t nof_zeros)
uint8_t& srsgnb::byte_buffer_writer::back()
Checks last appended byte.
Referenced by srsgnb::bit_encoder::pack.
size_t srsgnb::byte_buffer_writer::length() const
Number of bytes in the byte_buffer.
References srsgnb::byte_buffer::length.
Referenced by srsgnb::bit_encoder::nof_bytes, srsgnb::bit_encoder::nof_bits.
bool srsgnb::byte_buffer_writer::empty() const
Checks whether any byte has been written.
References srsgnb::byte_buffer::empty.