srsgnb::detail::manual_event_common
void* srsgnb::detail::manual_event_common::state
srsgnb::detail::manual_event_common::manual_event_common()=default
srsgnb::detail::manual_event_common::manual_event_common(const manual_event_common &event_)=delete
manual_event_common& srsgnb::detail::manual_event_common::operator=(const manual_event_common &event_)=delete
srsgnb::detail::manual_event_common::~manual_event_common()
void srsgnb::detail::manual_event_common::reset()
Resets event state.
References is_set.
bool srsgnb::detail::manual_event_common::is_set() const
Check if event value is set.
Referenced by reset, flush, srsgnb::manual_event< result_type >::get.
void srsgnb::detail::manual_event_common::flush()
triggers all awaiting coroutines after event is set
References is_set.
Referenced by srsgnb::manual_event< result_type >::set.