srsgnb::lower_phy_impl
constexpr unsigned srsgnb::lower_phy_impl::NOF_RG_BUFFER
Number of resource grid buffers.
srslog::basic_logger& srsgnb::lower_phy_impl::logger
Logger.
Referenced by process_symbol, realtime_process_loop, handle_resource_grid, lower_phy_impl, start, stop, request_uplink_slot.
baseband_gateway_transmitter& srsgnb::lower_phy_impl::transmitter
Baseband gateway transmitter.
Referenced by process_dl_symbol.
baseband_gateway_receiver& srsgnb::lower_phy_impl::receiver
Baseband gateway receiver.
Referenced by process_ul_symbol.
lower_phy_rx_symbol_notifier& srsgnb::lower_phy_impl::rx_symbol_notifier
Receive symbol handler.
Referenced by process_ul_symbol.
lower_phy_timing_notifier& srsgnb::lower_phy_impl::timing_notifier
Timing boundary handler.
Referenced by process_symbol.
lower_phy_error_notifier& srsgnb::lower_phy_impl::error_notifier
Error handler.
Referenced by process_dl_symbol.
circular_array<lower_phy_rg_buffer<const resource_grid_reader>, NOF_RG_BUFFER> srsgnb::lower_phy_impl::dl_rg_buffers
Container for downlink resource grids buffers. Each entry belongs to a slot.
Referenced by process_dl_symbol, process_symbol, handle_resource_grid, lower_phy_impl.
circular_array<lower_phy_rg_buffer<resource_grid>, NOF_RG_BUFFER> srsgnb::lower_phy_impl::ul_rg_buffers
Container for uplink resource grids buffers. Each entry belongs to a slot.
Referenced by process_ul_symbol, process_symbol, lower_phy_impl, request_uplink_slot.
std::vector<baseband_gateway_buffer_dynamic> srsgnb::lower_phy_impl::radio_buffers
Container for radio baseband buffers for each stream. Common for transmit and receive. The number of entries indicates the number of streams.
Referenced by process_ul_symbol, process_dl_symbol, lower_phy_impl.
std::vector<baseband_gateway_receiver::metadata> srsgnb::lower_phy_impl::receive_metadata
Container for radio receive metadata for each stream. The number of entries indicates the number of streams.
Referenced by process_ul_symbol, lower_phy_impl.
std::vector<std::unique_ptr<ofdm_symbol_modulator> > srsgnb::lower_phy_impl::modulators
Container for OFDM modulators. Each entry belongs to a different sector.
Referenced by process_ul_symbol, process_dl_symbol, lower_phy_impl.
std::vector<std::unique_ptr<ofdm_symbol_demodulator> > srsgnb::lower_phy_impl::demodulators
Container for OFDM demodulators. Each entry belongs to a different sector.
Referenced by process_ul_symbol, lower_phy_impl.
std::unique_ptr<prach_processor> srsgnb::lower_phy_impl::prach_proc
PRACH processor.
Referenced by process_ul_symbol, lower_phy_impl, request_prach_window.
const baseband_gateway_timestamp srsgnb::lower_phy_impl::rx_to_tx_delay
Receive-to-transmit delay in clock ticks.
Referenced by process_dl_symbol.
const unsigned srsgnb::lower_phy_impl::max_processing_delay_slots
Maximum allowed processing delay in slots.
Referenced by process_symbol, lower_phy_impl.
const unsigned srsgnb::lower_phy_impl::nof_symbols_per_slot
Number of symbols per slot.
Referenced by process_symbol.
const std::vector<lower_phy_sector_description> srsgnb::lower_phy_impl::sectors
Sector configurations.
Referenced by process_ul_symbol, process_dl_symbol, lower_phy_impl.
slot_point srsgnb::lower_phy_impl::ul_slot_context
Current uplink processing slot context.
Referenced by process_ul_symbol, process_symbol, lower_phy_impl.
slot_point srsgnb::lower_phy_impl::dl_slot_context
Current downlink processing slot context.
Referenced by process_dl_symbol, process_symbol.
unsigned srsgnb::lower_phy_impl::symbol_slot_idx
Current symbol index within the processing slot.
Referenced by process_symbol.
lower_phy_state_fsm srsgnb::lower_phy_impl::state_fsm
State of the lower PHY finite-state machine.
Referenced by realtime_process_loop, lower_phy_impl, stop.
processor_notifier_adaptor srsgnb::lower_phy_impl::notification_adaptor
Processor notification adaptor.
Referenced by lower_phy_impl.
baseband_gateway_timestamp lower_phy_impl::process_ul_symbol(unsigned symbol_idx)
Processes an uplink symbol.
symbol_idx Symbol index within a subframe. The radio timestamp of the received block.
References ul_rg_buffers, ul_slot_context, srsgnb::slot_point::system_slot, modulators, radio_buffers, receive_metadata, receiver, srsgnb::baseband_gateway_receiver::receive, sectors, srsgnb::lower_phy_sector_description::port_mapping, srsgnb::lower_phy_sector_port_mapping::stream_id, srsgnb::lower_phy_sector_port_mapping::channel_id, prach_proc, demodulators, srsgnb::lower_phy_rx_symbol_context::sector, srsgnb::lower_phy_rx_symbol_context::slot, srsgnb::lower_phy_rx_symbol_context::nof_symbols, rx_symbol_notifier, srsgnb::lower_phy_rx_symbol_notifier::on_rx_symbol.
Referenced by process_symbol.
void lower_phy_impl::process_dl_symbol(unsigned symbol_idx, baseband_gateway_timestamp timestamp)
Processes a downlink symbol.
symbol_idx Symbol index within a subframe. timestamp Radio timestamp for the transmitted symbol.
References srsgnb::baseband_gateway_transmitter::metadata::ts, rx_to_tx_delay, dl_rg_buffers, dl_slot_context, srsgnb::slot_point::system_slot, modulators, radio_buffers, sectors, srsgnb::lower_phy_error_notifier::late_resource_grid_context::sector, srsgnb::lower_phy_error_notifier::late_resource_grid_context::slot, srsgnb::lower_phy_error_notifier::late_resource_grid_context::symbol, error_notifier, srsgnb::lower_phy_error_notifier::on_late_resource_grid, srsgnb::lower_phy_sector_description::port_mapping, srsgnb::lower_phy_sector_port_mapping::stream_id, srsgnb::lower_phy_sector_port_mapping::channel_id, transmitter, srsgnb::baseband_gateway_transmitter::transmit.
Referenced by process_symbol.
void lower_phy_impl::process_symbol()
Processes uplink and downlink slots.
References symbol_slot_idx, logger, srslog::detail::logger_impl< T, Enum >::set_context, dl_slot_context, srsgnb::slot_point::system_slot, srsgnb::lower_phy_timing_context::slot, max_processing_delay_slots, timing_notifier, srsgnb::lower_phy_timing_notifier::on_tti_boundary, ul_slot_context, srsgnb::slot_point::subframe_slot_index, nof_symbols_per_slot, srsgnb::lower_phy_timing_notifier::on_ul_half_slot_boundary, srsgnb::lower_phy_timing_notifier::on_ul_full_slot_boundary, process_ul_symbol, process_dl_symbol, dl_rg_buffers, ul_rg_buffers.
Referenced by realtime_process_loop.
void lower_phy_impl::realtime_process_loop(task_executor &realtime_task_executor)
Runs the lower physical layer.
References process_symbol, state_fsm, srsgnb::task_executor::defer, srsgnb::lower_phy_state_fsm::on_async_executor_stop, logger.
Referenced by start.
static unsigned srsgnb::lower_phy_impl::get_rx_to_tx_delay(unsigned ul_to_dl_subframe_offset, phy_time_unit time_advance_calibration, lower_phy_ta_offset ta_offset, sampling_rate srate)
Calculates the reception-to-transmission (Rx-to-Tx) delay as a number of samples.
On the radio channel, uplink and downlink frames coexist on the same carrier. As explained in TS38.211 Section 4.3.1, the sequence of uplink frames precedes the sequence of downlink frames by a given time $T_{\mathrm{offset}} = N_{\mathrm{TA,offset}} * T_c$ (recall that TS38.211 Section 4.3.1 describes the issue from the UE standpoint, hence the extra term $N_{\mathrm{TA}} * T_c$). In other words, uplink frame $i$ starts $T_{\mathrm{offset}}$ units of time before the downlink frame with the same index $i$. Equivalently, one can index the OFDM symbols comprising the frames and draw the same timing relationship between symbols with the same index. By increasing the granularity even further, the alignment can be thought of as if at sample level. On the other hand, for an uplink and a downlink sample to coincide on the carrier at the same time, it is required that the lower PHY processes the downlink (transmit) sample in advance with respect to the uplink (receive) one, because of the delays introduced by the underlying radio device. The Rx-to-Tx delay is thus the number of samples by which the sequence of transmitted samples must precede that of received samples, as seen by the lower PHY processor, in order to achieve the aforementioned carrier alignment between uplink and downlink frames. More specifically, let $N_{\mathrm{offset}}$ be the "round-trip" delay introduced by the radio device (i.e., it is the sum of the delay experienced by a received sample before reaching the lower PHY plus the delay undergone by a downlink sample leaving the lower PHY, before transmission). Also, let $N_{\mathrm{TA, offset}}$ be the time-advance offset between downlink and uplink, as defined in TS38.211 Section 4.3.1. Finally, let $N_{\mathrm{cal}}$ be a calibration term that takes into account time-advance impairments due radio device buffering. All three offsets are expressed as a number of samples. Then, the Rx-to-Tx delay $N$ is given by \[ N=N_{\mathrm{offset}} - N_{\mathrm{cal}} + N_{\mathrm{TA, offset}} \] samples or, equivalently, physical layer units of time. ul_to_dl_subframe_offset UL-to-DL offset in subframes (recall, 1 subframe = 1ms). It maps to $N_{\mathrm{offset}}$. time_advance_calibration Time-advance radio calibration time, in physical layer units of time. It maps to $N_{\mathrm{cal}}$. ta_offset Time advance offset (see lower_phy_ta_offset for more information). It maps to $N_{\mathrm{TA, offset}}$. srate Sampling rate. The reception-to-transmission delay as a number of samples.
References srsgnb::phy_time_unit::from_seconds, srsgnb::phy_time_unit::from_units_of_Tc, srsgnb::phy_time_unit::to_samples, srsgnb::sampling_rate::to_Hz.
lower_phy_impl::lower_phy_impl(lower_phy_common_configuration &&common_config, const lower_phy_configuration &config)
Constructs a generic lower physical layer.
common_config Provides the factory specific necessary parameters to construct the lower physical layer. config Provides the common lower PHY parameters to construct the lower physical layer.
References logger, srslog::detail::logger_impl< T, Enum >::set_level, srsgnb::lower_phy_configuration::log_level, srsgnb::lower_phy_configuration::ul_to_dl_subframe_offset, srsgnb::lower_phy_configuration::time_advance_calibration, srsgnb::phy_time_unit::to_seconds, srsgnb::phy_time_unit::to_samples, srsgnb::lower_phy_configuration::srate, srsgnb::sampling_rate::to_Hz, srsgnb::lower_phy_configuration::max_processing_delay_slots, srsgnb::lower_phy_configuration::bb_gateway, srsgnb::lower_phy_configuration::error_notifier, srsgnb::lower_phy_configuration::rx_symbol_notifier, srsgnb::lower_phy_configuration::timing_notifier, modulators, srsgnb::lower_phy_configuration::sectors, demodulators, srsgnb::lower_phy_configuration::nof_channels_per_stream, radio_buffers, srsgnb::sampling_rate::get_dft_size, receive_metadata, ul_slot_context, srsgnb::slot_point::nof_slots_per_subframe, dl_rg_buffers, sectors, max_processing_delay_slots, ul_rg_buffers, state_fsm, srsgnb::lower_phy_state_fsm::on_successful_init, notification_adaptor, srsgnb::processor_notifier_adaptor::connect_error_notifier, srsgnb::processor_notifier_adaptor::connect_rx_symbol_notifier, prach_proc, srsgnb::processor_notifier_adaptor::get_prach_notifier.
void lower_phy_impl::start(task_executor &realtime_task_executor) override
Starts the lower physical layer operation.
realtime_task_executor Task executor for real time operation. The real time task executor is exclusively dedicated to the lower physical layer operation.
References logger, srsgnb::task_executor::defer, realtime_process_loop.
void lower_phy_impl::stop() override
Stops the lower physical layer operation.
References logger, state_fsm, srsgnb::lower_phy_state_fsm::stop_and_join.
void lower_phy_impl::request_prach_window(const prach_buffer_context &context, prach_buffer &buffer) override
Requests the lower PHY to capture a PRACH window.
The lower PHY must capture a PHY window identified by context. The capture must start at slot context.slot and symbol context.start_symbol. The capture must finish once buffer.is_full() returns true. context PRACH window context. buffer PRACH buffer used to write the PRACH window.
References prach_proc.
void lower_phy_impl::request_uplink_slot(const resource_grid_context &context, resource_grid &grid) override
Requests the lower PHY to provide an uplink slot.
The lower PHY must process the slot described by context and notify the demodulation per symbol basis of the requested slot. The notification contains the exact context and grid. context Resource grid context. buffer Resource grid to store the processed slot.
References logger, srsgnb::resource_grid_context::sector, srsgnb::resource_grid_context::slot, srsgnb::slot_point::system_slot, ul_rg_buffers.
void lower_phy_impl::handle_resource_grid(const resource_grid_context &context, const resource_grid_reader &grid) override
Handles the given resource grid to be transmitted.
context Resource grid context. grid Resource grid to transmit.
References logger, srsgnb::resource_grid_context::sector, srsgnb::resource_grid_context::slot, srsgnb::slot_point::system_slot, dl_rg_buffers.
lower_phy_request_handler& srsgnb::lower_phy_impl::get_request_handler() override
Returns a reference to the lower PHY request handler.
lower_phy_rg_handler& srsgnb::lower_phy_impl::get_rg_handler() override
Returns a reference to the lower PHY resource grid handler.
lower_phy_controller& srsgnb::lower_phy_impl::get_controller() override
Returns a reference to the lower PHY controller.