srsgnb::lower_phy_timing_notifier
virtual srsgnb::lower_phy_timing_notifier::~lower_phy_timing_notifier()=default
Default destructor.
virtual void srsgnb::lower_phy_timing_notifier::on_tti_boundary(const lower_phy_timing_context &context)=0
Notifies a new TTI boundary event.
Notifies that the processing of a new slot has started. It indicates in context the next slot available for transmission. context Notification context.
Referenced by srsgnb::lower_phy_impl::process_symbol.
virtual void srsgnb::lower_phy_timing_notifier::on_ul_half_slot_boundary(const lower_phy_timing_context &context)=0
Notifies that an uplink half slot has been received and processed by the lower PHY.
context Notification context.
Referenced by srsgnb::lower_phy_impl::process_symbol.
virtual void srsgnb::lower_phy_timing_notifier::on_ul_full_slot_boundary(const lower_phy_timing_context &context)=0
Notifies that an uplink full slot has been received and processed by the lower PHY.
After this notification, the lower PHY does not report more uplink receive symbols events for the given context. context Notification context.
Referenced by srsgnb::lower_phy_impl::process_symbol.