srsgnb::bounded_bitset
using srsgnb::bounded_bitset< N, reversed >::word_t = uint64_t
const size_t srsgnb::bounded_bitset< N, reversed >::bits_per_word
friend class bounded_bitset
std::array<word_t, (N - 1) / bits_per_word + 1> srsgnb::bounded_bitset< N, reversed >::buffer
size_t srsgnb::bounded_bitset< N, reversed >::cur_size
constexpr srsgnb::bounded_bitset< N, reversed >::bounded_bitset()=default
constexpr srsgnb::bounded_bitset< N, reversed >::bounded_bitset(size_t cur_size_)
constexpr srsgnb::bounded_bitset< N, reversed >::bounded_bitset(Iterator begin, Iterator end)
Constructs a bitset using iterators.
The constructed bitset size is equal to end - begin size. The values in the list are mapped one to one starting from begin. Iterator Boolean iterator type. begin Begin iterator. end End iterator.
constexpr srsgnb::bounded_bitset< N, reversed >::bounded_bitset(std::initializer_list< const bool > values)
Constructs a bitset from an initializer list.
The constructed bitset size is equal to values size. The values in the list are mapped one to one. values Boolean initializer list.
size_t srsgnb::bounded_bitset< N, reversed >::size() const noexcept
Current size of the bounded_bitset.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::push_back, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::find_lowest, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::all, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::find_highest, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::is_contiguous, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::operator==, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::operator|=, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::operator&=, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::to_string, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::to_uint64, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::from_uint64, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::to_hex, srsgnb::fliplr, srsgnb::fapi::dl_dci_pdu_builder::set_payload, srsgnb::fapi::dl_pdcch_pdu_builder::set_coreset_parameters, srsgnb::rb_allocation::get_prb_begin, srsgnb::rb_allocation::get_prb_end, srsgnb::prb_grant::operator&=, srsgnb::rb_allocation::get_contiguous_prb_mask, srsgnb::rb_allocation::get_other_prb_mask, srsgnb::rb_allocation::get_prb_mask, srsgnb::rb_allocation::get_prb_indices, srsgnb::re_pattern_list::get_inclusion_count, srsgnb::dmrs_sequence_generate, srsgnb::convert_rbgs_to_prbs, srsgnb::carrier_subslot_resource_grid::used_crbs, srsgnb::find_next_empty_interval, srsgnb::find_empty_interval_of_length.
void srsgnb::bounded_bitset< N, reversed >::resize(size_t new_size)
Resize of the bounded_bitset. If new_size > max_size() , an assertion is triggered.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::bounded_bitset, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::push_back.
void srsgnb::bounded_bitset< N, reversed >::set(size_t pos, bool val)
Set bit with provided index to either true or false. Assertion is triggered if pos >= max_size().
pos Position in bitset. val Value to set the bit.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::bounded_bitset, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::push_back, srsgnb::fliplr.
void srsgnb::bounded_bitset< N, reversed >::set(size_t pos)
Set bit with provided index to true. Assertion is triggered if pos >= N.
pos Position in bitset.
void srsgnb::bounded_bitset< N, reversed >::reset(size_t pos)
Set bit with provided index to false. Assertion is triggered if pos >= N.
pos Position in bitset.
Referenced by srsgnb::carrier_subslot_resource_grid::clear.
void srsgnb::bounded_bitset< N, reversed >::reset() noexcept
Reset all bits in the bounded_bitset to false. The size of the bitset is maintained.
void srsgnb::bounded_bitset< N, reversed >::push_back(bool val)
Appends a bit with value val to the set.
Assertion is triggered if the resultant size exceeds the maximum size of the bitset.
Referenced by srsgnb::dci_1_0_p_rnti_pack, srsgnb::dci_1_0_si_rnti_pack, srsgnb::dci_1_0_ra_rnti_pack.
void srsgnb::bounded_bitset< N, reversed >::push_back(Integer val, unsigned nof_bits)
Appends nof_bits bits to the set.
The least nof_bits significant bits of val are appended to the set, starting from the most significant bit and finishing with the least significant bit. Assertion is triggered if the resultant size exceeds the maximum size of the bitset.
bool srsgnb::bounded_bitset< N, reversed >::test(size_t pos) const
Check if bit with provided index is set to true.
pos Position in bitset. Returns true if bit at position pos is set.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::to_string, srsgnb::fapi::dl_dci_pdu_builder::set_payload, srsgnb::fapi::dl_pdcch_pdu_builder::set_coreset_parameters, srsgnb::rb_allocation::get_other_prb_mask, srsgnb::rb_allocation::get_prb_indices, srsgnb::re_pattern_list::get_inclusion_count, srsgnb::get_rg_subc_mask, srsgnb::dmrs_sequence_generate.
bounded_bitset<N, reversed>& srsgnb::bounded_bitset< N, reversed >::flip() noexcept
Toggle values of bits in bitset.
Returns this object.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::operator~.
bounded_bitset<N, reversed>& srsgnb::bounded_bitset< N, reversed >::fill(size_t startpos, size_t endpos, bool value=true)
Fills range of bits to either true or false.
startpos Starting bit index that will be set. endpos End bit index (excluding) where the bits stop being set. value Set bit range values to either true or false. Returns a reference to this object.
Referenced by srsgnb::prb_grant::operator&=, srsgnb::rb_allocation::get_contiguous_prb_mask, srsgnb::convert_rbgs_to_prbs, srsgnb::carrier_subslot_resource_grid::fill, srsgnb::carrier_subslot_resource_grid::used_crbs.
bounded_bitset<N2, reversed> srsgnb::bounded_bitset< N, reversed >::slice(size_t startpos, size_t endpos) const
Returns bounded_bitset<> that represents a slice or subview of the original bounded_bitset. Unless it is specified, the returned slice has the same template parameters "N" and "reversed" of "this".
startpos The bit index where the subview starts. endpos The bit index where the subview stops.
Referenced by srsgnb::carrier_subslot_resource_grid::used_crbs.
int srsgnb::bounded_bitset< N, reversed >::find_lowest(bool value=true) const noexcept
Finds the lowest bit with value set to the value passed as argument.
value The bit value to find, either true (1) or false (0). Returns the lowest found bit index or -1 in case no bit was found with the provided value argument.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::find_lowest, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::is_contiguous, srsgnb::rb_allocation::get_prb_begin, srsgnb::rb_allocation::get_contiguous_prb_mask, srsgnb::get_rg_subc_mask_reference, srsgnb::get_rg_subc_mask, srsgnb::convert_rbgs_to_prbs, srsgnb::find_next_empty_interval.
int srsgnb::bounded_bitset< N, reversed >::find_lowest(size_t startpos, size_t endpos, bool value=true) const noexcept
Finds, within a range of bit indexes, the lowest bit with value set to the value passed as argument.
startpos Starting bit index for the search. endpos End bit index for the search. value The bit value to find, either true (1) or false (0). Returns the lowest found bit index or -1 in case no bit was found with the provided value argument.
void srsgnb::bounded_bitset< N, reversed >::for_each(size_t startpos, size_t endpos, const T &&function, bool value=true) const noexcept
bool srsgnb::bounded_bitset< N, reversed >::all() const noexcept
Checks if all bits in the bitset are set to 1.
Returns true if all bits are 1.
Referenced by srsgnb::carrier_subslot_resource_grid::all_set.
bool srsgnb::bounded_bitset< N, reversed >::all(size_t start, size_t stop) const
Checks if all bits within a bit index range are set to 1.
Returns true if all the bits within the range are 1.
int srsgnb::bounded_bitset< N, reversed >::find_highest(bool value=true) const noexcept
Finds the highest bit with value set to the value passed as argument.
value The bit value to find, either true (1) or false (0). Returns the lowest found bit index or -1 in case no bit was found with the provided value argument.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::find_highest, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::is_contiguous, srsgnb::rb_allocation::get_prb_end, srsgnb::rb_allocation::get_contiguous_prb_mask, srsgnb::get_rg_subc_mask.
int srsgnb::bounded_bitset< N, reversed >::find_highest(size_t startpos, size_t endpos, bool value=true) const noexcept
Finds, within a range of bit indexes, the highest bit with value set to the value passed as argument.
startpos Starting bit index for the search. endpos End bit index for the search. value The bit value to find, either true (1) or false (0). Returns the lowest found bit index or -1 in case no bit was found with the provided value argument.
bool srsgnb::bounded_bitset< N, reversed >::any() const noexcept
Checks if at least one bit in the bitset is set to 1.
Returns true if at least one bit is 1.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::none, srsgnb::carrier_subslot_resource_grid::collides.
bool srsgnb::bounded_bitset< N, reversed >::any(size_t start, size_t stop) const
Checks if at least one bit in the bitset is set to 1 within a bit index range.
Returns true if at least one bit equal to 1 was found within the range.
bool srsgnb::bounded_bitset< N, reversed >::none() const noexcept
Checks if at no bit in the bitset is set to 1.
Returns true if no bit equal to 1 was found.
bool srsgnb::bounded_bitset< N, reversed >::is_contiguous(bool value=true) const noexcept
Determines whether all bits with value set to value are contiguous.
Bits with the same value are contiguous if: one bit with value is found, no bit with value is found, and all bits with value are consecutive. startpos Starting bit index for the search. endpos End bit index for the search. value The bit value to find, either true (1) or false (0). Returns the lowest found bit index or -1 in case no bit was found with the provided value argument.
Referenced by srsgnb::rb_allocation::is_contiguous, srsgnb::rb_allocation::get_prb_mask.
size_t srsgnb::bounded_bitset< N, reversed >::count() const noexcept
Counts the number of bits set to 1.
Returns the number of bits set to 1.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::is_contiguous, srsgnb::rb_allocation::get_nof_rb, srsgnb::rb_allocation::get_contiguous_prb_mask, srsgnb::dmrs_pdcch_processor_impl::map, srsgnb::dmrs_pdsch_processor_impl::map, srsgnb::cce_to_prb_mapping_interleaved, srsgnb::get_coreset_nof_prbs.
bool srsgnb::bounded_bitset< N, reversed >::operator==(const bounded_bitset< N, reversed > &other) const noexcept
Compares two bitsets.
Returns true if both bitsets are equal in size and values of bits.
bool srsgnb::bounded_bitset< N, reversed >::operator!=(const bounded_bitset< N, reversed > &other) const noexcept
bounded_bitset<N, reversed>& srsgnb::bounded_bitset< N, reversed >::operator|=(const bounded_bitset< N, reversed > &other)
Applies bitwise OR operation lhs |= rhs.
other Bitset which corresponds to the rhs of the operation. This object updated after the bitwise OR operation.
bounded_bitset<N, reversed>& srsgnb::bounded_bitset< N, reversed >::operator&=(const bounded_bitset< N, reversed > &other)
Applies bitwise AND operation lhs &= rhs.
other Bitset which corresponds to the rhs of the operation. This object updated after the bitwise AND operation.
bounded_bitset<N, reversed> srsgnb::bounded_bitset< N, reversed >::operator~() const noexcept
Flips values of bits in the bitset.
Returns reference to this object, updated after the flip operation.
OutputIt srsgnb::bounded_bitset< N, reversed >::to_string(OutputIt &&mem_buffer) const
Formatting helper for bitset.
OutputIt Output fmt memory buffer type. mem_buffer Fmt memory buffer. The memory buffer passed as argument.
uint64_t srsgnb::bounded_bitset< N, reversed >::to_uint64() const
Conversion of bounded_bitset to unsigned integer of 64 bits. If bitset size is larger than 64 bits, an assertion is triggered.
Unsigned integer representation of the bounded_bitset.
Referenced by srsgnb::get_coreset_start_crb.
void srsgnb::bounded_bitset< N, reversed >::from_uint64(uint64_t v)
Conversion of unsigned integer of 64 bits to bounded_bitset. If passed bitmap doesn't fit in the bitset, an assertion is triggered.
v Integer bitmap that is going to be stored in the bitset.
OutputIt srsgnb::bounded_bitset< N, reversed >::to_hex(OutputIt &&mem_buffer) const noexcept
Formatting of bounded_bitset to hex format.
OutputIt Fmt memory buffer type. mem_buffer Fmt memory buffer. The input fmt memory buffer.
static constexpr bool srsgnb::bounded_bitset< N, reversed >::bit_order() noexcept
static constexpr size_t srsgnb::bounded_bitset< N, reversed >::max_size() noexcept
void srsgnb::bounded_bitset< N, reversed >::sanitize_()
size_t srsgnb::bounded_bitset< N, reversed >::get_bitidx_(size_t bitpos) const noexcept
bool srsgnb::bounded_bitset< N, reversed >::test_(size_t bitpos) const noexcept
void srsgnb::bounded_bitset< N, reversed >::set_(size_t bitpos) noexcept
void srsgnb::bounded_bitset< N, reversed >::reset_(size_t bitpos) noexcept
size_t srsgnb::bounded_bitset< N, reversed >::nof_words_() const noexcept
word_t& srsgnb::bounded_bitset< N, reversed >::get_word_(size_t bitidx) noexcept
const word_t& srsgnb::bounded_bitset< N, reversed >::get_word_(size_t bitidx) const
size_t srsgnb::bounded_bitset< N, reversed >::word_idx_(size_t bitidx) const
void srsgnb::bounded_bitset< N, reversed >::assert_within_bounds_(size_t pos, bool strict) const noexcept
void srsgnb::bounded_bitset< N, reversed >::assert_range_bounds_(size_t startpos, size_t endpos) const noexcept
int srsgnb::bounded_bitset< N, reversed >::find_last_(size_t startpos, size_t endpos, bool value) const noexcept
int srsgnb::bounded_bitset< N, reversed >::find_first_(size_t startpos, size_t endpos, bool value) const noexcept
int srsgnb::bounded_bitset< N, reversed >::find_first_reversed_(size_t startpos, size_t endpos, bool value) const noexcept
bool srsgnb::bounded_bitset< N, reversed >::find_first_word_(size_t start, size_t stop, const C &c) const
Iterates the bitset word-wise, and for each word, compute the mask of active bits, and call callback that receives as an argument the word index and the active-bit mask. If the callback returns true, the iteration stops and the function returns true. start first bit index. stop end bit index. c Callback with signature "bool(size_t word_index, word_t active_mask)" called for each word of the bitset. When this callback returns true, the iteration is stopped. true if iteration was stopped early.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::fill, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::all, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::any, srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::find_first_word_.
bool srsgnb::bounded_bitset< N, reversed >::find_first_word_(size_t start, size_t stop, const C &c, std::true_type t) const
bool srsgnb::bounded_bitset< N, reversed >::find_first_word_(size_t start, size_t stop, const C &c, std::false_type t) const
static word_t srsgnb::bounded_bitset< N, reversed >::maskbit(size_t pos) noexcept
static size_t srsgnb::bounded_bitset< N, reversed >::max_nof_words_() noexcept