srslog::detail::dyn_arg_store_pool
std::vector<fmt::dynamic_format_arg_store<fmt::format_context> > srslog::detail::dyn_arg_store_pool::pool
std::vector<fmt::dynamic_format_arg_store<fmt::format_context>*> srslog::detail::dyn_arg_store_pool::free_list
mutex srslog::detail::dyn_arg_store_pool::m
srslog::detail::dyn_arg_store_pool::dyn_arg_store_pool()
fmt::dynamic_format_arg_store<fmt::format_context>* srslog::detail::dyn_arg_store_pool::alloc()
Returns a pointer to a free dyn arg store object, otherwise returns nullptr.
Referenced by srslog::log_backend_impl::alloc_arg_store.
void srslog::detail::dyn_arg_store_pool::dealloc(fmt::dynamic_format_arg_store< fmt::format_context > *p)
Deallocate the given dyn arg store object returning it to the pool.
Referenced by srslog::backend_worker::process_log_entry, srslog::log_backend_impl::push.