srslog::log_formatter
virtual srslog::log_formatter::~log_formatter()=default
virtual std::unique_ptr<log_formatter> srslog::log_formatter::clone() const =0
Returns a copy of the formatter.
virtual void srslog::log_formatter::format(detail::log_entry_metadata &&metadata, fmt::memory_buffer &buffer)=0
Formats the log entry into the input buffer.
void srslog::log_formatter::format_ctx(const srslog::context< Ts... > &ctx, detail::log_entry_metadata &&metadata, fmt::memory_buffer &buffer)
Formats the context and log entry into the input buffer.
References format_context_begin, srslog::context< Ts >::name, iterate_tuple, srslog::detail::metrics_container< Ts... >::contents, format_context_end.
void srslog::log_formatter::iterate_tuple(const std::tuple< Ts... > &t, unsigned level, fmt::memory_buffer &buffer, detail::index_sequence< Is... >)
Processes all elements in a tuple.
References process_element.
Referenced by format_ctx, process_element.
void srslog::log_formatter::process_element(const metric_set< Name, Ts... > &ms, unsigned level, fmt::memory_buffer &buffer)
Processes the input metric set.
References format_metric_set_begin, srslog::metric_set< Name, Ts >::name, iterate_tuple, srslog::detail::metrics_container< Ts... >::contents, format_metric_set_end.
Referenced by iterate_tuple, process_element.
void srslog::log_formatter::process_element(const metric_list< Name, T > &list, unsigned level, fmt::memory_buffer &buffer)
Processes the input metric list.
References format_list_begin, srslog::metric_list< Name, T >::name, process_element, format_list_end.
void srslog::log_formatter::process_element(const metric< Ty, Name, Units > &t, unsigned level, fmt::memory_buffer &buffer)
Processes the input metric.
References srslog::metric< Ty, Name, Units >::value, format_metric, srslog::metric< Ty, Name, Units >::name, srslog::metric< Ty, Name, Units >::units, srslog::metric< Ty, Name, Units >::kind.
virtual void srslog::log_formatter::format_context_begin(const detail::log_entry_metadata &md, fmt::string_view ctx_name, unsigned size, fmt::memory_buffer &buffer)=0
Derived classes should implement the following callbacks to format metric objects. Each callback is invoked at a different place of the formatting algorithm. This callback gets called at the beginning of the context formatting algorithm.
Referenced by format_ctx.
virtual void srslog::log_formatter::format_context_end(const detail::log_entry_metadata &md, fmt::string_view ctx_name, fmt::memory_buffer &buffer)=0
This callback gets called at the end of the context formatting algorithm.
Referenced by format_ctx.
virtual void srslog::log_formatter::format_metric_set_begin(fmt::string_view set_name, unsigned size, unsigned level, fmt::memory_buffer &buffer)=0
This callback gets called at the beginning of a metric set formatting procedure.
Referenced by process_element.
virtual void srslog::log_formatter::format_metric_set_end(fmt::string_view set_name, unsigned level, fmt::memory_buffer &buffer)=0
This callback gets called at the beginning of a metric set formatting end.
Referenced by process_element.
virtual void srslog::log_formatter::format_list_begin(fmt::string_view list_name, unsigned size, unsigned level, fmt::memory_buffer &buffer)=0
This callback gets called at the beginning of a metric list formatting procedure.
Referenced by process_element.
virtual void srslog::log_formatter::format_list_end(fmt::string_view list_name, unsigned level, fmt::memory_buffer &buffer)=0
This callback gets called at the end of a metric list formatting procedure.
Referenced by process_element.
virtual void srslog::log_formatter::format_metric(fmt::string_view metric_name, fmt::string_view metric_value, fmt::string_view metric_units, metric_kind kind, unsigned level, fmt::memory_buffer &buffer)=0
This callback gets called for each metric.
Referenced by process_element.