srslog::buffered_file_sink
const std::string srslog::buffered_file_sink::filename
file_utils::file srslog::buffered_file_sink::handler
std::vector<char> srslog::buffered_file_sink::buffer
bool srslog::buffered_file_sink::is_file_created
srslog::buffered_file_sink::buffered_file_sink(std::string filename, std::size_t capacity, std::unique_ptr< log_formatter > f)
srslog::buffered_file_sink::~buffered_file_sink() override
srslog::buffered_file_sink::buffered_file_sink(const buffered_file_sink &other)=delete
buffered_file_sink& srslog::buffered_file_sink::operator=(const buffered_file_sink &other)=delete
detail::error_string srslog::buffered_file_sink::write(detail::memory_buffer input_buffer) override
Writes the provided memory buffer into the sink.
References srslog::file_utils::file::create, has_room_for, srslog::detail::memory_buffer::size, srslog::detail::memory_buffer::begin, srslog::detail::memory_buffer::end, flush_buffer.
detail::error_string srslog::buffered_file_sink::flush() override
Flushes any buffered contents to the backing store.
References flush_buffer, srslog::file_utils::file::flush.
bool srslog::buffered_file_sink::has_room_for(std::size_t s) const
Returns true if the internal buffer has room for the specified input size, otherwise returns false.
Referenced by write.
detail::error_string srslog::buffered_file_sink::flush_buffer()
Flushes the buffer contents into the file.
References srslog::file_utils::file::write.
Referenced by write, flush.