srsgnb::srs_cu_cp::du_processor
srslog::basic_logger& srsgnb::srs_cu_cp::du_processor::logger
du_processor_config_t srsgnb::srs_cu_cp::du_processor::cfg
du_context srsgnb::srs_cu_cp::du_processor::context
slot_array<du_cell_context, MAX_NOF_DU_CELLS> srsgnb::srs_cu_cp::du_processor::cell_db
std::atomic<uint16_t> srsgnb::srs_cu_cp::du_processor::next_du_cell_index
flattened version of served cells list provided by DU/F1AP
std::unique_ptr<f1_interface> srsgnb::srs_cu_cp::du_processor::f1ap
std::unique_ptr<rrc_entity_du_interface> srsgnb::srs_cu_cp::du_processor::rrc
ue_manager srsgnb::srs_cu_cp::du_processor::ue_mng
f1ap_du_processor_adapter srsgnb::srs_cu_cp::du_processor::f1ap_ev_notifier
rrc_ue_du_processor_adapter srsgnb::srs_cu_cp::du_processor::rrc_ue_ev_notifier
slot_array<async_task_sequencer, MAX_NOF_UES> srsgnb::srs_cu_cp::du_processor::ue_ctrl_loop
timer_manager srsgnb::srs_cu_cp::du_processor::timer_db
du_processor::du_processor(const du_processor_config_t &cfg)
srsgnb::srs_cu_cp::du_processor::~du_processor()=default
void du_processor::handle_f1_setup_request(const f1_setup_request_message &msg) override
Handle the reception of a F1 Setup Request message and transmit the F1 Setup Response or F1 Setup Failure.
msg The received F1 Setup Request message.
References send_f1_setup_failure, srsgnb::srs_cu_cp::du_context::id, srsgnb::srs_cu_cp::du_context::name, srsgnb::srs_cu_cp::du_cell_context::pci, srsgnb::srs_cu_cp::du_cell_context::cgi, srsgnb::cgi_from_asn1, srsgnb::srs_cu_cp::du_cell_context::sys_info, send_f1_setup_response.
du_index_t du_processor::get_du_index() override
Get the DU index.
The DU index.
slot_array<du_cell_context, MAX_NOF_DU_CELLS>& srsgnb::srs_cu_cp::du_processor::get_cell_db()
du_context& srsgnb::srs_cu_cp::du_processor::get_context()
f1c_message_handler& srsgnb::srs_cu_cp::du_processor::get_f1c_message_handler()
f1c_statistics_handler& srsgnb::srs_cu_cp::du_processor::get_f1c_statistics_handler()
du_cell_index_t du_processor::get_next_du_cell_index()
size_t srsgnb::srs_cu_cp::du_processor::get_nof_ues()
ue_creation_complete_message du_processor::handle_ue_creation_request(const ue_creation_message &msg) override
Create a new UE context.
msg The UE creation message. Returns a UE creation complete message containing the index of the created UE and its SRB notifiers.
References srsgnb::srs_cu_cp::ue_manager::add_ue, find_cell, srsgnb::nr_cell_global_identity::nci, create_srb.
rrc_amf_connection_handler & du_processor::get_amf_connection_handler()
void du_processor::create_srb(const srb_creation_message &msg) override
Pass handle to AMF connection handler within RRC.
Create SRB entry in bearer list and add adapter handle.
References srsgnb::srb_id_to_lcid, srsgnb::create_pdcp_entity.
Referenced by handle_ue_creation_request.
void du_processor::handle_ue_context_release_command(const ue_context_release_command_message &msg) override
Handle a UE Context Release Command and notify F1AP.
msg The UE Context Release Command Message.
void srsgnb::srs_cu_cp::du_processor::handle_ue_async_task(ue_index_t ue_index, async_task< void > &&task) override
unique_timer srsgnb::srs_cu_cp::du_processor::make_unique_timer() override
timer_manager& srsgnb::srs_cu_cp::du_processor::get_timer_manager() override
du_cell_index_t du_processor::find_cell(uint64_t packed_nr_cell_id)
Lookup the cell based on a given NR cell ID.
packed_nr_cell_id The packed NR cell ID received over F1AP.
Referenced by handle_ue_creation_request.
void du_processor::send_f1_setup_response(const du_context &du_ctxt)
Create and transmit the F1 Setup response message.
Sender for F1AP messages. du_ctxt The context of the DU that should receive the message.
Referenced by handle_f1_setup_request.
void du_processor::send_f1_setup_failure(asn1::f1ap::cause_c::types::options cause)
Create and transmit the F1 Setup failure message.
cause The cause of the failure.
Referenced by handle_f1_setup_request.