srsgnb::upper_phy_timing_handler
virtual srsgnb::upper_phy_timing_handler::~upper_phy_timing_handler()=default
Default destructor.
virtual void srsgnb::upper_phy_timing_handler::handle_tti_boundary(const upper_phy_timing_context &context)=0
Handles a new TTI boundary event.
context Notification context.
Referenced by srsgnb::phy_timing_adapter::on_tti_boundary.
virtual void srsgnb::upper_phy_timing_handler::handle_ul_half_slot_boundary(const upper_phy_timing_context &context)=0
Handles a half slot (7th OFDM symbol) packet arrival.
context Notification context.
Referenced by srsgnb::phy_timing_adapter::on_ul_half_slot_boundary.
virtual void srsgnb::upper_phy_timing_handler::handle_ul_full_slot_boundary(const upper_phy_timing_context &context)=0
Handles a full slot (14th OFDM symbol) packet arrival.
context Notification context.
Referenced by srsgnb::phy_timing_adapter::on_ul_full_slot_boundary.