srsgnb::pdsch_processor_impl
std::unique_ptr<pdsch_encoder> srsgnb::pdsch_processor_impl::encoder
std::unique_ptr<pdsch_modulator> srsgnb::pdsch_processor_impl::modulator
std::unique_ptr<dmrs_pdsch_processor> srsgnb::pdsch_processor_impl::dmrs
std::array<static_vector<uint8_t, MAX_CODEWORD_SIZE>, MAX_NOF_TRANSPORT_BLOCKS> srsgnb::pdsch_processor_impl::codewords
unsigned int pdsch_processor_impl::compute_nof_data_re(const pdu_t &pdu)
Computes the number of RE used for mapping PDSCH data.
The number of RE excludes the elements described by pdu reserved and the RE used for DMRS. pdu Describes a PDSCH transmission. The number of resource elements.
References srsgnb::pdsch_processor::pdu_t::reserved, srsgnb::re_pattern_list::merge, srsgnb::pdsch_processor::pdu_t::dmrs, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::pdsch_processor::pdu_t::bwp_start_rb, srsgnb::pdsch_processor::pdu_t::bwp_size_rb, srsgnb::pdsch_processor::pdu_t::nof_cdm_groups_without_data, srsgnb::pdsch_processor::pdu_t::dmrs_symbol_mask, srsgnb::pdsch_processor::pdu_t::freq_alloc, srsgnb::rb_allocation::get_prb_mask, srsgnb::rb_allocation::get_nof_rb, srsgnb::NRE, srsgnb::pdsch_processor::pdu_t::nof_symbols, srsgnb::re_pattern_list::get_inclusion_count, srsgnb::pdsch_processor::pdu_t::start_symbol_index.
Referenced by process.
span< const uint8_t > pdsch_processor_impl::encode(span< const uint8_t > data, unsigned codeword_id, unsigned nof_layers, unsigned Nre, const pdu_t &pdu)
Encodes a codeword as per TS 38.212 section 7.2.
data Provides the data to transmit as packed bits. codeword_id Indicates the codeword identifier. nof_layers Indicates the number of layers the codeword is mapped on to. Nre Indicates the number of resource elements used for PDSCH mapping. pdu Provides the PDSCH processor PDU. A view of the encoded codeword.
References srsgnb::pdsch_processor::pdu_t::codewords, srsgnb::segmenter_config::base_graph, srsgnb::pdsch_processor::pdu_t::ldpc_base_graph, srsgnb::segmenter_config::rv, srsgnb::segmenter_config::mod, srsgnb::segmenter_config::Nref, srsgnb::pdsch_processor::pdu_t::tbs_lbrm_bytes, srsgnb::segmenter_config::nof_layers, srsgnb::segmenter_config::nof_ch_symbols, srsgnb::get_bits_per_symbol.
Referenced by process.
void pdsch_processor_impl::modulate(resource_grid_writer &grid, span< const span< const uint8_t >> temp_codewords, const pdu_t &pdu)
Modulates a PDSCH transmission as per TS 38.211 section 7.3.1.
grid Provides the destination resource grid. temp_codewords Provides the encoded codewords. pdu Provides the PDSCH processor PDU.
References srsgnb::pdsch_modulator::config_t::rnti, srsgnb::pdsch_processor::pdu_t::rnti, srsgnb::pdsch_modulator::config_t::bwp_size_rb, srsgnb::pdsch_processor::pdu_t::bwp_size_rb, srsgnb::pdsch_modulator::config_t::bwp_start_rb, srsgnb::pdsch_processor::pdu_t::bwp_start_rb, srsgnb::pdsch_modulator::config_t::modulation1, srsgnb::pdsch_processor::pdu_t::codewords, srsgnb::pdsch_modulator::config_t::modulation2, srsgnb::BPSK, srsgnb::pdsch_modulator::config_t::freq_allocation, srsgnb::pdsch_processor::pdu_t::freq_alloc, srsgnb::pdsch_modulator::config_t::start_symbol_index, srsgnb::pdsch_processor::pdu_t::start_symbol_index, srsgnb::pdsch_modulator::config_t::nof_symbols, srsgnb::pdsch_processor::pdu_t::nof_symbols, srsgnb::pdsch_modulator::config_t::dmrs_symb_pos, srsgnb::pdsch_processor::pdu_t::dmrs_symbol_mask, srsgnb::pdsch_modulator::config_t::nof_cdm_groups_without_data, srsgnb::pdsch_processor::pdu_t::nof_cdm_groups_without_data, srsgnb::pdsch_modulator::config_t::n_id, srsgnb::pdsch_processor::pdu_t::n_id, srsgnb::pdsch_modulator::config_t::scaling, srsgnb::convert_dB_to_amplitude, srsgnb::pdsch_processor::pdu_t::ratio_pdsch_data_to_sss_dB, srsgnb::pdsch_modulator::config_t::reserved, srsgnb::pdsch_processor::pdu_t::reserved, srsgnb::pdsch_modulator::config_t::ports, srsgnb::pdsch_processor::pdu_t::ports.
Referenced by process.
void pdsch_processor_impl::put_dmrs(resource_grid_writer &grid, const pdu_t &pdu)
Generates and maps DMRS for the PDSCH transmission as per TS 38.211 section 7.4.1.1.
grid Provides the destination resource grid. pdu Provides the PDSCH processor PDU.
References srsgnb::pdsch_processor::pdu_t::freq_alloc, srsgnb::rb_allocation::get_prb_mask, srsgnb::pdsch_processor::pdu_t::bwp_start_rb, srsgnb::pdsch_processor::pdu_t::bwp_size_rb, srsgnb::pdsch_processor::pdu_t::ref_point, srsgnb::pdsch_processor::pdu_t::PRB0, srsgnb::dmrs_pdsch_processor::config_t::slot, srsgnb::pdsch_processor::pdu_t::slot, srsgnb::dmrs_pdsch_processor::config_t::reference_point_k_rb, srsgnb::dmrs_pdsch_processor::config_t::type, srsgnb::pdsch_processor::pdu_t::dmrs, srsgnb::dmrs_pdsch_processor::config_t::scrambling_id, srsgnb::pdsch_processor::pdu_t::scrambling_id, srsgnb::dmrs_pdsch_processor::config_t::n_scid, srsgnb::pdsch_processor::pdu_t::n_scid, srsgnb::dmrs_pdsch_processor::config_t::amplitude, srsgnb::convert_dB_to_amplitude, srsgnb::pdsch_processor::pdu_t::ratio_pdsch_dmrs_to_sss_dB, srsgnb::dmrs_pdsch_processor::config_t::symbols_mask, srsgnb::pdsch_processor::pdu_t::dmrs_symbol_mask, srsgnb::dmrs_pdsch_processor::config_t::rb_mask, srsgnb::dmrs_pdsch_processor::config_t::ports, srsgnb::pdsch_processor::pdu_t::ports.
Referenced by process.
srsgnb::pdsch_processor_impl::pdsch_processor_impl(std::unique_ptr< pdsch_encoder > encoder_, std::unique_ptr< pdsch_modulator > modulator_, std::unique_ptr< dmrs_pdsch_processor > dmrs_)
Creates a generic PDSCH processor.
config Provides the necessary configuration.
void pdsch_processor_impl::process(resource_grid_writer &grid, static_vector< span< const uint8_t >, MAX_NOF_TRANSPORT_BLOCKS > data, const pdu_t &pdu) override
Processes a PDSCH transmission.
grid Provides the destination resource grid. data Provides the codewords to transmit. pdu Provides the necessary parameters to process the PDSCH transmission. The number of transport blocks must be equal to the number of codewords in pdu. The size of each transport block is determined by data[TB index].size()
References srsgnb::pdsch_processor::pdu_t::ports, srsgnb::pdsch_processor::pdu_t::codewords, srsgnb::pdsch_processor::pdu_t::tbs_lbrm_bytes, srsgnb::ldpc::MAX_CODEBLOCK_SIZE, srsgnb::pdsch_processor::pdu_t::nof_cdm_groups_without_data, compute_nof_data_re, srsgnb::pdsch_modulator::MAX_NOF_CODEWORDS, encode, modulate, put_dmrs.