srslog::sink
std::unique_ptr<log_formatter> srslog::sink::formatter
srslog::sink::sink(std::unique_ptr< log_formatter > f)
virtual srslog::sink::~sink()=default
log_formatter& srslog::sink::get_formatter()
Returns the formatter used by this sink.
Referenced by srslog::log_channel::operator().
const log_formatter& srslog::sink::get_formatter() const
virtual detail::error_string srslog::sink::write(detail::memory_buffer buffer)=0
Writes the provided memory buffer into the sink.
Referenced by srsgnb::log_sink_spy::write, srsgnb::log_sink_message_spy::write.
virtual detail::error_string srslog::sink::flush()=0
Flushes any buffered contents to the backing store.
Referenced by srsgnb::log_sink_spy::flush, srsgnb::log_sink_message_spy::flush.