srsgnb::pbch_encoder_impl
std::unique_ptr<crc_calculator> srsgnb::pbch_encoder_impl::crc24c
std::unique_ptr<pseudo_random_generator> srsgnb::pbch_encoder_impl::scrambler
std::unique_ptr<polar_interleaver> srsgnb::pbch_encoder_impl::interleaver
std::unique_ptr<polar_allocator> srsgnb::pbch_encoder_impl::alloc
std::unique_ptr<polar_code> srsgnb::pbch_encoder_impl::code
std::unique_ptr<polar_encoder> srsgnb::pbch_encoder_impl::encoder
std::unique_ptr<polar_rate_matcher> srsgnb::pbch_encoder_impl::rm
void pbch_encoder_impl::payload_generate(span< uint8_t > a, const srsgnb::pbch_encoder::pbch_msg_t &msg)
Implements TS 38.312 section 7.1.1 PBCH payload generation.
a Generated payload. msg PBCH message.
References srsgnb::span< T >::size, srsgnb::pbch_encoder::A, srsgnb::pbch_encoder::pbch_msg_t::payload, srsgnb::pbch_encoder::pbch_msg_t::sfn, srsgnb::pbch_encoder::pbch_msg_t::hrf, srsgnb::pbch_encoder::pbch_msg_t::L_max, srsgnb::pbch_encoder::pbch_msg_t::ssb_idx, srsgnb::pbch_encoder::pbch_msg_t::k_ssb.
Referenced by encode.
void pbch_encoder_impl::scramble(span< uint8_t > a_prime, const srsgnb::pbch_encoder::pbch_msg_t &msg, span< const uint8_t > a)
Implements TS 38.312 section 7.1.2 Scrambling.
a_prime Scrambled payload. msg PBCH message. a Payload.
References srsgnb::pbch_encoder::pbch_msg_t::N_id, srsgnb::pbch_encoder::A, srsgnb::pbch_encoder::pbch_msg_t::L_max, srsgnb::pbch_encoder::PAYLOAD_SIZE.
Referenced by encode.
void pbch_encoder_impl::crc_attach(span< uint8_t > b, span< const uint8_t > a_prime)
Implements TS 38.312 section 7.1.3 Transport block CRC attachment.
b Data with CRC attached. a_prime Payload after scrambling.
References srsgnb::span< T >::size, srsgnb::pbch_encoder::A, srsgnb::pbch_encoder::B, srsgnb::span< T >::data, srsgnb::span< T >::first, srsgnb::span< T >::last, srsgnb::pbch_encoder::CRC_LEN.
Referenced by encode.
void pbch_encoder_impl::channel_coding(span< uint8_t > d, span< const uint8_t > c)
Implements TS 38.312 section 7.1.4 Channel coding.
d Encoded data. c Payload after scrambling.
References srsgnb::span< T >::size, srsgnb::pbch_encoder::B, srsgnb::pbch_encoder::POLAR_N_MAX.
Referenced by encode.
void pbch_encoder_impl::rate_matching(span< uint8_t > f, span< const uint8_t > d)
Implements TS 38.312 section 7.1.5 Rate matching.
f Rate matched data. d Encoded data.
References srsgnb::span< T >::size, srsgnb::pbch_encoder::POLAR_N_MAX, srsgnb::pbch_encoder::E.
Referenced by encode.
srsgnb::pbch_encoder_impl::pbch_encoder_impl(std::unique_ptr< crc_calculator > crc24c_, std::unique_ptr< pseudo_random_generator > scrambler_, std::unique_ptr< polar_interleaver > interleaver_, std::unique_ptr< polar_allocator > allocator_, std::unique_ptr< polar_code > code_, std::unique_ptr< polar_encoder > encoder_, std::unique_ptr< polar_rate_matcher > rm_)
Constructs a generic PBCH encoder.
References srsgnb::pbch_encoder::B, srsgnb::pbch_encoder::E, srsgnb::pbch_encoder::POLAR_N_MAX_LOG.
void pbch_encoder_impl::encode(span< uint8_t > encoded, const pbch_msg_t &pbch_msg) override
Encodes a PBCH message.
encoded Encoded data. pbch_msg PBCH message to encode.
References srsgnb::span< T >::size, srsgnb::pbch_encoder::E, payload_generate, scramble, crc_attach, channel_coding, rate_matching.