srsgnb::rb_allocation
bounded_bitset<MAX_RB> srsgnb::rb_allocation::vrb_mask
Indicates, with a mask, the VRBs selected for the transmission.
Referenced by operator==, is_contiguous, get_prb_begin, get_prb_end, get_nof_rb, get_contiguous_prb_mask, get_other_prb_mask, get_prb_mask, get_prb_indices.
vrb_to_prb_mapper srsgnb::rb_allocation::vrb_to_prb_map
VRB-to-PRB mapper.
Referenced by operator==, is_contiguous, get_prb_begin, get_prb_end, get_contiguous_prb_mask, get_other_prb_mask, get_prb_mask, get_prb_indices.
bounded_bitset< MAX_RB > rb_allocation::get_contiguous_prb_mask(unsigned bwp_start_rb, unsigned bwp_size_rb) const
Computes the PRB allocation mask if the resultant allocation is contiguous and non-interleaved.
bwp_start_rb Indicates the BWP start PRB index relative to CRB0 (PointA). bwp_size_rb Indicates the BWP size in PRB units.
References vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::get_coreset_start, vrb_mask, srsgnb::bounded_bitset< N, reversed >::count, srsgnb::bounded_bitset< N, reversed >::find_lowest, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::find_highest, srsgnb::bounded_bitset< N, reversed >::fill.
Referenced by get_prb_mask.
bounded_bitset< MAX_RB > rb_allocation::get_other_prb_mask(unsigned bwp_start_rb, unsigned bwp_size_rb) const
Computes the PRB allocation mask for the cases not covered by get_contiguous_prb_mask().
bwp_start_rb Indicates the BWP start PRB index relative to CRB0 (PointA). bwp_size_rb Indicates the BWP size in PRB units.
References vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::get_allocation_indices, vrb_mask, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::test.
Referenced by get_prb_mask.
srsgnb::rb_allocation::rb_allocation()=default
Default constructor.
It constructs an empty allocation with default VRB-to-PRB mapping.
bool srsgnb::rb_allocation::operator==(const rb_allocation &other) const
Compares two frequency domain allocations.
Two allocations are considered equal if: their VRB masks are equal, and the VRB-to-PRB mapping is equal.
References vrb_mask, vrb_to_prb_map.
bool srsgnb::rb_allocation::is_contiguous() const
Determines if resultant VRB-to-PRB allocation is contiguous in frequency domain.
The PRB allocation is contiguous if: the VRB allocated for the transmission are contiguous, and the VRB-to-PRB mapping is not interleaved. True if the PRB allocation is contiguous. Otherwise, false.
References vrb_mask, srsgnb::bounded_bitset< N, reversed >::is_contiguous, vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::is_interleaved.
Referenced by srsgnb::pdsch_modulator_impl::modulate.
unsigned srsgnb::rb_allocation::get_prb_begin(unsigned bwp_start_rb) const
Gets the lowest allocated PRB index.
bwp_start_rb Indicates the BWP lowest PRB index relative to CRB0. A PRB index relative to CRB0 (PointA) if there are active VRB. Otherwise, zero.
References vrb_mask, srsgnb::bounded_bitset< N, reversed >::find_lowest, srsgnb::bounded_bitset< N, reversed >::size, vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::get_coreset_start.
Referenced by srsgnb::pdsch_modulator_impl::map_to_contiguous_prb.
unsigned srsgnb::rb_allocation::get_prb_end(unsigned bwp_start_rb) const
Gets the highest allocated PRB index plus one.
bwp_start_rb Indicates the BWP lowest PRB index relative to CRB0. A non-zero PRB index relative to CRB0 (PointA) if there are active VRB. Otherwise, zero.
References vrb_mask, srsgnb::bounded_bitset< N, reversed >::find_highest, srsgnb::bounded_bitset< N, reversed >::size, vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::get_coreset_start.
Referenced by srsgnb::pdsch_modulator_impl::map_to_contiguous_prb.
unsigned srsgnb::rb_allocation::get_nof_rb() const
Gets the number of allocated VRB.
References vrb_mask, srsgnb::bounded_bitset< N, reversed >::count.
Referenced by srsgnb::pdsch_processor_impl::compute_nof_data_re, srsgnb::pusch_demodulator_impl::demodulate.
bounded_bitset< MAX_RB > rb_allocation::get_prb_mask(unsigned bwp_start_rb, unsigned bwp_size_rb) const
Generates the PRB allocation mask for the frequency domain allocation.
Calculates the PRB allocation mask considering the BWP frequency allocation, the VRB mask and the VRB-to-PRB mapping. The resultant mask is represented in a bounded_bitset<MAX_RB> of size $N_{BWP,i}^{start}+N_{BWP,i}^{size}$ in which every set bit represents an active PRB. The first bit of the mask belongs to CRB0 (PointA). bwp_start_rb Indicates the BWP lowest PRB index relative to CRB0 (PointA) as $N_{BWP,i}^{start}$. bwp_size_rb Indicates the BWP size in PRB as $N_{BWP,i}^{size}$. The PRB allocation mask represented as a bounded bitset.
References srsgnb::MAX_RB, vrb_mask, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::is_contiguous, vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::is_interleaved, get_contiguous_prb_mask, get_other_prb_mask.
Referenced by srsgnb::pdsch_processor_impl::compute_nof_data_re, srsgnb::pdsch_processor_impl::put_dmrs.
static_vector< uint16_t, MAX_RB > rb_allocation::get_prb_indices(unsigned bwp_start_rb, unsigned bwp_size_rb) const
Generates the PRB allocation indexes for the frequency domain allocation.
Calculates the PRB allocation indexes considering the BWP frequency allocation, the VRB mask and the VRB-to-PRB mapping. The resultant indices are represented in a static_vector<uint16_t,MAX_RB> of size $N_{BWP,i}^{start}+N_{BWP,i}^{size}$. The indices are relative to CRB0 (PointA) and they are indexed in VRB increasing order. In other words, the first index indicates the PRB index of the lowest active VRB. Correspondingly, the last index corresponds to the highest active VRB. This method is intended for non-contiguous and/or interleaved allocation. For contiguous non-interleaved transmission use get_prb_begin() and get_prb_end(). bwp_start_rb Indicates the BWP lowest PRB index relative to CRB0 (PointA) as $N_{BWP,i}^{start}$. bwp_size_rb Indicates the BWP size in PRB as $N_{BWP,i}^{size}$. The resultant PRB allocation indices represented as a static vector.
References srsgnb::MAX_RB, vrb_mask, srsgnb::bounded_bitset< N, reversed >::size, vrb_to_prb_map, srsgnb::vrb_to_prb_mapper::get_allocation_indices, srsgnb::bounded_bitset< N, reversed >::test.
Referenced by srsgnb::pdsch_modulator_impl::map_to_prb_other.
rb_allocation srsgnb::rb_allocation::make_type0(const bounded_bitset< MAX_RB > &vrb_bitmap, const optional< vrb_to_prb_mapper > &vrb_to_prb_map_={})
Creates a Type 0 RB allocation object.
Type 0 allocation is described in TS38.214 Section 5.1.2.2.1 for PDSCH and Section 6.1.2.2.1 for PUSCH. vrb_bitmap VRB allocation bitmap in which each entry represents an active RB. vrb_to_prb_map_ Optional VRB-to-PRB mapping (for PDSCH only). An RB allocation instance.
rb_allocation srsgnb::rb_allocation::make_type1(unsigned rb_start, unsigned rb_count, const optional< vrb_to_prb_mapper > &vrb_to_prb_map_={})
Creates a Type 1 RB allocation object.
Type 1 allocation is described in TS38.214 Section 5.1.2.2.2 for PDSCH and Section 6.1.2.2.2 for PUSCH. rb_start Indicates the lowest VRB used for this transmission as $RB_{start}$. rb_count Indicates the number of consecutive active VRB for this transmission as $L_{RB_s}$. vrb_to_prb_map_ Optional VRB-to-PRB mapping (for PDSCH only). An RB allocation instance.
rb_allocation srsgnb::rb_allocation::make_custom(std::initializer_list< const unsigned > vrb_indexes, const optional< vrb_to_prb_mapper > &vrb_to_prb_map_={})
Creates a custom allocation object using a list of VRB indexes.
The custom allocation is indexed for testing and it is not described in the TS. The VRB mask is constructed from an integer initializer list that indicates the VRBs used for the PDSCH or PUSCH transmission. The index list order is irrelevant and the index zero represents VRB0. vrb_indexes Provides the VRB indexes. vrb_to_prb_map_ Optional VRB-to-PRB mapping (for PDSCH only). An RB allocation instance.