srsgnb::pdu_rx_handler
mac_common_config_t& srsgnb::pdu_rx_handler::cfg
srslog::basic_logger& srsgnb::pdu_rx_handler::logger
scheduler_feedback_handler& srsgnb::pdu_rx_handler::sched
mac_ul_ue_manager& srsgnb::pdu_rx_handler::ue_manager
du_rnti_table& srsgnb::pdu_rx_handler::rnti_table
pdu_rx_handler::pdu_rx_handler(mac_common_config_t &cfg_, scheduler_feedback_handler &sched_, mac_ul_ue_manager &ue_manager_, du_rnti_table &rnti_table_)
bool pdu_rx_handler::handle_rx_pdu(slot_point sl_rx, du_cell_index_t cell_index, mac_rx_pdu pdu)
Decode MAC Rx PDU, log contents and handle subPDUs. sl_rx Slot when MAC UL PDU was received. cell_index Cell index where MAC UL PDU was received. pdu MAC UL PDU received. true if all subPDUs were correctly handled.
References handle_crnti_ce, handle_rx_subpdus.
bool pdu_rx_handler::push_ul_ccch_msg(du_ue_index_t ue_index, byte_buffer ul_ccch_msg)
Called to push stored UL CCCH to upper layers, once the UE has been created in the DU manager.
References srsgnb::byte_buffer::length.
bool pdu_rx_handler::handle_rx_subpdus(decoded_mac_rx_pdu &pdu)
Handle subPDUs contained in a MAC UL PDU. pdu MAC UL PDU being processed. true if all subPDUs were correctly handled.
References srsgnb::decoded_mac_rx_pdu::ue_index, srsgnb::decoded_mac_rx_pdu::decoded_subpdus, srsgnb::lcid_ul_sch_t::is_sdu, handle_sdu, handle_mac_ce.
Referenced by handle_rx_pdu, handle_crnti_ce.
bool pdu_rx_handler::handle_sdu(const decoded_mac_rx_pdu &ctx, const mac_ul_sch_subpdu &sdu, mac_ul_ue_context *ue)
Handle UL SDU targetted at LCIDs >= 1. pdu MAC UL PDU being processed. subpdu subPDU of PDU where CRNTI CE was detected. ue MAC UL UE object for which the sdu is directed. true if correctly handled.
References srsgnb::decoded_mac_rx_pdu::cell_index_rx, srsgnb::decoded_mac_rx_pdu::pdu_rx.
Referenced by handle_rx_subpdus.
bool pdu_rx_handler::handle_mac_ce(decoded_mac_rx_pdu &pdu, const mac_ul_sch_subpdu &subpdu)
Handle UL MAC CE. pdu MAC UL PDU being processed. subpdu subPDU of PDU where CRNTI CE was detected. true if correctly handled.
References srsgnb::lcid_ul_sch_t::CCCH_SIZE_48, srsgnb::lcid_ul_sch_t::CCCH_SIZE_64, handle_ccch_msg, srsgnb::decode_sbsr, srsgnb::make_sched_lcg_report, srsgnb::decoded_mac_rx_pdu::cell_index_rx, srsgnb::decoded_mac_rx_pdu::ue_index, srsgnb::decoded_mac_rx_pdu::pdu_rx, srsgnb::MAX_LOGICAL_CHANNEL_GROUP, srsgnb::decode_lbsr, srsgnb::long_bsr_report::list.
Referenced by handle_rx_subpdus.
bool pdu_rx_handler::handle_ccch_msg(decoded_mac_rx_pdu &pdu, const mac_ul_sch_subpdu &sdu)
Handle UL CCCH Message pdu MAC UL PDU being processed. subpdu subPDU of PDU where CRNTI CE was detected. true if correctly handled.
References srsgnb::decoded_mac_rx_pdu::pdu_rx, srsgnb::decoded_mac_rx_pdu::cell_index_rx, srsgnb::decoded_mac_rx_pdu::slot_rx.
Referenced by handle_mac_ce.
bool pdu_rx_handler::handle_crnti_ce(decoded_mac_rx_pdu &pdu, const mac_ul_sch_subpdu &subpdu)
Handle CRNTI MAC CE see TS 38.321, 6.1.3.2 - C-RNTI MAC CE pdu MAC UL PDU being processed. subpdu subPDU of PDU where CRNTI CE was detected. true if correctly handled.
References srsgnb::decoded_mac_rx_pdu::pdu_rx, srsgnb::decode_crnti_ce, srsgnb::decoded_mac_rx_pdu::ue_index, srsgnb::du_l2_ul_executor_mapper::executor, srsgnb::task_executor::execute, handle_rx_subpdus, srsgnb::decoded_mac_rx_pdu::cell_index_rx.
Referenced by handle_rx_pdu.