srslog::backend_worker
detail::work_queue<detail::log_entry>& srslog::backend_worker::queue
detail::dyn_arg_store_pool& srslog::backend_worker::arg_pool
detail::shared_variable<bool> srslog::backend_worker::running_flag
error_handler srslog::backend_worker::err_handler
std::once_flag srslog::backend_worker::start_once_flag
std::thread srslog::backend_worker::worker_thread
fmt::memory_buffer srslog::backend_worker::fmt_buffer
srslog::backend_worker::backend_worker(detail::work_queue< detail::log_entry > &queue, detail::dyn_arg_store_pool &arg_pool)
srslog::backend_worker::backend_worker(const backend_worker &)=delete
backend_worker& srslog::backend_worker::operator=(const backend_worker &)=delete
srslog::backend_worker::~backend_worker()
void backend_worker::start(backend_priority priority)
Starts the backend worker thread. After returning from this function the secondary thread is ensured to be running. Calling this function more than once has no effect.
References create_worker.
void backend_worker::stop()
Stops the backend worker thread if it is running, otherwise the call has no effect. After returning from this function the secondary thread is ensured to have terminated. Calling this function more than once has no effect.
Referenced by srslog::log_backend_impl::stop.
bool srslog::backend_worker::is_running() const
Returns true if the worker thread is currently running, otherwise returns false.
Referenced by set_error_handler, srslog::log_backend_impl::is_running.
void srslog::backend_worker::set_error_handler(error_handler new_err_handler)
Uses the specified error handler to receive error notifications. Calls to this method when the worker is running will get ignored.
References is_running.
Referenced by srslog::log_backend_impl::set_error_handler.
void backend_worker::create_worker(backend_priority priority)
Creates the worker thread. NOTE: This function should be only called once.
References set_thread_priority, do_work.
Referenced by start.
void backend_worker::do_work()
Entry function used by the secondary thread.
References report_queue_on_full_once, process_log_entry, process_outstanding_entries.
Referenced by create_worker.
void backend_worker::process_log_entry(detail::log_entry &&entry)
Processes the log entry.
References srslog::detail::dyn_arg_store_pool::dealloc.
Referenced by do_work, process_outstanding_entries.
void backend_worker::process_outstanding_entries()
Processes outstanding entries in the queue until it gets empty.
References process_log_entry.
Referenced by do_work.
void srslog::backend_worker::report_queue_on_full_once()
Checks the current size of the queue reporting an error message if it is about to reach its maximum capacity. Error message is only reported once to avoid spamming.
References srslog::detail::work_queue< T, capacity >::is_almost_full, srslog::detail::work_queue< T, capacity >::get_capacity.
Referenced by do_work.
void backend_worker::set_thread_priority(backend_priority priority) const
Establishes the specified thread priority for the calling thread.
Referenced by create_worker.