srsgnb::rx_softbuffer_codeblock_pool
std::vector<entry> srsgnb::rx_softbuffer_codeblock_pool::entries
Stores all codeblock entries.
Referenced by rx_softbuffer_codeblock_pool, reserve, free, get_soft_bits, get_data_bits.
constexpr unsigned srsgnb::rx_softbuffer_codeblock_pool::UNRESERVED_CB_ID
Default CB identifier for unreserved codeblocks.
Referenced by reserve, free, srsgnb::rx_softbuffer_impl::reserve.
srsgnb::rx_softbuffer_codeblock_pool::rx_softbuffer_codeblock_pool(unsigned nof_codeblocks, unsigned max_codeblock_size)
Creates a receive buffer codeblock pool.
nof_codeblocks Indicates the maximum number of codeblocks. max_codeblock_size Indicates the maximum codeblock size.
References entries, srsgnb::divide_ceil.
unsigned srsgnb::rx_softbuffer_codeblock_pool::reserve()
Reserves a codeblock softbuffer.
The codeblock identifier in the pool if it is reserved successfully. Otherwise, UNRESERVED_CB_ID
References entries, UNRESERVED_CB_ID.
Referenced by srsgnb::rx_softbuffer_impl::reserve.
void srsgnb::rx_softbuffer_codeblock_pool::free(unsigned cb_id)
Frees a codeblock softbuffer.
cb_id Indicates the codeblock identifier in the pool.
References UNRESERVED_CB_ID, entries.
Referenced by srsgnb::rx_softbuffer_impl::free.
span<log_likelihood_ratio> srsgnb::rx_softbuffer_codeblock_pool::get_soft_bits(unsigned cb_id)
Gets a codeblock soft-bit buffer.
cb_id Indicates the codeblock identifier. A view to the codeblock soft-bit buffer.
References entries.
Referenced by srsgnb::rx_softbuffer_impl::get_codeblock_soft_bits.
span<uint8_t> srsgnb::rx_softbuffer_codeblock_pool::get_data_bits(unsigned cb_id)
Gets a codeblock data-bit buffer.
cb_id Indicates the codeblock identifier. A view to the codeblock data-bit buffer.
References entries.
Referenced by srsgnb::rx_softbuffer_impl::get_codeblock_data_bits.