srslog::detail::logger_impl
using srslog::detail::logger_impl< T, Enum >::enum_base_type = typename std::underlying_type<Enum>::type
constexpr unsigned srslog::detail::logger_impl< T, Enum >::size
const std::string srslog::detail::logger_impl< T, Enum >::logger_id
const std::array<log_channel*, size> srslog::detail::logger_impl< T, Enum >::channels
detail::mutex srslog::detail::logger_impl< T, Enum >::m
srslog::detail::logger_impl< T, Enum >::logger_impl(std::string id, Args &&... args)
srslog::detail::logger_impl< T, Enum >::logger_impl(const logger_impl &other)=delete
logger_impl& srslog::detail::logger_impl< T, Enum >::operator=(const logger_impl &other)=delete
const std::string& srslog::detail::logger_impl< T, Enum >::id() const
Returns the id string of the logger.
void srslog::detail::logger_impl< T, Enum >::set_level(Enum lvl)
Change the logging level.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl.
void srslog::detail::logger_impl< T, Enum >::set_context(uint32_t x)
Set the specified context value to all the channels of the logger.
Referenced by srsgnb::phy_error_adapter::on_late_resource_grid, srsgnb::phy_error_adapter::on_prach_request_late, srsgnb::phy_error_adapter::on_prach_request_overflow, srsgnb::lower_phy_impl::process_symbol.
void srslog::detail::logger_impl< T, Enum >::set_hex_dump_max_size(int x)
Set the maximum number of bytes to can be printed in a hex dump to all the channels of the logger.
bool operator<=(Enum lhs, Enum rhs)
Comparison operator for enum types, used by the set_level method.