srsgnb::du_l2_ul_executor_mapper
virtual srsgnb::du_l2_ul_executor_mapper::~du_l2_ul_executor_mapper()=default
virtual task_executor& srsgnb::du_l2_ul_executor_mapper::rebind_executor(du_ue_index_t ue_index, du_cell_index_t pcell_index)=0
Method to signal the detection of a new UE and potentially change its executor based on its parameters (e.g. PCell). ue_index Index of the UE. pcell_index Primary Cell of the new UE. task executor of this UE.
virtual task_executor& srsgnb::du_l2_ul_executor_mapper::executor(du_ue_index_t ue_index)=0
Method to return the executor to which a UE is currently binded. ue_index Index of the UE. task executor of the UE with given UE Index.
Referenced by srsgnb::mac_ul_processor::handle_rx_data_indication, srsgnb::pdu_rx_handler::handle_crnti_ce.
task_executor& srsgnb::du_l2_ul_executor_mapper::executor()
Method to return the default executor with no associated UE index. ue_index Index of the UE. task executor.
References executor.
Referenced by executor, srsgnb::ue_index_based_ul_executor_mapper::rebind_executor.