srsgnb::prach_buffer
virtual srsgnb::prach_buffer::~prach_buffer()=default
Default destructor.
virtual unsigned srsgnb::prach_buffer::get_sequence_length() const =0
Gets the sequence length.
Referenced by srsgnb::prach_detector_simple_impl::detect.
virtual unsigned srsgnb::prach_buffer::get_max_nof_symbols() const =0
Gets the maximum number of symbols.
virtual span<cf_t> srsgnb::prach_buffer::get_symbol(unsigned symbol_index)=0
Gets a read-write view of a PRACH OFDM symbol.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::prach_detector_simple_impl::detect.
virtual span<const cf_t> srsgnb::prach_buffer::get_symbol(unsigned symbol_index) const =0
Gets a read-only view of a PRACH OFDM symbol.