srsgnb::rx_softbuffer_impl
rx_softbuffer_identifier srsgnb::rx_softbuffer_impl::reservation_id
Reservation identifier.
Referenced by reserve, match_id.
slot_point srsgnb::rx_softbuffer_impl::reservation_expire_slot
Indicates the slot the softbuffer will expire at.
Referenced by reserve, run_slot.
rx_softbuffer_codeblock_pool& srsgnb::rx_softbuffer_impl::codeblock_pool
Reference to the codeblock pool.
Referenced by reserve, free, get_codeblock_soft_bits, get_codeblock_data_bits.
static_vector<bool, MAX_NOF_SEGMENTS> srsgnb::rx_softbuffer_impl::crc
Stores codeblocks CRCs.
Referenced by reserve, get_nof_codeblocks, reset_codeblocks_crc, get_codeblocks_crc.
static_vector<unsigned, MAX_NOF_SEGMENTS> srsgnb::rx_softbuffer_impl::codeblock_ids
Stores codeblock identifiers.
Referenced by reserve, free, is_reserved, get_codeblock_soft_bits, get_codeblock_data_bits.
srsgnb::rx_softbuffer_impl::rx_softbuffer_impl(rx_softbuffer_codeblock_pool &pool)
Creates a receive softbuffer.
pool Provides the codeblock softbuffer pool.
void srsgnb::rx_softbuffer_impl::reserve(const rx_softbuffer_identifier &id, const slot_point &expire_slot, unsigned int nof_codeblocks)
Reserves the buffer.
id Indicates the reservation identifier. expire_slot Indicates the slot at which the reservation expires. nof_codeblocks Indicates the number of codeblocks to reserve.
References reservation_id, reservation_expire_slot, codeblock_ids, free, crc, srsgnb::rx_softbuffer_codeblock_pool::UNRESERVED_CB_ID, codeblock_pool, srsgnb::rx_softbuffer_codeblock_pool::reserve.
void srsgnb::rx_softbuffer_impl::free()
Returns the reservation to the pool.
References codeblock_ids, codeblock_pool, srsgnb::rx_softbuffer_codeblock_pool::free.
Referenced by reserve, run_slot.
void srsgnb::rx_softbuffer_impl::run_slot(const slot_point &slot)
Releases buffers that expire at the current slot.
slot Indicates the current slot.
References is_reserved, reservation_expire_slot, free.
bool srsgnb::rx_softbuffer_impl::match_id(const rx_softbuffer_identifier &identifier) const
Determines if the buffer matches the given identifier.
References is_reserved, reservation_id.
bool srsgnb::rx_softbuffer_impl::is_reserved() const
Check if the softbuffer is reserved.
References codeblock_ids.
Referenced by run_slot, match_id, get_nof_codeblocks, reset_codeblocks_crc, get_codeblocks_crc, get_codeblock_soft_bits, get_codeblock_data_bits.
unsigned srsgnb::rx_softbuffer_impl::get_nof_codeblocks() const override
Gets the number of codeblocks.
References is_reserved, crc.
void srsgnb::rx_softbuffer_impl::reset_codeblocks_crc() override
Resets all codeblocks CRCs.
References is_reserved, crc.
span<bool> srsgnb::rx_softbuffer_impl::get_codeblocks_crc() override
Gets all codeblocks CRCs.
A view of the codeblocks CRCs: each entry represents the CRC state of a codeblock.
References is_reserved, crc.
span<log_likelihood_ratio> srsgnb::rx_softbuffer_impl::get_codeblock_soft_bits(unsigned codeblock_id, unsigned codeblock_size) override
Gets a codeblock soft-bit buffer.
codeblock_id Indicates the codeblock identifier. codeblock_size Indicates the codeblock size. A view of the codeblock soft bits. The codeblock identifier must not exceed get_max_nof_codeblocks()-1.
References is_reserved, codeblock_ids, codeblock_pool, srsgnb::rx_softbuffer_codeblock_pool::get_soft_bits.
span<uint8_t> srsgnb::rx_softbuffer_impl::get_codeblock_data_bits(unsigned codeblock_id, unsigned data_size) override
Gets a codeblock data-bit buffer.
codeblock_id Indicates the codeblock identifier. data_size Indicates the data size, i.e. the number of data/information bits in the codeblock. A view of the codeblock data bits (the information message). The codeblock identifier must not exceed get_max_nof_codeblocks()-1. Data bits do not include filler bits, codeblock-specific CRC bits or zero-padding bits.
References is_reserved, codeblock_ids, codeblock_pool, srsgnb::rx_softbuffer_codeblock_pool::get_data_bits, srsgnb::span< T >::size, srsgnb::span< T >::first.