srsgnb::pseudo_random_generator
virtual srsgnb::pseudo_random_generator::~pseudo_random_generator()=default
Default destructor.
virtual void srsgnb::pseudo_random_generator::init(unsigned c_init)=0
Initializes the pseudo-random generator with the given seed.
c_init Initialization seed (parameter $c_{\mathrm{init}}$ in TS38.211 Section 5.2.1).
virtual void srsgnb::pseudo_random_generator::init(const state_s &state)=0
Initializes the pseudo-random generator at the given state.
state Generator internal state description.
virtual state_s srsgnb::pseudo_random_generator::get_state() const =0
Returns the current state of the pseudo-random generator.
virtual void srsgnb::pseudo_random_generator::advance(unsigned count)=0
Advances the pseudo-random generator state without generating sequence bits or applying any mask.
count Number of state advance steps (corresponds to the number of sequence bits that would be generated by the same state advance).
Referenced by srsgnb::dmrs_sequence_generate.
virtual void srsgnb::pseudo_random_generator::apply_xor_byte(span< uint8_t > out, span< const uint8_t > in)=0
XOR-applies the generated sequence to a byte buffer.
The generated sequence is used to scramble (bit-wise XOR each element) the input sequence. Both input and output sequence are represented in packed format (each entry corresponds to 8 bits). out Ouput data sequence. in Input data sequence. Input and output sequences should have the same length. This method modifies the internal state of the pseudo-random generator.
virtual void srsgnb::pseudo_random_generator::apply_xor_bit(span< uint8_t > out, span< const uint8_t > in)=0
XOR-applies the generated sequence to a bit buffer.
The generated sequence is used to scramble (bit-wise XOR each element) the input sequence. Both input and output sequence are represented in unpacked format (each entry corresponds to 1 bit). out Ouput data sequence. in Input data sequence. Input and output sequences should have the same length. This method modifies the internal state of the pseudo-random generator.
virtual void srsgnb::pseudo_random_generator::apply_xor(span< log_likelihood_ratio > out, span< const log_likelihood_ratio > in)=0
XOR-applies the generated sequence to a buffer of log-likelihood ratios.
The generated sequence is used to scramble (bit-wise XOR each element) the input sequence of soft bits. Here, the XOR operation between a log-likelihood ratio $\ell$ and a (pseudo-random) bit $b$ returns $\ell$ if $b = 0$ and $-\ell$ if $b = 1$. out Ouput data sequence. in Input data sequence. Input and output sequences should have the same length. This method modifies the internal state of the pseudo-random generator.
virtual void srsgnb::pseudo_random_generator::generate(span< float > buffer, float value)=0
Generates a floating-point pseudo-random sequence with the given amplitude.
The elements of the generated sequence will have the form $\pm a$, where $a$ denotes the amplitude. buffer Output sequence. value Sequence amplitude. The sequence length is inferred from the size of the output container. This method modifies the internal state of the pseudo-random generator.
Referenced by srsgnb::dmrs_sequence_generate.
virtual void srsgnb::pseudo_random_generator::generate(span< cf_t > buffer, float value)
Generates a complex floating-point pseudo-random sequence with the given amplitude.
The amplitude refers to both parts, real and imaginary, of the sequence. In other words, the elements will have the form $\pm a \pm \mj a$, where $a$ denotes the amplitude. buffer Output sequence. value Sequence amplitude. The sequence length is inferred from the size of the output container. This method modifies the internal state of the pseudo-random generator.
References generate, srsgnb::span< T >::data, srsgnb::span< T >::size.
Referenced by generate.