srsgnb::fapi::dl_tti_request_message_builder
dl_tti_request_message& srsgnb::fapi::dl_tti_request_message_builder::msg
srsgnb::fapi::dl_tti_request_message_builder::dl_tti_request_message_builder(dl_tti_request_message &msg)
Constructs a builder that will help to fill the given DL TTI request message.
dl_tti_request_message_builder& srsgnb::fapi::dl_tti_request_message_builder::set_basic_parameters(uint16_t sfn, uint16_t slot, uint16_t n_group)
Sets the DL_TTI.request basic parameters and returns a reference to the builder. nPDUs and nPDUsOfEachType properties are filled by the add_*_pdu() functions. These parameters are specified in SCF-222 v4.0 section 3.4.2 in table DL_TTI.request message body.
Referenced by srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_downlink_scheduler_results.
dl_pdcch_pdu_builder srsgnb::fapi::dl_tti_request_message_builder::add_pdcch_pdu(unsigned nof_dci_in_pdu)
Adds a PDCCH PDU to the message, fills its basic parameters using the given arguments and returns a PDCCH PDU builder. nof_dci_in_pdu Number of DCIs in the PDCCH PDU.
dl_pdsch_pdu_builder srsgnb::fapi::dl_tti_request_message_builder::add_pdsch_pdu(rnti_t rnti)
Adds a PDSCH PDU to the message, fills its basic parameters using the given arguments and returns a PDSCH PDU builder.
References add_pdsch_pdu, srsgnb::fapi::dl_pdsch_pdu_builder::set_basic_parameters.
dl_pdsch_pdu_builder srsgnb::fapi::dl_tti_request_message_builder::add_pdsch_pdu()
Adds a PDSCH PDU to the message, fills its basic parameters using the given arguments and returns a PDSCH PDU builder.
Referenced by add_pdsch_pdu.
dl_csi_rs_pdu_builder srsgnb::fapi::dl_tti_request_message_builder::add_csi_rs_pdu(uint16_t start_rb, uint16_t nof_rbs, csi_type type, uint8_t row, uint16_t freq_domain, uint8_t symb_l0, uint8_t symb_l1, csi_cdm_type cdm_type, csi_freq_density_type freq_density, uint16_t scrambling_id)
Adds a CSI-RS PDU to the message and returns a CSI-RS PDU builder.
dl_ssb_pdu_builder srsgnb::fapi::dl_tti_request_message_builder::add_ssb_pdu(pci_t phys_cell_id, beta_pss_profile_type beta_pss_profile_nr, uint8_t ssb_block_index, uint8_t ssb_subcarrier_offset, uint16_t ssb_offset_pointA)
Adds a SSB PDU to the message, fills its basic parameters using the given arguments and returns a SSB PDU builder.
References add_ssb_pdu, srsgnb::fapi::dl_ssb_pdu_builder::set_basic_parameters.
dl_ssb_pdu_builder srsgnb::fapi::dl_tti_request_message_builder::add_ssb_pdu()
Adds a SSB PDU to the message and returns a SSB PDU builder.
Referenced by add_ssb_pdu.