srslog::file_sink
const size_t srslog::file_sink::max_size
const bool srslog::file_sink::force_flush
const std::string srslog::file_sink::base_filename
file_utils::file srslog::file_sink::handler
size_t srslog::file_sink::current_size
uint32_t srslog::file_sink::file_index
srslog::file_sink::file_sink(std::string name, size_t max_size, bool force_flush, std::unique_ptr< log_formatter > f)
srslog::file_sink::file_sink(const file_sink &other)=delete
file_sink& srslog::file_sink::operator=(const file_sink &other)=delete
detail::error_string srslog::file_sink::write(detail::memory_buffer buffer) override
Writes the provided memory buffer into the sink.
References is_first_write, create_file, handle_rotation, srslog::detail::memory_buffer::size, flush, srslog::file_utils::file::write.
detail::error_string srslog::file_sink::flush() override
Flushes any buffered contents to the backing store.
References srslog::file_utils::file::flush.
Referenced by write.
uint32_t srslog::file_sink::get_file_index() const
Returns the current file index.
bool srslog::file_sink::is_first_write() const
Returns true when the sink has never written data to a file, otherwise returns false.
Referenced by write.
detail::error_string srslog::file_sink::create_file()
Creates a new file and increments the file index counter.
References srslog::file_utils::file::create.
Referenced by write, handle_rotation.
detail::error_string srslog::file_sink::handle_rotation(size_t size)
Handles the file rotation feature when it is activated. NOTE: The file handler must be valid.
References create_file.
Referenced by write.