srsgnb::cell_slot_resource_grid
friend struct cell_resource_allocator
std::vector<carrier_resource_grid> srsgnb::cell_slot_resource_grid::carrier_grids
Carrier Resource Grids.
Referenced by clear.
std::array<unsigned, NOF_NUMEROLOGIES> srsgnb::cell_slot_resource_grid::numerology_to_grid_idx
cell_slot_resource_grid::cell_slot_resource_grid(span< const scs_specific_carrier > scs_carriers)
void cell_slot_resource_grid::clear()
Reset the resource grid to empty.
References carrier_grids.
Referenced by srsgnb::cell_slot_resource_allocator::clear.
void cell_slot_resource_grid::fill(grant_info grant)
Allocates the symbol x RB range in the cell resource grid. prbs PRB interval of the allocation. PRB=0 corresponds to the first PRB of the BWP. symbols OFDM symbol interval of the allocation.
References srsgnb::grant_info::crbs.
Referenced by srsgnb::prach_scheduler::run_slot, srsgnb::ra_scheduler::fill_rar_grant, srsgnb::sib1_scheduler::allocate_sib1, srsgnb::schedule_ssb, srsgnb::pdcch_scheduler_impl::pdcch_slot_allocator::allocate_cce.
bool cell_slot_resource_grid::collides(grant_info grant) const
Checks whether the provided symbol x RB range collides with any other allocation in the cell resource grid. grant contains the symbol x RB range whose available we want to check. true if at least one symbol x RB of grant is currently occupied in the resource grid.
References srsgnb::cell_slot_resource_grid::carrier_resource_grid::subslot_rbs, srsgnb::carrier_subslot_resource_grid::collides, srsgnb::grant_info::crbs.
Referenced by srsgnb::prach_scheduler::run_slot, srsgnb::pdcch_scheduler_impl::pdcch_slot_allocator::allocate_cce.
bool cell_slot_resource_grid::collides(subcarrier_spacing scs, ofdm_symbol_range ofdm_symbols, crb_interval crbs) const
prb_bitmap cell_slot_resource_grid::used_crbs(const bwp_configuration &bwp_cfg, ofdm_symbol_range symbols) const
Calculates a bitmap where each bit set to one represents a CRB that is occupied or unavailable. A CRB is considered occupied if it is outside of the provided BWP CRB boundaries or if it is already allocated in at least one OFDM symbol of the provided OFDM symbol range.
bwp_cfg Bandwidth configuration for which the allocation is to be made. symbols Range of OFDM symbols, where the search for available CRBs is carrier out. a CRB bitmap with bits set to one for unavailable CRBs.
References srsgnb::cell_slot_resource_grid::carrier_resource_grid::subslot_rbs, srsgnb::carrier_subslot_resource_grid::used_crbs, srsgnb::bwp_configuration::crbs.
Referenced by srsgnb::ra_scheduler::schedule_rar, srsgnb::sib1_scheduler::allocate_sib1.
bool cell_slot_resource_grid::all_set(grant_info grant) const
Checks whether all the provided symbol x RB range in the cell resource grid are set. grant contains the symbol x RB range to be tested. true if all symbols x RBs of grant are currently set in the resource grid.
References srsgnb::grant_info::crbs.
bool cell_slot_resource_grid::all_set(subcarrier_spacing scs, ofdm_symbol_range ofdm_symbols, crb_interval crbs) const
cell_slot_resource_grid::carrier_resource_grid & cell_slot_resource_grid::get_carrier(subcarrier_spacing scs)
const cell_slot_resource_grid::carrier_resource_grid & cell_slot_resource_grid::get_carrier(subcarrier_spacing scs) const