srsgnb::upper_phy_rx_symbol_handler
virtual srsgnb::upper_phy_rx_symbol_handler::~upper_phy_rx_symbol_handler()=default
Default destructor.
virtual void srsgnb::upper_phy_rx_symbol_handler::handle_rx_symbol(const upper_phy_rx_symbol_context &context, const resource_grid_reader &grid)=0
Handles the reception of an OFDM symbol.
context Notification context: specifies sector, slot and symbol. grid Resource grid for the current slot (encompasses all receive antenna ports).
Referenced by srsgnb::phy_rx_symbol_adapter::on_rx_symbol.
virtual void srsgnb::upper_phy_rx_symbol_handler::handle_rx_prach_window(const prach_buffer_context &context, const prach_buffer &buffer)=0
Handles the arrival of PRACH sequences.
context PRACH context: specifies sector, slot and window. buffer Read-only buffer containing the PRACH sequence.
Referenced by srsgnb::phy_rx_symbol_adapter::on_rx_prach_window.
virtual void srsgnb::upper_phy_rx_symbol_handler::handle_rx_srs_symbol(const upper_phy_rx_symbol_context &context)=0
Handles the arrival of SRS packets at a given symbol.
context Notification context: specifies sector, slot and symbol.
Referenced by srsgnb::phy_rx_symbol_adapter::on_rx_srs_symbol.