srsgnb::dmrs_pbch_processor_impl
const unsigned srsgnb::dmrs_pbch_processor_impl::NOF_RE
DMRS PBCH Sequence length in the SSB.
Referenced by generation.
std::unique_ptr<pseudo_random_generator> srsgnb::dmrs_pbch_processor_impl::prg
unsigned dmrs_pbch_processor_impl::c_init(const config_t &config)
Computes the initial pseudo-random state.
config provides the required parameters to calculate the value the initial pseudo-random state
References srsgnb::dmrs_pbch_processor::config_t::ssb_idx, srsgnb::dmrs_pbch_processor::config_t::hrf, srsgnb::dmrs_pbch_processor::config_t::L_max, srsgnb::dmrs_pbch_processor::config_t::phys_cell_id.
Referenced by generation.
void dmrs_pbch_processor_impl::generation(std::array< cf_t, NOF_RE > &sequence, const config_t &config) const
Implements TS 38.211 section 7.4.1.4.1 Sequence generation.
sequence provides the destination of the sequence generation config provides the required fields to generate the signal
References c_init, NOF_RE.
Referenced by map.
void dmrs_pbch_processor_impl::mapping(const std::array< cf_t, NOF_RE > &sequence, resource_grid_writer &grid, const config_t &config) const
Implements TS 38.211 section 7.4.1.4.2 Mapping to physical resources.
sequence provides the source of the sequence grid provides the grid destination to map the signal config provides the required fields to map the signal
References srsgnb::dmrs_pbch_processor::config_t::phys_cell_id, srsgnb::dmrs_pbch_processor::config_t::ssb_first_symbol, srsgnb::dmrs_pbch_processor::config_t::ssb_first_subcarrier, srsgnb::SSB_BW_RE, srsgnb::dmrs_pbch_processor::config_t::ports, srsgnb::resource_grid_writer::put.
Referenced by map.
srsgnb::dmrs_pbch_processor_impl::dmrs_pbch_processor_impl(std::unique_ptr< pseudo_random_generator > pseudo_random_generator)
void dmrs_pbch_processor_impl::map(resource_grid_writer &grid, const config_t &config) override
Generates and maps DM-RS for PBCH.
grid Destination resource grid. config Configuration to generate and map the signal.
References generation, mapping.