srsgnb::polar_decoder_impl
node_rate
See function rate_0_node().
srsvec::aligned_vec<log_likelihood_ratio> srsgnb::polar_decoder_impl::llr_alloc
LLR values for stage 0 (i.e., received LLRs).
Referenced by polar_decoder_impl.
std::vector<log_likelihood_ratio*> srsgnb::polar_decoder_impl::llr0
Pointers to the upper half of the LLR values for all stages.
Referenced by polar_decoder_impl, init, rate_1_node, rate_r_node.
std::vector<log_likelihood_ratio*> srsgnb::polar_decoder_impl::llr1
Pointers to the lower half of LLR values for all stages.
Referenced by polar_decoder_impl, init, rate_r_node.
srsvec::aligned_vec<uint8_t> srsgnb::polar_decoder_impl::est_bit
Temporary estimated bits.
Referenced by polar_decoder_impl, init, rate_1_node, rate_r_node.
params_s srsgnb::polar_decoder_impl::param
Decoder inner parameters.
Referenced by polar_decoder_impl, init, rate_0_node, rate_1_node, rate_r_node, simplified_node.
state_s srsgnb::polar_decoder_impl::state
Decoder state.
Referenced by polar_decoder_impl, init, rate_0_node, rate_1_node, rate_r_node, simplified_node.
tmp_node_s srsgnb::polar_decoder_impl::tmp_node_type
Node type manager.
Referenced by init.
std::unique_ptr<polar_encoder> srsgnb::polar_decoder_impl::enc
A polar encoder.
Referenced by rate_1_node.
void polar_decoder_impl::init(span< uint8_t > data_decoded, span< const log_likelihood_ratio > input_llr, uint8_t code_size_log, span< const uint16_t > frozen_set)
Polar decoder initialization.
Initializes internal parameters and registers. data_decoded Register for writing the decoded data. input_llr Input codeblock as a sequence of log-likelihood ratios. code_size_log Codeblock size (binary logarithm thereof). frozen_set Indices of the frozen bits.
References param, srsgnb::polar_decoder_impl::params_s::code_size_log, srsgnb::polar_decoder_impl::params_s::code_stage_size, srsgnb::span< T >::first, est_bit, llr0, llr1, state, srsgnb::polar_decoder_impl::state_s::stage, srsgnb::polar_decoder_impl::state_s::active_node_per_stage, srsgnb::polar_decoder_impl::state_s::flag_finished, tmp_node_type, srsgnb::polar_decoder_impl::tmp_node_s::compute, srsgnb::polar_decoder_impl::params_s::node_type.
Referenced by decode.
void polar_decoder_impl::rate_0_node()
Updates a RATE_0 node.
All decoded bits below a RATE_0 node are 0. The function updates the p->state->active_node_per_stage pointer to point to the next active node. It is assumed that message bits are initialized to 0.
References param, srsgnb::polar_decoder_impl::params_s::code_size_log, srsgnb::polar_decoder_impl::params_s::code_stage_size, state, srsgnb::polar_decoder_impl::state_s::active_node_per_stage, srsgnb::polar_decoder_impl::state_s::stage, srsgnb::polar_decoder_impl::state_s::flag_finished.
Referenced by simplified_node.
void polar_decoder_impl::rate_1_node(span< uint8_t > data_decoded)
Updates a RATE_1 node.
RATE_1 nodes at stage $ s $ return the associated $2^s$ estimated bits by making a hard decision on them. RATE_1 nodes also update message bits vector.
References state, srsgnb::polar_decoder_impl::state_s::stage, srsgnb::polar_decoder_impl::state_s::active_node_per_stage, param, srsgnb::polar_decoder_impl::params_s::code_stage_size, srsgnb::polar_decoder_impl::params_s::code_size_log, est_bit, srsgnb::span< T >::subspan, llr0, enc, srsgnb::polar_decoder_impl::state_s::flag_finished.
Referenced by simplified_node.
void polar_decoder_impl::rate_r_node(span< uint8_t > data_decoded)
Updates a RATE_R node.
RATE_R nodes at stage $ s $ return the associated $2^s$ decoded bit by calling the child nodes to the right and left of the decoding tree and then polar encoding (xor) their output.
References state, srsgnb::polar_decoder_impl::state_s::stage, param, srsgnb::polar_decoder_impl::params_s::code_stage_size, llr0, llr1, simplified_node, srsgnb::polar_decoder_impl::state_s::flag_finished, srsgnb::polar_decoder_impl::state_s::active_node_per_stage, est_bit, srsgnb::span< T >::data.
Referenced by simplified_node.
void polar_decoder_impl::simplified_node(span< uint8_t > data_decoded)
Node processing.
Switches between the different types of node for the SSC algorithm. Nodes in the decoding tree at stage $ s$ get the $2^s$ LLRs from the parent node and return the associated $2^s$ estimated bits.
References state, srsgnb::polar_decoder_impl::state_s::stage, srsgnb::polar_decoder_impl::state_s::active_node_per_stage, param, srsgnb::polar_decoder_impl::params_s::node_type, RATE_1, rate_1_node, RATE_0, rate_0_node, RATE_R, rate_r_node.
Referenced by rate_r_node, decode.
polar_decoder_impl::polar_decoder_impl(std::unique_ptr< polar_encoder > enc_, uint8_t nMax)
Polar decoder initialization.
Initializes all the polar decoder variables according to the Simplified Successive Cancellation (SSC) decoder algorithm and the maximum given code size. enc A polar encoder. code_size_log The $ log_2$ of the number of bits of the decoder input/output vector. A unique pointer to the initialized SSC polar decoder.
References param, srsgnb::polar_decoder_impl::params_s::code_stage_size, state, srsgnb::polar_decoder_impl::state_s::active_node_per_stage, est_bit, llr0, llr1, llr_alloc, srsgnb::polar_decoder_impl::params_s::node_type_alloc, srsgnb::polar_decoder_impl::params_s::node_type.
void polar_decoder_impl::decode(span< uint8_t > data_decoded, span< const log_likelihood_ratio > input_llr, const polar_code &code) override
Decodes the input (LLR) codeword with the specified polar decoder.
data_decoded The decoder output vector. input_llr The decoder LLR input vector. code Polar code descriptor.
References init, simplified_node.