srsgnb::detail::base_slot_array
using srsgnb::detail::base_slot_array< Vec >::base_t = base_slot_array_view<Vec>
using srsgnb::detail::base_slot_array< Vec >::value_type = typename base_slot_array_view<Vec>::value_type
using srsgnb::detail::base_slot_array< Vec >::iterator = typename base_slot_array_view<Vec>::iterator
using srsgnb::detail::base_slot_array< Vec >::const_iterator = typename base_slot_array_view<Vec>::const_iterator
constexpr srsgnb::detail::base_slot_array< Vec >::base_slot_array()=default
srsgnb::detail::base_slot_array< Vec >::base_slot_array(const base_slot_array &)=default
srsgnb::detail::base_slot_array< Vec >::base_slot_array(base_slot_array &&other) noexcept
base_slot_array& srsgnb::detail::base_slot_array< Vec >::operator=(const base_slot_array &)=default
base_slot_array& srsgnb::detail::base_slot_array< Vec >::operator=(base_slot_array &&other) noexcept
void srsgnb::detail::base_slot_array< Vec >::clear() noexcept
Clear all elements of the container.
void srsgnb::detail::base_slot_array< Vec >::erase(size_t idx) noexcept
Erase object pointed by the given index idx Position of the erased element in the array
Referenced by srsgnb::slot_vector< srsgnb::mac_sdu_rx_notifier * >::erase.
void srsgnb::detail::base_slot_array< Vec >::erase(iterator it) noexcept
Erase object pointed by the given iterator. Iterator must point to valid element it container iterator
void srsgnb::detail::base_slot_array< Vec >::insert(size_t idx, U &&u)
Insert given object in given index idx Position of the constructed element in the array u object to insert
Referenced by srsgnb::slot_vector< srsgnb::mac_sdu_rx_notifier * >::insert.
void srsgnb::detail::base_slot_array< Vec >::emplace(size_t idx, Args &&... args)
Overwrite array element with given index with a newly constructed object idx Position of the constructed element in the array args Arguments to pass to element ctor
Referenced by srsgnb::slot_vector< srsgnb::mac_sdu_rx_notifier * >::emplace.