srslog::detail::memory_buffer
const char* const srslog::detail::memory_buffer::buffer
const size_t srslog::detail::memory_buffer::length
srslog::detail::memory_buffer::memory_buffer(const char *buffer, size_t length)
srslog::detail::memory_buffer::memory_buffer(const std::string &s)
const char* srslog::detail::memory_buffer::data() const
Returns a pointer to the start of the memory block.
Referenced by srsgnb::log_sink_spy::write, srsgnb::log_sink_message_spy::write, srslog::file_utils::file::write, srslog::stream_sink::write, srslog::syslog_sink::write.
const char* srslog::detail::memory_buffer::begin() const
Returns an iterator to the beginning of the buffer.
Referenced by srslog::buffered_file_sink::write.
const char* srslog::detail::memory_buffer::end() const
Returns an iterator to the end of the buffer.
Referenced by srslog::buffered_file_sink::write.
size_t srslog::detail::memory_buffer::size() const
Returns the size of the memory block.
Referenced by srslog::file_sink::write, srsgnb::log_sink_spy::write, srsgnb::log_sink_message_spy::write, srslog::buffered_file_sink::write, srslog::file_utils::file::write, srslog::stream_sink::write, srslog::syslog_sink::write.