srsgnb::phy_time_unit
using srsgnb::phy_time_unit::value_type = int64_t
Internal value type. It uses 64-bit word to avoid intermediate multiplications to overflow.
constexpr value_type srsgnb::phy_time_unit::MAX_SCS_HZ
Maximum subcarrier spacing in hertz, constant $\Delta f_{max}$.
constexpr value_type srsgnb::phy_time_unit::N_F
Constant $N_f$.
constexpr double srsgnb::phy_time_unit::T_C
Reference time unit in seconds, that is $T_c = 1/(\Delta f_{max} \times N_f)$.
Referenced by to_seconds, from_seconds.
constexpr value_type srsgnb::phy_time_unit::SCS_REF_HZ
Reference subcarrier spacing, constant $\Delta f_{ref}$.
Referenced by is_sample_accurate, to_samples.
constexpr value_type srsgnb::phy_time_unit::N_F_REF
DFT size for the reference subcarrier spacing, constant $N_{f,ref}$.
Referenced by is_sample_accurate, to_samples.
constexpr value_type srsgnb::phy_time_unit::KAPPA
Constant $\kappa=T_s/T_c=64$.
Referenced by is_sample_accurate, to_samples, to_Ta, from_units_of_kappa.
value_type srsgnb::phy_time_unit::value
Actual value as a multiple of $T_c$.
Referenced by to_seconds, is_sample_accurate, to_samples, to_Ta, operator+, operator+=, operator-, operator-=.
constexpr srsgnb::phy_time_unit::phy_time_unit(value_type value_)
Private constructor from a value in units of $T_c$.
srsgnb::phy_time_unit::phy_time_unit()=default
Creates a default physical layer time of zero units.
Referenced by from_units_of_kappa, from_units_of_Tc, from_seconds.
constexpr U srsgnb::phy_time_unit::to_seconds() const
Gets the time in seconds.
U Return type. Must be a floating point type (default: double).
References value, T_C.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl.
constexpr bool srsgnb::phy_time_unit::is_sample_accurate(U sampling_rate_Hz_) const
Determines if the time value is sample accurate given a sampling rate in hertz.
The time value is sample accurate if the time is equivalent to an integer number of samples for the given sampling rate. U Any data type that can be converted to value_type. sampling_rate_Hz Sample rate in hertz. True if the time is equivalent to an integer number of samples, false otherwise.
References value, SCS_REF_HZ, N_F_REF, KAPPA.
Referenced by srsgnb::cyclic_prefix::is_valid, to_samples.
constexpr unsigned srsgnb::phy_time_unit::to_samples(U sampling_rate_Hz_) const
Gets the time expressed as a number of samples for the given sampling rate.
An assertion is triggered if the result would be a non-integer number of samples. U Any data type that can be converted to value_type. scs Subcarrier spacing in hertz. dft_size DFT size corresponding to the subcarrier spacing. The time value in samples.
References is_sample_accurate, value, SCS_REF_HZ, N_F_REF, KAPPA.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl, srsgnb::lower_phy_impl::get_rx_to_tx_delay, srsgnb::ofdm_symbol_demodulator_impl::get_cp_offset, srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::ofdm_symbol_demodulator_impl::get_symbol_size, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_symbol_modulator_impl::get_symbol_size, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::phase_compensation_lut::phase_compensation_lut.
constexpr unsigned srsgnb::phy_time_unit::to_Ta(subcarrier_spacing scs) const
Gets the time expressed in units of $T_{\mathrm{A}}$.
Conversion is performed as per TS38.213 Section 4.2. scs Subcarrier spacing.
References value, srsgnb::pow2, srsgnb::to_numerology_value, KAPPA.
Referenced by srsgnb::ra_scheduler::fill_rar_grant.
constexpr phy_time_unit srsgnb::phy_time_unit::operator+(phy_time_unit other)
Overload addition operator.
References value.
constexpr phy_time_unit srsgnb::phy_time_unit::operator+=(phy_time_unit other)
Overload addition operator.
References value.
constexpr phy_time_unit srsgnb::phy_time_unit::operator-(phy_time_unit other)
Overload subtraction operator.
References value.
constexpr phy_time_unit srsgnb::phy_time_unit::operator-=(phy_time_unit other)
Overload subtraction operator.
References value.
static constexpr phy_time_unit srsgnb::phy_time_unit::from_units_of_kappa(unsigned units_of_kappa)
Creates a physical layer time from units of $\kappa$.
References phy_time_unit, KAPPA.
Referenced by srsgnb::cyclic_prefix::is_valid, srsgnb::cyclic_prefix::get_length, srsgnb::get_prach_preamble_long_info.
static constexpr phy_time_unit srsgnb::phy_time_unit::from_units_of_Tc(unsigned units_of_Tc)
Creates a physical layer time from units of $T_c$.
References phy_time_unit.
Referenced by srsgnb::lower_phy_impl::get_rx_to_tx_delay.
static constexpr phy_time_unit srsgnb::phy_time_unit::from_seconds(double seconds)
Creates a physical layer time from seconds.
References phy_time_unit, T_C.
Referenced by srsgnb::lower_phy_impl::get_rx_to_tx_delay, srsgnb::prach_detector_simple_impl::detect.