srsgnb::benchmarker
std::string srsgnb::benchmarker::title
Benchmark main title.
Referenced by print_percentile_header.
unsigned srsgnb::benchmarker::nof_repetitions
Number of repetitions.
Referenced by print_percentile_header, print_percentiles_time, print_percentiles_throughput, new_measure.
std::vector<benchmark_result> srsgnb::benchmarker::benchmark_results
Collects different measurements.
Referenced by get_max_meas_time_ns, get_description_width, print_percentiles_time, print_percentiles_throughput, new_measure.
std::pair<unsigned, unsigned> srsgnb::benchmarker::get_max_meas_time_ns() const
Get the maximum measured execution time.
A pair of values containing the maximum execution time and the number of elements in order.
References benchmark_results.
Referenced by get_percentile_width_time, get_percentile_width_throughput.
unsigned srsgnb::benchmarker::get_percentile_width_time() const
Get percentile column width for execution time.
References get_max_meas_time_ns.
Referenced by print_percentiles_time.
unsigned srsgnb::benchmarker::get_percentile_width_throughput() const
Get percentile column width for execution throughput.
References get_max_meas_time_ns, convert_to_throughput.
Referenced by print_percentiles_throughput.
unsigned srsgnb::benchmarker::get_description_width() const
Get description column width.
References benchmark_results.
Referenced by print_percentiles_time, print_percentiles_throughput.
void srsgnb::benchmarker::print_percentile_header(unsigned descr_width, unsigned percentile_width, const std::string &units) const
Prints the percentile header.
descr_width Description column width. percentile_width Percentiles column width. units Units displayed in the header.
References title, nof_repetitions.
Referenced by print_percentiles_time, print_percentiles_throughput.
static double srsgnb::benchmarker::convert_to_throughput(unsigned time_ns, unsigned size)
Converts a measurement into throughput in millions of elements per second.
time_ns Execution time in nanoseconds. size Number of elements processed during the measurement. The calculated throughput.
Referenced by get_percentile_width_throughput, print_percentiles_throughput.
srsgnb::benchmarker::benchmarker(const std::string &title_, unsigned nof_repetitions_)
Creates a bench marker.
title_ Indicates the benchmark title for the percentile report. nof_repetitions_ Indicates the number of repetitions of the function to measure the performance.
void srsgnb::benchmarker::print_percentiles_time() const
Prints the time execution measurements in nanoseconds.
References get_percentile_width_time, get_description_width, print_percentile_header, benchmark_results, nof_repetitions.
void srsgnb::benchmarker::print_percentiles_throughput(const std::string &units) const
Prints the throughput measurements in millions of elements per seconds.
units Units counted in the throughput (ie. bits, symbols, etc.).
References get_percentile_width_throughput, get_description_width, print_percentile_header, benchmark_results, convert_to_throughput, nof_repetitions.
void srsgnb::benchmarker::new_measure(const std::string &description, unsigned size, Func &&function)
Performs a new performance measurement.
Func Lambda type to perform the benchmark. description Measurement description for later reporting. size Number of elements processed in the measurement. function Lambda function to call repeatedly.
References nof_repetitions, benchmark_results.