srsgnb::rx_softbuffer
virtual srsgnb::rx_softbuffer::~rx_softbuffer()=default
Default destructor.
virtual unsigned srsgnb::rx_softbuffer::get_nof_codeblocks() const =0
Gets the number of codeblocks.
Referenced by srsgnb::pusch_decoder_impl::decode.
virtual void srsgnb::rx_softbuffer::reset_codeblocks_crc()=0
Resets all codeblocks CRCs.
Referenced by srsgnb::pusch_decoder_impl::decode.
virtual span<bool> srsgnb::rx_softbuffer::get_codeblocks_crc()=0
Gets all codeblocks CRCs.
A view of the codeblocks CRCs: each entry represents the CRC state of a codeblock.
Referenced by srsgnb::pusch_decoder_impl::decode.
virtual span<log_likelihood_ratio> srsgnb::rx_softbuffer::get_codeblock_soft_bits(unsigned codeblock_id, unsigned codeblock_size)=0
Gets a codeblock soft-bit buffer.
codeblock_id Indicates the codeblock identifier. codeblock_size Indicates the codeblock size. A view of the codeblock soft bits. The codeblock identifier must not exceed get_max_nof_codeblocks()-1.
Referenced by srsgnb::pusch_decoder_impl::decode.
virtual span<uint8_t> srsgnb::rx_softbuffer::get_codeblock_data_bits(unsigned codeblock_id, unsigned data_size)=0
Gets a codeblock data-bit buffer.
codeblock_id Indicates the codeblock identifier. data_size Indicates the data size, i.e. the number of data/information bits in the codeblock. A view of the codeblock data bits (the information message). The codeblock identifier must not exceed get_max_nof_codeblocks()-1. Data bits do not include filler bits, codeblock-specific CRC bits or zero-padding bits.
Referenced by srsgnb::pusch_decoder_impl::decode.