srsgnb::span
using srsgnb::span< T >::element_type = T
Member types.
using srsgnb::span< T >::value_type = typename std::remove_cv<T>::type
using srsgnb::span< T >::size_type = std::size_t
using srsgnb::span< T >::difference_type = std::ptrdiff_t
using srsgnb::span< T >::pointer = element_type*
using srsgnb::span< T >::const_pointer = const element_type*
using srsgnb::span< T >::reference = element_type&
using srsgnb::span< T >::const_reference = const element_type&
using srsgnb::span< T >::iterator = pointer
using srsgnb::span< T >::reverse_iterator = std::reverse_iterator<iterator>
pointer srsgnb::span< T >::ptr
size_type srsgnb::span< T >::len
constexpr srsgnb::span< T >::span() noexcept=default
Constructs an empty span with data() == nullptr and size() == 0.
constexpr srsgnb::span< T >::span(pointer ptr_, size_type len_) noexcept
Constructs a span that is a view over the range [ptr, ptr + len).
constexpr srsgnb::span< T >::span(pointer first, pointer last) noexcept
Constructs a span that is a view over the range [first, last).
constexpr srsgnb::span< T >::span(element_type(&arr)[N]) noexcept
Constructs a span that is a view over the array arr.
constexpr srsgnb::span< T >::span(std::array< U, N > &arr) noexcept
Constructs a span that is a view over the array arr.
constexpr srsgnb::span< T >::span(const std::array< U, N > &arr) noexcept
Constructs a span that is a view over the array arr.
constexpr srsgnb::span< T >::span(Container &c) noexcept
Constructs a span that is a view over the container c.
constexpr srsgnb::span< T >::span(const Container &c) noexcept
Constructs a span that is a view over the container c.
constexpr srsgnb::span< T >::span(const span< U > &other) noexcept
span& srsgnb::span< T >::operator=(const span &other) noexcept=default
srsgnb::span< T >::~span() noexcept=default
constexpr size_type srsgnb::span< T >::size() const noexcept
Returns the number of elements in the span.
Referenced by srsgnb::span< const uint8_t >::empty, srsgnb::span< const uint8_t >::back, srsgnb::span< const uint8_t >::end, srsgnb::span< const uint8_t >::first, srsgnb::span< const uint8_t >::last, srsgnb::span< const uint8_t >::subspan, srsgnb::fapi::dl_pdsch_pdu_builder::set_cbg_re_tx_ctrl_parameters, srsgnb::fapi::dl_pdsch_pdu_builder::set_maintenance_v3_rm_references_parameters, srsgnb::fapi::tx_data_request_builder::add_pdu_custom_payload, srsgnb::fapi::ul_pucch_pdu_builder::add_uci_part1_part2_corresnpondence_v3, srsgnb::fapi::ul_pusch_pdu_builder::add_uci_part1_part2_corresnpondence_v3, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::low_papr_sequence_collection::low_papr_sequence_collection, srsgnb::pseudo_random_generator::generate, srsgnb::srsvec::average_power, srsgnb::dft_processor_fftw_impl::get_size, srsgnb::dft_processor_fftx_impl::run, srsgnb::dft_processor_fftx_impl::get_size, srsgnb::dft_processor_generic_impl::get_size, srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::ofdm_slot_demodulator_impl::demodulate, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_slot_modulator_impl::modulate, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::prach_processor_worker::accumulate_samples, srsgnb::resource_grid_impl::put, srsgnb::resource_grid_impl::get, srsgnb::crc_calculator_impl::calculate_bit, srsgnb::ldpc_decoder_impl::decode, srsgnb::ldpc_decoder_generic::compute_var_to_check_msgs, srsgnb::ldpc_decoder_generic::get_hard_bits, srsgnb::ldpc_encoder_impl::encode, srsgnb::ldpc_encoder_generic::write_codeblock, srsgnb::ldpc_rate_dematcher_impl::rate_dematch, srsgnb::ldpc_rate_dematcher_impl::allot_llrs, srsgnb::ldpc_rate_dematcher_impl::deinterleave_llrs, srsgnb::ldpc_rate_matcher_impl::rate_match, srsgnb::ldpc_rate_matcher_impl::select_bits, srsgnb::ldpc_segmenter_impl::segment, srsgnb::polar_interleaver_impl::interleave, srsgnb::short_block_detector_impl::detect_3_11, srsgnb::short_block_detector_impl::detect, srsgnb::short_block_encoder_impl::encode, srsgnb::demodulation_mapper_impl::demodulate_soft, srsgnb::modulation_mapper_impl::modulate, srsgnb::pbch_encoder_impl::payload_generate, srsgnb::pbch_encoder_impl::crc_attach, srsgnb::pbch_encoder_impl::channel_coding, srsgnb::pbch_encoder_impl::rate_matching, srsgnb::pbch_encoder_impl::encode, srsgnb::pbch_modulator_impl::put, srsgnb::pdcch_encoder_impl::crc_attach, srsgnb::pdcch_encoder_impl::channel_coding, srsgnb::pdcch_encoder_impl::encode, srsgnb::pdsch_encoder_impl::encode, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pusch_decoder_impl::decode, srsgnb::re_pattern::get_inclusion_mask, srsgnb::re_pattern::get_exclusion_mask, srsgnb::rx_softbuffer_impl::get_codeblock_data_bits, srsgnb::low_papr_sequence_generator_impl::r_uv_arg_mprb, srsgnb::low_papr_sequence_generator_impl::r_uv_arg, srsgnb::low_papr_sequence_generator_impl::cexp, srsgnb::low_papr_sequence_generator_impl::generate, srsgnb::pseudo_random_generator_impl::generate, srsgnb::pseudo_random_generator_impl::apply_xor_byte, srsgnb::pseudo_random_generator_impl::apply_xor_bit, srsgnb::pseudo_random_generator_impl::apply_xor, srsgnb::csi_rs_processor_impl::build_grid_allocation, srsgnb::csi_rs_processor_impl::apply_cdm, srsgnb::dmrs_sequence_generate, srsgnb::dmrs_pdsch_processor_impl::mapping, srsgnb::ra_scheduler::fill_rar_grant, srsgnb::srsvec::dot_prod.
constexpr size_type srsgnb::span< T >::size_bytes() const noexcept
Returns the size of the sequence in bytes.
constexpr bool srsgnb::span< T >::empty() const noexcept
Checks if the span is empty.
Referenced by srsgnb::span< const uint8_t >::front, srsgnb::span< const uint8_t >::back, srsgnb::srsvec::average_power, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::dmrs_pucch_processor_format1_impl::sequence_generation.
reference srsgnb::span< T >::front() const
Returns a reference to the first element in the span. NOTE: Calling front on an empty span results in undefined behavior.
reference srsgnb::span< T >::back() const
Returns a reference to the last element in the span. NOTE: Calling back on an empty span results in undefined behavior.
reference srsgnb::span< T >::operator[](size_type idx) const
Returns a reference to the idx-th element of the sequence. NOTE: The behavior is undefined if idx is out of range.
constexpr pointer srsgnb::span< T >::data() const noexcept
Returns a pointer to the beginning of the sequence.
Referenced by srsgnb::byte_buffer::deep_copy, srsgnb::span< const uint8_t >::front, srsgnb::span< const uint8_t >::back, srsgnb::span< const uint8_t >::begin, srsgnb::span< const uint8_t >::end, srsgnb::span< const uint8_t >::subspan, srsgnb::fapi::tx_data_request_builder::add_pdu_custom_payload, srsgnb::pseudo_random_generator::generate, srsgnb::dft_processor_fftw_impl::dft_processor_fftw_impl, srsgnb::dft_processor_generic_impl::run, srsgnb::crc_calculator_impl::calculate_bit, srsgnb::polar_code_impl::set, srsgnb::polar_decoder_impl::rate_r_node, srsgnb::polar_rate_matcher_impl::rate_match, srsgnb::pbch_encoder_impl::crc_attach, srsgnb::dmrs_pucch_processor_format2_impl::estimate.
constexpr iterator srsgnb::span< T >::begin() const noexcept
Returns an iterator to the first element of the span.
Referenced by srsgnb::span< const uint8_t >::rend, srsgnb::span< const uint8_t >::equals, srsgnb::fapi::dl_pdsch_pdu_builder::set_cbg_re_tx_ctrl_parameters, srsgnb::fapi::dl_pdsch_pdu_builder::set_maintenance_v3_rm_references_parameters, srsgnb::fapi::dl_pdsch_pdu_builder::set_maintenance_v4_basic_parameters, srsgnb::fapi::crc_indication_message_builder::add_pdu, srsgnb::fapi::uci_pusch_pdu_builder::set_harq_parameters, srsgnb::fapi::uci_pusch_pdu_builder::set_csi_part1_parameters, srsgnb::fapi::uci_pusch_pdu_builder::set_csi_part2_parameters, srsgnb::fapi::uci_pucch_pdu_format_0_1_builder::set_harq_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_sr_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_harq_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_csi_part1_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_csi_part2_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_uci_part1_payload, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_uci_part2_payload, srsgnb::fapi::ul_pucch_pdu_builder::add_uci_part1_part2_corresnpondence_v3, srsgnb::fapi::ul_pucch_pdu_builder::set_uci_part1_part2_corresnpondence_v3_basic_parameters, srsgnb::fapi::ul_pusch_pdu_builder::add_uci_part1_part2_corresnpondence_v3, srsgnb::fapi::ul_pusch_pdu_builder::add_optional_pusch_data, srsgnb::fapi::ul_pusch_pdu_builder::add_optional_pusch_ptrs, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::dft_processor_fftx_impl::run, srsgnb::resource_grid_impl::get, srsgnb::ldpc_decoder_generic::load_soft_bits, srsgnb::ldpc_decoder_generic::compute_var_to_check_msgs, srsgnb::ldpc_decoder_generic::get_hard_bits, srsgnb::ldpc_encoder_generic::preprocess_systematic_bits, srsgnb::ldpc_rate_dematcher_impl::allot_llrs, srsgnb::ldpc_rate_matcher_impl::select_bits, srsgnb::short_block_detector_impl::detect_3_11, srsgnb::demodulation_mapper_impl::demodulate_soft, srsgnb::pdcch_encoder_impl::crc_attach, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::pusch_decoder_impl::decode, srsgnb::get_rg_subc_mask.
constexpr iterator srsgnb::span< T >::end() const noexcept
Returns an iterator to the element following the last element of the span.
Referenced by srsgnb::span< const uint8_t >::rbegin, srsgnb::span< const uint8_t >::equals, srsgnb::fapi::dl_pdsch_pdu_builder::set_cbg_re_tx_ctrl_parameters, srsgnb::fapi::dl_pdsch_pdu_builder::set_maintenance_v3_rm_references_parameters, srsgnb::fapi::dl_pdsch_pdu_builder::set_maintenance_v4_basic_parameters, srsgnb::fapi::crc_indication_message_builder::add_pdu, srsgnb::fapi::uci_pusch_pdu_builder::set_harq_parameters, srsgnb::fapi::uci_pusch_pdu_builder::set_csi_part1_parameters, srsgnb::fapi::uci_pusch_pdu_builder::set_csi_part2_parameters, srsgnb::fapi::uci_pucch_pdu_format_0_1_builder::set_harq_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_sr_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_harq_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_csi_part1_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_csi_part2_parameters, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_uci_part1_payload, srsgnb::fapi::uci_pucch_pdu_format_2_3_4_builder::set_uci_part2_payload, srsgnb::fapi::ul_pucch_pdu_builder::add_uci_part1_part2_corresnpondence_v3, srsgnb::fapi::ul_pucch_pdu_builder::set_uci_part1_part2_corresnpondence_v3_basic_parameters, srsgnb::fapi::ul_pusch_pdu_builder::add_uci_part1_part2_corresnpondence_v3, srsgnb::fapi::ul_pusch_pdu_builder::add_optional_pusch_data, srsgnb::fapi::ul_pusch_pdu_builder::add_optional_pusch_ptrs, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::dft_processor_fftx_impl::run, srsgnb::ldpc_decoder_generic::load_soft_bits, srsgnb::ldpc_decoder_generic::compute_var_to_check_msgs, srsgnb::ldpc_encoder_generic::preprocess_systematic_bits, srsgnb::ldpc_rate_dematcher_impl::allot_llrs, srsgnb::short_block_detector_impl::detect_3_11, srsgnb::demodulation_mapper_impl::demodulate_soft, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::pusch_decoder_impl::decode.
constexpr reverse_iterator srsgnb::span< T >::rbegin() const noexcept
Returns a reverse iterator to the first element of the reversed span.
constexpr reverse_iterator srsgnb::span< T >::rend() const noexcept
Returns a reverse iterator to the element following the last element of the reversed span.
span<element_type> srsgnb::span< T >::first(size_type count) const
Obtains a span that is a view over the first count elements of this span. NOTE: The behavior is undefined if count > size().
Referenced by srsgnb::ofdm_slot_demodulator_impl::demodulate, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_slot_modulator_impl::modulate, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::prach_processor_worker::accumulate_samples, srsgnb::ldpc_decoder_impl::decode, srsgnb::ldpc_decoder_generic::update_variable_to_check_messages, srsgnb::ldpc_encoder_generic::preprocess_systematic_bits, srsgnb::ldpc_rate_dematcher_impl::rate_dematch, srsgnb::ldpc_rate_matcher_impl::rate_match, srsgnb::polar_code_impl::set, srsgnb::polar_decoder_impl::init, srsgnb::pbch_encoder_impl::crc_attach, srsgnb::pdcch_encoder_impl::crc_attach, srsgnb::pdsch_encoder_impl::encode, srsgnb::prach_detector_simple_impl::detect, srsgnb::rx_softbuffer_impl::get_codeblock_data_bits, srsgnb::dmrs_sequence_generate, srsgnb::dmrs_pdsch_processor_impl::mapping, srsgnb::pss_processor_impl::generation, srsgnb::dmrs_pucch_processor_format2_impl::sequence_generation, srsgnb::sss_processor_impl::generation.
span<element_type> srsgnb::span< T >::last(size_type count) const
Obtains a span that is a view over the last count elements of this span. NOTE: The behavior is undefined if count > size().
Referenced by srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::ofdm_slot_demodulator_impl::demodulate, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_slot_modulator_impl::modulate, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::resource_grid_impl::put, srsgnb::resource_grid_impl::get, srsgnb::ldpc_encoder_generic::preprocess_systematic_bits, srsgnb::pbch_encoder_impl::crc_attach, srsgnb::pdcch_encoder_impl::crc_attach, srsgnb::prach_detector_simple_impl::detect, srsgnb::dmrs_sequence_generate, srsgnb::pss_processor_impl::generation, srsgnb::sss_processor_impl::generation.
span<element_type> srsgnb::span< T >::subspan(size_type offset, size_type count) const
Obtains a span that is a view over the count elements of this span starting at offset offset.
Referenced by srsgnb::span< const uint8_t >::first, srsgnb::span< const uint8_t >::last, srsgnb::baseband_gateway_buffer_dynamic::get_channel_buffer, srsgnb::channel_estimate::get_path_ch_estimate, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::prach_processor_worker::accumulate_samples, srsgnb::prach_buffer_static< SEQ_LEN, MAX_NOF_SYMB >::get_symbol, srsgnb::resource_grid_impl::put, srsgnb::resource_grid_impl::get, srsgnb::crc_calculator_impl::calculate_bit, srsgnb::ldpc_decoder_generic::update_variable_to_check_messages, srsgnb::ldpc_encoder_generic::preprocess_systematic_bits, srsgnb::ldpc_rate_matcher_impl::select_bits, srsgnb::ldpc_segmenter_impl::segment, srsgnb::polar_code_impl::set, srsgnb::polar_decoder_impl::rate_1_node, srsgnb::pdcch_encoder_impl::crc_attach, srsgnb::pdsch_encoder_impl::encode, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::pusch_decoder_impl::decode, srsgnb::get_rg_subc_mask, srsgnb::csi_rs_processor_impl::map, srsgnb::dmrs_pucch_processor_format1_impl::estimate.
bool srsgnb::span< T >::equals(span rhs) const
Returns true if the input span has the same elements as this.