srsgnb::fapi::ul_tti_request_message_builder
using srsgnb::fapi::ul_tti_request_message_builder::pdu_type = ul_tti_request_message::pdu_type
ul_tti_request_message& srsgnb::fapi::ul_tti_request_message_builder::msg
srsgnb::fapi::ul_tti_request_message_builder::ul_tti_request_message_builder(ul_tti_request_message &msg)
ul_tti_request_message_builder& srsgnb::fapi::ul_tti_request_message_builder::set_basic_parameters(uint16_t sfn, uint16_t slot)
Sets the UL_TTI.request basic parameters and returns a reference to the builder. These parameters are specified in SCF-222 v4.0 section 3.4.3 in table UL_TTI,request message body.
Referenced by srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_uplink_scheduler_results.
ul_prach_pdu_builder srsgnb::fapi::ul_tti_request_message_builder::add_prach_pdu(pci_t pci, uint8_t num_occasions, prach_format_type format_type, uint8_t index_fd_ra, uint8_t prach_start_symbol, uint16_t num_cs)
Adds a PRACH PDU to the message and returns a builder that helps to fill the parameters. These parameters are specified in SCF-222 v4.0 section 3.4.3.1 in table PRACH PDU.
References add_prach_pdu, srsgnb::fapi::ul_prach_pdu_builder::set_basic_parameters.
Referenced by srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_uplink_scheduler_results.
ul_prach_pdu_builder srsgnb::fapi::ul_tti_request_message_builder::add_prach_pdu()
Adds a PRACH PDU to the message and returns a builder that helps to fill the parameters. These parameters are specified in SCF-222 v4.0 section 3.4.3.1 in table PRACH PDU.
Referenced by add_prach_pdu.
ul_pucch_pdu_builder srsgnb::fapi::ul_tti_request_message_builder::add_pucch_pdu(rnti_t rnti, uint32_t handle, pucch_format_type format_type, multi_slot_tx_indicator_type multi_slot_tx_type, bool pi2_bpsk)
Adds a PUCCH format 0/1 PDU to the message and returns a builder that helps to fill the parameters. These parameters are specified in SCF-222 v4.0 section 3.4.3.3 in table PUCCH PDU.
ul_pusch_pdu_builder srsgnb::fapi::ul_tti_request_message_builder::add_pusch_pdu(rnti_t rnti, uint32_t handle)
Adds a PUSCH PDU to the message and returns a builder that helps to fill the parameters. These parameters are specified in SCF-222 v4.0 section 3.4.3.2 in table PUSCH PDU.
References srsgnb::fapi::ul_pusch_pdu_builder::set_basic_parameters.