srslog::text_formatter
bool srslog::text_formatter::do_one_line_ctx_format
Flags that the formatting should take place into a single line.
Referenced by format_context_begin, format_context_end, format_metric_set_begin, format_metric_set_end, format_metric, format_list_begin.
std::vector<scope> srslog::text_formatter::scope_stack
srslog::text_formatter::text_formatter()
std::unique_ptr< log_formatter > text_formatter::clone() const override
Returns a copy of the formatter.
void text_formatter::format(detail::log_entry_metadata &&metadata, fmt::memory_buffer &buffer) override
Formats the log entry into the input buffer.
void text_formatter::format_context_begin(const detail::log_entry_metadata &md, fmt::string_view ctx_name, unsigned size, fmt::memory_buffer &buffer) override
Derived classes should implement the following callbacks to format metric objects. Each callback is invoked at a different place of the formatting algorithm. This callback gets called at the beginning of the context formatting algorithm.
References do_one_line_ctx_format.
void text_formatter::format_context_end(const detail::log_entry_metadata &md, fmt::string_view ctx_name, fmt::memory_buffer &buffer) override
This callback gets called at the end of the context formatting algorithm.
References do_one_line_ctx_format.
void text_formatter::format_metric_set_begin(fmt::string_view set_name, unsigned size, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the beginning of a metric set formatting procedure.
References do_one_line_ctx_format, get_indents.
void text_formatter::format_metric_set_end(fmt::string_view set_name, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the beginning of a metric set formatting end.
References do_one_line_ctx_format.
void text_formatter::format_list_begin(fmt::string_view list_name, unsigned size, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the beginning of a metric list formatting procedure.
References do_one_line_ctx_format, get_indents.
void srslog::text_formatter::format_list_end(fmt::string_view list_name, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the end of a metric list formatting procedure.
void text_formatter::format_metric(fmt::string_view metric_name, fmt::string_view metric_value, fmt::string_view metric_units, metric_kind kind, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called for each metric.
References do_one_line_ctx_format, consume_element, get_current_set_name, needs_comma, get_indents.
const std::string& srslog::text_formatter::get_current_set_name() const
Returns the set name of current scope.
Referenced by format_metric.
void srslog::text_formatter::consume_element()
Consumes an element in the current scope.
Referenced by format_metric.
bool srslog::text_formatter::needs_comma() const
Returns true if the current element needs a comma.
Referenced by format_metric.
unsigned srslog::text_formatter::get_indents(unsigned level) const
Returns the number of indentations required for the input nesting level.
Referenced by format_metric_set_begin, format_metric, format_list_begin.