srsgnb::byte_buffer_segment
using srsgnb::byte_buffer_segment::value_type = uint8_t
using srsgnb::byte_buffer_segment::iterator = uint8_t*
using srsgnb::byte_buffer_segment::const_iterator = const uint8_t*
constexpr static size_t srsgnb::byte_buffer_segment::SEGMENT_SIZE
constexpr static size_t srsgnb::byte_buffer_segment::DEFAULT_HEADROOM
metadata_storage srsgnb::byte_buffer_segment::metadata_
std::array<uint8_t, SEGMENT_SIZE> srsgnb::byte_buffer_segment::buffer
uint8_t* srsgnb::byte_buffer_segment::payload_data_
uint8_t* srsgnb::byte_buffer_segment::payload_data_end_
srsgnb::byte_buffer_segment::byte_buffer_segment(size_t headroom=DEFAULT_HEADROOM)
srsgnb::byte_buffer_segment::byte_buffer_segment(const byte_buffer_segment &other) noexcept
srsgnb::byte_buffer_segment::byte_buffer_segment(byte_buffer_segment &&other) noexcept
byte_buffer_segment& srsgnb::byte_buffer_segment::operator=(const byte_buffer_segment &other) noexcept
byte_buffer_segment& srsgnb::byte_buffer_segment::operator=(byte_buffer_segment &&other) noexcept
bool srsgnb::byte_buffer_segment::empty() const
Checks whether segment has no payload.
size_t srsgnb::byte_buffer_segment::headroom() const
Returns how much space in bytes there is at the head of the segment.
Referenced by prepend, reserve_prepend, resize.
size_t srsgnb::byte_buffer_segment::length() const
Returns size in bytes of segment.
Referenced by trim_head, trim_tail, srsgnb::byte_buffer::trim_tail.
size_t srsgnb::byte_buffer_segment::tailroom() const
Returns how much space in bytes there is at the tail of the segment.
Referenced by append, srsgnb::byte_buffer::append, srsgnb::byte_buffer::resize.
void srsgnb::byte_buffer_segment::append(span< const uint8_t > bytes)
Appends a span of bytes at the tail of the segment.
References append.
Referenced by append, srsgnb::byte_buffer::append.
void srsgnb::byte_buffer_segment::append(It it_begin, It it_end)
Appends a iterator range of bytes at the tail of the segment.
References tailroom.
void srsgnb::byte_buffer_segment::append(uint8_t byte)
Appends single byte at the tail of the segment.
References tailroom.
void srsgnb::byte_buffer_segment::prepend(span< const uint8_t > bytes)
Prepends segment with provided span of bytes.
References headroom.
void srsgnb::byte_buffer_segment::reserve_prepend(size_t nof_bytes)
Reserves headroom space in segment. nof_bytes Number of bytes to reserve.
References headroom.
void srsgnb::byte_buffer_segment::trim_head(size_t nof_bytes)
Removes "nof_bytes" from the head of the segment.
References length.
void srsgnb::byte_buffer_segment::trim_tail(size_t nof_bytes)
Removes "nof_bytes" from the tail of the segment.
References length.
Referenced by srsgnb::byte_buffer::trim_tail.
void srsgnb::byte_buffer_segment::resize(size_t nof_bytes)
Resizes payload of segment.
References headroom.
Referenced by srsgnb::byte_buffer::resize.
uint8_t& srsgnb::byte_buffer_segment::operator[](size_t idx)
const uint8_t& srsgnb::byte_buffer_segment::operator[](size_t idx) const
const uint8_t* srsgnb::byte_buffer_segment::data() const
uint8_t* srsgnb::byte_buffer_segment::data()
uint8_t& srsgnb::byte_buffer_segment::back()
const uint8_t& srsgnb::byte_buffer_segment::back() const
iterator srsgnb::byte_buffer_segment::begin()
iterator srsgnb::byte_buffer_segment::end()
const_iterator srsgnb::byte_buffer_segment::begin() const
const_iterator srsgnb::byte_buffer_segment::end() const
metadata_storage& srsgnb::byte_buffer_segment::metadata()
const metadata_storage& srsgnb::byte_buffer_segment::metadata() const
byte_buffer_segment* srsgnb::byte_buffer_segment::next()
const byte_buffer_segment* srsgnb::byte_buffer_segment::next() const
bool srsgnb::byte_buffer_segment::operator==(const Container &other) const
bool srsgnb::byte_buffer_segment::operator!=(const Container &other) const
static size_t srsgnb::byte_buffer_segment::capacity()
size_t srsgnb::byte_buffer_segment::tailroom_start() const