srsgnb::pseudo_random_generator_impl
constexpr unsigned srsgnb::pseudo_random_generator_impl::SEQUENCE_PAR_BITS
Bitmask for the parallelized bits.
Referenced by advance, generate, apply_xor_byte, apply_xor_bit, apply_xor, step_par_x1, step_par_x2.
constexpr unsigned srsgnb::pseudo_random_generator_impl::SEQUENCE_MASK
Bitmask for the parallelized bits.
Referenced by apply_xor_byte, step_par_x1, step_par_x2.
constexpr unsigned srsgnb::pseudo_random_generator_impl::SEQUENCE_SEED_LEN
Length of the generator seed in bits.
Referenced by srsgnb::pseudo_random_generator_impl::x2_init_s::x2_init_s, srsgnb::pseudo_random_generator_impl::x2_init_s::get, step_par_x1, step_x1, step_par_x2, step_x2.
constexpr unsigned srsgnb::pseudo_random_generator_impl::SEQUENCE_NC
Parameter $N_{\mathrm{C}}$, as defined in TS38.211 Section 5.2.1.
Corresponds to the delay between the state sequences $x_1(n), x_2(n)$ and the output sequence $c(n) = x_1(n + N_{\mathrm{C}}) \oplus x_2(n + N_{\mathrm{C}})$.
Referenced by srsgnb::pseudo_random_generator_impl::x1_init_s::x1_init_s, srsgnb::pseudo_random_generator_impl::x2_init_s::x2_init_s.
const pseudo_random_generator_impl::x1_init_s pseudo_random_generator_impl::x1_init
Sequence $x_1(n)$ initializer object.
Referenced by init.
const pseudo_random_generator_impl::x2_init_s pseudo_random_generator_impl::x2_init
Sequence $x_2(n)$ initializer object.
Referenced by init.
uint32_t srsgnb::pseudo_random_generator_impl::x1
Memory register for sequence $x_1(n)$.
Referenced by srsgnb::pseudo_random_generator_impl::x1_init_s::get, init, advance, generate, apply_xor_byte, apply_xor_bit, apply_xor, get_state.
uint32_t srsgnb::pseudo_random_generator_impl::x2
Memory register for sequence $x_2(n)$.
Referenced by srsgnb::pseudo_random_generator_impl::x2_init_s::get, init, advance, generate, apply_xor_byte, apply_xor_bit, apply_xor, get_state.
static uint32_t srsgnb::pseudo_random_generator_impl::step_par_x1(uint32_t state)
Advances sequence $x_1(n)$ SEQUENCE_PAR_BITS steps simultaneously.
state Current 32-bit long state. New 32-bit long state.
References SEQUENCE_MASK, SEQUENCE_SEED_LEN, SEQUENCE_PAR_BITS.
Referenced by advance, generate, apply_xor_byte, apply_xor_bit, apply_xor.
static uint32_t srsgnb::pseudo_random_generator_impl::step_x1(uint32_t state)
Advances sequence $x_1(n)$ one steps.
state Current 32-bit long state. New 32-bit long state.
References SEQUENCE_SEED_LEN.
Referenced by srsgnb::pseudo_random_generator_impl::x1_init_s::x1_init_s, advance, generate, apply_xor_bit, apply_xor.
static uint32_t srsgnb::pseudo_random_generator_impl::step_par_x2(uint32_t state)
Advances sequence $x_2(n)$ SEQUENCE_PAR_BITS steps simultaneously.
state Current 32-bit long state. New 32-bit long state.
References SEQUENCE_MASK, SEQUENCE_SEED_LEN, SEQUENCE_PAR_BITS.
Referenced by advance, generate, apply_xor_byte, apply_xor_bit, apply_xor.
static uint32_t srsgnb::pseudo_random_generator_impl::step_x2(uint32_t state)
Advances sequence $x_2(n)$ one steps.
state Current 32-bit long state. New 32-bit long state.
References SEQUENCE_SEED_LEN.
Referenced by srsgnb::pseudo_random_generator_impl::x2_init_s::x2_init_s, advance, generate, apply_xor_bit, apply_xor.
srsgnb::pseudo_random_generator_impl::pseudo_random_generator_impl()=default
Default constructor.
void pseudo_random_generator_impl::init(unsigned c_init) override
Initializes the pseudo-random generator with the given seed.
c_init Initialization seed (parameter $c_{\mathrm{init}}$ in TS38.211 Section 5.2.1).
References x1, x1_init, srsgnb::pseudo_random_generator_impl::x1_init_s::get, x2, x2_init, srsgnb::pseudo_random_generator_impl::x2_init_s::get.
void pseudo_random_generator_impl::init(const state_s &c_init) override
Initializes the pseudo-random generator at the given state.
state Generator internal state description.
References x1, srsgnb::pseudo_random_generator::state_s::x1, x2, srsgnb::pseudo_random_generator::state_s::x2.
pseudo_random_generator::state_s pseudo_random_generator_impl::get_state() const override
Returns the current state of the pseudo-random generator.
References x1, x2.
void pseudo_random_generator_impl::advance(unsigned count) override
Advances the pseudo-random generator state without generating sequence bits or applying any mask.
count Number of state advance steps (corresponds to the number of sequence bits that would be generated by the same state advance).
References SEQUENCE_PAR_BITS, x1, step_par_x1, x2, step_par_x2, step_x1, step_x2.
void pseudo_random_generator_impl::apply_xor_byte(span< uint8_t > out, span< const uint8_t > in) override
XOR-applies the generated sequence to a byte buffer.
The generated sequence is used to scramble (bit-wise XOR each element) the input sequence. Both input and output sequence are represented in packed format (each entry corresponds to 8 bits). out Ouput data sequence. in Input data sequence. Input and output sequences should have the same length. This method modifies the internal state of the pseudo-random generator.
References srsgnb::span< T >::size, x1, x2, SEQUENCE_MASK, step_par_x1, step_par_x2, SEQUENCE_PAR_BITS, srsgnb::reverse_byte.
void pseudo_random_generator_impl::apply_xor_bit(span< uint8_t > out, span< const uint8_t > in) override
XOR-applies the generated sequence to a bit buffer.
The generated sequence is used to scramble (bit-wise XOR each element) the input sequence. Both input and output sequence are represented in unpacked format (each entry corresponds to 1 bit). out Ouput data sequence. in Input data sequence. Input and output sequences should have the same length. This method modifies the internal state of the pseudo-random generator.
References srsgnb::span< T >::size, SEQUENCE_PAR_BITS, x1, x2, step_par_x1, step_par_x2, step_x1, step_x2.
void pseudo_random_generator_impl::apply_xor(span< log_likelihood_ratio > out, span< const log_likelihood_ratio > in) override
XOR-applies the generated sequence to a buffer of log-likelihood ratios.
The generated sequence is used to scramble (bit-wise XOR each element) the input sequence of soft bits. Here, the XOR operation between a log-likelihood ratio $\ell$ and a (pseudo-random) bit $b$ returns $\ell$ if $b = 0$ and $-\ell$ if $b = 1$. out Ouput data sequence. in Input data sequence. Input and output sequences should have the same length. This method modifies the internal state of the pseudo-random generator.
References srsgnb::span< T >::size, SEQUENCE_PAR_BITS, x1, x2, step_par_x1, step_par_x2, step_x1, step_x2.
void pseudo_random_generator_impl::generate(span< float > buffer, float value) override
Generates a floating-point pseudo-random sequence with the given amplitude.
The elements of the generated sequence will have the form $\pm a$, where $a$ denotes the amplitude. buffer Output sequence. value Sequence amplitude. The sequence length is inferred from the size of the output container. This method modifies the internal state of the pseudo-random generator.
References srsgnb::span< T >::size, SEQUENCE_PAR_BITS, x1, x2, step_par_x1, step_par_x2, step_x1, step_x2.