srsgnb::log_likelihood_ratio
constexpr srsgnb::log_likelihood_ratio::operator value_type() const
Converts the LLR to a plain value_type value.
References value.
constexpr value_type srsgnb::log_likelihood_ratio::to_value_type() const
Converts the LLR to a plain value_type value.
References value.
constexpr srsgnb::log_likelihood_ratio::operator int() const
Converts the LLR to a plain int value.
References value.
constexpr int srsgnb::log_likelihood_ratio::to_int() const
Converts the LLR to a plain int value.
References value.
Referenced by abs.
constexpr uint8_t srsgnb::log_likelihood_ratio::to_hard_bit() const
Converts the LLR to a hard bit.
By convention, the null LLR indeterminate case returns a 0 bit.
References value.
constexpr bool srsgnb::log_likelihood_ratio::operator==(log_likelihood_ratio rhs) const
Plain comparison operator.
References value.
constexpr bool srsgnb::log_likelihood_ratio::operator!=(log_likelihood_ratio rhs) const
Plain comparison operator.
References value.
constexpr bool srsgnb::log_likelihood_ratio::operator>(log_likelihood_ratio rhs) const
Plain comparison operator.
References value.
constexpr bool srsgnb::log_likelihood_ratio::operator<(log_likelihood_ratio rhs) const
Plain comparison operator.
References value.
constexpr bool srsgnb::log_likelihood_ratio::operator>=(log_likelihood_ratio rhs) const
Plain comparison operator.
References value.
constexpr bool srsgnb::log_likelihood_ratio::operator<=(log_likelihood_ratio rhs) const
Plain comparison operator.
References value.
using srsgnb::log_likelihood_ratio::value_type = int8_t
Alias for the underlying data type used for representing the LLR value.
value_type srsgnb::log_likelihood_ratio::value
Actual LLR value.
Referenced by log_likelihood_ratio, operator value_type, to_value_type, operator int, to_int, to_hard_bit, operator-, operator==, operator!=, operator>, operator<, operator>=, operator<=, isfinite, copysign, soft_xor, operator+=, promotion_sum, quantize.
constexpr value_type srsgnb::log_likelihood_ratio::LLR_INFTY
Represents a log-likelihood ratio set to infinity.
An LLR takes the value LLR_INFTY when the corresponding bit is certainly zero. Similarly, an LLR takes the value -LLR_INFTY when the corresponding bit is certainly one.
Referenced by log_likelihood_ratio, infinity, promotion_sum.
constexpr value_type srsgnb::log_likelihood_ratio::LLR_MAX
Maximum (finite) value of a log-likelihood ratio.
Finite LLRs take values between -LLR_MAX and LLR_MAX (both included).
Referenced by log_likelihood_ratio, max, min, isfinite, operator+=, promotion_sum, quantize.
constexpr srsgnb::log_likelihood_ratio::log_likelihood_ratio()=default
Default constructor.
constexpr srsgnb::log_likelihood_ratio::log_likelihood_ratio(T val)
Constructor from integral type.
Creates a new LLR set to the provided value if the latter is in the range -LLR_MAX to LLR_MAX, or if it is LLR_INFTY. Otherwise, terminates the program execution. T The input type. Must be an integral type. val The value the LLR is set to. Implicit conversions are allowed on purpose.
References LLR_MAX, LLR_INFTY, value.
constexpr log_likelihood_ratio& srsgnb::log_likelihood_ratio::operator=(const log_likelihood_ratio &other)=default
Default assignment operator.
constexpr log_likelihood_ratio srsgnb::log_likelihood_ratio::operator-() const
Negation (additive inverse).
References value.
log_likelihood_ratio srsgnb::log_likelihood_ratio::operator+(log_likelihood_ratio rhs) const
Saturated sum.
The result is clipped if larger (in absolute value) than log_likelihood_ratio::LLR_MAX. Then, for instance, LLR_MAX + 2 = LLR_MAX and -LLR_MAX - 2 = -LLR_MAX.
log_likelihood_ratio log_likelihood_ratio::operator+=(log_likelihood_ratio rhs)
Addition assignment with saturated sum.
References value, LLR_MAX.
log_likelihood_ratio srsgnb::log_likelihood_ratio::operator-(log_likelihood_ratio rhs) const
Saturated difference.
Follows naturally from the saturated sum: a - b = a + (-b).
log_likelihood_ratio srsgnb::log_likelihood_ratio::operator-=(log_likelihood_ratio rhs)
Subtraction assignment with saturated sum.
log_likelihood_ratio log_likelihood_ratio::quantize(float value, float range_limit)
Clips and quantizes a real-valued (float), continuous log-likelihood ratio to the discrete representation of type log_likelihood_ratio.
value The real-valued log-likelihood ratio to quantize. range_limit The input value mapped to LLR_MAX. A quantized representation of value as a log_likelihood_ratio quantity. The quantization in the range (-range_limit, range_limit) is mid-tread uniform, with quantization step range_limit / LLR_MAX . All values larger (in magnitude) than range_limit, will be clipped and mapped to LLR_MAX, depending on their sign.
References value, LLR_MAX.
static constexpr log_likelihood_ratio srsgnb::log_likelihood_ratio::infinity()
Returns the special value "positive infinity".
References LLR_INFTY.
static constexpr log_likelihood_ratio srsgnb::log_likelihood_ratio::max()
Returns the maximum finite LLR value.
References LLR_MAX.
static constexpr log_likelihood_ratio srsgnb::log_likelihood_ratio::min()
Returns the minimum finite LLR value.
References LLR_MAX.
static constexpr bool srsgnb::log_likelihood_ratio::isfinite(log_likelihood_ratio llr)
Checks whether a log-likelihood ratio has a finite value.
References value, LLR_MAX.
Referenced by isinf.
static constexpr bool srsgnb::log_likelihood_ratio::isinf(log_likelihood_ratio llr)
Checks whether a log-likelihood ratio has an infinite value.
References isfinite.
log_likelihood_ratio log_likelihood_ratio::promotion_sum(log_likelihood_ratio a, log_likelihood_ratio b)
Promotion sum.
As opposed to the saturated sum (i.e., log_likelihood_ratio::operator+), results larger (in absolute value) than LLR_MAX are set to LLR_INFTY. a First summand. b Second summand. The promotion sum of a and b.
References value, LLR_MAX, LLR_INFTY.
Referenced by srsgnb::ldpc_decoder_generic::update_soft_bits.
static constexpr log_likelihood_ratio srsgnb::log_likelihood_ratio::copysign(log_likelihood_ratio a, T b)
Copy sign from a number.
T An arithmetic type. a A log-likelihood ratio. b A real number. A log-likelihood ratio with the magnitude of a and the sign of b. A zero in the second argument is considered as a positive number, following the convention of std::copysign.
References value.
Referenced by srsgnb::ldpc_decoder_generic::update_check_to_variable_messages.
static value_type srsgnb::log_likelihood_ratio::abs(log_likelihood_ratio a)
Absolute value.
References to_int.
Referenced by srsgnb::ldpc_decoder_generic::update_check_to_variable_messages.
static log_likelihood_ratio srsgnb::log_likelihood_ratio::soft_xor(log_likelihood_ratio x, log_likelihood_ratio y)
Soft XOR operation.
The soft XOR between two LLRs x and y is the log-likelihood ratio corresponding to the logical XOR operation $a \oplus b$, where $a$ and $b$ are the bits whose soft representation is x and y, respectively. For complexity reasons, the true soft xor function \[ \text{soft_xor}(x, y) = \sign(x y) \cdot \Phi\Bigl(\Phi(\abs{x}) + \Phi(\abs{y})\Bigr) \qquad\text{with } \Phi: \mathbb{R}_+ \to \mathbb{R}_+; u \mapsto \Phi(u) = -\ln\Bigl(\tanh\Bigl(\frac{u}{2}\Bigr)\Bigr) \] is replaced by the common approximation \[ \text{soft_xor}(x, y) \approx \sign(x y) \cdot \min\bigl\{\abs{x}, \abs{y}\bigr\}. \]
References value.
int srsgnb::log_likelihood_ratio::norm_squared(const T &x)
Squared Euclidean norm of a sequence of LLRs.
Computes the squared Euclidean norm (sum of the squares of the elements) of the input sequence of LLRs. T A span (or any container convertible to a span) of a log-likelihood ratios (either constant or volatile). x A sequence of (possibly constant) log-likelihood ratios. The squared Euclidean norm of x as an integer. This function treats the LLRs as real values, thus neither saturation nor promotion apply.
Referenced by srsgnb::short_block_detector_impl::detect_3_11.
V srsgnb::log_likelihood_ratio::dot_prod(const T &x, const U &y, V init)
Dot product of a sequence of LLRs and a sequence of values of an arithmetic type.
Computes the dot product (a.k.a. inner product or scalar product) of the two input sequences, adding an initial offset. T A span (or any container convertible to a span) of log-likelihood ratios (either constant or volatile). U A span (or any container convertible to a span) of an arithmetic type. V Output type (must be compatible with the product of objects of type T and U). x A sequence of (possibly constant) log-likelihood ratios. y A second sequence of values. init Initialization value. The dot product between the two spans plus init, i.e. $ x \cdot y + \mathrm{init} = \sum_i x_i y_i + \mathrm{init}$. The two input spans must have the same length. This function treats the LLRs as real values, thus neither saturation nor promotion apply.
Referenced by srsgnb::short_block_detector_impl::detect_3_11.