srsgnb::srs_cu_cp::du_processor_f1c_interface
virtual srsgnb::srs_cu_cp::du_processor_f1c_interface::~du_processor_f1c_interface()=default
virtual du_index_t srsgnb::srs_cu_cp::du_processor_f1c_interface::get_du_index()=0
Get the DU index.
The DU index.
Referenced by srsgnb::srs_cu_cp::f1ap_du_processor_adapter::get_du_index.
virtual void srsgnb::srs_cu_cp::du_processor_f1c_interface::handle_f1_setup_request(const f1_setup_request_message &msg)=0
Handle the reception of a F1 Setup Request message and transmit the F1 Setup Response or F1 Setup Failure.
msg The received F1 Setup Request message.
Referenced by srsgnb::srs_cu_cp::f1ap_du_processor_adapter::on_f1_setup_request_received.
virtual ue_creation_complete_message srsgnb::srs_cu_cp::du_processor_f1c_interface::handle_ue_creation_request(const ue_creation_message &msg)=0
Create a new UE context.
msg The UE creation message. Returns a UE creation complete message containing the index of the created UE and its SRB notifiers.
Referenced by srsgnb::srs_cu_cp::f1ap_du_processor_adapter::on_create_ue.