srsgnb::srs_du::ssb_freq_position_generator
const unsigned srsgnb::srs_du::ssb_freq_position_generator::dl_arfcn
Parameters that are passed to the constructor.
Referenced by get_ss_ref_hz, get_next_ssb_location.
const unsigned srsgnb::srs_du::ssb_freq_position_generator::n_rbs
Transmission bandwidth configuration $N_{RB}$, as per Table 5.3.2-1, TS 38.104.
const subcarrier_spacing srsgnb::srs_du::ssb_freq_position_generator::scs_common
const subcarrier_spacing srsgnb::srs_du::ssb_freq_position_generator::scs_ssb
double srsgnb::srs_du::ssb_freq_position_generator::point_A_hz
Point A, as per TS 38.211, Section 4.4.4.2, expressed in Hz.
Referenced by find_M_raster, get_next_ssb_location.
double srsgnb::srs_du::ssb_freq_position_generator::f_ref_hz
RF reference frequency (a.k.a. centre frequency), as per TS 38.104, Section 5.4.2.1.
double srsgnb::srs_du::ssb_freq_position_generator::bw_ub_hz
Band upper-bound expressed in Hz. We consider the last subcarrier of the last CRB as band upper-bound.
Referenced by find_M_raster, get_next_ssb_location.
ssb_pattern_case srsgnb::srs_du::ssb_freq_position_generator::ssb_case
SSB case, as per TS 38.213, Section 4.1.
unsigned srsgnb::srs_du::ssb_freq_position_generator::ssb_first_symbol
First symbol where the 1st SSB within the burst gets allocated, as per TS 38.211, Section 4.1.
uint8_t srsgnb::srs_du::ssb_freq_position_generator::max_ss0_idx
Maximum value of row index of Table 13-11, TS 38.213 that can be addressed for a specific configuration.
unsigned srsgnb::srs_du::ssb_freq_position_generator::N_raster
This is the $N$ parameter in the synchronization raster, as per Table 5.4.3.1-1, TS 38.104.
Referenced by find_M_raster, get_next_ssb_location.
unsigned srsgnb::srs_du::ssb_freq_position_generator::M_raster
This is the $M$ parameter in the synchronization raster, as per Table 5.4.3.1-1, TS 38.104.
Referenced by find_M_raster, get_next_ssb_location.
ssb_freq_position_generator::ssb_freq_position_generator(unsigned dl_arfcn, nr_band nr_band, unsigned n_rbs_, subcarrier_spacing scs_common, subcarrier_spacing scs_ssb)
ssb_freq_location ssb_freq_position_generator::get_next_ssb_location()
Return the next viable position of the SSB on the raster, so that the SSB falls within the band CRBs and the SSB subcarriers are aligned with those of the CRBs.
References srsgnb::srs_du::ssb_freq_location::is_valid, dl_arfcn, srsgnb::MIN_ARFCN_3_GHZ_24_5_GHZ, srsgnb::N_UB_SYNC_RASTER_1, srsgnb::N_UB_SYNC_RASTER_2, N_raster, M_raster, find_M_raster, get_ss_ref_hz, point_A_hz, bw_ub_hz, srsgnb::scs_to_khz.
unsigned srsgnb::srs_du::ssb_freq_position_generator::get_ssb_first_symbol() const
unsigned srsgnb::srs_du::ssb_freq_position_generator::get_max_ss0_idx() const
unsigned ssb_freq_position_generator::find_M_raster()
Finds the $M$ parameter of the sync raster so that the SSB subcarriers are aligned to those of the CRBs.
References M_raster, get_ss_ref_hz, N_raster, point_A_hz, bw_ub_hz, srsgnb::scs_to_khz.
Referenced by get_next_ssb_location.
double ssb_freq_position_generator::get_ss_ref_hz(unsigned N, unsigned M)
Get the SSB central frequency, or SS_ref, given the parameters N, M, as per Table 5.4.3.1-1, TS 38.104.
References dl_arfcn, srsgnb::MIN_ARFCN_3_GHZ_24_5_GHZ, srsgnb::N_SIZE_SYNC_RASTER_1_HZ, srsgnb::M_SIZE_SYNC_RASTER_1_HZ, srsgnb::N_REF_OFFSET_3_GHZ_24_5_GHZ, srsgnb::N_SIZE_SYNC_RASTER_2_HZ.
Referenced by find_M_raster, get_next_ssb_location.