srsgnb::downlink_processor
virtual srsgnb::downlink_processor::~downlink_processor()=default
virtual void srsgnb::downlink_processor::process_pdcch(const pdcch_processor::pdu_t &pdu)=0
Process the given PDCCH PDU.
pdu PDCCH PDU to process.
Referenced by srsgnb::fapi_adaptor::fapi_to_phy_translator::dl_tti_request.
virtual void srsgnb::downlink_processor::process_pdsch(const static_vector< span< const uint8_t >, pdsch_processor::MAX_NOF_TRANSPORT_BLOCKS > &data, const pdsch_processor::pdu_t &pdu)=0
Process the given PDSCH PDU and its related data, which it is given in data parameter.
data Contains the data of the PDSCH. pdu PDSCH PDU to process.
Referenced by srsgnb::fapi_adaptor::fapi_to_phy_translator::tx_data_request.
virtual void srsgnb::downlink_processor::process_ssb(const ssb_processor::pdu_t &pdu)=0
Process the given SSB PDU.
pdu SSB PDU to process.
Referenced by srsgnb::fapi_adaptor::fapi_to_phy_translator::dl_tti_request.
virtual void srsgnb::downlink_processor::process_nzp_csi_rs(const csi_rs_processor::config_t &config)=0
Process the given CSI-RS configuration.
config NZP-CSI-RS configuration to process.
virtual void srsgnb::downlink_processor::configure_resource_grid(const resource_grid_context &context, resource_grid &grid)=0
Configures the resource grid of the downlink_processor.
context Resource grid context that contains the information of the processing slot. grid Resource grid that will contain the data of the processed downlink channels. Calling this method is mandatory before processing any PDU. The resource grid number of ports and bandwidth must be sufficient to accommodate all the PDUs.
virtual void srsgnb::downlink_processor::finish_processing_pdus()=0
Stops accepting PDUs.
When this method is called, the interface will not expect to process more PDUs, so once it finishes to process all the enqueued PDUs, the resource grid will be sent to the lower bound gateway using the context from configure_resource_grid() to provide the processing context of the resource grid in the lower physical layer.