srsgnb::unique_timer
constexpr auto srsgnb::unique_timer::INVALID_TIMER_ID
timer_manager::timer_handle* srsgnb::unique_timer::handle
srsgnb::unique_timer::unique_timer()=default
srsgnb::unique_timer::unique_timer(timer_manager::timer_handle *pimpl)
srsgnb::unique_timer::unique_timer(const unique_timer &)=delete
unique_timer& srsgnb::unique_timer::operator=(const unique_timer &)=delete
srsgnb::unique_timer::unique_timer(unique_timer &&other) noexcept
unique_timer& srsgnb::unique_timer::operator=(unique_timer &&other) noexcept
srsgnb::unique_timer::~unique_timer()
bool srsgnb::unique_timer::is_valid() const
Returns true if the timer is valid, otherwise returns false if already released.
Referenced by id, is_set, is_running, has_expired, time_elapsed, duration, set, run, stop.
timer_id_t srsgnb::unique_timer::id() const
Returns the unique timer identifier.
References is_valid, srsgnb::timer_manager::timer_handle::id.
bool srsgnb::unique_timer::is_set() const
Returns true if the timer duration has been set, otherwise returns false.
References is_valid, srsgnb::timer_manager::timer_handle::is_set.
bool srsgnb::unique_timer::is_running() const
Returns true if the timer is currently running, otherwise returns false.
References is_valid, srsgnb::timer_manager::timer_handle::is_running.
Referenced by srsgnb::rlc_tx_am_entity::get_polling_bit.
bool srsgnb::unique_timer::has_expired() const
Returns true if the timer has expired, otherwise returns false.
References is_valid, srsgnb::timer_manager::timer_handle::has_expired.
timer_tick_difference_t srsgnb::unique_timer::time_elapsed() const
Returns the elapsed time in ticks.
References is_valid, srsgnb::timer_manager::timer_handle::time_elapsed.
timer_tick_difference_t srsgnb::unique_timer::duration() const
Returns the configured duration for this timer measured in ticks.
References is_valid, srsgnb::timer_manager::timer_handle::duration.
Referenced by set.
void srsgnb::unique_timer::set(timer_tick_difference_t duration, unique_function< void(timer_id_t)> callback)
Configures the duration of the timer calling the provided callback upon timer expiration.
References is_valid, srsgnb::timer_manager::timer_handle::set, duration.
void srsgnb::unique_timer::set(timer_tick_difference_t duration)
Configures the duration of the timer.
References is_valid, srsgnb::timer_manager::timer_handle::set, duration.
void srsgnb::unique_timer::run()
Activates the timer to start ticking.
References is_valid, srsgnb::timer_manager::timer_handle::run.
Referenced by srsgnb::rlc_tx_am_entity::get_polling_bit.
void srsgnb::unique_timer::stop()
Stops the timer from ticking.
References is_valid, srsgnb::timer_manager::timer_handle::stop.
Referenced by srsgnb::rlc_tx_am_entity::get_polling_bit.