srsgnb::ofdm_symbol_modulator_impl
unsigned srsgnb::ofdm_symbol_modulator_impl::dft_size
Indicates the DFT size.
Referenced by ofdm_symbol_modulator_impl, modulate, get_symbol_size.
unsigned srsgnb::ofdm_symbol_modulator_impl::rg_size
Indicates the resource grid bandwidth in resource elements.
Referenced by ofdm_symbol_modulator_impl, modulate.
cyclic_prefix srsgnb::ofdm_symbol_modulator_impl::cp
Cyclic prefix type.
Referenced by modulate, get_symbol_size.
subcarrier_spacing srsgnb::ofdm_symbol_modulator_impl::scs
Numerology.
Referenced by modulate, get_symbol_size.
unsigned srsgnb::ofdm_symbol_modulator_impl::sampling_rate_Hz
Sampling rate in Hz.
Referenced by modulate, get_symbol_size.
float srsgnb::ofdm_symbol_modulator_impl::scale
Scaling factor at the DFT output.
Referenced by ofdm_symbol_modulator_impl, modulate.
std::unique_ptr<dft_processor> srsgnb::ofdm_symbol_modulator_impl::dft
DFT processor.
Referenced by ofdm_symbol_modulator_impl, modulate.
phase_compensation_lut srsgnb::ofdm_symbol_modulator_impl::phase_compensation_table
Phase compensation look-up table.
Referenced by modulate.
ofdm_symbol_modulator_impl::ofdm_symbol_modulator_impl(ofdm_modulator_common_configuration &common_config, const ofdm_modulator_configuration &ofdm_config)
Constructs an OFDM symbol modulator.
common_config Provides specific configuration parameters from the factory. ofdm_config Provides generic OFDM configuration parameters.
References scale, dft_size, rg_size, dft.
unsigned srsgnb::ofdm_symbol_modulator_impl::get_symbol_size(unsigned symbol_index) const override
Gets a symbol size including cyclic prefix.
symbol_index Indicates the symbol index within the subframe. The number of samples for the given symbol index.
References cp, srsgnb::cyclic_prefix::get_length, scs, srsgnb::phy_time_unit::to_samples, sampling_rate_Hz, dft_size.
Referenced by srsgnb::ofdm_slot_modulator_impl::get_slot_size, srsgnb::ofdm_slot_modulator_impl::modulate.
void ofdm_symbol_modulator_impl::modulate(span< cf_t > ouput, const resource_grid_reader &grid, unsigned port_index, unsigned symbol_index) override
Modulates an OFDM signal with symbol granularity.
output Provides the time domain modulated signal. grid Provides the input as frequency-domain signal corresponding to one slot. port_index Indicates the port index to modulate. symbol_index Symbol index within the subframe to modulate. The input size must be consistent with the configured bandwidth. The output size must be equal to the the symbol size.
References srsgnb::get_nsymb_per_slot, cp, srsgnb::cyclic_prefix::get_length, scs, srsgnb::phy_time_unit::to_samples, sampling_rate_Hz, srsgnb::span< T >::size, dft_size, srsgnb::scs_to_khz, srsgnb::resource_grid_reader::is_empty, srsgnb::resource_grid_reader::get, dft, rg_size, phase_compensation_table, srsgnb::phase_compensation_lut::get_coefficient, scale, srsgnb::span< T >::last, srsgnb::span< T >::first.
Referenced by srsgnb::ofdm_slot_modulator_impl::modulate.