srsgnb::timer_manager
using srsgnb::timer_manager::timer_tick_t = uint32_t
This type represents a tick.
constexpr size_t srsgnb::timer_manager::WHEEL_SHIFT
Wheel configuration parameters.
constexpr size_t srsgnb::timer_manager::WHEEL_SIZE
constexpr size_t srsgnb::timer_manager::WHEEL_MASK
constexpr uint64_t srsgnb::timer_manager::STOPPED_FLAG
Timer state constant definitions.
constexpr uint64_t srsgnb::timer_manager::RUNNING_FLAG
constexpr uint64_t srsgnb::timer_manager::EXPIRED_FLAG
constexpr timer_tick_difference_t srsgnb::timer_manager::MAX_TIMER_DURATION
friend class unique_timer
std::atomic<timer_tick_t> srsgnb::timer_manager::cur_time
Current timer absolute tick.
Referenced by srsgnb::timer_manager::timer_handle::time_elapsed, tick_all.
size_t srsgnb::timer_manager::nof_timers_running
Number of created timer_impl objects that are currently running.
Referenced by nof_running_timers.
size_t srsgnb::timer_manager::nof_free_timers
Number of created timer_impl objects that can be reused.
Referenced by nof_timers, timer_manager.
std::deque<timer_handle> srsgnb::timer_manager::timer_list
List of created timer_impl objects. Note: Using a deque to maintain reference validity on emplace_back. Also, this deque will only grow.
Referenced by nof_timers, timer_manager, tick_all, stop_all.
srsgnb::intrusive_forward_list<timer_handle> srsgnb::timer_manager::free_list
Free list of timer_impl objects in timer_list.
Referenced by timer_manager.
std::vector<srsgnb::intrusive_double_linked_list<timer_handle> > srsgnb::timer_manager::time_wheel
Timer wheel, which is circularly indexed via a running timer timeout. Collisions are resolved via an intrusive list in timer_impl.
Referenced by tick_all.
std::mutex srsgnb::timer_manager::mutex
Protects the addition/modification/removal of timers in timer_manager.
Referenced by srsgnb::timer_manager::timer_handle::set, nof_timers, nof_running_timers, tick_all, stop_all, destroy_timer, start_run, stop_timer.
static bool srsgnb::timer_manager::decode_is_running_flag(uint64_t value)
Miscellaneous decoding helper functions.
Referenced by srsgnb::timer_manager::timer_handle::is_running, srsgnb::timer_manager::timer_handle::time_elapsed.
static bool srsgnb::timer_manager::decode_is_expired_flag(uint64_t value)
static timer_tick_difference_t srsgnb::timer_manager::decode_duration(uint64_t value)
static timer_tick_t srsgnb::timer_manager::decode_timeout(uint64_t value)
static uint64_t srsgnb::timer_manager::encode_state(uint64_t mode_flag, timer_tick_difference_t duration, timer_tick_t timeout)
timer_manager::timer_manager(size_t capacity=64)
Default ctor capacity Number of timers to pre-reserve and speed up timer construction.
References timer_list, free_list, nof_free_timers.
void timer_manager::tick_all()
Advances one tick all running timers.
References mutex, cur_time, time_wheel, timer_list, srsgnb::timer_manager::timer_handle::state, srsgnb::timer_manager::timer_handle::callback, srsgnb::timer_manager::timer_handle::id.
void timer_manager::stop_all()
Stops all running timers.
References mutex, timer_list.
unique_timer timer_manager::create_unique_timer()
Creates a new instance of a unique timer.
size_t srsgnb::timer_manager::nof_timers() const
Returns the number of timers handled by this instance.
References mutex, timer_list, nof_free_timers.
size_t srsgnb::timer_manager::nof_running_timers() const
Returns the number of running timers handled by this instance.
References mutex, nof_timers_running.
void srsgnb::timer_manager::defer_callback(timer_tick_difference_t duration, F f)
Defer the call of the provided callback until duration ticks have elapsed.
References srsgnb::timer_manager::timer_handle::destroy, srsgnb::timer_manager::timer_handle::set, srsgnb::timer_manager::timer_handle::run.
static constexpr timer_tick_difference_t srsgnb::timer_manager::max_timer_duration()
Returns the maximum allowed duration value.
static constexpr size_t srsgnb::timer_manager::get_wheel_size()
Returns the size of the internal timer wheel.
timer_manager::timer_handle & timer_manager::create_timer()
void timer_manager::destroy_timer(timer_handle &timer)
Called when timer is removed. The timer object gets registered in free list for reuse.
References mutex.
Referenced by srsgnb::timer_manager::timer_handle::destroy.
void timer_manager::destroy_timer_nolock(timer_handle &timer)
void timer_manager::start_run(timer_handle &timer, timer_tick_difference_t duration=0)
Called when timer is started.
References mutex.
Referenced by srsgnb::timer_manager::timer_handle::run.
void timer_manager::start_run_nolock(timer_handle &timer, timer_tick_difference_t duration=0)
void timer_manager::stop_timer(timer_handle &timer, bool expiry)
Called when user manually stops timer (as an alternative to expiry).
References mutex.
Referenced by srsgnb::timer_manager::timer_handle::stop.
void timer_manager::stop_timer_nolock(timer_handle &timer, bool expiry)