srsgnb::preamble_format
values
values srsgnb::preamble_format::value
Preamble actual value.
Referenced by is_long_preamble, operator==, operator!=, operator values.
srsgnb::preamble_format::preamble_format()
Creates a default format.
srsgnb::preamble_format::preamble_format(values value_)
Creates a preamble format from value.
bool srsgnb::preamble_format::is_long_preamble() const
Checks whether the preamble format is a long or short preamble.
The preambles are listed as per TS38.211 Table 6.3.3.1-1 for long preambles, and TS38.211 Table 6.3.3.1-2 for short preambles.
References value.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::prach_processor_worker::handle_request, srsgnb::prach_generator_impl::generate.
bool srsgnb::preamble_format::operator==(const preamble_format &other) const
Equality operator overload: comparison with a preamble_format object.
References value.
bool srsgnb::preamble_format::operator==(values other_value) const
Equality operator overload: comparison with a preamble_format::values value.
References value.
bool srsgnb::preamble_format::operator!=(const preamble_format &other) const
Inequality operator overload: comparison with a preamble_format object.
References value.
bool srsgnb::preamble_format::operator!=(values other_value) const
Inequality operator overload: comparison with a preamble_format::values value.
References value.
srsgnb::preamble_format::operator values() const
Parenthesis operator overload: returns the value.
References value.