srsgnb::pusch_demodulator_impl
std::unique_ptr<channel_equalizer> srsgnb::pusch_demodulator_impl::equalizer
Channel equalization component, also in charge of combining contributions of all receive antenna ports.
Referenced by demodulate, pusch_demodulator_impl.
std::unique_ptr<demodulation_mapper> srsgnb::pusch_demodulator_impl::demapper
Demodulation mapper component: transforms channel symbols into log-likelihood ratios (i.e., soft bits).
Referenced by demodulate, pusch_demodulator_impl.
std::unique_ptr<pseudo_random_generator> srsgnb::pusch_demodulator_impl::descrambler
Descrambler component.
Referenced by demodulate, pusch_demodulator_impl.
re_measurement<cf_t> srsgnb::pusch_demodulator_impl::ch_symbols
Buffer used to transfer channel modulation symbols from the resource grid to the equalizer.
Referenced by demodulate.
re_measurement<cf_t> srsgnb::pusch_demodulator_impl::mod_symbols_eq
Buffer used to store channel modulation symbols at the equalizer output.
Referenced by demodulate.
re_measurement<float> srsgnb::pusch_demodulator_impl::noise_vars_eq
Buffer used to transfer symbol noise variances at the equalizer output.
Referenced by demodulate.
static_vector<cf_t, MAX_NOF_DATA_LLR> srsgnb::pusch_demodulator_impl::mod_symbols_data
Buffer used to transfer channel modulation symbols to the demodulator.
Referenced by demodulate.
static_vector<float, MAX_NOF_DATA_LLR> srsgnb::pusch_demodulator_impl::noise_vars_data
Buffer used to transfer symbol noise variances to the demodulator.
Referenced by demodulate.
srsgnb::pusch_demodulator_impl::pusch_demodulator_impl(std::unique_ptr< channel_equalizer > eq, std::unique_ptr< demodulation_mapper > demap, std::unique_ptr< pseudo_random_generator > dscr)
Constructor: sets up internal components and acquires their ownership.
References equalizer, demapper, descrambler.
void pusch_demodulator_impl::demodulate(data_llr_buffer &data, harq_ack_llr_buffer &harq_ack, csi_part1_llr &csi_part1, csi_part2_llr &csi_part2, const resource_grid_reader &grid, const channel_estimate &estimates, const configuration &config) override
Demodulates a PUSCH transmission.
Computes log-likelihood ratios from channel samples by reversing all the operations described in TS38.211 Section 6.3.1. The method also extracts control bits that were multiplexed with PUSCH data as per TS38.212 Section 6.2.7. The size of data determines the codeword size in LLR. The size of harq_ack determines the number of LLR for HARQ-ACK. The size of csi_part1 determines the number of LLR for CSI Part1. The size of csi_part2 determines the number of LLR for CSI Part2. The total number of LLR must be consistent with the number of RE allocated to the transmission. data Codeword LLR destination buffer. harq_ack HARQ-ACK LLR destination buffer. csi_part1 CSI Part1 LLR destination buffer. csi_part2 CSI Part2 LLR destination buffer. grid Resource grid for the current slot. estimates Channel estimates for the REs allocated to the PUSCH transmission. config Configuration parameters.
References srsgnb::re_measurement_dimensions::nof_prb, srsgnb::pusch_demodulator::configuration::freq_allocation, srsgnb::rb_allocation::get_nof_rb, srsgnb::re_measurement_dimensions::nof_symbols, srsgnb::pusch_demodulator::configuration::nof_symbols, srsgnb::re_measurement_dimensions::nof_slices, srsgnb::pusch_demodulator::configuration::rx_ports, ch_symbols, srsgnb::re_measurement< measure_type >::resize, get_ch_symbols, srsgnb::pusch_demodulator::configuration::nof_tx_layers, mod_symbols_eq, noise_vars_eq, equalizer, remove_dmrs, mod_symbols_data, noise_vars_data, demapper, srsgnb::pusch_demodulator::configuration::modulation, srsgnb::pusch_demodulator::configuration::rnti, srsgnb::pow2, srsgnb::pusch_demodulator::configuration::n_id, descrambler, extract_harq_ack, extract_csi_part1, extract_csi_part2.
void srsgnb::pusch_demodulator_impl::get_ch_symbols(re_measurement< cf_t > &symbols, const resource_grid_reader &grid, const configuration &config)
Gets channel symbols from the resource grid.
symbols PUSCH channel symbols, organized by receive antenna port. grid Resource grid for the current slot. config Configuration parameters.
Referenced by demodulate.
void srsgnb::pusch_demodulator_impl::remove_dmrs(static_vector< cf_t, MAX_NOF_DATA_LLR > &symbols_out, static_vector< float, MAX_NOF_DATA_LLR > &noise_vars_out, const re_measurement< cf_t > &symbols_in, const re_measurement< float > &noise_vars_in, const configuration &config)
Removes elements corresponding to DM-RS symbols and reserved positions.
From the equalizer output, removes all estimated modulation symbols and noise variances corresponding to DM-RS positions. Also, performs layer demapping, thus returning two one-dimensional sequences. symbols_out Layer-demapped sequence of estimated modulation symbols. noise_vars_out Layer-demapped sequence of equivalent symbol noise variances. symbols_in Equalized modulation and DM-RS symbols, grouped by layer. noise_vars_in Equivalent symbol noise variances, grouped by layer. config Configuration parameters.
Referenced by demodulate.
void srsgnb::pusch_demodulator_impl::extract_harq_ack(harq_ack_llr_buffer &harq_ack, data_llr_buffer &data, const configuration &config)
Extracts HARQ-ACK soft bits from the sequence of multiplexed data and control bits.
See TS38.212 Section 6.2.7. harq_ack Sequence of HARQ-ACK soft bits. [in/out] data Sequence of data soft bits (possibly multiplexed with control ones). config Configuration parameters. The elements of data corresponding to HARQ-ACK bits will be set to zero (i.e., fully indeterminate data soft bit).
Referenced by demodulate.
void srsgnb::pusch_demodulator_impl::extract_csi_part1(csi_part1_llr &csi_part1, data_llr_buffer &data, const configuration &config)
Extracts CSI Part1 soft bits from the sequence of multiplexed data and control bits.
See TS38.212 Section 6.2.7. csi_part1 Sequence of CSI Part1 soft bits. [in/out] data Sequence of data soft bits (possibly multiplexed with control ones). config Configuration parameters. The elements of data corresponding to CSI Part1 bits will be set to zero (i.e., fully indeterminate data soft bit).
Referenced by demodulate.
void srsgnb::pusch_demodulator_impl::extract_csi_part2(csi_part2_llr &csi_part2, data_llr_buffer &data, const configuration &config)
Extracts CSI Part2 soft bits from the sequence of multiplexed data and control bits.
See TS38.212 Section 6.2.7. csi_part1 Sequence of CSI Part2 soft bits. [in/out] data Sequence of data soft bits (possibly multiplexed with control ones). config Configuration parameters. The elements of data corresponding to CSI Part2 bits will be set to zero (i.e., fully indeterminate data soft bit).
Referenced by demodulate.