srsgnb::re_pattern_list
constexpr unsigned srsgnb::re_pattern_list::MAX_RE_PATTERN
Defines the maximum number or RE pattern a list can carry.
Referenced by merge.
static_vector<re_pattern, MAX_RE_PATTERN> srsgnb::re_pattern_list::list
Resource element pattern storage.
Referenced by clear, get_nof_entries, merge, get_inclusion_mask, get_inclusion_count, get_exclusion_mask.
srsgnb::re_pattern_list::re_pattern_list()=default
Default constructor.
srsgnb::re_pattern_list::re_pattern_list(std::initializer_list< const re_pattern > patterns)
Create a pattern list from an initializer list of patterns.
This is useful for static constant pattern list creation. For example: re_pattern_listlist={ {0,52,1,{1,0,0,0,1,0,0,0,1,0,0,0},{0,0,0,0,0,0,1,0,0,0,0,0,0,0}}, {0,52,1,{1,0,0,0,1,0,0,0,1,0,0,0},{0,0,0,0,0,0,0,0,0,0,1,0,0,0}}}; patterns Initializer list with patterns.
References merge.
srsgnb::re_pattern_list::re_pattern_list(const re_pattern_list &other)
Copy constructor.
other Provides other instance.
void srsgnb::re_pattern_list::clear()
Clear the current pattern list.
References list.
unsigned srsgnb::re_pattern_list::get_nof_entries() const
Get the number of internal resource element pattern.
References list.
void re_pattern_list::merge(const re_pattern &pattern)
Merges a given resource element pattern into the list.
This method tries to combine a new pattern with the existing ones in the list according to if the resource block allocation parameters are identical, and the symbol mask or the resource element mask is identical. Otherwise, the pattern is appended in the list. pattern Provides the reference to a resource element pattern.
References list, srsgnb::re_pattern::rb_begin, srsgnb::re_pattern::rb_end, srsgnb::re_pattern::rb_stride, srsgnb::re_pattern::symbols, srsgnb::re_pattern::re_mask, srsgnb::NRE, srsgnb::MAX_NSYMB_PER_SLOT, MAX_RE_PATTERN.
Referenced by re_pattern_list, srsgnb::pdsch_processor_impl::compute_nof_data_re.
bool re_pattern_list::operator==(const re_pattern_list &other) const
Checks if the pattern list is equal to another pattern list.
Two pattern lists are considered equal if their generated inclusion masks are equal for the maximum number of RBs and symbols. other The other pattern list. True if the patterns described by the two lists are equal.
References srsgnb::MAX_NSYMB_PER_SLOT, get_inclusion_mask.
bool srsgnb::re_pattern_list::operator!=(const re_pattern_list &other) const
Checks if the pattern list is the pattern list is different from another pattern list.
other The other pattern list. True if the patterns described by the two lists are different.
void re_pattern_list::get_inclusion_mask(span< bool > mask, unsigned symbol) const
Includes the described resource element pattern list in a resource grid symbol mask.
This method sets to true the elements that are described in the pattern list for a given symbol index. The mask represents resource elements allocation for a given symbol in a resource grid. mask Provides a mask representing an entire symbol in a resource grid. symbol Indicates the symbol index for the mask to be included. This method expects that the number of elements of mask is equal to or greater than rb_end.
References list.
Referenced by operator==.
unsigned re_pattern_list::get_inclusion_count(unsigned start_symbol, unsigned nof_symbols, const bounded_bitset< MAX_RB > &prb_mask) const
Counts the number of elements included in the described pattern.
This method counts the included elements in the described pattern for a symbol range and a selection of PRB. start_symbol Indicates the start symbol index within the slot. nof_symbols Indicates the number of symbols within the slot. prb_mask Selection of PRB to count. The number of included elements.
References list, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::test, srsgnb::NRE.
Referenced by srsgnb::pdsch_processor_impl::compute_nof_data_re.
void re_pattern_list::get_exclusion_mask(span< bool > mask, unsigned symbol) const
Excludes the described resource element pattern list in a resource grid symbol mask.
This method sets to false the elements that are described in the pattern list for a given symbol index. The mask represents resource elements allocation for a given symbol in a resource grid. mask Provides a mask representing an entire symbol in a resource grid. symbol Indicates the symbol index for the mask to be excluded. This method expects that the number of elements of mask is equal to or greater than rb_end.
References list.
Referenced by srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other.