srsgnb::srs_cu_cp::cu_cp
timer_manager srsgnb::srs_cu_cp::cu_cp::timers
cu_cp_configuration srsgnb::srs_cu_cp::cu_cp::cfg
srslog::basic_logger& srsgnb::srs_cu_cp::cu_cp::logger
std::unique_ptr<ngap> srsgnb::srs_cu_cp::cu_cp::ngap_entity
slot_array<std::unique_ptr<du_processor>, MAX_NOF_DUS> srsgnb::srs_cu_cp::cu_cp::du_db
slot_array<async_task_sequencer, MAX_NOF_DUS> srsgnb::srs_cu_cp::cu_cp::du_ctrl_loop
async_task_sequencer srsgnb::srs_cu_cp::cu_cp::main_ctrl_loop
f1ap_cu_cp_adapter srsgnb::srs_cu_cp::cu_cp::f1ap_ev_notifier
rrc_ue_ngap_adapter srsgnb::srs_cu_cp::cu_cp::rrc_ue_ngap_ev_notifier
cu_cp::cu_cp(const cu_cp_configuration &cfg_)
cu_cp::~cu_cp()
void cu_cp::start()
void cu_cp::stop()
f1c_message_handler & cu_cp::get_f1c_message_handler(du_index_t du_index) override
Get the F1C message handler interface of the DU processor object.
du_index The index of the DU processor object. The F1C message handler interface of the DU processor object.
References find_du.
f1c_statistics_handler & cu_cp::get_f1c_statistics_handler(du_index_t du_index) override
Get the F1C statistics handler interface of the DU processor object.
du_index The index of the DU processor object. The F1C statistics handler interface of the DU processor object.
References find_du.
void cu_cp::on_new_connection() override
Notifies the CU-CP about a new DU connection.
References add_du.
void cu_cp::handle_du_remove_request(const du_index_t du_index) override
Handles a remove request. The corresponding DU processor object will be removed.
du_index The index of the DU processor object to delete.
References remove_du.
void cu_cp::on_amf_connection() override
Notifies the CU-CP about a successful AMF connection.
void cu_cp::on_amf_connection_drop() override
Notifies the CU-CP about a dropped AMF connection.
size_t cu_cp::get_nof_dus() const override
Get the number of DUs connected to the CU-CP.
The number of DUs.
size_t cu_cp::get_nof_ues() const override
Get the number of UEs connected to the all DUs of the CU-CP.
The number of UEs.
void cu_cp::add_du()
Adds a DU processor object to the CU-CP.
Create DU object with valid index.
References get_next_du_index.
Referenced by on_new_connection.
void cu_cp::remove_du(du_index_t du_index)
Removes the specified DU processor object from the CU-CP.
du_index The index of the DU processor to delete.
Referenced by handle_du_remove_request.
du_processor & cu_cp::find_du(du_index_t du_index)
Find a DU object.
du_index The index of the DU processor object. The DU processor object.
Referenced by get_f1c_message_handler, get_f1c_statistics_handler.
du_index_t cu_cp::get_next_du_index()
Get the next available index from the DU processor database.
The DU index.
Referenced by add_du.