srsgnb::prach_processor_notifier
virtual srsgnb::prach_processor_notifier::~prach_processor_notifier()=default
Default destructor.
virtual void srsgnb::prach_processor_notifier::on_prach_request_late(const prach_buffer_context &context)=0
Notifies a PRACH request outside the slot window.
See lower_phy_error_notifier::on_prach_request_late for more information. context PRACH context.
Referenced by srsgnb::prach_processor_worker::run_state_wait.
virtual void srsgnb::prach_processor_notifier::on_prach_request_overflow(const prach_buffer_context &context)=0
Notifies an excess of PRACH requests.
See lower_phy_error_notifier::on_prach_request_late for more information. context PRACH context.
Referenced by srsgnb::prach_processor_impl::handle_request.
virtual void srsgnb::prach_processor_notifier::on_rx_prach_window(const prach_buffer &buffer, const prach_buffer_context &context)=0
Notifies the completion of the PRACH request processing.
See lower_phy_error_notifier::on_prach_request_late for more information. buffer PRACH buffer. context PRACH context.
Referenced by srsgnb::prach_processor_worker::accumulate_samples.