srsgnb::rlc_tx_am_entity
const rlc_tx_am_config srsgnb::rlc_tx_am_entity::cfg
rlc_rx_am_status_provider* srsgnb::rlc_tx_am_entity::status_provider
rlc_tx_am_state srsgnb::rlc_tx_am_entity::st
rlc_sdu_queue srsgnb::rlc_tx_am_entity::sdu_queue
uint32_t srsgnb::rlc_tx_am_entity::sn_under_segmentation
pdu_retx_queue_list<rlc_tx_amd_retx> srsgnb::rlc_tx_am_entity::retx_queue
std::mutex srsgnb::rlc_tx_am_entity::mutex
const uint32_t srsgnb::rlc_tx_am_entity::mod
Tx counter modulus.
const uint32_t srsgnb::rlc_tx_am_entity::tx_window_size
std::unique_ptr<rlc_pdu_window_base<rlc_tx_amd_pdu_box> > srsgnb::rlc_tx_am_entity::tx_window
const uint32_t srsgnb::rlc_tx_am_entity::head_min_size
const uint32_t srsgnb::rlc_tx_am_entity::head_max_size
unique_timer srsgnb::rlc_tx_am_entity::poll_retransmit_timer
t-PollRetransmit This timer is used by the transmitting side of an AM RLC entity in order to retransmit a poll (see sub clause 5.3.3). Ref: TS 38.322 Sec. 7.3
Referenced by get_polling_bit.
constexpr uint32_t srsgnb::rlc_tx_am_entity::tx_mod_base(uint32_t x)
byte_buffer_slice_chain rlc_tx_am_entity::build_new_pdu(uint32_t nof_bytes)
Builds a new RLC PDU. This will be called after checking whether control, retransmission, or segment PDUs needed to be transmitted first. It will read an SDU from the SDU queue, build a new PDU, and add it to the tx_window. SDU segmentation is applied if necessary.
An empty PDU is returned if nof_bytes is insufficient or the TX buffer is empty. nof_bytes Limits the maximum size of the requested PDU. One PDU
References srsgnb::rlc_tx_am_state::tx_next, build_new_sdu_segment, srsgnb::rlc_am_pdu_header::dc, srsgnb::rlc_am_pdu_header::p, get_polling_bit, srsgnb::rlc_am_pdu_header::si.
Referenced by pull_pdu.
byte_buffer_slice_chain rlc_tx_am_entity::build_new_sdu_segment(rlc_tx_amd_pdu_box &tx_pdu, uint32_t nof_bytes)
Builds a new RLC PDU segment, from a RLC SDU.
tx_pdu the tx_pdu info contained in the tx_window. nof_bytes Limits the maximum size of the requested PDU. One PDU segment
References srsgnb::rlc_tx_am_state::tx_next, srsgnb::rlc_am_pdu_header::dc, srsgnb::rlc_am_pdu_header::p, get_polling_bit, srsgnb::rlc_am_pdu_header::si.
Referenced by build_new_pdu.
byte_buffer_slice_chain rlc_tx_am_entity::build_continuation_sdu_segment(rlc_tx_amd_pdu_box &tx_pdu, uint32_t nof_bytes)
byte_buffer_slice_chain rlc_tx_am_entity::build_retx_pdu(uint32_t nof_bytes)
byte_buffer_slice_chain rlc_tx_am_entity::build_retx_pdu_without_segmentation(rlc_tx_amd_retx &retx, uint32_t nof_bytes)
byte_buffer_slice_chain rlc_tx_am_entity::build_retx_pdu_with_segmentation(rlc_tx_amd_retx &retx, uint32_t nof_bytes)
void rlc_tx_am_entity::handle_buffer_state_update()
Called when buffer state needs to be updated and forwarded to lower layers.
References srsgnb::rlc_tx_buffer_state_update_notifier::on_buffer_state_update.
uint32_t rlc_tx_am_entity::get_buffer_state_nolock()
void srsgnb::rlc_tx_am_entity::log_state(srslog::basic_levels level)
rlc_tx_am_entity::rlc_tx_am_entity(du_ue_index_t du_index, lcid_t lcid, const rlc_tx_am_config &config, rlc_tx_upper_layer_control_notifier &upper_cn, rlc_tx_buffer_state_update_notifier &buffer_state_notif, timer_manager &timers)
void srsgnb::rlc_tx_am_entity::set_status_provider(rlc_rx_am_status_provider *status_provider_)
void rlc_tx_am_entity::handle_sdu(rlc_sdu sdu) override
Interface for higher layers to pass SDUs into RLC.
sdu SDU to be handled
byte_buffer_slice_chain rlc_tx_am_entity::pull_pdu(uint32_t nof_bytes) override
Pulls a PDU from the lower end of the RLC TX entity An empty PDU is returned if nof_bytes is insufficient or the TX buffer is empty.
nof_bytes Limits the maximum size of the requested PDU. One PDU
References srsgnb::byte_buffer::length, srsgnb::INVALID_RLC_SN, build_new_pdu.
uint32_t rlc_tx_am_entity::get_buffer_state() override
Get the buffer status information This function provides the current buffer state of the RLC TX entity. This is the gross total size required to fully flush the TX entity (potentially by multiple calls to pull_pdu).
Provides the current buffer state
void srsgnb::rlc_tx_am_entity::handle_status_pdu(rlc_am_status_pdu status_pdu) override
uint8_t rlc_tx_am_entity::get_polling_bit(uint32_t sn, bool is_retx, uint32_t payload_size)
Determines whether the polling bit in a PDU header has to be set or not Ref: TS 38.322, Sec. 5.3.3.2.
sn Sequence number of PDU to be transmitted is_retx Flags whether this PDU is a retransmission or not payload_size Length of the data field mapped to the AMD PDU 1 if the polling bit has to be set, otherwise 0
References srsgnb::rlc_tx_am_state::poll_sn, srsgnb::rlc_tx_am_state::pdu_without_poll, srsgnb::rlc_tx_am_state::byte_without_poll, srsgnb::rlc_tx_am_config::poll_pdu, srsgnb::rlc_tx_am_config::poll_byte, srsgnb::INVALID_RLC_SN, srsgnb::rlc_tx_am_config::t_poll_retx, poll_retransmit_timer, srsgnb::unique_timer::is_running, srsgnb::unique_timer::run, srsgnb::unique_timer::stop.
Referenced by build_new_pdu, build_new_sdu_segment.
void rlc_tx_am_entity::timer_expired(uint32_t timeout_id)
std::unique_ptr< rlc_pdu_window_base< rlc_tx_amd_pdu_box > > rlc_tx_am_entity::create_tx_window(rlc_am_sn_size sn_size)
Creates the tx_window according to sn_size sn_size Size of the sequence number (SN) unique pointer to tx_window instance