srsgnb::slot_point
constexpr uint32_t srsgnb::slot_point::NOF_NUMEROLOGIES
Number of possible numerologies.
Referenced by slot_point, clear, valid.
constexpr uint16_t srsgnb::slot_point::NOF_SFNS
Number of possible SFNs.
Referenced by slot_point, nof_slots_per_system_frame.
uint32_t srsgnb::slot_point::numerology_val
Tag for numerology used: {0: 15 kHz, 1: 30 kHz, 2: 60 kHz, 3: 120 kHz, 4: 240 kHz}.
Referenced by clear, valid, numerology, nof_slots_per_subframe, operator==.
uint32_t srsgnb::slot_point::count_val
Count value that encodes both SFN (0..1023) and slot index (0..9/19/39/79/159).
Referenced by slot_index, sfn, system_slot, hrf_slot_index, subframe_slot_index, operator==, operator<, operator-, operator++, operator+=.
constexpr srsgnb::slot_point::slot_point()
Default constructor. Sets slot_point in invalid state.
constexpr srsgnb::slot_point::slot_point(uint32_t numerology, uint32_t count)
Takes a numerology and total count value.
References numerology, NOF_NUMEROLOGIES, nof_slots_per_system_frame.
constexpr srsgnb::slot_point::slot_point(uint32_t numerology, uint32_t sfn_val, uint32_t slot_radio_frame_idx_)
Takes a numerology, SFN and slot index in radio frame.
References numerology, NOF_NUMEROLOGIES, NOF_SFNS, nof_slots_per_frame.
constexpr srsgnb::slot_point::slot_point(uint32_t numerology, uint32_t sfn_val, uint32_t subframe_index_, uint32_t slot_subframe_index_)
Takes a numerology, SFN, subframe index and slot index within subframe.
References numerology, NOF_NUMEROLOGIES, NOF_SFNS, srsgnb::NOF_SUBFRAMES_PER_FRAME, nof_slots_per_subframe.
void srsgnb::slot_point::clear()
Sets slot_point to invalid state.
References numerology_val, NOF_NUMEROLOGIES.
constexpr bool srsgnb::slot_point::valid() const
Determines whether slot_point was correctly initialized.
References numerology_val, NOF_NUMEROLOGIES.
Referenced by srsgnb::downlink_processor_pool_impl::get_processor, srsgnb::uplink_processor_pool_impl::get_processor, srsgnb::cell_resource_allocator::slot_indication.
constexpr uint32_t srsgnb::slot_point::numerology() const
Numerology index (0..4).
References numerology_val.
Referenced by slot_point, operator<, srsgnb::set_slot_numerology, srsgnb::processor_pool_repository< T >::get_processor, srsgnb::slot_is_dl, srsgnb::cell_resource_allocator::slot_indication, srsgnb::schedule_ssb.
constexpr uint32_t srsgnb::slot_point::slot_index() const
Slot index in radio frame. Value: SCS=15kHz: (0..9), SCS=30kHz: (0..19), SCS=60kHz: (0..39), SCS=120kHz: (0..79), SCS=240kHz: (0..159)
References count_val, nof_slots_per_frame.
Referenced by subframe_index, srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_downlink_scheduler_results, srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_downlink_data, srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_uplink_scheduler_results, srsgnb::fapi_adaptor::phy_to_fapi_results_event_translator::on_new_prach_results, srsgnb::fapi_adaptor::phy_to_fapi_time_event_translator::on_tti_boundary, srsgnb::csi_rs_processor_impl::generate_sequence, srsgnb::dmrs_pdcch_processor_impl::c_init, srsgnb::dmrs_pdsch_processor_impl::sequence_generation, srsgnb::dmrs_pucch_processor_format2_impl::c_init, srsgnb::pucch_helper::get_alpha_index, srsgnb::get_ra_rnti.
constexpr uint32_t srsgnb::slot_point::sfn() const
Radio Frame Number. Value: (0..1023).
References count_val, nof_slots_per_frame.
Referenced by srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_downlink_scheduler_results, srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_downlink_data, srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_uplink_scheduler_results, srsgnb::fapi_adaptor::phy_to_fapi_results_event_translator::on_new_prach_results, srsgnb::fapi_adaptor::phy_to_fapi_time_event_translator::on_tti_boundary, srsgnb::ssb_processor_impl::process, srsgnb::prach_scheduler::run_slot.
constexpr uint32_t srsgnb::slot_point::nof_slots_per_system_frame() const
Number of slots per system frame.
References nof_slots_per_frame, NOF_SFNS.
Referenced by slot_point, operator<, operator-, operator++, operator+=.
constexpr uint32_t srsgnb::slot_point::nof_slots_per_subframe() const
Number of slots present in a subframe. Depends on numerology.
References numerology_val.
Referenced by slot_point, nof_slots_per_frame, subframe_index, subframe_slot_index, srsgnb::lower_phy_impl::lower_phy_impl, srsgnb::sib1_scheduler::schedule_sib1, srsgnb::schedule_ssb.
constexpr uint32_t srsgnb::slot_point::nof_slots_per_frame() const
Number of slots present in a frame. Depends on numerology.
References nof_slots_per_subframe, srsgnb::NOF_SUBFRAMES_PER_FRAME.
Referenced by slot_point, slot_index, sfn, nof_slots_per_system_frame, nof_hrf_slots, srsgnb::pucch_helper::get_alpha_index.
constexpr uint32_t srsgnb::slot_point::subframe_index() const
Subframe index in a radio frame. Value: (0..9).
References slot_index, nof_slots_per_subframe.
Referenced by is_odd_hrf, srsgnb::prach_scheduler::run_slot.
constexpr uint32_t srsgnb::slot_point::system_slot() const
Conversion of slot_point to system slot.
References count_val.
Referenced by srsgnb::phy_error_adapter::on_late_resource_grid, srsgnb::phy_error_adapter::on_prach_request_late, srsgnb::phy_error_adapter::on_prach_request_overflow, srsgnb::lower_phy_impl::process_ul_symbol, srsgnb::lower_phy_impl::process_dl_symbol, srsgnb::lower_phy_impl::process_symbol, srsgnb::lower_phy_impl::handle_resource_grid, srsgnb::lower_phy_impl::request_uplink_slot, srsgnb::resource_grid_pool_impl::get_resource_grid, srsgnb::processor_pool_repository< T >::get_processor.
constexpr uint32_t srsgnb::slot_point::to_uint() const
constexpr srsgnb::slot_point::operator uint32_t() const
constexpr uint32_t srsgnb::slot_point::nof_hrf_slots() const
Get Half Radio Frame size in number of slots.
References nof_slots_per_frame.
Referenced by hrf_slot_index.
constexpr bool srsgnb::slot_point::is_odd_hrf() const
Checks if slot is in second half of the radio frame.
References subframe_index, srsgnb::NOF_SUBFRAMES_PER_FRAME.
Referenced by srsgnb::ssb_processor_impl::process.
constexpr uint32_t srsgnb::slot_point::hrf_slot_index() const
Get MOD(slot index, Nof slots in Half Frame)
References count_val, nof_hrf_slots.
Referenced by srsgnb::ssb_processor_impl::process.
constexpr uint32_t srsgnb::slot_point::subframe_slot_index() const
Get MOD(slot index, Nof slots in a subframe)
References count_val, nof_slots_per_subframe.
Referenced by srsgnb::lower_phy_impl::process_symbol.
constexpr bool srsgnb::slot_point::operator==(const slot_point &other) const
Equality comparison of two slot_point objects. Two slot points are equal if their numerology, SFN and slot index have the same value.
References count_val, numerology_val.
constexpr bool srsgnb::slot_point::operator!=(const slot_point &other) const
Inequality comparison of two slot_point objects.
constexpr bool srsgnb::slot_point::operator<(const slot_point &other) const
Checks if "lhs" slot point is lower than "rhs". It assumes that both "lhs" and "rhs" use the same numerology This comparison accounts for the wrap-around of both slot index and SFNs. The ambiguity range of the comparison is equal to half of the total number of slots in a hyperframe.
References numerology, count_val, nof_slots_per_system_frame.
constexpr bool srsgnb::slot_point::operator<=(const slot_point &other) const
Other lower/higher comparisons that build on top of operator== and operator<.
constexpr bool srsgnb::slot_point::operator>=(const slot_point &other) const
constexpr bool srsgnb::slot_point::operator>(const slot_point &other) const
constexpr slot_difference srsgnb::slot_point::operator-(const slot_point &other) const
Implements the subtraction of two slot points. a signed integer that is positive if "lhs" is higher than "rhs", zero if equal, and negative otherwise.
References count_val, nof_slots_per_system_frame.
slot_point& srsgnb::slot_point::operator++()
Increment slot_point. It accounts for slot index and SFN wrap-around.
References count_val, nof_slots_per_system_frame.
slot_point srsgnb::slot_point::operator++(int)
slot_point& srsgnb::slot_point::operator+=(Unsigned jump)
Sum of slot_point by an integer jump value.
References count_val, nof_slots_per_system_frame.
Referenced by operator-=.
slot_point& srsgnb::slot_point::operator+=(int jump)
slot_point& srsgnb::slot_point::operator-=(uint32_t jump)
Subtraction of slot point by an integer jump value.
References operator+=.
slot_point& srsgnb::slot_point::operator-=(int jump)
constexpr bool srsgnb::slot_point::is_in_interval(slot_point begin, slot_point end) const
Determines whether this slot_point fits within provided slot point range.