srsgnb::resource_grid_reader
virtual srsgnb::resource_grid_reader::~resource_grid_reader()=default
Default destructor.
virtual bool srsgnb::resource_grid_reader::is_empty(unsigned port) const =0
Determines whether a given port is empty.
A port is considered empty if no put method have been called since last zero set. If zeros are written using any put method, the port is considered not empty. An invalid port index triggers an assertion. port Port index. True if the given port is empty. Otherwise, false.
Referenced by srsgnb::ofdm_symbol_modulator_impl::modulate.
virtual void srsgnb::resource_grid_reader::get(span< cf_t > symbols, unsigned port, span< const resource_grid_coordinate > coordinates) const =0
Gets a number of elements from the grid for a given port according to a list of coordinates.
symbols Destination symbol buffer. port Port index. coordinates List of grid symbolsubcarrier coordinates. The number of elements in coordinates and symbols shall be the same.
Referenced by srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::dmrs_pucch_processor_format1_impl::mapping, srsgnb::dmrs_pucch_processor_format2_impl::mapping.
virtual span<cf_t> srsgnb::resource_grid_reader::get(span< cf_t > symbols, unsigned port, unsigned l, unsigned k_init, span< const bool > mask) const =0
Gets a number of resource elements in the resource grid at the given port and symbol using a mask to indicate which subcarriers are mapped and which are not.
symbols Destination symbol buffer. port Port index. l Symbol index. k_init Initial subcarrier index. mask Boolean mask denoting the subcarriers to be read (if true), starting from k_init. A span<cf_t> with the unused entries of symbols. The number of elements of mask shall be equal to or greater than the resource grid number of subcarriers. The number of elements of symbol shall be equal to or greater than the number of true elements in mask.
virtual void srsgnb::resource_grid_reader::get(span< cf_t > symbols, unsigned port, unsigned l, unsigned k_init) const =0
Gets a consecutive number of resource elements for a given port and symbol l starting at k_init.
symbols Destination symbol buffer. port Port index. l Symbol index. k_init Initial subcarrier index. The sum of k_init and the number of elements in symbols shall not exceed the resource grid number of subcarriers.