srsgnb::ofdm_symbol_demodulator_impl
unsigned srsgnb::ofdm_symbol_demodulator_impl::dft_size
Indicates the DFT size.
Referenced by ofdm_symbol_demodulator_impl, get_cp_offset, demodulate, get_symbol_size.
unsigned srsgnb::ofdm_symbol_demodulator_impl::rg_size
Indicates the resource grid bandwidth in resource elements.
Referenced by ofdm_symbol_demodulator_impl, demodulate, get_rg_size.
cyclic_prefix srsgnb::ofdm_symbol_demodulator_impl::cp
Cyclic prefix type.
Referenced by get_cp_offset, demodulate, get_symbol_size.
subcarrier_spacing srsgnb::ofdm_symbol_demodulator_impl::scs
Numerology.
Referenced by get_cp_offset, demodulate, get_symbol_size.
unsigned srsgnb::ofdm_symbol_demodulator_impl::sampling_rate_Hz
Sampling rate in Hz.
Referenced by get_cp_offset, demodulate, get_symbol_size.
float srsgnb::ofdm_symbol_demodulator_impl::scale
Scaling factor at the DFT output.
Referenced by ofdm_symbol_demodulator_impl, demodulate.
std::unique_ptr<dft_processor> srsgnb::ofdm_symbol_demodulator_impl::dft
DFT processor.
Referenced by ofdm_symbol_demodulator_impl, demodulate.
phase_compensation_lut srsgnb::ofdm_symbol_demodulator_impl::phase_compensation_table
Phase compensation table.
Referenced by demodulate.
std::vector<cf_t> srsgnb::ofdm_symbol_demodulator_impl::compensated_output
Internal buffer aimed at storing the phase compensated DFT outputs.
Referenced by ofdm_symbol_demodulator_impl, demodulate.
ofdm_symbol_demodulator_impl::ofdm_symbol_demodulator_impl(ofdm_demodulator_common_configuration &common_config, const ofdm_demodulator_configuration &ofdm_config)
Constructs an OFDM symbol demodulator.
common_config Provides specific configuration parameters from the factory. ofdm_config Provides generic OFDM configuration parameters.
References scale, dft_size, rg_size, dft, compensated_output.
unsigned srsgnb::ofdm_symbol_demodulator_impl::get_rg_size() const
Gets the resource grid bandwidth in resource elements.
The number of resource elements in the grid.
References rg_size.
unsigned ofdm_symbol_demodulator_impl::get_cp_offset(unsigned symbol_index, unsigned slot_index) const
Gets the offset in samples to the start of (the cyclic prefix of) a given symbol.
symbol_index Indicates the symbol index within the subframe. slot_index Slot index within the subframe containing the symbol to demodulate. The number of samples preceding the given symbol.
References srsgnb::get_nsymb_per_slot, cp, srsgnb::cyclic_prefix::get_length, scs, srsgnb::phy_time_unit::to_samples, sampling_rate_Hz, dft_size.
unsigned srsgnb::ofdm_symbol_demodulator_impl::get_symbol_size(unsigned symbol_index) const override
Gets a symbol size including cyclic prefix.
symbol_index Indicates the symbol index within the subframe. The number of samples for the given symbol index.
References cp, srsgnb::cyclic_prefix::get_length, scs, srsgnb::phy_time_unit::to_samples, sampling_rate_Hz, dft_size.
Referenced by srsgnb::ofdm_slot_demodulator_impl::get_slot_size, srsgnb::ofdm_slot_demodulator_impl::demodulate.
void ofdm_symbol_demodulator_impl::demodulate(resource_grid_writer &grid, span< const cf_t > input, unsigned port_index, unsigned symbol_index) override
Demodulates an OFDM signal with symbol granularity.
grid Provides the output as frequency-domain signal corresponding to one slot. input Provides the time domain modulated signal. port_index Indicates the port index to demodulate. symbol_index Symbol index within the subframe to demodulate. The input size must be equal to the the symbol size including the cyclic prefix. The output size must be consistent with the configured bandwidth.
References srsgnb::get_nsymb_per_slot, cp, srsgnb::cyclic_prefix::get_length, scs, srsgnb::phy_time_unit::to_samples, sampling_rate_Hz, srsgnb::span< T >::size, dft_size, srsgnb::scs_to_khz, dft, srsgnb::span< T >::last, phase_compensation_table, srsgnb::phase_compensation_lut::get_coefficient, scale, compensated_output, rg_size, srsgnb::resource_grid_writer::put.
Referenced by srsgnb::ofdm_slot_demodulator_impl::demodulate.