srslog::json_formatter
unsigned srslog::json_formatter::nest_level
std::vector<scope> srslog::json_formatter::scope_stack
srslog::json_formatter::json_formatter()
std::unique_ptr< log_formatter > json_formatter::clone() const override
Returns a copy of the formatter.
void json_formatter::format(detail::log_entry_metadata &&metadata, fmt::memory_buffer &buffer) override
Formats the log entry into the input buffer.
void json_formatter::format_context_begin(const detail::log_entry_metadata &md, fmt::string_view ctx_name, unsigned size, fmt::memory_buffer &buffer) override
Derived classes should implement the following callbacks to format metric objects. Each callback is invoked at a different place of the formatting algorithm. This callback gets called at the beginning of the context formatting algorithm.
References push_scope.
void json_formatter::format_context_end(const detail::log_entry_metadata &md, fmt::string_view ctx_name, fmt::memory_buffer &buffer) override
This callback gets called at the end of the context formatting algorithm.
References pop_scope.
void json_formatter::format_metric_set_begin(fmt::string_view set_name, unsigned size, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the beginning of a metric set formatting procedure.
References in_list_scope, indents, increment_nest_level, consume_element, push_scope.
void json_formatter::format_metric_set_end(fmt::string_view set_name, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the beginning of a metric set formatting end.
References pop_scope, indents, needs_comma, in_list_scope, decrement_nest_level.
void json_formatter::format_list_begin(fmt::string_view list_name, unsigned size, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the beginning of a metric list formatting procedure.
References consume_element, indents, push_list_scope.
void json_formatter::format_list_end(fmt::string_view list_name, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called at the end of a metric list formatting procedure.
References pop_scope, indents, needs_comma.
void json_formatter::format_metric(fmt::string_view metric_name, fmt::string_view metric_value, fmt::string_view metric_units, metric_kind kind, unsigned level, fmt::memory_buffer &buffer) override
This callback gets called for each metric.
References consume_element, indents, needs_comma.
void srslog::json_formatter::push_scope(unsigned size)
Pushes a new entry in the scope stack.
Referenced by format_context_begin, format_metric_set_begin.
void srslog::json_formatter::push_list_scope(unsigned size)
Pushes a new list entry in the scope stack.
Referenced by format_list_begin.
void srslog::json_formatter::pop_scope()
Pops the topmost entry in the scope stack.
Referenced by format_context_end, format_metric_set_end, format_list_end.
void srslog::json_formatter::consume_element()
Consumes an element in the current scope.
Referenced by format_metric_set_begin, format_metric, format_list_begin.
bool srslog::json_formatter::needs_comma() const
Returns true if the current element needs a comma.
Referenced by format_metric_set_end, format_metric, format_list_end.
bool srslog::json_formatter::in_list_scope() const
Returns true if the current scope is a list.
Referenced by format_metric_set_begin, format_metric_set_end.
void srslog::json_formatter::increment_nest_level()
Increments the nesting level by one.
Referenced by format_metric_set_begin.
void srslog::json_formatter::decrement_nest_level()
Decrements the nesting level by one.
Referenced by format_metric_set_end.
unsigned srslog::json_formatter::indents(unsigned level) const
Return the number of space chars to indent the specified level.
Referenced by format_metric_set_begin, format_metric_set_end, format_metric, format_list_begin, format_list_end.