srsgnb::downlink_processor_single_executor_impl
upper_phy_rg_gateway& srsgnb::downlink_processor_single_executor_impl::gateway
resource_grid_context srsgnb::downlink_processor_single_executor_impl::rg_context
resource_grid* srsgnb::downlink_processor_single_executor_impl::current_grid
std::unique_ptr<pdcch_processor> srsgnb::downlink_processor_single_executor_impl::pdcch_proc
std::unique_ptr<pdsch_processor> srsgnb::downlink_processor_single_executor_impl::pdsch_proc
std::unique_ptr<ssb_processor> srsgnb::downlink_processor_single_executor_impl::ssb_proc
std::unique_ptr<csi_rs_processor> srsgnb::downlink_processor_single_executor_impl::csi_rs_proc
task_executor& srsgnb::downlink_processor_single_executor_impl::executor
unsigned srsgnb::downlink_processor_single_executor_impl::pending_pdus
bool srsgnb::downlink_processor_single_executor_impl::is_send_allowed
std::mutex srsgnb::downlink_processor_single_executor_impl::mutex
Protects pending_pdus and is_send_allowed.
Referenced by configure_resource_grid, handle_resource_grid_send_opportunity, increase_pending_pdus, decrease_pending_pdus_and_try_sending_grid.
downlink_processor_single_executor_impl::downlink_processor_single_executor_impl(upper_phy_rg_gateway &gateway, std::unique_ptr< pdcch_processor > pdcch_proc_, std::unique_ptr< pdsch_processor > pdsch_proc_, std::unique_ptr< ssb_processor > ssb_proc_, std::unique_ptr< csi_rs_processor > csi_rs_proc_, task_executor &executor)
Builds a downlink processor single executor impl object with the given parameters.
gateway Gateway that will be used to send the resource grids. pdcch_proc_ PDSCH processor used to process PDSCH PDUs. pdsch_proc_ PDCCH processor used to process PDCCH PDUs. ssb_proc_ SSB processor used to process SSB PDUs. csi_rs_proc_ CSI-RS processor used to process CSI-RS configurations. executor Task executor that will be used to process every PDU.
void downlink_processor_single_executor_impl::process_pdcch(const pdcch_processor::pdu_t &pdu) override
Process the given PDCCH PDU.
pdu PDCCH PDU to process.
References increase_pending_pdus, srsgnb::task_executor::execute, decrease_pending_pdus_and_try_sending_grid.
void downlink_processor_single_executor_impl::process_pdsch(const static_vector< span< const uint8_t >, pdsch_processor::MAX_NOF_TRANSPORT_BLOCKS > &data, const pdsch_processor::pdu_t &pdu) override
Process the given PDSCH PDU and its related data, which it is given in data parameter.
data Contains the data of the PDSCH. pdu PDSCH PDU to process.
References increase_pending_pdus, srsgnb::task_executor::execute, decrease_pending_pdus_and_try_sending_grid.
void downlink_processor_single_executor_impl::process_ssb(const ssb_processor::pdu_t &pdu) override
Process the given SSB PDU.
pdu SSB PDU to process.
References increase_pending_pdus, srsgnb::task_executor::execute, decrease_pending_pdus_and_try_sending_grid.
void downlink_processor_single_executor_impl::process_nzp_csi_rs(const csi_rs_processor::config_t &config) override
Process the given CSI-RS configuration.
config NZP-CSI-RS configuration to process.
References increase_pending_pdus, srsgnb::task_executor::execute, decrease_pending_pdus_and_try_sending_grid.
void downlink_processor_single_executor_impl::configure_resource_grid(const resource_grid_context &context, resource_grid &grid) override
Configures the resource grid of the downlink_processor.
context Resource grid context that contains the information of the processing slot. grid Resource grid that will contain the data of the processed downlink channels. Calling this method is mandatory before processing any PDU. The resource grid number of ports and bandwidth must be sufficient to accommodate all the PDUs.
References mutex.
void srsgnb::downlink_processor_single_executor_impl::finish_processing_pdus() override
Stops accepting PDUs.
When this method is called, the interface will not expect to process more PDUs, so once it finishes to process all the enqueued PDUs, the resource grid will be sent to the lower bound gateway using the context from configure_resource_grid() to provide the processing context of the resource grid in the lower physical layer.
void downlink_processor_single_executor_impl::handle_resource_grid_send_opportunity()
Handles a send opportunity to send the resource grid. If all the conditions are met, the resource grid will be sent, otherwise it will do nothing.
References mutex, srsgnb::upper_phy_rg_gateway::send.
Referenced by decrease_pending_pdus_and_try_sending_grid.
void downlink_processor_single_executor_impl::increase_pending_pdus()
Increases the number of pending PDUs to be processed by 1.
References mutex.
Referenced by process_pdcch, process_pdsch, process_ssb, process_nzp_csi_rs.
void downlink_processor_single_executor_impl::decrease_pending_pdus_and_try_sending_grid()
Decreases the number of pending PDUs to be processed by 1 and tries to send the resource grid through the gateway.
References mutex, handle_resource_grid_send_opportunity.
Referenced by process_pdcch, process_pdsch, process_ssb, process_nzp_csi_rs.