srslog::file_utils::file
std::string srslog::file_utils::file::path
std::FILE* srslog::file_utils::file::handle
srslog::file_utils::file::~file()
srslog::file_utils::file::operator bool() const
std::FILE* srslog::file_utils::file::get_handle() const
Returns the handle of the underlying file.
const std::string& srslog::file_utils::file::get_path() const
Returns the path of the file.
detail::error_string srslog::file_utils::file::create(const std::string &new_path)
Creates a new file in the specified path by previously closing any opened file.
References close.
Referenced by srslog::file_sink::create_file, srslog::buffered_file_sink::write.
detail::error_string srslog::file_utils::file::write(detail::memory_buffer buffer)
Writes the provided memory buffer into an open file, otherwise does nothing.
References srslog::detail::memory_buffer::data, srslog::detail::memory_buffer::size, close.
Referenced by srslog::file_sink::write, srslog::buffered_file_sink::flush_buffer.
detail::error_string srslog::file_utils::file::flush()
Flushes the contents of an open file, otherwise does nothing.
References close.
Referenced by srslog::file_sink::flush, srslog::buffered_file_sink::flush.
void srslog::file_utils::file::close()
Closes an open file, otherwise does nothing.
Referenced by create, write, flush.