srsgnb::prach_processor_worker
states
The worker has not been configured yet with any request or the previously configured request has already been processed. It transitions to wait when a request is set.
std::unique_ptr<ofdm_prach_demodulator> srsgnb::prach_processor_worker::demodulator
OFDM PRACH demodulator.
Referenced by accumulate_samples.
task_executor& srsgnb::prach_processor_worker::async_task_executor
Asynchronous task executor.
Referenced by accumulate_samples.
unsigned srsgnb::prach_processor_worker::sampling_rate_Hz
Sampling rate in Hz.
Referenced by handle_request, prach_processor_worker.
srsvec::aligned_vec<cf_t> srsgnb::prach_processor_worker::temp_baseband
Temporary baseband buffer of size TEMP_BASEBAND_BUFFER_SIZE.
Referenced by accumulate_samples.
prach_processor_notifier* srsgnb::prach_processor_worker::notifier
PRACH processor notifier.
Referenced by run_state_wait, accumulate_samples, connect.
std::atomic<states> srsgnb::prach_processor_worker::state
Current worker state.
Referenced by run_state_wait, accumulate_samples, handle_request, process_symbol, is_available.
prach_buffer_context srsgnb::prach_processor_worker::prach_context
Current context.
Referenced by run_state_wait, run_state_collecting, accumulate_samples, handle_request.
prach_buffer* srsgnb::prach_processor_worker::buffer
Current PRACH buffer.
Referenced by accumulate_samples, handle_request.
unsigned srsgnb::prach_processor_worker::window_length
Current PRACH occasion window length.
Referenced by accumulate_samples, handle_request.
unsigned srsgnb::prach_processor_worker::nof_samples
Current number of collected samples.
Referenced by run_state_wait, accumulate_samples, handle_request.
void prach_processor_worker::run_state_wait(span< const cf_t > samples, const prach_processor_baseband::symbol_context &context)
Runs state wait.
References prach_context, srsgnb::prach_buffer_context::slot, srsgnb::prach_buffer_context::start_symbol, notifier, srsgnb::prach_processor_notifier::on_prach_request_late, state, idle, srsgnb::prach_buffer_context::sector, srsgnb::prach_buffer_context::port, nof_samples, collecting, accumulate_samples.
Referenced by process_symbol.
void prach_processor_worker::run_state_collecting(span< const cf_t > samples, const prach_processor_baseband::symbol_context &context)
Runs state collecting.
References prach_context, srsgnb::prach_buffer_context::sector, srsgnb::prach_buffer_context::port, accumulate_samples.
Referenced by process_symbol.
void prach_processor_worker::accumulate_samples(span< const cf_t > samples)
Accumulates samples in the internal buffer.
References window_length, nof_samples, srsgnb::span< T >::size, temp_baseband, srsgnb::span< T >::subspan, srsgnb::span< T >::first, state, processing, async_task_executor, srsgnb::task_executor::execute, srsgnb::ofdm_prach_demodulator::configuration::format, prach_context, srsgnb::prach_buffer_context::format, srsgnb::ofdm_prach_demodulator::configuration::rb_offset, srsgnb::prach_buffer_context::rb_offset, srsgnb::ofdm_prach_demodulator::configuration::nof_prb_ul_grid, srsgnb::prach_buffer_context::nof_prb_ul_grid, srsgnb::ofdm_prach_demodulator::configuration::pusch_scs, srsgnb::prach_buffer_context::pusch_scs, demodulator, buffer, notifier, srsgnb::prach_processor_notifier::on_rx_prach_window, idle.
Referenced by run_state_wait, run_state_collecting.
srsgnb::prach_processor_worker::prach_processor_worker(std::unique_ptr< ofdm_prach_demodulator > demodulator_, task_executor &async_task_executor_, unsigned dft_size_15kHz)
Creates a PRACH processor worker.
References sampling_rate_Hz.
void srsgnb::prach_processor_worker::connect(prach_processor_notifier &notifier_)
Connects the worker with the given PRACH processor notifier.
References notifier.
void prach_processor_worker::handle_request(prach_buffer &buffer, const prach_buffer_context &context)
Handles a PRACH occasion request.
PRACH buffer. PRACH occasion context.
References state, idle, prach_context, buffer, srsgnb::prach_buffer_context::format, srsgnb::preamble_format::is_long_preamble, srsgnb::get_prach_preamble_long_info, window_length, srsgnb::prach_preamble_information::cp_length, srsgnb::prach_preamble_information::symbol_length, sampling_rate_Hz, nof_samples, wait.
void prach_processor_worker::process_symbol(span< const cf_t > samples, const prach_processor_baseband::symbol_context &context)
Processes an OFDM symbol.
samples Baseband samples. context OFDM symbol context.
References state, idle, wait, run_state_wait, collecting, run_state_collecting, processing.
bool srsgnb::prach_processor_worker::is_available() const
Determines whether the PRACH processor worker is available.
A PRACH processor is available when it is idle. See states for more information regarding the PRACH worker internal states.
References state, idle.