srsgnb::harq_process
const harq_id_t srsgnb::harq_process::pid
uint32_t srsgnb::harq_process::max_retx
slot_point srsgnb::harq_process::slot_tx
For DL, slot_tx corresponds to the slot when the TB in the HARQ process is going to be transmitted by the gNB. For UL, slot_tx corresponds to the slot when the TB in the HARQ process is going to be transmitted by the UE.
Referenced by srsgnb::dl_harq_process::new_tx, srsgnb::dl_harq_process::new_retx, srsgnb::ul_harq_process::new_tx, srsgnb::ul_harq_process::new_retx.
slot_point srsgnb::harq_process::slot_ack
For DL, slot_ack is the slot at which gNB is expected to receive the ACK via UCI. For UL, slot_ack is the slot when the PUSCH CRC will be processed. It coincides with slot_tx.
Referenced by slot_indication, srsgnb::dl_harq_process::new_tx, srsgnb::dl_harq_process::new_retx.
prb_grant srsgnb::harq_process::prbs_
static_vector<tb_t, MAX_NOF_LAYERS> srsgnb::harq_process::tb
srsgnb::harq_process::harq_process(harq_id_t id_)
void srsgnb::harq_process::slot_indication(slot_point slot_rx)
Indicate the beginning of a new slot.
References empty, slot_ack, nof_retx, max_nof_retx.
void srsgnb::harq_process::reset()
Clear the contents of this HARQ process and reset it back to empty state.
bool srsgnb::harq_process::set_tbs(uint32_t tbs)
bool srsgnb::harq_process::set_mcs(uint32_t mcs)
bool srsgnb::harq_process::empty() const
Checks whether the HARQ process has no Transport Block currently stored.
Referenced by srsgnb::ra_scheduler::fill_rar_grant, slot_indication.
bool srsgnb::harq_process::empty(unsigned tb_idx) const
bool srsgnb::harq_process::has_pending_retx() const
Checks whether the TB has not been positively ACKED yet.
bool srsgnb::harq_process::has_pending_retx(unsigned tb_idx) const
uint32_t srsgnb::harq_process::nof_retx() const
Number of times the currently stored TB has been retransmitted.
Referenced by slot_indication.
uint32_t srsgnb::harq_process::max_nof_retx() const
Current maximum value of retransmissions of a single TB.
Referenced by slot_indication.
uint32_t srsgnb::harq_process::tbs(unsigned tb_index) const
bool srsgnb::harq_process::ndi(unsigned tb_index) const
uint32_t srsgnb::harq_process::mcs(unsigned tb_index) const
const prb_grant& srsgnb::harq_process::prbs() const
slot_point srsgnb::harq_process::harq_slot_tx() const
slot_point srsgnb::harq_process::harq_slot_ack() const
int srsgnb::harq_process::ack_info(uint32_t tb_idx, bool ack)
bool srsgnb::harq_process::new_tx_common(slot_point slot_tx, slot_point slot_ack, const prb_grant &grant, uint32_t mcs, uint32_t max_retx)
bool srsgnb::harq_process::new_retx_common(slot_point slot_tx, slot_point slot_ack, const prb_grant &grant)
bool srsgnb::harq_process::new_retx_common(slot_point slot_tx, slot_point slot_ack)