srsgnb::radio_session_uhd_impl
states
using srsgnb::radio_session_uhd_impl::port_to_stream_channel = std::pair<unsigned, unsigned>
Maps ports to stream and channel indexes.
constexpr double srsgnb::radio_session_uhd_impl::START_STREAM_DELAY_S
Defines the start stream command delay in seconds.
Referenced by start_rx_stream.
std::atomic<states> srsgnb::radio_session_uhd_impl::state
Indicates the current state.
Referenced by stop, is_successful.
radio_uhd_device_type srsgnb::radio_session_uhd_impl::type
Indicates the device type.
radio_uhd_device srsgnb::radio_session_uhd_impl::device
Wraps the UHD device functions.
Referenced by set_time_to_gps_time, wait_sensor_locked, set_tx_gain_unprotected, set_rx_gain_unprotected, set_tx_freq, set_rx_freq, start_rx_stream.
static_vector<port_to_stream_channel, RADIO_MAX_NOF_PORTS> srsgnb::radio_session_uhd_impl::tx_port_map
Indexes the transmitter port indexes into stream and channel index as first and second.
Referenced by set_tx_gain_unprotected, set_tx_freq, set_rx_freq.
static_vector<port_to_stream_channel, RADIO_MAX_NOF_PORTS> srsgnb::radio_session_uhd_impl::rx_port_map
Indexes the receiver port indexes into stream and channel index as first and second.
Referenced by set_rx_gain_unprotected, set_rx_freq.
static_vector<std::unique_ptr<radio_uhd_tx_stream>, RADIO_MAX_NOF_PORTS> srsgnb::radio_session_uhd_impl::tx_streams
Vector or transmit streams.
Referenced by stop, transmit.
static_vector<std::unique_ptr<radio_uhd_rx_stream>, RADIO_MAX_NOF_PORTS> srsgnb::radio_session_uhd_impl::rx_streams
Vector or receive streams.
Referenced by start_rx_stream, stop, transmit, receive.
double srsgnb::radio_session_uhd_impl::sampling_rate_hz
std::mutex srsgnb::radio_session_uhd_impl::stream_start_mutex
Protects the stream start.
Referenced by start_rx_stream.
bool srsgnb::radio_session_uhd_impl::stream_start_required
Indicates if the reception streams require start.
Referenced by start_rx_stream.
bool radio_session_uhd_impl::set_time_to_gps_time()
Set the synchronization time to GPS mode.
True if no exception is caught. Otherwise false.
References device.
bool radio_session_uhd_impl::wait_sensor_locked(bool &is_locked, const std::string &sensor_name, bool is_mboard, int timeout)
Waits for a sensor to be locked.
is_locked Indicates if the sensor is locked by the time the method returns. sensor_name Indicates the sensor name. is_mboard Indicates if the sensor is from the motherboard or daughterboard. timeout Indicates the amount of time to wait. True if no exception is caught. Otherwise false.
References device.
bool radio_session_uhd_impl::set_tx_gain_unprotected(unsigned port_idx, double gain_dB)
Set transmission gain from the class itself.
port_idx Indicates the port index. gain_dB Indicates the gain value. True if the port index and gain value are valid, and no exception is caught. Otherwise false.
References tx_port_map, device.
Referenced by set_tx_gain.
bool radio_session_uhd_impl::set_rx_gain_unprotected(unsigned port_idx, double gain_dB)
Set reception gain from the class itself.
port_idx Indicates the port index. gain_dB Indicates the gain value. True if the port index and gain value are valid, and no exception is caught. Otherwise false.
References rx_port_map, device.
Referenced by set_rx_gain.
bool radio_session_uhd_impl::set_tx_freq(unsigned port_idx, radio_configuration::lo_frequency frequency)
Set transmission frequency.
port_idx Indicates the port index. frequency Provides the frequency tuning parameters True if the port index and frequency value are valid, and no exception is caught. Otherwise false.
References tx_port_map, device, srsgnb::radio_configuration::lo_frequency::center_frequency_hz.
bool radio_session_uhd_impl::set_rx_freq(unsigned port_idx, radio_configuration::lo_frequency frequency)
Set reception frequency.
port_idx Indicates the port index. frequency Provides the frequency tuning parameters True if the port index and frequency value are valid, and no exception is caught. Otherwise false.
References rx_port_map, tx_port_map, device, srsgnb::radio_configuration::lo_frequency::center_frequency_hz.
bool radio_session_uhd_impl::start_rx_stream()
Start receive streams.
True if no exception is caught. Otherwise false.
References stream_start_mutex, stream_start_required, device, START_STREAM_DELAY_S, rx_streams.
Referenced by receive.
radio_session_uhd_impl::radio_session_uhd_impl(const radio_configuration::radio &radio_config, task_executor &async_executor, radio_notification_handler &notifier_)
Constructs a radio session based on UHD.
References srsgnb::radio_configuration::radio::args, srsgnb::radio_configuration::radio::log_level, srsgnb::radio_configuration::radio::sampling_rate_hz.
bool srsgnb::radio_session_uhd_impl::is_successful() const
Indicates that the radio session was initialized succesfully.
True if no exception is caught during initialization. Otherwise false.
References state.
radio_management_plane& srsgnb::radio_session_uhd_impl::get_management_plane() override
Gets the management plane.
The reference to the management plane for this radio session.
baseband_gateway& srsgnb::radio_session_uhd_impl::get_baseband_gateway() override
Gets the data plane.
The reference to the data plane for this radio session.
void radio_session_uhd_impl::stop() override
Stops the radio session operation.
Any call to transmit or receive after calling stop() will return instantly without interacting with the physical radio.
References state, tx_streams, rx_streams.
baseband_gateway_transmitter& srsgnb::radio_session_uhd_impl::get_transmitter() override
Get the transmitter gateway.
baseband_gateway_receiver& srsgnb::radio_session_uhd_impl::get_receiver() override
Get the receiver gateway.
void radio_session_uhd_impl::transmit(unsigned stream_id, const baseband_gateway_transmitter::metadata &metadata, baseband_gateway_buffer &data) override
Transmits a given baseband buffer in a given time provided in the metadata.
stream_id Radio stream identifier. metadata Provides additional parameters for transmission. data Provides the baseband buffer to transmit. The data buffers must the same number of channels than the stream. The application terminates if the stream identifier is invalid.
References tx_streams, rx_streams, srsgnb::baseband_gateway_transmitter::metadata::ts.
baseband_gateway_receiver::metadata radio_session_uhd_impl::receive(baseband_gateway_buffer &data, unsigned stream_id) override
Receives a given baseband buffer.
data Provides the baseband buffer destination and the number of samples to receive. stream_id Radio stream identifier. Receive metadata. The data buffers must the same number of channels than the stream. The application terminates if the stream identifier is invalid.
References rx_streams, start_rx_stream, srsgnb::baseband_gateway_receiver::metadata::ts.
bool srsgnb::radio_session_uhd_impl::set_tx_gain(unsigned port_idx, double gain_dB) override
Set the transmission gain of a given port in runtime.
port_id Indicates the port identifier. gain_dB Indicates the new gain. True if the operation is successful. Otherwise, false. The port identifier is indexed from stream ascending order and then port.
References set_tx_gain_unprotected.
bool srsgnb::radio_session_uhd_impl::set_rx_gain(unsigned port_idx, double gain_dB) override
Set the reception gain of a given port in runtime.
port_id Indicates the port identifier. gain_dB Indicates the new gain. True if the operation is successful. Otherwise, false. The port identifier is indexed from stream ascending order and then port.
References set_rx_gain_unprotected.