srsgnb::interval
T srsgnb::interval< T >::start_
T srsgnb::interval< T >::stop_
srsgnb::interval< T >::interval()
srsgnb::interval< T >::interval(U start_point, V stop_point)
T srsgnb::interval< T >::start() const
T srsgnb::interval< T >::stop() const
bool srsgnb::interval< T >::empty() const
auto srsgnb::interval< T >::length() const -> decltype(std::declval< T >() - std::declval< T >())
Interval length.
Referenced by srsgnb::interval< slot_point >::extend, srsgnb::interval< slot_point >::displace_to, srsgnb::convert_rbgs_to_prbs, srsgnb::get_nof_rbgs, srsgnb::ra_scheduler::schedule_rar, srsgnb::ra_scheduler::fill_rar_grant, srsgnb::sib1_scheduler::allocate_sib1, srsgnb::sib1_scheduler::fill_sib1_grant, srsgnb::prb_to_crb, srsgnb::get_coreset_nof_prbs, srsgnb::find_empty_interval_of_length.
void srsgnb::interval< T >::set(T start_point, T stop_point)
void srsgnb::interval< T >::extend(T length_increment)
Increase the interval length, maintaining the same starting point. length_increment Length increment/decrement to apply to current interval size. In case length_increment < 0, the condition -length_increment <= length() must be met.
void srsgnb::interval< T >::resize(T new_length)
Set the interval length, maintaining the same starting point.
Referenced by srsgnb::ra_scheduler::schedule_rar.
void srsgnb::interval< T >::displace_by(int offset)
Move interval by an offset.
Referenced by srsgnb::carrier_subslot_resource_grid::fill, srsgnb::carrier_subslot_resource_grid::collides, srsgnb::carrier_subslot_resource_grid::all_set.
void srsgnb::interval< T >::displace_to(T start_point)
Move interval start to provided starting point.
bool srsgnb::interval< T >::overlaps(interval other) const
If this and other intervals overlap.
Referenced by srsgnb::interval< slot_point >::intersect, srsgnb::operator|, srsgnb::operator&.
bool srsgnb::interval< T >::contains(T point) const
If interval contains provided point.
Referenced by srsgnb::ra_scheduler::run_slot, srsgnb::crb_to_prb.
bool srsgnb::interval< T >::contains(interval other) const
If interval contains provided interval.
interval<T>& srsgnb::interval< T >::intersect(const interval< T > &other)
Assign to this interval the intersection between this and the provided interval.
Referenced by srsgnb::prb_grant::operator&=.