srsgnb::crc_calculator_impl
const std::map< crc_generator_poly, crc_calculator_impl::crc_table_s > crc_calculator_impl::crc_tables
Map of CRC tables for the different polynomials.
const crc_table_s& srsgnb::crc_calculator_impl::table
Current CRC table.
Referenced by put_byte, reversecrcbit.
const unsigned srsgnb::crc_calculator_impl::order
Generator polynomial order.
Referenced by put_byte.
const uint64_t srsgnb::crc_calculator_impl::crcmask
String of order consecutive ones (used for isolating meaningful bits).
Referenced by get_checksum.
uint64_t srsgnb::crc_calculator_impl::crc
Computed checksum.
Referenced by reset, put_byte, get_checksum, reversecrcbit, calculate_bit.
const crc_generator_poly srsgnb::crc_calculator_impl::poly
Identifier of the cyclic generator polynomial.
Referenced by get_generator_poly.
void crc_calculator_impl::reset()
Clears internal registers.
References crc.
Referenced by calculate_bit.
void crc_calculator_impl::put_byte(unsigned char byte)
Includes the given byte into the CRC computation.
References order, crc, table.
Referenced by calculate_bit.
crc_calculator_checksum_t crc_calculator_impl::get_checksum() const
Reads the current value of crc.
References crc, crcmask.
Referenced by calculate_bit.
void crc_calculator_impl::reversecrcbit(unsigned nbits)
Reverses the nbits least significant bits of crc.
References crc, table, srsgnb::crc_calculator_impl::crc_table_s::polynom, srsgnb::crc_calculator_impl::crc_table_s::crcmask.
Referenced by calculate_bit.
crc_calculator_impl::crc_calculator_impl(crc_generator_poly poly_)
Initializes the CRC calculator with the provided cyclic generator polynomial.
crc_calculator_checksum_t srsgnb::crc_calculator_impl::calculate_byte(span< const uint8_t > input) override
Calculates the checksum from a byte buffer (8 packed bits in every input byte).
data Provides the byte buffer. The resulting CRC checksum.
crc_calculator_checksum_t crc_calculator_impl::calculate_bit(span< const uint8_t > input) override
Calculates the checksum from a bit buffer (1 bit in for every input byte).
data Provides the byte buffer. The resulting CRC checksum.
References reset, srsgnb::span< T >::size, srsgnb::span< T >::subspan, srsgnb::span< T >::data, put_byte, crc, get_checksum, reversecrcbit.
crc_generator_poly srsgnb::crc_calculator_impl::get_generator_poly() const override
Returns the identifier of the generator polynomial.
References poly.