srsgnb::pdcch_modulator_impl
constexpr unsigned srsgnb::pdcch_modulator_impl::MAX_RB_PER_PDCCH
Defines the maximum number of resource blocks used in a transmission. It considers the maximum aggregation level of 16 and a REG size of 6 RB.
constexpr unsigned srsgnb::pdcch_modulator_impl::NOF_RE_PER_RB
Defines the number of resource elements available for PDCCH in a resource block.
constexpr unsigned srsgnb::pdcch_modulator_impl::MAX_RE
Defines the maximum number of resource elements that can be utilised for a PDCCH transmission.
constexpr unsigned srsgnb::pdcch_modulator_impl::MAX_BITS
Defines the maximum number of bits that can be utilised for a PDCCH transmission.
std::unique_ptr<modulation_mapper> srsgnb::pdcch_modulator_impl::modulator
Provides an implementation of the modulator.
Referenced by modulate, pdcch_modulator_impl.
std::unique_ptr<pseudo_random_generator> srsgnb::pdcch_modulator_impl::scrambler
Provides an implementation of the the pseudo-random generator.
Referenced by scramble, pdcch_modulator_impl.
void pdcch_modulator_impl::scramble(span< uint8_t > b_hat, span< const uint8_t > b, const config_t &config)
Scrambles a codeword. Implements TS 38.211 section 7.3.2.3 Scrambling.
b_hat Output bits after scrambling. b Inputs bits to scramble. config Provides the scrambler configuration.
References srsgnb::pdcch_modulator::config_t::n_rnti, srsgnb::pdcch_modulator::config_t::n_id, scrambler.
Referenced by modulate.
void pdcch_modulator_impl::modulate(span< cf_t > d_pdcch, span< const uint8_t > b_hat, float scaling)
Modulates a codeword. Implements TS 38.211 section 7.3.2.4 PDCCH modulation.
d_pdcch Output symbols. b_hat Inputs bits to perform the modulation mapping. scaling Indicates the signal scaling if the value is valid (not 0, NAN nor INF).
References modulator, srsgnb::QPSK.
Referenced by modulate.
void pdcch_modulator_impl::map(resource_grid_writer &grid, span< const cf_t > d_pdcch, const config_t &config)
Maps the modulated symbols to resource elements in the grid. Implements TS 38.211 section 7.3.2.5 Mapping to physical resources.
grid Provides the destination resource grid. d_pdcch Provides the block of complex-valued symbols to map. config Provides the mapper configuration.
References srsgnb::get_rg_subc_mask_reference, srsgnb::pdcch_modulator::config_t::rb_mask, srsgnb::get_rg_subc_mask, srsgnb::pdcch_modulator::config_t::ports, srsgnb::pdcch_modulator::config_t::start_symbol_index, srsgnb::pdcch_modulator::config_t::duration, srsgnb::resource_grid_writer::put.
Referenced by modulate.
void pdcch_modulator_impl::modulate(resource_grid_writer &grid, span< const uint8_t > data, const config_t &config) override
Modulates a PDCCH codeword according to TS 38.211 section 7.3.2 Physical downlink control channel.
grid Provides the destination resource grid. data Provides the encoded and unpacked bits to modulate. config Provides the configuration. The codeword length shall be consistent with the resource mapping.
References scramble, modulate, srsgnb::pdcch_modulator::config_t::scaling, map.
srsgnb::pdcch_modulator_impl::pdcch_modulator_impl(std::unique_ptr< modulation_mapper > modulator_, std::unique_ptr< pseudo_random_generator > scrambler_)
Generic PDCCH modulator instance constructor.
References modulator, scrambler.