srsgnb::lcid_ul_sch_t
options
CCCH of 64 bits.
using srsgnb::lcid_ul_sch_t::underlying_type = std::underlying_type_t<lcid_t>
underlying_type srsgnb::lcid_ul_sch_t::lcid_val
srsgnb::lcid_ul_sch_t::lcid_ul_sch_t(underlying_type lcid_=PADDING)
lcid_ul_sch_t& srsgnb::lcid_ul_sch_t::operator=(underlying_type lcid)
srsgnb::lcid_ul_sch_t::operator underlying_type() const
underlying_type srsgnb::lcid_ul_sch_t::value() const
bool srsgnb::lcid_ul_sch_t::is_ccch() const
Whether LCID belongs to CCCH.
References CCCH_SIZE_48, CCCH_SIZE_64.
Referenced by has_length_field.
bool srsgnb::lcid_ul_sch_t::is_ce() const
Whether LCID is an MAC CE.
bool srsgnb::lcid_ul_sch_t::is_sdu() const
Whether LCID belongs to a Radio Bearer Logical Channel.
References LCID1.
Referenced by has_length_field, srsgnb::pdu_rx_handler::handle_rx_subpdus.
bool srsgnb::lcid_ul_sch_t::is_valid_lcid() const
Returns false for all reserved values in Table 6.2.1-1 and 6.2.1-2.
Referenced by srsgnb::mac_ul_sch_subpdu::unpack.
bool srsgnb::lcid_ul_sch_t::has_length_field() const
Whether LCID subPDU has associated length field.
References is_ccch, is_sdu.
Referenced by srsgnb::mac_ul_sch_subpdu::unpack.
bool srsgnb::lcid_ul_sch_t::is_var_len_ce() const
uint32_t srsgnb::lcid_ul_sch_t::sizeof_ce() const
bool srsgnb::lcid_ul_sch_t::operator==(lcid_ul_sch_t other) const
bool srsgnb::lcid_ul_sch_t::operator!=(lcid_ul_sch_t other) const