srsgnb::dmrs_type
options
constexpr unsigned srsgnb::dmrs_type::DMRS_MAX_PORTS_TYPE1
Defines the maximum number of ports for DMRS type 1.
Referenced by dmrs_max_ports_type.
constexpr unsigned srsgnb::dmrs_type::DMRS_MAX_PORTS_TYPE2
Defines the maximum number of ports for DMRS type 2.
Referenced by dmrs_max_ports_type.
options srsgnb::dmrs_type::value
Indicates the cyclic prefix type.
Referenced by operator==, nof_dmrs_per_rb, dmrs_max_ports_type, get_dmrs_pattern.
constexpr srsgnb::dmrs_type::dmrs_type()=default
Default dmrs_type as normal.
constexpr srsgnb::dmrs_type::dmrs_type(options opt)
Construct from value. It allows implicit conversion from a DMRS type option.
constexpr srsgnb::dmrs_type::dmrs_type(const dmrs_type &other)
Construct from another DMRS type.
constexpr bool srsgnb::dmrs_type::operator==(options opt) const
Comparison to value.
References value.
constexpr bool srsgnb::dmrs_type::operator==(const dmrs_type &other) const
Comparison to other instance.
References value.
constexpr unsigned srsgnb::dmrs_type::nof_dmrs_per_rb() const
Calculates the number of resource elements that carry DMRS for PDSCH or PUSCH per resource block and symbol.
type Provides the type of DMRS. The number of resource elements occupied by DMRS in a resource block and symbol.
References value.
Referenced by srsgnb::dmrs_pdsch_processor_impl::sequence_generation, srsgnb::dmrs_pdsch_processor_impl::map.
constexpr unsigned srsgnb::dmrs_type::dmrs_max_ports_type() const
Provides the maximum number of ports supported by the DMRS type.
References value, DMRS_MAX_PORTS_TYPE1, DMRS_MAX_PORTS_TYPE2.
re_pattern srsgnb::dmrs_type::get_dmrs_pattern(unsigned bwp_start_rb, unsigned bwp_size_rb, unsigned nof_cdm_groups_without_data, span< const bool > symbol_mask) const
Gets a DMRS transmission pattern.
It creates a RE pattern that describes the reserved resource elements for DMRS in PDSCH or PUSCH transmissions. bwp_start_rb Indicates the start of the BWP. bwp_size_rb Indicates the size of the BWP. nof_cdm_groups_without_data Indicates the number of CDM groups without data for the transmission. symbol_mask Indicates, with a mask, the symbols carrying DMRS. An RE pattern describing the reserved elements for DMRS.
References srsgnb::span< T >::size, srsgnb::re_pattern::symbols, srsgnb::re_pattern::rb_begin, srsgnb::re_pattern::rb_end, srsgnb::re_pattern::rb_stride, value, srsgnb::NRE, srsgnb::re_pattern::re_mask, srsgnb::span< T >::begin, srsgnb::span< T >::end.
Referenced by srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::pdsch_processor_impl::compute_nof_data_re.