srsgnb::task_executor
virtual srsgnb::task_executor::~task_executor()=default
virtual void srsgnb::task_executor::execute(unique_task task)=0
Dispatches a task to be executed. According to this policy, executor may invoke task inplace if it deemed safe to do so.
Referenced by srsgnb::mac_cell_processor::handle_slot_indication, srsgnb::mac_ul_processor::handle_rx_data_indication, srsgnb::pdu_rx_handler::handle_crnti_ce, srsgnb::prach_processor_worker::accumulate_samples, srsgnb::downlink_processor_single_executor_impl::process_pdcch, srsgnb::downlink_processor_single_executor_impl::process_pdsch, srsgnb::downlink_processor_single_executor_impl::process_ssb, srsgnb::downlink_processor_single_executor_impl::process_nzp_csi_rs, srsgnb::uplink_processor_single_executor_impl::process_prach.
virtual void srsgnb::task_executor::defer(unique_task task)=0
Dispatches a task to be later executed. The task always gets enqueued for later invocation.
Referenced by srsgnb::lower_phy_impl::realtime_process_loop, srsgnb::lower_phy_impl::start, srsgnb::radio_uhd_tx_stream::run_recv_async_msg.