srsgnb::low_papr_sequence_generator_impl
constexpr unsigned srsgnb::low_papr_sequence_generator_impl::NOF_ZC_SEQ
Defines the maximum number of short sequences.
const std::array< std::array< float, 6 >, low_papr_sequence_generator_impl::NOF_ZC_SEQ > low_papr_sequence_generator_impl::phi_M_sc_6
Defines Phi values for M_sc=6 Table 5.2.2.2-1 in TS 38.211.
Referenced by r_uv_arg_0dot5prb.
const std::array< std::array< float, 12 >, low_papr_sequence_generator_impl::NOF_ZC_SEQ > low_papr_sequence_generator_impl::phi_M_sc_12
Defines Phi values for M_sc=12 Table 5.2.2.2-2 in TS 38.211.
Referenced by r_uv_arg_1prb.
const std::array< std::array< float, 18 >, low_papr_sequence_generator_impl::NOF_ZC_SEQ > low_papr_sequence_generator_impl::phi_M_sc_18
Defines Phi values for M_sc=18 Table 5.2.2.2-3 in TS 38.211.
Referenced by r_uv_arg_1dot5prb.
const std::array< std::array< float, 24 >, low_papr_sequence_generator_impl::NOF_ZC_SEQ > low_papr_sequence_generator_impl::phi_M_sc_24
Defines Phi values for M_sc=24 Table 5.2.2.2-4 in TS 38.211.
Referenced by r_uv_arg_2prb.
void low_papr_sequence_generator_impl::r_uv_arg_0dot5prb(span< float > tmp_arg, unsigned u)
Generates argument for the sequence $r^{(\alpha, \beta)}_{u,v}(n)$ for base sequences of length 6.
tmp_arg Argument generation destination. u Indicates the sequence group index {0,29}.
References phi_M_sc_6.
Referenced by r_uv_arg.
void low_papr_sequence_generator_impl::r_uv_arg_1prb(span< float > tmp_arg, unsigned u)
Generates argument for the sequence $r^{(\alpha, \beta)}_{u,v}(n)$ for base sequences of length 12.
tmp_arg Argument generation destination. u Indicates the sequence group index {0,29}.
References phi_M_sc_12.
Referenced by r_uv_arg.
void low_papr_sequence_generator_impl::r_uv_arg_1dot5prb(span< float > tmp_arg, unsigned u)
Generates argument for the sequence $r^{(\alpha, \beta)}_{u,v}(n)$ for base sequences of length 18.
tmp_arg Argument generation destination. u Indicates the sequence group index {0,29}.
References phi_M_sc_18.
Referenced by r_uv_arg.
void low_papr_sequence_generator_impl::r_uv_arg_2prb(span< float > tmp_arg, unsigned u)
Generates argument for the sequence $r^{(\alpha, \beta)}_{u,v}(n)$ for base sequences of length 24.
tmp_arg Argument generation destination. u Indicates the sequence group index {0,29}.
References phi_M_sc_24.
Referenced by r_uv_arg.
void low_papr_sequence_generator_impl::r_uv_arg_mprb(span< float > tmp_arg, unsigned u, unsigned v)
Generates argument for the sequence $r^{(\alpha, \beta)}_{u,v}(n)$ for base sequences of length 36 or larger.
tmp_arg Argument generation destination. u Indicates the sequence group index {0,29}. v Indicates the sequence base index {0,1}.
References srsgnb::span< T >::size, srsgnb::prime_lower_than.
Referenced by r_uv_arg.
void low_papr_sequence_generator_impl::r_uv_arg(span< float > tmp_arg, unsigned u, unsigned v)
Generates argument for the sequence $r^{(\alpha, \beta)}_{u,v}(n)$.
tmp_arg Argument generation destination. u Indicates the sequence group index {0,29}. v Indicates the sequence base index {0,1}.
References srsgnb::span< T >::size, r_uv_arg_0dot5prb, r_uv_arg_1prb, r_uv_arg_1dot5prb, r_uv_arg_2prb, r_uv_arg_mprb, srsgnb::srsgnb_terminate.
Referenced by generate.
void low_papr_sequence_generator_impl::cexp(span< cf_t > sequence, float alpha, const span< const float > tmp_arg)
Generates sequence $r^{(\alpha, \beta)}_{u,v}(n) = e^{-j (temp_arg[n] + \alpha \times n) }$.
sequence Sequence generation destination. alpha Provides parameter $\alpha$. tmp_arg Provides the complex exponential argument.
References srsgnb::span< T >::size, srsgnb::COMPLEX_J.
Referenced by generate.
void low_papr_sequence_generator_impl::generate(span< cf_t > sequence, unsigned u, unsigned v, float alpha) const override
Generates a $r^{(\alpha, \beta)}_{u,v}$ sequence as per TS 38.211 section 5.2.2.
sequence Provides the destination buffer and the sequence length. u Indicates the sequence group {0...29}. v Indicates the sequence base {0,1}. alpha Indicates the $\alpha$ parameter.
References srsgnb::span< T >::size, r_uv_arg, cexp.