srsgnb::vrb_to_prb_mapper
unsigned srsgnb::vrb_to_prb_mapper::coreset_start
Indicates VRB index of the lowest VRB in the CORESET used for the DCI transmission.
Referenced by get_coreset_start, operator==, create_non_interleaved_common_ss, create_interleaved_coreset0, create_interleaved_common, get_allocation_indices.
unsigned srsgnb::vrb_to_prb_mapper::nof_bundles
Indicates the number of RB bundles $N_{bundle}$. It is set to zero for non-interleaved mapping.
Referenced by is_interleaved, operator==, create_non_interleaved_common_ss, create_interleaved_coreset0, create_interleaved_common, create_interleaved_other, get_allocation_indices.
unsigned srsgnb::vrb_to_prb_mapper::first_bundle_size
Indicates the first RB bundle size.
Referenced by operator==, create_interleaved_coreset0, create_interleaved_common, create_interleaved_other, get_allocation_indices.
unsigned srsgnb::vrb_to_prb_mapper::last_bundle_size
Indicates the last RB bundle size.
Referenced by operator==, create_interleaved_coreset0, create_interleaved_common, create_interleaved_other, get_allocation_indices.
unsigned srsgnb::vrb_to_prb_mapper::other_bundle_size
Indicates the other RB bundle sizes.
Referenced by operator==, create_interleaved_coreset0, create_interleaved_common, create_interleaved_other, get_allocation_indices.
vrb_to_prb_mapper vrb_to_prb_mapper::create_non_interleaved_common_ss(unsigned N_start_coreset)
Creates a non-interleaved VRB-to-PRB mapper for PDSCH transmissions scheduled by DCI Format 1_0 in common SS.
Implemented as per TS38.211 Section 7.3.1.6 Case 1: A virtual resource $n$ is mapped to the physical block $n + N_{start}^{CORESET}$. If the PDSCH is scheduled with DCI format 1_0 with the CRC scrambled by SI-RNTI in Type0-PDCCH common search space in CORESET 0, the BWP start and size must match with the CORESET0 start and size. Consequently, $N_{start}^{CORESET}$ must be zero. N_start_coreset VRB index of the lowest-numbered RB in the CORESET used for the DCI transmission as $N_{start}^{CORESET}$. A VRB-to-PRB mapper instance.
References coreset_start, nof_bundles.
vrb_to_prb_mapper vrb_to_prb_mapper::create_non_interleaved_other()
Creates a non-interleaved VRB-to-PRB mapper for PDSCH transmissions scheduled by DCI other than Format 1_0 in common SS.
Implemented as per TS38.211 Section 7.3.1.6 Case 2: A virtual resouce $n$ is mapped to the physical block $n$. A VRB-to-PRB mapper instance.
vrb_to_prb_mapper vrb_to_prb_mapper::create_interleaved_coreset0(unsigned N_start_coreset, unsigned N_bwp_init_size)
Creates a VRB-to-PRB mapper for PDSCH transmissions scheduled with DCI Format 1_0 with the CRC scrambled by SI-RNTI in Type0-PDCCH common SS in CORESET0.
Implemented as per TS38.211 Section 7.3.1.6 Case 3: the number of bundles is calculated as $N_{bundle}=\lceil N_{BWP,init}^{size}/L \rceil$, the last RB bundle consists of $N_{BWP,init}^{size} \bmod L$ if $N_{BWP,init}^{size} \bmod L > 0$, all other resource block bundles consist of $L$ RBs, and the bundle size is $L=2$. N_start_coreset VRB index of the lowest-numbered RB in the CORESET used for the DCI transmission as $N_{start}^{CORESET}$. N_bwp_init_size The size in RBs of CORESET0 as $N_{BWP,init}^{size}$. A VRB-to-PRB mapper instance.
References coreset_start, nof_bundles, srsgnb::divide_ceil, last_bundle_size, first_bundle_size, other_bundle_size.
vrb_to_prb_mapper vrb_to_prb_mapper::create_interleaved_common(unsigned N_start_coreset, unsigned N_bwp_i_start, unsigned N_bwp_init_size)
Creates a VRB-to-PRB mapper for PDSCH transmissions scheduled by DCI format 1_0 in any common SS except Type0-PDCCH common SS in CORESET0.
Implemented as per TS38.211 Section 7.3.1.6 Case 4: the set of $N_{BWP,init}^{size}$ virtual RBs starting at $N_{BWP,i}^{start}$ is divided into $N_{bundle}=\lceil (N_{BWP,init}^{size} + ((N_{BWP,i}^{start} + N_{start}^{CORESET}) \bmod L))/L \rceil$, the bundle size is $L=2$, the first RB bundle consists of $L - ((N_{BWP,init}^{size} + N_{start}^{CORESET}) \bmod L)$, the last RB bundle consists of $(N_{BWP,init}^{size} + N_{BWP,i}^{start} + N_{start}^{CORESET}) \bmod L$ if $(N_{BWP,init}^{size} + N_{BWP,i}^{start} + N_{start}^{CORESET}) \bmod L > 0$ and $L$ RB otherwise, and all other resource block bundles consist of $L$ RBs. N_start_coreset VRB index of the lowest-numbered RB in the CORESET used for the DCI transmission as $N_{start}^{CORESET}$. N_bwp_i_start BWP $i$ starting position $N_{BWP,i}^{start}$. N_bwp_init_size The size in RBs of CORESET0 if available, otherwise the initial bandwidth part size as $N_{BWP,init}^{size}$. A VRB-to-PRB mapper instance.
References coreset_start, nof_bundles, srsgnb::divide_ceil, first_bundle_size, last_bundle_size, other_bundle_size.
vrb_to_prb_mapper vrb_to_prb_mapper::create_interleaved_other(unsigned N_bwp_i_start, unsigned N_bwp_i_size, unsigned L_i)
Creates a VRB-to-PRB mapper for all other PDSCH transmissions with interleaved mapping.
Implemented as per TS38.211 Section 7.3.1.6 Case 5: the set of $N_{BWP,i}^{size}$ virtual RBs starting at $N_{BWP,i}^{start}$ is divided into $N_{bundle}=\lceil (N_{BWP,i}^{size} + (N_{BWP,i}^{start} \bmod L_i))/L_i \rceil$, the first RB bundle consists of $L_i - N_{BWP,i}^{size} \bmod L_i$, the last RB bundle consists of $(N_{BWP,i}^{size}+N_{BWP,i}^{start}) \bmod L_i$ if $(N_{BWP,i}^{size}+N_{BWP,i}^{start}) \bmod L_i > 0$ and $L_i$ RBs otherwise, all other resource block bundles consist of $L_i$ RBs. N_bwp_i_start BWP $i$ starting position $N_{BWP,i}^{start}$. N_bwp_i_size BWP $i$ size $N_{BWP,i}^{size}$. L_i RB Bundle size for BWP $i$ in RBs $L_i$. A VRB-to-PRB mapper instance.
References nof_bundles, srsgnb::divide_ceil, first_bundle_size, last_bundle_size, other_bundle_size.
bool srsgnb::vrb_to_prb_mapper::is_interleaved() const
Checks whether the resource allocation is interleaved.
The resource allocation is interleaved if the number of bundles is not zero. True if the resource allocation is interleaved. Otherwise, False.
References nof_bundles.
Referenced by srsgnb::rb_allocation::is_contiguous, srsgnb::rb_allocation::get_prb_mask, get_allocation_indices.
unsigned srsgnb::vrb_to_prb_mapper::get_coreset_start() const
Gets the CORESET start VRB index.
VRB index of the lowest-numbered RB in the CORESET used for the DCI transmission. A VRB index if the PDSCH transmission is scheduled by a DCI in a common SS. Otherwise, 0.
References coreset_start.
Referenced by srsgnb::rb_allocation::get_prb_begin, srsgnb::rb_allocation::get_prb_end, srsgnb::rb_allocation::get_contiguous_prb_mask.
static_vector< uint16_t, MAX_RB > vrb_to_prb_mapper::get_allocation_indices(unsigned bwp_size) const
Calculates a PDSCH allocation PRB indices.
bwp_size Indicates the BWP size. Return the PRB indices relative to the lowest PRB of the BWP.
References is_interleaved, coreset_start, nof_bundles, first_bundle_size, last_bundle_size, other_bundle_size.
Referenced by srsgnb::rb_allocation::get_other_prb_mask, srsgnb::rb_allocation::get_prb_indices.
bool srsgnb::vrb_to_prb_mapper::operator==(const vrb_to_prb_mapper &other) const
Equal comparison between two VRB-to-PRB mappers.
Two mappers are considered equal if their CORESET start, number of bundles and RB bundle sizes are equal.
References coreset_start, nof_bundles, first_bundle_size, last_bundle_size, other_bundle_size.