srsgnb::cyclic_prefix
options
Indicates normal cyclic prefix length.
options srsgnb::cyclic_prefix::value
Indicates the cyclic prefix type.
Referenced by operator options, to_string, is_valid, get_length.
constexpr srsgnb::cyclic_prefix::cyclic_prefix()=default
Default constructor as normal.
constexpr srsgnb::cyclic_prefix::cyclic_prefix(options opt)
Construct from value. It allows implicit conversion from a cyclic prefix option.
constexpr srsgnb::cyclic_prefix::cyclic_prefix(const cyclic_prefix &other)
Construct from another cyclic prefix type.
constexpr srsgnb::cyclic_prefix::operator options() const
Implicit conversion to enumerate.
References value.
std::string srsgnb::cyclic_prefix::to_string() const
Get the string value.
References value, NORMAL.
bool srsgnb::cyclic_prefix::is_valid(subcarrier_spacing scs, unsigned dft_size) const
Checks the validity of the DFT size and subcarrier spacing for the current cyclic prefix.
A cyclic prefix is valid if it results in an integer number of samples. Othwerwise, it is not valid. scs Subcarrier spacing. dft_size DFT size. True if the cyclic prefix is valid for the given SCS and DFT size.
References srsgnb::to_numerology_value, value, EXTENDED, srsgnb::phy_time_unit::from_units_of_kappa, srsgnb::phy_time_unit::is_sample_accurate.
constexpr phy_time_unit srsgnb::cyclic_prefix::get_length(unsigned symbol_idx, subcarrier_spacing scs) const
Calculates the cyclic prefix length in samples as per TS38.211 Section 5.3.1.
symbol_idx Symbol index within the subframe. scs Subcarrier spacing numerology. The cyclic prefix length in PHY time units.
References srsgnb::to_numerology_value, value, EXTENDED, srsgnb::pow2, srsgnb::phy_time_unit::from_units_of_kappa.
Referenced by srsgnb::ofdm_symbol_demodulator_impl::get_cp_offset, srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::ofdm_symbol_demodulator_impl::get_symbol_size, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_symbol_modulator_impl::get_symbol_size, srsgnb::phase_compensation_lut::phase_compensation_lut.