srsgnb::byte_buffer
using srsgnb::byte_buffer::value_type = uint8_t
using srsgnb::byte_buffer::iterator = iterator_impl<uint8_t>
using srsgnb::byte_buffer::const_iterator = iterator_impl<const uint8_t>
std::shared_ptr<byte_buffer_segment> srsgnb::byte_buffer::head
byte_buffer_segment* srsgnb::byte_buffer::tail
size_t srsgnb::byte_buffer::len
srsgnb::byte_buffer::byte_buffer()=default
srsgnb::byte_buffer::byte_buffer(const byte_buffer &) noexcept=default
Explicit copy ctor. User should use copy() method for copy assignments.
srsgnb::byte_buffer::byte_buffer(span< const uint8_t > bytes)
srsgnb::byte_buffer::byte_buffer(std::initializer_list< uint8_t > lst)
srsgnb::byte_buffer::byte_buffer(It other_begin, It other_end)
srsgnb::byte_buffer::byte_buffer(byte_buffer &&other) noexcept
byte_buffer& srsgnb::byte_buffer::operator=(const byte_buffer &) noexcept=delete
copy assignment is disabled. Use std::move, .copy() or .deep_copy() instead.
byte_buffer& srsgnb::byte_buffer::operator=(byte_buffer &&other) noexcept
Move assignment of byte_buffer. It avoids unnecessary reference counting increment.
byte_buffer& srsgnb::byte_buffer::operator=(span< const uint8_t > bytes) noexcept
Assignment of span of bytes.
References clear, append.
byte_buffer srsgnb::byte_buffer::deep_copy() const
Performs a deep copy (byte by bytes) of this byte_buffer.
References append, srsgnb::span< T >::data.
byte_buffer srsgnb::byte_buffer::copy() const
Performs a shallow copy. Head segment reference counter is incremented.
void srsgnb::byte_buffer::append(span< const uint8_t > bytes)
Appends bytes to the byte buffer. This function may retrieve new segments from a memory pool.
References empty, srsgnb::byte_buffer_segment::tailroom, srsgnb::byte_buffer_segment::append.
Referenced by operator=, deep_copy, append, srsgnb::byte_buffer_writer::append, srsgnb::make_byte_buffer.
void srsgnb::byte_buffer::append(const std::initializer_list< uint8_t > &bytes)
Appends an initializer list of bytes.
References append.
Referenced by append.
void srsgnb::byte_buffer::append(const byte_buffer &other)
Appends bytes from another byte_buffer. This function may allocate new segments.
References empty, srsgnb::byte_buffer_segment::tailroom, srsgnb::byte_buffer_segment::append.
void srsgnb::byte_buffer::append(uint8_t byte)
Appends bytes to the byte buffer. This function may allocate new segments.
References empty, srsgnb::byte_buffer_segment::tailroom, srsgnb::byte_buffer_segment::append.
void srsgnb::byte_buffer::append(const byte_buffer_view &view)
Appends a view of bytes into current byte buffer.
References empty, append.
void srsgnb::byte_buffer::append(const byte_buffer_slice &view)
Appends an owning view of bytes into current byte buffer.
References empty, append.
void srsgnb::byte_buffer::prepend(span< const uint8_t > bytes)
Prepends bytes to byte_buffer. This function may allocate new segments.
References empty.
byte_buffer_view srsgnb::byte_buffer::reserve_prepend(size_t nof_bytes)
Prepends space in byte_buffer. This function may allocate new segments. nof_bytes Number of bytes to reserve at header. range of bytes that were reserved.
References empty.
byte_buffer& srsgnb::byte_buffer::chain_after(byte_buffer after)
Chains two byte buffers. The after byte buffer becomes empty.
References empty.
byte_buffer& srsgnb::byte_buffer::chain_before(byte_buffer before)
Chains two byte buffers. The before byte buffer becomes empty.
References empty.
void srsgnb::byte_buffer::clear()
Clear byte buffer.
Referenced by operator=, srsgnb::decoded_mac_rx_pdu::clear.
void srsgnb::byte_buffer::trim_head(size_t nof_bytes)
Removes "nof_bytes" from the head of the byte_buffer.
References length.
int srsgnb::byte_buffer::trim_tail(size_t nof_bytes)
Remove "nof_bytes" bytes at the end of the byte_buffer. If the length is greater than the length of the last segment, the function will fail and return -1 without modifying the byte_buffer.
0 if successful, -1 otherwise.
References srsgnb::byte_buffer_segment::length, srsgnb::byte_buffer_segment::trim_tail.
bool srsgnb::byte_buffer::empty() const
Checks whether byte_buffer is empty.
References length.
Referenced by append, prepend, chain_after, chain_before, resize, srsgnb::byte_buffer_writer::empty, reserve_prepend.
size_t srsgnb::byte_buffer::length() const
Checks byte_buffer length.
Referenced by trim_head, empty, linearize, resize, srsgnb::byte_buffer_writer::length, srsgnb::srs_cu_cp::pdcp_du_processor_adapter::on_new_pdu, srsgnb::sctp_network_gateway::handle_pdu, srsgnb::pdu_rx_handler::push_ul_ccch_msg, srsgnb::rlc_tx_am_entity::pull_pdu, srsgnb::rlc_tx_um_entity::pull_pdu.
uint8_t& srsgnb::byte_buffer::back()
const uint8_t& srsgnb::byte_buffer::back() const
const uint8_t& srsgnb::byte_buffer::operator[](size_t i) const
bool srsgnb::byte_buffer::operator==(const Container &container) const
bool srsgnb::byte_buffer::operator!=(const byte_buffer &other) const
iterator srsgnb::byte_buffer::begin()
const_iterator srsgnb::byte_buffer::cbegin() const
const_iterator srsgnb::byte_buffer::begin() const
iterator srsgnb::byte_buffer::end()
const_iterator srsgnb::byte_buffer::end() const
const_iterator srsgnb::byte_buffer::cend() const
bool srsgnb::byte_buffer::is_contiguous() const
Test if byte buffer is contiguous in memory, i.e. it has only one segment.
Referenced by linearize.
int srsgnb::byte_buffer::linearize()
Moves the bytes stored in different segments of the byte_buffer into first segment. 0 if the data could fit in one segment. -1 otherwise, and the byte_buffer remains unaltered.
References is_contiguous, length.
void srsgnb::byte_buffer::resize(size_t new_sz)
Set byte_buffer length. Note: It doesn't initialize newly created bytes.
References length, empty, srsgnb::byte_buffer_segment::tailroom, srsgnb::byte_buffer_segment::resize.
Referenced by srsgnb::srs_cu_cp::rrc_ue_ngap_adapter::on_ul_nas_transport_message.
void srsgnb::byte_buffer::append_segment()
void srsgnb::byte_buffer::prepend_segment()