srsgnb::processor_notifier_adaptor
prach_adaptor srsgnb::processor_notifier_adaptor::prach
PRACH adaptor.
Referenced by connect_rx_symbol_notifier, connect_error_notifier, get_prach_notifier.
void srsgnb::processor_notifier_adaptor::connect_rx_symbol_notifier(lower_phy_rx_symbol_notifier &notifier)
Connects the adaptor with a lower physical layer reception notifier.
References prach, srsgnb::processor_notifier_adaptor::prach_adaptor::connect_rx_symbol_notifier.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl.
void srsgnb::processor_notifier_adaptor::connect_error_notifier(lower_phy_error_notifier &notifier)
Connects the adaptor to a lower physical layer error notifier.
References prach, srsgnb::processor_notifier_adaptor::prach_adaptor::connect_error_notifier.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl.
prach_processor_notifier& srsgnb::processor_notifier_adaptor::get_prach_notifier()
Gets the PRACH processor notifier adaptor.
References prach.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl.