srsgnb::dmrs_pucch_processor_format2_impl
constexpr unsigned srsgnb::dmrs_pucch_processor_format2_impl::STRIDE
Defines the DMRS index increment in frequency domain.
Referenced by mapping.
constexpr unsigned srsgnb::dmrs_pucch_processor_format2_impl::NOF_DMRS_PER_RB
Defines the number of DMRS per active resource block.
Referenced by sequence_generation, estimate.
constexpr unsigned srsgnb::dmrs_pucch_processor_format2_impl::MAX_NOF_DMRS_PER_SYMBOL
Defines the maximum number of DMRS for PDCCH that can be found in a symbol.
std::unique_ptr<pseudo_random_generator> srsgnb::dmrs_pucch_processor_format2_impl::prg
Pseudo-random sequence generator instance.
Referenced by sequence_generation.
unsigned dmrs_pucch_processor_format2_impl::c_init(unsigned symbol, const config_t &config)
Computes the initial pseudo-random state.
symbol Denotes the symbol index. config Provides the required parameters. The initial pseudo-random state. implemented according to TS 38.211 section 6.4.1.3.2.1.
References srsgnb::dmrs_pucch_processor::config_t::slot, srsgnb::slot_point::slot_index, srsgnb::dmrs_pucch_processor::config_t::n_id_0, srsgnb::get_nsymb_per_slot, srsgnb::dmrs_pucch_processor::config_t::cp, srsgnb::pow2.
Referenced by sequence_generation.
void dmrs_pucch_processor_format2_impl::sequence_generation(span< cf_t > sequence, unsigned symbol, unsigned start_prb, const config_t &config)
Implements TS 38.211 section 6.4.1.3.2.1 Sequence generation.
sequence Provides the sequence destination. symbol Denotes the symbol index. start_prb Denotes the index of first PRB allocated for DM-RS in the current symbol. config Provides the required parameters to calculate the sequences.
References prg, c_init, NOF_DMRS_PER_RB, srsgnb::span< T >::first, srsgnb::dmrs_pucch_processor::config_t::nof_prb.
Referenced by estimate.
void dmrs_pucch_processor_format2_impl::mapping(span< cf_t > ce, const resource_grid_reader &grid, unsigned start_prb, unsigned nof_prb, unsigned symbol) const
Implements TS 38.211 section 6.4.1.3.2.2 Mapping to physical resources.
ce Container for storing extracted slot symbol DMRS pilots. grid Provides the source grid to read the signal. start_prb Provides a PRB index for the given symbol. nof_prb Provides number of PRBs allocated for DM-RS pilots. symbol Denotes the symbol index.
References srsgnb::NRE, STRIDE, srsgnb::resource_grid_reader::get.
Referenced by estimate.
srsgnb::dmrs_pucch_processor_format2_impl::dmrs_pucch_processor_format2_impl(std::unique_ptr< pseudo_random_generator > prg_)
void dmrs_pucch_processor_format2_impl::estimate(channel_estimate &estimate, const resource_grid_reader &grid, const config_t &config) override
Generates and maps DMRS for PUCCH according to TS 38.211 section 6.4.1.3.
estimate Channel estimation results. grid Provides the source resource grid. config Provides the required configuration to estimate channel.
References srsgnb::PUCCH_FORMAT2_MAX_NSYMB, srsgnb::dmrs_pucch_processor::config_t::intra_slot_hopping, srsgnb::dmrs_pucch_processor::config_t::nof_symbols, srsgnb::PUCCH_FORMAT2_MIN_NSYMB, srsgnb::dmrs_pucch_processor::config_t::start_symbol_index, srsgnb::dmrs_pucch_processor::config_t::nof_prb, NOF_DMRS_PER_RB, srsgnb::span< T >::data, srsgnb::dmrs_pucch_processor::config_t::second_hop_prb, srsgnb::dmrs_pucch_processor::config_t::starting_prb, sequence_generation, mapping.