srsgnb::pbch_modulator_impl
std::unique_ptr<modulation_mapper> srsgnb::pbch_modulator_impl::modulator
std::unique_ptr<pseudo_random_generator> srsgnb::pbch_modulator_impl::scrambler
void pbch_modulator_impl::scramble(span< const uint8_t > b, span< uint8_t > b_hat, const config_t &config)
Implements TS 38.211 section 7.3.3.1 Scrambling b Inputs bits to scramble b_hat Output bits after scrambling config PBCH modulator arguments
References srsgnb::pbch_modulator::config_t::phys_cell_id, srsgnb::pbch_modulator::config_t::ssb_idx, srsgnb::pbch_modulator::M_bit.
Referenced by put.
void pbch_modulator_impl::modulate(span< const uint8_t > b_hat, span< cf_t > d_pbch)
Implements TS 38.211 section 7.3.3.2 Modulation b_hat Inputs bits to scramble d_pbch Output symbols
References srsgnb::QPSK.
Referenced by put.
void pbch_modulator_impl::map(span< const cf_t > d_pbch, resource_grid_writer &grid, const config_t &config)
Implements TS 38.211 section 7.3.3.3 Mapping to physical resources d_pbch Provides the symbols to map grid is the destination resource grid config PBCH modulator arguments
References srsgnb::pbch_modulator::config_t::ssb_first_symbol, srsgnb::pbch_modulator::config_t::ssb_first_subcarrier, srsgnb::pbch_modulator::config_t::phys_cell_id, srsgnb::SSB_BW_RE, srsgnb::pbch_modulator::config_t::ports, srsgnb::resource_grid_writer::put.
Referenced by put.
srsgnb::pbch_modulator_impl::pbch_modulator_impl(std::unique_ptr< modulation_mapper > modulator_, std::unique_ptr< pseudo_random_generator > prg_)
void pbch_modulator_impl::put(span< const uint8_t > bits, resource_grid_writer &grid, const config_t &config) override
Modulates a PBCH message according to TS38.211 Section 7.3.3.
bits Input bits. grid Destination resource grid. config Destination resource grid.
References srsgnb::span< T >::size, srsgnb::pbch_modulator::M_bit, scramble, modulate, map.