srsgnb::dft_processor
direction
Converts a time domain signal into frequency domain.
For the FFTW based libraries, it is equivalent to FFTW_FORWARD sign.
static std::string srsgnb::dft_processor::direction_to_string(direction dir)
Converts a DFT direction to string.
References DIRECT.
Referenced by srsgnb::dft_processor_fftw_impl::dft_processor_fftw_impl.
virtual srsgnb::dft_processor::~dft_processor()=default
Default destructor.
virtual direction srsgnb::dft_processor::get_direction() const =0
Gets the DFT direction.
virtual unsigned srsgnb::dft_processor::get_size() const =0
Gets the DFT number of points.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate.
virtual span<cf_t> srsgnb::dft_processor::get_input()=0
Gets a view of the internal input DFT buffer.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate.
virtual span<const cf_t> srsgnb::dft_processor::run()=0
Executes the DFT from the internal input data.
A view of the internal output DFT buffer.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate.