srsgnb::dft_processor_fftw_impl::fftw_wisdom_filename
std::array<char, 256> srsgnb::dft_processor_fftw_impl::fftw_wisdom_filename::data
Persistent memory. It does not get freed.
Referenced by fftw_wisdom_filename, operator=, clear, empty, get.
dft_processor_fftw_impl::fftw_wisdom_filename::fftw_wisdom_filename()
Creates a default FFTW wisdom file name.
References clear, data.
fftw_wisdom_filename& srsgnb::dft_processor_fftw_impl::fftw_wisdom_filename::operator=(const std::string &new_filename)
Overwrites the current file name.
References data, clear.
void srsgnb::dft_processor_fftw_impl::fftw_wisdom_filename::clear()
Erase the current file name.
References data.
Referenced by fftw_wisdom_filename, srsgnb::dft_processor_fftw_impl::~dft_processor_fftw_impl, operator=.
bool srsgnb::dft_processor_fftw_impl::fftw_wisdom_filename::empty() const
Checks if the file name was erased or non existent.
References data.
Referenced by srsgnb::dft_processor_fftw_impl::dft_processor_fftw_impl, srsgnb::dft_processor_fftw_impl::~dft_processor_fftw_impl.
const char* srsgnb::dft_processor_fftw_impl::fftw_wisdom_filename::get() const
Get the file name.
References data.
Referenced by srsgnb::dft_processor_fftw_impl::dft_processor_fftw_impl, srsgnb::dft_processor_fftw_impl::~dft_processor_fftw_impl.