srsgnb::lower_phy_state_fsm
states
Indicates the lower physical layer has not been initialized.
states srsgnb::lower_phy_state_fsm::state
Indicates the current state.
Referenced by is_running_unprotected, on_successful_init, on_async_executor_stop, stop_and_join.
std::mutex srsgnb::lower_phy_state_fsm::mutex
Protects the concurrent access to the instance.
Referenced by on_successful_init, on_async_executor_stop, stop_and_join.
std::condition_variable srsgnb::lower_phy_state_fsm::cvar
Used to wait for certain state transitions.
Referenced by on_async_executor_stop, stop_and_join.
bool srsgnb::lower_phy_state_fsm::is_running_unprotected() const
Same than is_running().
References state, RUNNING.
Referenced by stop_and_join.
void srsgnb::lower_phy_state_fsm::on_successful_init()
Notifies the successful component initialization.
References mutex, state, UNINITIALIZED, RUNNING.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl.
void srsgnb::lower_phy_state_fsm::on_async_executor_stop()
Notifies the asynchronous task executor stopped.
References mutex, state, STOPPED, cvar.
Referenced by srsgnb::lower_phy_impl::realtime_process_loop.
void srsgnb::lower_phy_state_fsm::stop_and_join()
Signals a stop and join.
References mutex, is_running_unprotected, state, WAIT_STOP, UNINITIALIZED, STOPPED, cvar.
Referenced by srsgnb::lower_phy_impl::stop.
bool srsgnb::lower_phy_state_fsm::is_running() const