srsgnb::sampling_rate
using srsgnb::sampling_rate::value_type = uint64_t
Value storage type.
value_type srsgnb::sampling_rate::value
Actual value in hertz.
Referenced by is_valid, get_dft_size, to_Hz, to_kHz, to_MHz.
srsgnb::sampling_rate::sampling_rate()=default
Default constructor.
Referenced by from_Hz.
constexpr bool srsgnb::sampling_rate::is_valid(T scs_Hz) const
Determines if the sampling rate is valid for a certain subcarrier spacing.
T Any type convertible to value_type. scs_Hz Subcarrier spacing in hertz. True if the sampling rate value is not zero and is divisible by the subcarrier spacing, false otherwise.
References value.
Referenced by get_dft_size, sampling_rate.
constexpr bool srsgnb::sampling_rate::is_valid(subcarrier_spacing scs) const
Determines if the sampling rate is valid for a certain subcarrier spacing.
scs Subcarrier spacing enumerator. True if the sampling rate value is not zero and is divisible by the subcarrier spacing, false otherwise.
References is_valid, srsgnb::scs_to_khz.
Referenced by is_valid.
constexpr unsigned srsgnb::sampling_rate::get_dft_size(T scs_Hz) const
Gets the DFT size corresponding to the sampling rate, for a given subcarrier spacing.
An assertion is triggered if the combination of sampling rate and subcarrier spacing is invalid (see is_valid()). T Any type convertible to value_type. scs_Hz The given subcarrier spacing in hertz. The sampling rate represented as the size of a DFT with the given subcarrier spacing.
References is_valid, value.
Referenced by lower_phy_factory_generic::create, srsgnb::lower_phy_impl::lower_phy_impl.
constexpr unsigned srsgnb::sampling_rate::get_dft_size(subcarrier_spacing scs) const
Gets the DFT size corresponding to the sampling rate, for a given subcarrier spacing.
An assertion is triggered if the combination of sampling rate and subcarrier spacing is invalid (see is_valid()). scs Subcarrier spacing enumerator. The sampling rate represented as the size of a DFT with the given subcarrier spacing.
References get_dft_size, srsgnb::scs_to_khz.
Referenced by get_dft_size.
constexpr T srsgnb::sampling_rate::to_Hz() const
Gets the sampling rate in hertz.
T Any type that can be converted from value_type. The value in hertz.
References value.
Referenced by srsgnb::lower_phy_impl::lower_phy_impl, srsgnb::lower_phy_impl::get_rx_to_tx_delay.
constexpr T srsgnb::sampling_rate::to_kHz() const
Gets the sampling rate in kHz.
T Any type that can be converted from value_type. The value in hertz.
References value.
constexpr double srsgnb::sampling_rate::to_MHz() const
Gets the sampling rate in MHz.
References value.
static sampling_rate srsgnb::sampling_rate::from_Hz(T value_Hz)
Creates a sampling_rate object from its value in hertz.
An assertion is triggered if: the sampling rate is zero, or it is not a multiple of 15kHz. T Any type convertible to value_type. value_Hz Sampling rate in hertz.
References sampling_rate.
Referenced by from_kHz, from_MHz.
static sampling_rate srsgnb::sampling_rate::from_kHz(T value_kHz)
Creates a sampling_rate object from its value in kHz.
An assertion is triggered if: the sampling rate is zero, or it is not multiple of 15kHz. T Any type convertible to value_type. value_kHz Sampling rate in kHz.
References from_Hz.
static sampling_rate srsgnb::sampling_rate::from_MHz(T value_MHz)
Creates a sampling_rate object from its value in MHz.
An assertion is triggered if: the sampling rate is zero, or it is not multiple of 15kHz. T Any type convertible to value_type. value_MHz Sampling rate in Mhz.
References from_Hz.
constexpr srsgnb::sampling_rate::sampling_rate(value_type value_)
Private constructor.
References is_valid.