srsgnb::radio_uhd_tx_stream_fsm
states
Indicates the stream was not initialized successfully.
constexpr double srsgnb::radio_uhd_tx_stream_fsm::WAIT_EOB_ACK_TIMEOUT_S
Wait for end-of-burst acknowledgement timeout in seconds.
Referenced by async_event_underflow, transmit_block.
states srsgnb::radio_uhd_tx_stream_fsm::state
Indicates the current state.
Referenced by init_successful, async_event_underflow, async_event_end_of_burst_ack, transmit_block.
std::mutex srsgnb::radio_uhd_tx_stream_fsm::mutex
Protects the class concurrent access.
Referenced by init_successful, async_event_underflow, async_event_end_of_burst_ack.
uhd::time_spec_t srsgnb::radio_uhd_tx_stream_fsm::wait_eob_timeout
void srsgnb::radio_uhd_tx_stream_fsm::init_successful()
Notifies that the transmit stream has been initialized successfully.
References mutex, state, START_BURST.
void srsgnb::radio_uhd_tx_stream_fsm::async_event_underflow(const uhd::time_spec_t &time_spec)
Notifies an underflow event.
Transitions state end of burst if it is in a burst. time_spec Indicates the time the underflow event occurred.
References mutex, state, IN_BURST, END_OF_BURST, WAIT_EOB_ACK_TIMEOUT_S.
Referenced by srsgnb::radio_uhd_tx_stream::recv_async_msg.
void srsgnb::radio_uhd_tx_stream_fsm::async_event_end_of_burst_ack()
Notifies an end-of-burst acknowledgement.
Transitions state to start burst if it is waiting for the end-of-burst.
References mutex, state, WAIT_END_OF_BURST, START_BURST.
Referenced by srsgnb::radio_uhd_tx_stream::recv_async_msg.
bool srsgnb::radio_uhd_tx_stream_fsm::transmit_block(uhd::tx_metadata_t &metadata, uhd::time_spec_t &time_spec)
Notifies a new block transmission.
metadata Provides the destination of the required metadata. time_spec Indicates the transmission time. True if the block shall be transmitted. False if the block shall be ignored.
References state, START_BURST, IN_BURST, END_OF_BURST, WAIT_END_OF_BURST, WAIT_EOB_ACK_TIMEOUT_S, UNINITIALIZED, STOP.
Referenced by srsgnb::radio_uhd_tx_stream::transmit_block.
void srsgnb::radio_uhd_tx_stream_fsm::stop(uhd::tx_metadata_t &metadata)
bool srsgnb::radio_uhd_tx_stream_fsm::is_stopped() const