srsgnb::resource_grid_writer
virtual srsgnb::resource_grid_writer::~resource_grid_writer()=default
Default destructor.
virtual void srsgnb::resource_grid_writer::put(unsigned port, span< const resource_grid_coordinate > coordinates, span< const cf_t > symbols)=0
Puts a number of elements in the grid for a given port according to a list of coordinates.
port Port index. coordinates List of grid symbolsubcarrier coordinates. symbols List of symbols to written at the specified coordinates. The number of elements in coordinates and symbols shall be the same.
Referenced by srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::pbch_modulator_impl::map, srsgnb::pdcch_modulator_impl::map, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::csi_rs_processor_impl::map, srsgnb::dmrs_pbch_processor_impl::mapping, srsgnb::dmrs_pdcch_processor_impl::mapping, srsgnb::dmrs_pdsch_processor_impl::mapping, srsgnb::pss_processor_impl::mapping, srsgnb::sss_processor_impl::mapping.
virtual span<const cf_t> srsgnb::resource_grid_writer::put(unsigned port, unsigned l, unsigned k_init, span< const bool > mask, span< const cf_t > symbols)=0
Puts a number of resource elements in the resource grid at the given port and symbol using a mask to indicate which subcarriers are mapped and which are not.
port Port index. l Symbol index. k_init Initial subcarrier index. mask Boolean mask denoting the subcarriers to be written (if true), starting from k_init. symbols Symbols to be written into the resource grid. A span<cf_t> containing the unused entries of symbols. The number of elements of mask shall be equal to or greater than the resource grid number of subcarriers. The number of elements of symbols shall be equal to or greater than the number of true elements in mask.
virtual void srsgnb::resource_grid_writer::put(unsigned port, unsigned l, unsigned k_init, span< const cf_t > symbols)=0
Puts a consecutive number of resource elements for the given port and symbol l, starting at k_init.
port Port index. l Symbol index. k_init Initial subcarrier index. symbols Symbols to be written into the resource grid. The sum of k_init and the number of elements in symbols shall not exceed the resource grid number of subcarriers.