srsgnb::pdsch_modulator_impl
std::unique_ptr<modulation_mapper> srsgnb::pdsch_modulator_impl::modulator
std::unique_ptr<pseudo_random_generator> srsgnb::pdsch_modulator_impl::scrambler
static_vector<static_vector<cf_t, MAX_CODEWORD_SIZE>, MAX_NOF_CODEWORDS> srsgnb::pdsch_modulator_impl::temp_d
Temporal modulated data.
Referenced by modulate.
static_vector<static_vector<cf_t, MAX_RB * NRE * MAX_NSYMB_PER_SLOT>, MAX_PORTS> srsgnb::pdsch_modulator_impl::temp_x
void pdsch_modulator_impl::scramble(span< uint8_t > b_hat, span< const uint8_t > b, unsigned q, const config_t &config)
Scrambles a codeword. Implements TS 38.211 section 7.3.1.1 Scrambling.
b_hat Output bits after scrambling. b Inputs bits to scramble. q Codeword index {0,1}. config Provides the scrambler configuration.
References srsgnb::pdsch_modulator::config_t::rnti, srsgnb::pdsch_modulator::config_t::n_id.
Referenced by modulate.
void pdsch_modulator_impl::modulate(span< cf_t > d_pdsch, span< const uint8_t > b_hat, modulation_scheme modulation, float scaling)
Modulates a codeword. Implements TS 38.211 section 7.3.1.2 Modulation.
d_pdsch Output symbols. b_hat Inputs bits to perform the modulation mapping. modulation Indicates the modulation scheme (QPSK, 16QAM, ...). scaling Indicates the signal scaling if the value is valid (not 0, NAN nor INF).
Referenced by modulate.
void pdsch_modulator_impl::layer_map(static_vector< span< cf_t >, MAX_PORTS > &x_pdsch, static_vector< span< cf_t >, MAX_NOF_CODEWORDS > d_pdsch)
Maps codewords into layers. Implements TS 38.211 section 7.3.1.3 Layer mapping.
x_pdsch Layer mapping result destination. d_pdsch Layer mapping codeword source. The number of layers and codewords is deduced from the parameters.
Referenced by modulate.
void pdsch_modulator_impl::map_to_contiguous_prb(resource_grid_writer &grid, static_vector< span< cf_t >, MAX_PORTS > x_pdsch, const config_t &config)
Maps contiguous resource elements from the layer index layer into the physical resource grid.
Implements TS 38.211 sections 7.3.1.4 Antenna port mapping, 7.3.1.5 Layer mapping, 7.3.1.5 Mapping to virtual resource blocks and 7.3.1.6 Mapping from virtual to physical resource blocks. grid Provides the destination resource grid. x_pdsch PDSCH resource elements that have been already mapped to layers. The number of layers and codewords is deduced from the parameters.
References srsgnb::MAX_NSYMB_PER_SLOT, srsgnb::pdsch_modulator::config_t::start_symbol_index, srsgnb::pdsch_modulator::config_t::nof_symbols, srsgnb::pdsch_modulator::config_t::freq_allocation, srsgnb::rb_allocation::get_prb_begin, srsgnb::pdsch_modulator::config_t::bwp_start_rb, srsgnb::NRE, srsgnb::rb_allocation::get_prb_end, srsgnb::pdsch_modulator::config_t::dmrs_config_type, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::pdsch_modulator::config_t::bwp_size_rb, srsgnb::pdsch_modulator::config_t::nof_cdm_groups_without_data, srsgnb::pdsch_modulator::config_t::dmrs_symb_pos, srsgnb::span< T >::begin, srsgnb::span< T >::end, srsgnb::re_pattern::get_exclusion_mask, srsgnb::pdsch_modulator::config_t::reserved, srsgnb::re_pattern_list::get_exclusion_mask, srsgnb::pdsch_modulator::config_t::ports, srsgnb::resource_grid_writer::put, srsgnb::span< T >::subspan, srsgnb::span< T >::empty, srsgnb::span< T >::size.
Referenced by modulate.
void pdsch_modulator_impl::map_to_prb_other(resource_grid_writer &grid, static_vector< span< cf_t >, MAX_PORTS > x_pdsch, const config_t &config)
Maps non-contiguous resource elements into the physical resource grid of the given antenna ports.
Implements TS 38.211 sections 7.3.1.4 Antenna port mapping, 7.3.1.5 Layer mapping, 7.3.1.5 Mapping to virtual resource blocks and 7.3.1.6 Mapping from virtual to physical resource blocks x_pdsch Layer mapping result destination. d_pdsch Layer mapping codeword source. The number of layers and codewords is deduced from the parameters.
References srsgnb::pdsch_modulator::config_t::freq_allocation, srsgnb::rb_allocation::get_prb_indices, srsgnb::pdsch_modulator::config_t::bwp_start_rb, srsgnb::pdsch_modulator::config_t::bwp_size_rb, srsgnb::MAX_NSYMB_PER_SLOT, srsgnb::pdsch_modulator::config_t::start_symbol_index, srsgnb::pdsch_modulator::config_t::nof_symbols, srsgnb::pdsch_modulator::config_t::dmrs_config_type, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::pdsch_modulator::config_t::nof_cdm_groups_without_data, srsgnb::pdsch_modulator::config_t::dmrs_symb_pos, srsgnb::span< T >::begin, srsgnb::span< T >::end, srsgnb::NRE, srsgnb::re_pattern::get_exclusion_mask, srsgnb::pdsch_modulator::config_t::reserved, srsgnb::re_pattern_list::get_exclusion_mask, srsgnb::pdsch_modulator::config_t::ports, srsgnb::span< T >::subspan, srsgnb::resource_grid_writer::put.
Referenced by modulate.
srsgnb::pdsch_modulator_impl::pdsch_modulator_impl(std::unique_ptr< modulation_mapper > modulator_, std::unique_ptr< pseudo_random_generator > scrambler_)
Generic PDSCH modulator instance constructor.
void pdsch_modulator_impl::modulate(resource_grid_writer &grid, span< const span< const uint8_t >> codewords, const config_t &config) override
Modulates a PDSCH codeword according to TS38.211 section 7.3.1 Physical downlink shared channel.
grid Provides the destination resource grid. codewords Provides the encoded codewords to modulate. config Provides the configuration reference. The number of codewords shall be consistent with the number of layers. The codeword length shall be consistent with the resource mapping, considering the reserved resource elements.
References srsgnb::pdsch_modulator::config_t::ports, temp_d, srsgnb::pdsch_modulator::MAX_NOF_CODEWORDS, srsgnb::pdsch_modulator::config_t::modulation1, srsgnb::pdsch_modulator::config_t::modulation2, srsgnb::get_bits_per_symbol, scramble, modulate, srsgnb::pdsch_modulator::config_t::scaling, srsgnb::MAX_PORTS, layer_map, srsgnb::pdsch_modulator::config_t::freq_allocation, srsgnb::rb_allocation::is_contiguous, map_to_contiguous_prb, map_to_prb_other.