srsgnb::byte_buffer_slice
using srsgnb::byte_buffer_slice::value_type = byte_buffer_view::value_type
using srsgnb::byte_buffer_slice::iterator = byte_buffer_view::iterator
using srsgnb::byte_buffer_slice::const_iterator = byte_buffer_view::const_iterator
byte_buffer_view srsgnb::byte_buffer_slice::sliced_view
byte_buffer srsgnb::byte_buffer_slice::buf
srsgnb::byte_buffer_slice::byte_buffer_slice()=default
srsgnb::byte_buffer_slice::byte_buffer_slice(byte_buffer &&buf_)
srsgnb::byte_buffer_slice::byte_buffer_slice(const byte_buffer &buf_)
srsgnb::byte_buffer_slice::byte_buffer_slice(const byte_buffer &buf_, size_t offset, size_t length)
srsgnb::byte_buffer_slice::byte_buffer_slice(const byte_buffer &buf_, byte_buffer_view view)
void srsgnb::byte_buffer_slice::clear()
byte_buffer_view srsgnb::byte_buffer_slice::view() const
Converts to non-owning byte buffer view.
Referenced by srsgnb::rlc_rx_um_entity::handle_pdu, srsgnb::srs_cu_cp::rrc_ue_entity::handle_ul_ccch_pdu, srsgnb::srs_cu_cp::rrc_ue_entity::handle_ul_dcch_pdu.
srsgnb::byte_buffer_slice::operator byte_buffer_view() const
byte_buffer_slice srsgnb::byte_buffer_slice::make_slice(size_t offset, size_t size)
Returns another owning sub-view with dimensions specified in arguments.
References srsgnb::byte_buffer_view::view.
Referenced by srsgnb::rlc_rx_um_entity::handle_pdu, srsgnb::rlc_tx_um_entity::pull_pdu.
byte_buffer_slice& srsgnb::byte_buffer_slice::advance(size_t offset)
Advances slice by provided offset. The length of the slice gets automatically reduced by the provided offset.
bool srsgnb::byte_buffer_slice::empty() const
size_t srsgnb::byte_buffer_slice::length() const
const uint8_t& srsgnb::byte_buffer_slice::operator[](size_t idx) const
iterator srsgnb::byte_buffer_slice::begin()
const_iterator srsgnb::byte_buffer_slice::begin() const
iterator srsgnb::byte_buffer_slice::end()
const_iterator srsgnb::byte_buffer_slice::end() const
bool srsgnb::byte_buffer_slice::operator==(const Range &r) const
bool srsgnb::byte_buffer_slice::operator!=(const Range &r) const