srsgnb::srsvec
void srsgnb::srsvec::add(span< const cf_t > x, span< const cf_t > y, span< cf_t > z)
void srsgnb::srsvec::add(span< const float > x, span< const float > y, span< float > z)
void srsgnb::srsvec::add(span< const int16_t > x, span< const int16_t > y, span< int16_t > z)
void srsgnb::srsvec::add(span< const int8_t > x, span< const int8_t > y, span< int8_t > z)
void srsgnb::srsvec::binary_xor(const T &x, const U &y, V &&z)
void srsgnb::srsvec::binary_and(const T &x, const U &y, V &&z)
void srsgnb::srsvec::binary_or(const T &x, const U &y, V &&z)
span< uint8_t > srsgnb::srsvec::bit_unpack(span< uint8_t > bits, unsigned value, unsigned nof_bits)
Unpacks an unsigned integer value into bits.
The first bit in the sequence corresponds to the bit of index nof_bits - 1 of value. The LSB of value is mapped to the last element in the sequence. bits Unpacked bits sequence. value Provides the value to unpack. nof_bits Indicates the number of bits to unpack. A view of the remaining (behind nof_bits) unpacked bits of value.
void srsgnb::srsvec::bit_unpack(span< uint8_t > unpacked, span< const uint8_t > packed)
Unpacks bytes into bits.
unpacked View of the unpacked bits. packed View of the packed bits. The number of unpacked elements must be equal to eight times the number of packed elements.
unsigned srsgnb::srsvec::bit_pack(span< const uint8_t > &bits, unsigned nof_bits)
Packs a number of bits into an integer value.
bits View of unpacked bits. nof_bits Indicates the number of bits. An integer containing the packed bits. The number of elements in bits must be greater than or equal to nof_bits. nof_bits must not exceed 32 bits. After execution, bits will contain only the unused bits.
void srsgnb::srsvec::bit_pack(span< uint8_t > packed, span< const uint8_t > unpacked)
Packs a number of bits into bytes.
packed View of packed bits. unpacked View of unpacked bits. The number of unpacked elements must be equal to eight times the number packed elements.
bool srsgnb::srsvec::equal(const T1 &s1, const T2 &s2)
const T* srsgnb::srsvec::find(span< const T > input, T value)
Finds the first value in \input that is equal to value.
The implementation is equivalent to: constT*find(span<constT>input,Tvalue){ returnstd::find(input.begin(),input.end(),value); } T Any data type that is one byte wide. input Input values. value Value to find. The pointer to the first element that is equal to value if any, input.end() otherwise.
std::pair< unsigned, float > srsgnb::srsvec::max_abs_element(span< const cf_t > x)
Finds the maximum absolute value in a complex span.
In case two elements have the same absolute value, the one with lowest index is selected. The implementation is equivalent to: std::pair<unsigned,float>max_abs_element(span<constcf_t>x){ constcf_t*it=std::max_element(x.begin(),x.end(),[](cf_ta,cf_tb){return(abs_sq(a)<abs_sq(b));}); return{static_cast<unsigned>(it-x.begin()),abs_sq(*it)}; } x Input samples. A pair comprising the index and the squared modulo of the maximum element.
void srsgnb::srsvec::convert(span< const cf_t > x, float scale, span< int16_t > z)
Converts from complex float to int16 applying the given scaling x is the input data scale input data scaling prior conversion z resultant data
void srsgnb::srsvec::convert_swap(span< const cf_t > x, float scale, span< int16_t > z)
Converts and swaps real and imaginary from complex float to int16 applying the given scaling x is the input data scale input data scaling prior conversion z resultant data
void srsgnb::srsvec::convert(span< const int16_t > x, float scale, span< cf_t > z)
Converts from int16 to complex float applying the given scaling x is the input data scale input data scaling after conversion z resultant data
void srsgnb::srsvec::convert_swap(span< const int16_t > x, float scale, span< cf_t > z)
Converts and swaps real and imaginary from int16 to complex float applying the given scaling x is the input data scale input data scaling after conversion z resultant data
void srsgnb::srsvec::convert(span< const float > x, float scale, span< int16_t > z)
Converts from float to int16 applying the given scaling x is the input data scale input data scaling prior conversion z resultant data
void srsgnb::srsvec::convert(span< const int16_t > x, float scale, span< float > z)
Converts from int16 to float applying the given scaling x is the input data scale input data scaling after conversion z resultant data
void srsgnb::srsvec::copy(T &&dst, const U &src)
V srsgnb::srsvec::dot_prod(const T &x, const U &y, V init)
Dot product of two spans.
Computes the dot product (a.k.a. inner product or scalar product) of the two sequences represented by the input spans, adding an initial offset. T A span of an arithmetic type. U A span of an arithmetic type. V Output type (must be compatible with the product of object of type T and U). x First span. y Second span. init Initialization value. The dot product between the two spans plus init, i.e. $ x \cdot y + \mathrm{init} = \sum_i x_i y_i + \mathrm{init}$. The two input spans must have the same length.
References dot_prod.
Referenced by dot_prod.
cf_t srsgnb::srsvec::dot_prod(span< const cf_t > x, span< const cf_t > y)
Dot product of two complex spans.
Computes the dot product (a.k.a. inner product or scalar product) of the two complex sequences. The sequences are represented by the input spans x and y, the second sequence y is conjugated. The implementation is equivalent to: cf_tdot_prod(span<constcf_t>x,span<constcf_t>y){ returnstd::inner_product(x.begin(),x.end(),y.begin(),cf_t(0.0F),std::plus<>(),[](cf_ta,cf_tb){returna *std::conj(b);}); } x First span. y Second span. The dot product between the two spans, i.e. $ x \cdot \conj{y}= \sum_i x_i \conj{y}_i $. The two input spans must have the same length.
References dot_prod, srsgnb::span< T >::size.
Referenced by dot_prod.
float srsgnb::srsvec::average_power(span< const cf_t > x)
Estimates the average power of a complex span - linear scale.
The average power of a span is defined as its squared Euclidean norm divided by the number of its elements, i.e. dot_prod(x, x) / x.size().
References average_power, srsgnb::span< T >::empty, srsgnb::span< T >::size.
Referenced by average_power.
void srsgnb::srsvec::prod(span< const cf_t > x, span< const cf_t > y, span< cf_t > z)
void srsgnb::srsvec::prod(span< const cf_t > x, span< const float > y, span< cf_t > z)
void srsgnb::srsvec::prod(span< const float > x, span< const cf_t > y, span< cf_t > z)
void srsgnb::srsvec::prod(span< const float > x, span< const float > y, span< float > z)
void srsgnb::srsvec::prod_conj(span< const cf_t > x, span< const cf_t > y, span< cf_t > z)
void srsgnb::srsvec::sc_prod(span< const cf_t > x, cf_t h, span< cf_t > z)
void srsgnb::srsvec::sc_prod(span< const cf_t > x, float h, span< cf_t > z)
void srsgnb::srsvec::sc_prod(span< const float > x, float h, span< float > z)
void srsgnb::srsvec::zero(T &&x)