srsgnb
constexpr log_likelihood_ratio srsgnb::LLR_MAX
Maximum finite log-likelihood ratio value.
Referenced by srsgnb::ldpc_decoder_generic::update_check_to_variable_messages.
constexpr log_likelihood_ratio srsgnb::LLR_MIN
Minimum finite log-likelihood ratio value.
constexpr log_likelihood_ratio srsgnb::LLR_INFINITY
"Positive infinity" log-likelihood ratio.
Referenced by srsgnb::ldpc_rate_dematcher_impl::allot_llrs.
bsr_format
lower_phy_ta_offset
For FR1 FDD band with LTE-NR coexistence case.
crc_generator_poly
polar_code_ibil
polar_interleaver_direction
csi_rs_cdm_type
No CDM, i.e. CDM group of size 1.
csi_rs_freq_density
One RE occupied in even-numbered PRB.
nr_band
bs_channel_bandwidth_fr1
min_channel_bandwidth
du_ue_index_t
du_cell_index_t
ue_cell_index_t
duplex_mode
Paired FDD.
frequency_range
Frequency range 1, from 410 to 7125 MHz.
lcid_t
srb_id_t
drb_id_t
ldpc_base_graph_type
modulation_scheme
90-degree shifting Binary Phase Shift Keying (/2-BPSK) described in TS38.211 Section 5.1.1.
aggregation_level
coreset_id
ssb_coreset0_mplex_pattern
pdsch_mcs_table
Identifies MCS index table 1, TS38.214 Table 5.1.3.1-1.
restricted_set_config
pucch_group_hopping
Implies neither group or sequence hopping is enabled.
pucch_format
pusch_mcs_table
Identifies MCS index table 1, TS38.214 Table 5.1.3.1-1.
rnti_t
sib1_rtx_periodicity
ssb_periodicity
ssb_pss_to_sss_epre
ssb_pattern_case
Case A - 15 kHz SCS, FR1: index pattern $\{2, 8\} + 14\cdot n$.
subcarrier_spacing
rlc_mode
rlc_um_sn_size
rlc_am_sn_size
rlc_dc_field
rlc_si_field
rlc_control_pdu_type
search_space_id
bwp_id_t
pdsch_mapping_type
dmrs_typeA_position
dmrs_config_type
dmrs_additional_positions
dmrs_max_length
nominal_rbg_size
dci_dl_format
dci_ul_format
dci_dl_rnti_config_type
os_thread_realtime_priority
harq_id_t
using srsgnb::cf_t = typedef std::complex<float>
Type to store complex samples.
using srsgnb::error_type = typedef expected<default_success_t, E>
using srsgnb::const_span = typedef span<const T>
using srsgnb::unique_task = typedef unique_function<void(), default_unique_task_buffer_size>
Generic moveable task.
using srsgnb::baseband_gateway_timestamp = typedef uint64_t
Describes a baseband gateway timestamp. It is expressed in multiples of the sample time.
using srsgnb::radio_sample_type = typedef std::complex<float>
Defines the radio sample type.
using srsgnb::lcg_id_t = typedef uint32_t
Logical Channel Group.
using srsgnb::cqi_report = typedef uint8_t
CQI Value reported.
using srsgnb::rssi_report = typedef uint16_t
RSSI value reported.
using srsgnb::harq_pid_value = typedef uint8_t
HARQ process ID value.
using srsgnb::mac_rx_pdu_list = typedef static_vector<mac_rx_pdu, MAX_UL_PDUS_PER_SLOT>
using srsgnb::crc_calculator_checksum_t = typedef unsigned
Checksum type.
using srsgnb::dmrs_symbol_list = typedef static_vector<cf_t, MAX_NOF_LAYER_DMRS_SYMBOLS>
Container for DM-RS symbols.
using srsgnb::segment_data = typedef static_vector<uint8_t, MAX_SEG_LENGTH>
Alias for the segment data container.
using srsgnb::described_segment = typedef std::pair<segment_data, codeblock_metadata>
Alias for the full segment characterization.
described_segment.first() Contains the segment data, including CRC, in unpacked format (each bit is represented by a uint8_t entry). described_segment.second() Contains the segment metadata, useful for processing the corresponding segment (e.g., encoding, rate-matching).
using srsgnb::described_rx_codeblock = typedef std::pair<span<const log_likelihood_ratio>, codeblock_metadata>
Alias for the full codeblock characterization at the receiver.
described_rx_codeblock.first() Contains a view to the LLRs corresponding to one codeblock. described_rx_codeblock.second() Contains the codeblock metadata, useful for processing the corresponding codeblock (e.g., decoding, rate-dematching).
using srsgnb::du_ue_list = typedef slot_array<T, MAX_NOF_DU_UES>
Representation of a list of UEs indexed by DU UE Index.
using srsgnb::pci_t = typedef uint16_t
3GPP TS 38.331, PhysCellId ::= INTEGER (0..1007)
using srsgnb::prb_index_list = typedef static_vector<uint16_t, pdcch_constants::MAX_NOF_RB_PDCCH>
Describes a PRB index list of unsigned 16 bit indicating the PRB index.
using srsgnb::freq_resource_bitmap = typedef bounded_bitset<pdcch_constants::MAX_NOF_FREQ_RESOURCES>
Describes a frequency resource bitmap for CORESET allocation. Each resource represents a group of 6 PRBs. See TS 38.331, "ControlResourceSet"
using srsgnb::dci_payload = typedef bounded_bitset<pdcch_constants::MAX_DCI_PAYLOAD_SIZE>
DCI payload data type.
using srsgnb::pdcch_candidate_list = typedef static_vector<uint8_t, PDCCH_MAX_NOF_CANDIDATES_SS>
PDCCH candidate data type.
using srsgnb::sch_mcs_index = typedef bounded_integer<uint8_t, 0, 31>
Physical Downlink and Uplink Shared Channel Modulation and Code Scheme Index, parameter $fI_{MCS}$f in TS38.214 Section 5.1.3.1.
using srsgnb::slot_difference = typedef int
Represents the difference between two slot points.
using srsgnb::slot_interval = typedef interval<slot_point>
Slot Interval [start, stop).
using srsgnb::dmrs_symbol_mask = typedef bounded_bitset<14>
Data type used to represent a DMRS symbol mask for PDSCH and PUSCH transmissions.
Each bit set in the bitset represents a symbol within the slot. The first bit corresponds to the first symbol.
using srsgnb::prb_bitmap = typedef bounded_bitset<MAX_NOF_PRBS, true>
Bitset of PRBs with size up to 275.
using srsgnb::rbg_bitmap = typedef bounded_bitset<MAX_NOF_RBGS, true>
Bitset of RBGs with size up to 18.
using srsgnb::ul_bsr_lcg_report_list = typedef static_vector<ul_bsr_lcg_report, MAX_LOGICAL_CHANNEL_GROUP>
using srsgnb::async_procedure = typedef base_resumable_procedure<async_task<R> >
Base class of non-coroutine resumable tasks.
using srsgnb::coro_context = typedef detail::base_coro_frame<typename FutureType::promise_type>
Helper to pass coroutine frame context to operator() of coroutines.
using srsgnb::timer_tick_difference_t = typedef uint32_t
Type to represent a time difference measured in ticks.
using srsgnb::timer_id_t = typedef uint32_t
Type to represent a unique timer identifier.
using srsgnb::lcg_bsr_report_list = typedef static_vector<lcg_bsr_report, MAX_LOGICAL_CHANNEL_GROUP>
List of reported UL BSRs.
using srsgnb::crb_bitmap = typedef bounded_bitset<MAX_NOF_PRBS, true>
Bitset of CRBs with size up to 275.
using srsgnb::ssb_information_list = typedef srsgnb::static_vector<ssb_information, MAX_SSB_PER_SLOT>
using srsgnb::ue_list = typedef stable_id_map<du_ue_index_t, ue, MAX_NOF_DU_UES>
Container that stores all scheduler UEs.
constexpr size_t srsgnb::default_unique_function_buffer_size
Size of the small buffer embedded in "unique_function<R(Args...)>", used to store functors without calling "new".
constexpr size_t srsgnb::default_unique_task_buffer_size
const lcg_id_t srsgnb::MAX_LOGICAL_CHANNEL_GROUP
TS 38.321, 6.1.3.1 - Buffer Status Report MAC CEs.
Referenced by srsgnb::pdu_rx_handler::handle_mac_ce.
constexpr size_t srsgnb::MAX_DL_PDUS_PER_SLOT
constexpr size_t srsgnb::MAX_UL_PDUS_PER_SLOT
Maximum number of PDUs per slot. This value is implementation-defined. It should match FAPI MaxULPDUsPerSlot.
constexpr unsigned srsgnb::MAX_RB
Defines the maximum number of Resource Blocks (RB) that a resource grid can carry.
Referenced by srsgnb::channel_estimate::channel_estimate, srsgnb::re_measurement< cf_t >::re_measurement, srsgnb::re_measurement< cf_t >::resize, srsgnb::rb_allocation::get_prb_mask, srsgnb::rb_allocation::get_prb_indices.
constexpr unsigned srsgnb::NRE
Defines the number of Resource Elements (RE) per Resource Block (RB) in frequency domain.
Referenced by srsgnb::channel_estimate::channel_estimate, srsgnb::dmrs_type::get_dmrs_pattern, srsgnb::re_measurement< cf_t >::resize, srsgnb::low_papr_sequence_collection::low_papr_sequence_collection, ssb_get_k_first, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::pdsch_processor_impl::compute_nof_data_re, srsgnb::re_pattern::get_inclusion_mask, srsgnb::re_pattern::get_exclusion_mask, srsgnb::re_pattern_list::merge, srsgnb::re_pattern_list::get_inclusion_count, get_rg_subc_mask_reference, get_rg_subc_mask, srsgnb::csi_rs_processor_impl::map, srsgnb::dmrs_pucch_processor_format1_impl::mapping, srsgnb::dmrs_pucch_processor_format1_impl::estimate, srsgnb::dmrs_pucch_processor_format2_impl::mapping, srsgnb::pucch_helper::get_alpha_index.
constexpr unsigned srsgnb::SSB_BW_RB
Defines the SSB bandwidth in Resource Blocks (RBs)
constexpr unsigned srsgnb::SSB_DURATION_NSYMB
SS/PBCH Block duration in OFDM symbols.
constexpr unsigned srsgnb::SSB_BW_RE
Defines the SSB bandwidth in Resource Elements.
Referenced by srsgnb::pbch_modulator_impl::map, srsgnb::dmrs_pbch_processor_impl::mapping.
constexpr unsigned srsgnb::MAX_PORTS
Defines the maximum number of ports for any channel transmission.
Referenced by srsgnb::pdsch_modulator_impl::modulate, srsgnb::dmrs_pdsch_processor_impl::mapping.
constexpr uint8_t srsgnb::PLACEHOLDER_ONE
UCI placeholder bit.
A placeholder for setting a bit to 1 in the scrambler. It is denoted as "\c x" in TS38.212 Section 5.3.3 and in TS38.211 Section 6.3.1.1.
constexpr uint8_t srsgnb::PLACEHOLDER_REPEAT
UCI placeholder bit.
A placeholder for repeating the previous bit in the scrambler. It is denoted as "\c y" in TS38.212 Section 5.3.3 and in TS38.211 Section 6.3.1.1.
constexpr unsigned srsgnb::MAX_NOF_LAYER_DMRS_SYMBOLS
Maximum number of DM-RS symbols for one layer.
At most half of the total number of subcarriers (i.e., MAX_RB * NRE / 2) is assigned a DM-RS symbol. Moreover, the number of OFDM symbols carrying DM-RS in a slot is at most $4 \times 2$, being 4 the maximum number of positions $\bar{l}$ and 2 the maximum number of indices $l'$, as per TS38.211 Section 6.4.1.1.
constexpr unsigned srsgnb::MAX_SEG_LENGTH
Maximum segment length.
This is given by the maximum lifting size (i.e., 384) times the maximum number of information bits in base graph BG1 (i.e., 22), as per TS38.212 Section 5.2.2.
constexpr unsigned srsgnb::MAX_NOF_SEGMENTS
Maximum number of segments per transport block.
constexpr unsigned srsgnb::DMRS_MAX_NPORTS
Defines the maximum number of ports DMRS can be mapped to.
constexpr unsigned srsgnb::RADIO_MAX_NOF_CHANNELS
Maximum number of channels per stream in a radio baseband unit.
constexpr unsigned srsgnb::RADIO_MAX_NOF_STREAMS
Maximum number of streams that a radio baseband unit can support.
constexpr unsigned srsgnb::RADIO_MAX_NOF_PORTS
Total maximum number of ports that a radio baseband unit can support.
const unsigned srsgnb::KHZ_TO_HZ
const double srsgnb::HZ_TO_KHZ
constexpr unsigned srsgnb::MAX_NSYMB_PER_SLOT
Returns the maximum number of OFDM symbols per slot.
Referenced by srsgnb::channel_estimate::channel_estimate, srsgnb::re_measurement< cf_t >::re_measurement, srsgnb::re_measurement< cf_t >::resize, srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other, srsgnb::re_pattern_list::merge, srsgnb::re_pattern_list::operator==, srsgnb::dmrs_pdsch_processor_impl::map, srsgnb::pucch_helper::get_alpha_index.
const unsigned srsgnb::NOF_OFDM_SYM_PER_SLOT_NORMAL_CP
The number of OFDM symbols per slot is constant for all numerologies.
Referenced by sliv_to_ofdm_symbols, srsgnb::carrier_subslot_resource_grid::fill, srsgnb::carrier_subslot_resource_grid::collides, srsgnb::carrier_subslot_resource_grid::used_crbs, srsgnb::carrier_subslot_resource_grid::all_set.
const unsigned srsgnb::NOF_OFDM_SYM_PER_SLOT_EXTENDED_CP
constexpr lcid_t srsgnb::MAX_LCID
Maximum value of Logical Channel ID. See TS 38.331, maxLC-ID.
constexpr std::size_t srsgnb::MAX_NOF_SRBS
constexpr unsigned srsgnb::MODULATION_MAX_BITS_PER_SYMBOL
Maximum number of bits per symbol.
Referenced by get_bits_per_symbol.
constexpr pci_t srsgnb::MAX_PCI
const size_t srsgnb::MAX_NOF_CORESETS_PER_BWP
Max number of CORESETs per BWP per cell (including UE-specific and common CORESETs). See TS 38.331, "PDCCH-Config".
constexpr unsigned srsgnb::PDCCH_MAX_NOF_CANDIDATES_SS
Maximum number of candidates per aggregation level in a SS as per TS38.331 SearchSpace.
Referenced by pdcch_candidates_common_ss_get_lowest_cce.
constexpr pdcch_type0_css_coreset_description srsgnb::PDCCH_TYPE0_CSS_CORESET_RESERVED
Reserved CORESET for Type0-PDCCH CSS.
const prach_configuration srsgnb::PRACH_CONFIG_RESERVED
Reserved PRACH configuration. Indicates the configuration parameters are invalid.
Referenced by prach_configuration_get.
constexpr uint16_t srsgnb::PRACH_CYCLIC_SHIFTS_RESERVED
Reserved number of cyclic shifts. It indicates the number of cyclic shifts is invalid.
Referenced by prach_cyclic_shifts_get.
constexpr prach_frequency_mapping_information srsgnb::PRACH_FREQUENCY_MAPPING_INFORMATION_RESERVED
Reserved PRACH frequency-domain mapping information.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate, prach_frequency_mapping_get.
constexpr unsigned srsgnb::PUCCH_FORMAT1_N_MAX
Maximum number of symbols (without DMRS) that NR-PUCCH format 1 can transmit.
Referenced by srsgnb::dmrs_pucch_processor_format1_impl::estimate.
constexpr unsigned srsgnb::PUCCH_FORMAT2_MIN_NSYMB
Minimum number of symbols that NR-PUCCH format 2 can transmit.
Referenced by srsgnb::dmrs_pucch_processor_format2_impl::estimate.
constexpr unsigned srsgnb::PUCCH_FORMAT2_MAX_NSYMB
Maximum number of symbols that NR-PUCCH format 2 can transmit.
Referenced by srsgnb::dmrs_pucch_processor_format2_impl::estimate.
constexpr unsigned srsgnb::PUCCH_FORMAT2_MAX_NPRB
Maximum number of PRBs allocated for NR-PUCCH format 2.
constexpr std::size_t srsgnb::MAX_NOF_PRBS
Maximum number of PRBs of a UE carrier, for any SCS. See TS 38.331 - "maxNrofPhysicalResourceBlocks".
constexpr std::size_t srsgnb::NOF_SUBCARRIERS_PER_RB
See TS 38.211, 4.4.4.1 - Resource Blocks, General.
Referenced by get_rb_bw_khz, get_nof_prbs, tbs_calculator_pdsch_calculate.
constexpr uint32_t srsgnb::NOF_SUBFRAMES_PER_FRAME
Number of subframers per frame. This constant doesn't depend on the numerology used.
Referenced by srsgnb::slot_point::slot_point, srsgnb::slot_point::nof_slots_per_frame, srsgnb::slot_point::is_odd_hrf, srsgnb::pucch_helper::get_alpha_index.
constexpr uint32_t srsgnb::SUBFRAME_DURATION_MSEC
Duration of a subframe in milliseconds.
constexpr size_t srsgnb::NOF_BEAMS
Maximum number of SS/PBCH beams in a SS/PBCH period as per TS38.213 Section 4.1.
const unsigned srsgnb::NOF_SSB_PRBS
const size_t srsgnb::NOF_NUMEROLOGIES
Number of possible numerology values.
Referenced by srsgnb::processor_pool_repository< T >::get_processor, srsgnb::processor_pool_repository< T >::insert.
constexpr size_t srsgnb::MAX_NOF_SEARCH_SPACE_PER_BWP
See TS 38.331, "SearchSpaceId" - The number of Search Spaces per BWP is limited to 10 including the common and UE specific Search Spaces.
const size_t srsgnb::MAX_NOF_RBGS
Maximum number of resource block groups per BWP. See TS 38.214, Sections 5.1.2.2.1 and 6.1.2.2.1.
const size_t srsgnb::MAX_NOF_LAYERS
Maximum number of layers (implementation-defined)
const unsigned srsgnb::FR1_MAX_FREQUENCY_ARFCN
SSB constants. FR1 = 410 MHz 7125 MHz and ARFCN corresponding to 7.125GHz is 875000.
Referenced by schedule_ssb.
const unsigned srsgnb::CUTOFF_FREQ_ARFCN_CASE_A_B_C
The cutoff frequency for case A, B and C paired is 3GHz, corresponding to 600000 ARFCN (TS 38.213, Section 4.1).
Referenced by schedule_ssb.
const unsigned srsgnb::CUTOFF_FREQ_ARFCN_CASE_C_UNPAIRED
The cutoff frequency for case C unpaired is 1.88GHz, corresponding to 376000 ARFCN (TS 38.213, Section 4.1).
Referenced by schedule_ssb.
const unsigned srsgnb::NOF_SSB_OFDM_SYMBOLS
const unsigned srsgnb::SIB1_PERIODICITY
SIB1 constants. SIB1 periodicity, see TS 38.331, Section 5.2.1.
const unsigned srsgnb::MAX_NUM_BEAMS
[Implementation defined] Max numbers of beams, to be used for SIB1 scheduler. NOTE: This is temporary, and valid only for FR1.
Referenced by srsgnb::sib1_scheduler::schedule_sib1, srsgnb::sib1_scheduler::precompute_sib1_n0.
const size_t srsgnb::MAX_GRANTS
Maximum grants per slot. Implementation-specific.
const size_t srsgnb::MAX_LC_GRANTS
Maximum Logical channels per TB. Implementation-specific.
const size_t srsgnb::MAX_SSB_PER_SLOT
Maximum SSB opportunity per slot. This can be derived from the candidate ODFM symbols indices within the ranges 0-13, 14-27, 28-41, 42-55, etc.. from TS 38.213, Section 4.1.
constexpr size_t srsgnb::MAX_SIB1_PDUS_PER_SLOT
[Implementation defined] This corresponds to "Number of search space sets per slot" in Table 13-11, TS 38.213.
Referenced by srsgnb::fapi_adaptor::mac_to_fapi_translator::on_new_downlink_data.
constexpr size_t srsgnb::MAX_RAR_PDUS_PER_SLOT
[Implementation defined] This corresponds to maximum number of RARs that can be scheduled per slot.
const static size_t srsgnb::MAX_NOF_PRACHS_PER_SLOT
Maximum number of PRACH occasions within a slot as per TS38.211, Tables 6.3.3.2-[2-4] and maximum msg1-FDM of 8 according to TS 38.331.
const static size_t srsgnb::MAX_NOF_CODEWORDS_PER_PDSCH
Maximum number of codewords per PDSCH grant. Implementation-specific.
constexpr float srsgnb::TWOPI
Defines two times Pi.
const unsigned srsgnb::NOF_SSB_SUBCARRIERS
Number of subcarriers within a SSB block, as per TS 38.211, Section 7.4.3.1.
const unsigned srsgnb::MIN_ARFCN_3_GHZ_24_5_GHZ
Min ARFCN value for range of frequencies 3GHz-24.25GHz, as per Table 5.4.2.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_ss_ref_hz, srsgnb::srs_du::ssb_freq_position_generator::get_next_ssb_location.
const unsigned srsgnb::MIN_ARFCN_24_5_GHZ_100_GHZ
Min ARFCN value for range of frequencies above 24.25GHz, as per Table 5.4.2.1-1, TS 38.104.
const double srsgnb::N_REF_OFFSET_3_GHZ_24_5_GHZ
Offet $F_{REF-Offs}$ expressed in Hz, for 3GHz-24.25GHz freq. range, as per Table 5.4.2.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_ss_ref_hz.
const double srsgnb::N_SIZE_SYNC_RASTER_1_HZ
Freq. step in Hz, corresponding to $N$ for 0GHz-3GHz freq. range, as per Table 5.4.3.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_ss_ref_hz.
const double srsgnb::M_SIZE_SYNC_RASTER_1_HZ
Freq. step in Hz, corresponding to $M$ for 0GHz-3GHz freq. range, as per Table 5.4.3.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_ss_ref_hz.
const double srsgnb::N_SIZE_SYNC_RASTER_2_HZ
Freq. step in Hz, corresponding to $M$ for 3GHz-24.25GHz freq. range, as per Table 5.4.3.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_ss_ref_hz.
const unsigned srsgnb::N_UB_SYNC_RASTER_1
Upper-bound for $N$ within 0GHz-3GHz freq. range, as per Table 5.4.3.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_next_ssb_location.
const unsigned srsgnb::N_UB_SYNC_RASTER_2
Upper-bound for $N$ within 3GHz-24.25GHz freq. range, as per Table 5.4.3.1-1, TS 38.104.
Referenced by srsgnb::srs_du::ssb_freq_position_generator::get_next_ssb_location.
constexpr unsigned srsgnb::MAX_TBS
Maximum accepted transport block size.
constexpr unsigned srsgnb::MAX_BLOCK_LENGTH
Maximum length of a codeword.
Referenced by srsgnb::short_block_detector_impl::detect_3_11, srsgnb::short_block_detector_impl::detect.
constexpr unsigned srsgnb::MAX_MSG_LENGTH
Maximum length of a message.
constexpr unsigned srsgnb::MAX_NOF_CODEWORDS_2
Half of the maximum codebook size.
const uint32_t srsgnb::INVALID_RLC_SN
Reserved number representing an invalid RLC sequence number.
Referenced by srsgnb::rlc_tx_am_entity::pull_pdu, srsgnb::rlc_tx_am_entity::get_polling_bit.
const uint32_t srsgnb::RETX_COUNT_NOT_STARTED
Reserved number representing that RETX has not started.
constexpr uint32_t srsgnb::rlc_am_nr_status_pdu_sizeof_header_ack_sn
Header fixed part and ACK SN.
constexpr uint32_t srsgnb::rlc_am_nr_status_pdu_sizeof_nack_sn_ext_12bit_sn
NACK SN and extension fields (12 bit SN)
constexpr uint32_t srsgnb::rlc_am_nr_status_pdu_sizeof_nack_sn_ext_18bit_sn
NACK SN and extension fields (18 bit SN)
constexpr uint32_t srsgnb::rlc_am_nr_status_pdu_sizeof_nack_so
NACK segment offsets (start and end)
constexpr uint32_t srsgnb::rlc_am_nr_status_pdu_sizeof_nack_range
NACK range (nof consecutively lost SDUs)
constexpr uint32_t srsgnb::RLC_AM_NR_TYP_NACKS
Expected number of NACKs in status PDU before needing to realloc.
constexpr size_t srsgnb::rlc_am_pdu_header_so_size
constexpr size_t srsgnb::rlc_am_pdu_header_min_size_12bit
constexpr size_t srsgnb::rlc_am_pdu_header_min_size_18bit
constexpr size_t srsgnb::rlc_um_pdu_header_size_complete_sdu
constexpr size_t srsgnb::rlc_um_pdu_header_size_6bit_sn_no_so
constexpr size_t srsgnb::rlc_um_pdu_header_size_12bit_sn_no_so
constexpr size_t srsgnb::rlc_um_pdu_header_size_6bit_sn_with_so
constexpr size_t srsgnb::rlc_um_pdu_header_size_12bit_sn_with_so
constexpr pdsch_default_time_allocation_config srsgnb::PDSCH_DEFAULT_TIME_ALLOCATION_RESERVED
Reserved default PDSCH time-domain allocation. It indicates the configuration is invalid.
void srsgnb::set_bitmap_bit(Integer &bitmap, unsigned bit, bool enable)
Sets the value of a bit in the bitmap. When enable is true, it sets the bit, otherwise it clears the bit.
bitmap Bitmap to modify. bit Bit to change. enable Value to set. If true, sets the bit(1), otherwise clears it(0). Use this function with integer data types, otherwise it produces undefined behaviour.
bool srsgnb::check_bitmap_bit(Integer bitmap, unsigned bit)
Checks the value of a bit in the bitmap and returns a true if the bit is set, otherwise false.
bitmap Bitmap to check. bit Bit to check. True when the bit equals 1, otherwise false. Use this function with integer data types, otherwise it produces undefined behaviour.
constexpr Integer srsgnb::mask_msb_zeros(size_t N)
Returns an unsigned integer with the N most significant bits (MSB) set to zero, and the remaining bits set to 1.
Integer Type of unsigned integer returned by the function. N Number of MSB bits set to zero. Resulting integer bitmap.
constexpr Integer srsgnb::mask_lsb_ones(size_t N)
Returns an unsigned integer with the N least significant bits (LSB) set to zero, and the remaining bits set to 1.
Integer Type of unsigned integer returned by the function. N Number of LSB bits set to zero. Resulting integer bitmap.
constexpr Integer srsgnb::mask_msb_ones(size_t N)
Returns an unsigned integer with the N most significant bits (MSB) set to one, and the remaining bits set to zero.
Integer Type of unsigned integer returned by the function. N Number of MSB bits set to one. Resulting integer bitmap.
Integer srsgnb::mask_lsb_zeros(size_t N)
Returns an unsigned integer with the N least significant bits (LSB) set to one, and the remaining bits set to zero.
Integer Type of unsigned integer returned by the function. N Number of LSB bits set to one. Resulting integer bitmap.
Integer srsgnb::zero_msb_count(Integer value)
Counts the number of contiguous bits set to zero, starting from the MSB.
Integer Integer type of received bitmap. value Integer bitmap count of bits set to zero.
References srsgnb::detail::bitset_builtin_helper< Integer >::zero_msb_count.
Integer srsgnb::find_first_msb_one(Integer value)
Finds the position of the first bit set to one, starting from the MSB.
Integer Integer type of received bitmap. value Integer bitmap MSB position with the bit set to one. The MSB has position sizeof(Integer) * 8 - 1.
Integer srsgnb::find_first_lsb_one(Integer value)
Finds the position of the first bit set to one, starting from the LSB.
Integer Integer type of received bitmap. value Integer bitmap LSB position with the bit set to one. The LSB has position zero.
References srsgnb::detail::bitset_builtin_helper< Integer >::zero_lsb_count.
Referenced by get_coreset_start_crb.
int srsgnb::count_ones(Integer value)
bounded_bitset<N, reversed> srsgnb::operator&(const bounded_bitset< N, reversed > &lhs, const bounded_bitset< N, reversed > &rhs) noexcept
Bitwise AND operation result = lhs & rhs.
new bounded_bitset that results from the Bitwise AND operation.
bounded_bitset<N, reversed> srsgnb::operator|(const bounded_bitset< N, reversed > &lhs, const bounded_bitset< N, reversed > &rhs) noexcept
Bitwise AND operation result = lhs | rhs.
new bounded_bitset that results from the Bitwise OR operation.
bounded_bitset<N, reversed> srsgnb::fliplr(const bounded_bitset< N, reversed > &other) noexcept
Flip bits from left to right.
new bounded_bitset that results from the fliplr operation.
References srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::set.
bounded_bitset<N2, reversed> srsgnb::fold_and_accumulate(const bounded_bitset< N, reversed > &other, size_t fold_length, size_t slice_offset, size_t slice_length) noexcept
Divides a bitset of size "S" into "M" smaller bitsets, where each bitset has length "L=S/M". A bitwise-or operation is performed across bitsets. At the end, a slice with an offset "O" and length "K" is taken from the bitset of length "L" that resulted from the bitwise-or operation. This operation is equivalent to reshaping an array of bits of size "S" into a matrix of dimensions "(M, L)" and applying an "or" operation across all bits of each column. The resulting array of "L" bits, is then sliced with an offset "O" and length "K". The operation asserts if "S % L != 0". E.g. Consider the bitset 1000 0100 0000 1001 (S=16), L=4, O=1, K=2. This function performs the following steps:
Break the bitset into M=S/L=4 parts: {1000, 0100, 0000, 1001}. Bitwise-or all the M parts: 1101. Slice the bitset obtained in 2. with offset O=1 and slice length K=2: 10. N2 maximum bitset size for returned bitset. other original bitset of length "S". fold_length length of each folded bitset "L". slice_offset offset from where to slice each fold "O". slice_length length of the slice taken from each fold "K". bitset of size slice_length with the or-accumulated folds.
bounded_bitset<N2, reversed> srsgnb::fold_and_accumulate(const bounded_bitset< N, reversed > &other, size_t fold_length) noexcept
Performs the fold and accumulate operation, but without slicing at the end.
N2 maximum bitset size for returned bitset. reversed internal bit order representation of returned bitset. other original bitset from where folds are generated. fold_length length of each fold bitset. bitset of size fold_length with the accumulated folds.
bool srsgnb::operator==(const byte_buffer &buf, span< const uint8_t > bytes)
bool srsgnb::operator==(span< const uint8_t > bytes, const byte_buffer &buf)
bool srsgnb::operator!=(const byte_buffer &buf, span< const uint8_t > bytes)
bool srsgnb::operator!=(span< const uint8_t > bytes, const byte_buffer &buf)
byte_buffer srsgnb::make_byte_buffer(std::string hex_str)
Converts a hex string (e.g. 01FA02) to a byte buffer.
References srsgnb::byte_buffer::append.
bool srsgnb::operator==(const interval< T > &lhs, const interval< T > &rhs)
bool srsgnb::operator!=(const interval< T > &lhs, const interval< T > &rhs)
bool srsgnb::operator<(const interval< T > &lhs, const interval< T > &rhs)
Compares interval starting points. In case the starting point is the same, the interval with shorter length is the lowest.
interval<T> srsgnb::operator|(const interval< T > &lhs, const interval< T > &rhs)
Make union of intervals. If intervals do not overlap, the empty interval is returned.
References srsgnb::interval< T >::overlaps.
interval<T> srsgnb::operator&(const interval< T > &lhs, const interval< T > &rhs)
Make intersection of intervals.
References srsgnb::interval< T >::overlaps.
bool srsgnb::operator==(const optional< T > &lhs, const optional< T > &rhs) noexcept
bool srsgnb::operator==(const optional< T > &lhs, const T &rhs) noexcept
bool srsgnb::operator!=(const optional< T > &lhs, const optional< T > &rhs) noexcept
bool srsgnb::operator!=(const optional< T > &lhs, const T &rhs) noexcept
bool srsgnb::operator<(const optional< T > &lhs, const optional< T > &rhs) noexcept
split_slot_span<T> srsgnb::make_slot_span(T *array, typename std::conditional< std::is_const< T >::value, const bool, bool >::type *present, size_t N)
split_slot_span<T> srsgnb::make_slot_span(T(&array)[N], typename std::conditional< std::is_const< T >::value, const bool, bool >::type(&present)[N])
bool srsgnb::operator==(span< T > lhs, span< T > rhs)
bool srsgnb::operator!=(span< T > lhs, span< T > rhs)
constexpr std::array<std::remove_cv_t<T>, N> srsgnb::to_array(T(&a)[N])
Helper method to generate an std::array from a C array without needing to derive the size N.
constexpr std::array<std::remove_cv_t<T>, N> srsgnb::to_array(T(&&a)[N])
check_outcome srsgnb::is_du_cell_config_valid(const du_cell_config &cell_cfg)
Checks whether the provided DU cell configuration is valid.
cell_cfg DU cell configuration. in case an invalid parameter is detected, returns a string containing an error message.
References srsgnb::du_cell_config::scs_common.
const char* srsgnb::to_string(bsr_format bsr)
sched_cell_configuration_request_message srsgnb::make_scheduler_cell_configuration_request(const mac_cell_creation_request &request)
Convert a cell configuration request to the MAC into a cell configuration request of the scheduler.
sched_ue_creation_request_message srsgnb::make_scheduler_ue_creation_request(const mac_ue_create_request_message &request)
Convert a UE creation request for the MAC into a UE creation request of the scheduler.
std::unique_ptr< mac_interface > srsgnb::create_mac(mac_ul_ccch_notifier &event_notifier, du_l2_ul_executor_mapper &ul_exec_mapper, du_l2_dl_executor_mapper &dl_exec_mapper, task_executor &ctrl_exec, mac_result_notifier &phy_notifier)
std::unique_ptr< pdcp_entity > srsgnb::create_pdcp_entity(pdcp_entity_creation_message &msg)
Creates an instance of a PDCP entity.
Referenced by srsgnb::srs_cu_cp::du_processor::create_srb.
std::shared_ptr< dft_processor_factory > srsgnb::create_dft_processor_factory_generic()
Creates a DFT processor factory based on a generic Radix-2 DFT implementation.
std::shared_ptr< dft_processor_factory > srsgnb::create_dft_processor_factory_fftx()
Creates a DFT processor factory based on SPIRAL's FFTX.
std::shared_ptr< dft_processor_factory > srsgnb::create_dft_processor_factory_fftw(bool avoid_wisdom=false, const std::string &wisdom_filename="")
Creates a DFT processor factory based on FFTW library.
avoid_wisdom Set to true to avoid loading FFTW wisdom from a file. wisdom_filename Indicates the FFTW wisdom filename. Leave empty for default value. It is ignored if the option avoid_wisdom is true. A valid pointer to a DFT processor factory if FFTW is available. Otherwise, nullptr.
std::unique_ptr< lower_phy_factory > srsgnb::create_lower_phy_factory_sw(std::shared_ptr< ofdm_modulator_factory > modulator_factory, std::shared_ptr< ofdm_demodulator_factory > demodulator_factory, std::shared_ptr< prach_processor_factory > prach_processor_factory)
Creates a software based lower physical layer factory.
std::shared_ptr< ofdm_modulator_factory > srsgnb::create_ofdm_modulator_factory_generic(ofdm_factory_generic_configuration &config)
Creates a generic OFDM modulator factory.
std::shared_ptr< ofdm_demodulator_factory > srsgnb::create_ofdm_demodulator_factory_generic(ofdm_factory_generic_configuration &config)
Creates a generic OFDM demodulator factory.
std::shared_ptr< ofdm_prach_demodulator_factory > srsgnb::create_ofdm_prach_demodulator_factory_sw(std::shared_ptr< dft_processor_factory > dft_factory, unsigned dft_size_15kHz)
Creates a software generic PRACH demodulator.
dft_factory DFT factory. dft_size_15kHz DFT size for 15kHz subcarrier spacing.
std::shared_ptr< prach_processor_factory > srsgnb::create_prach_processor_factory_sw(std::shared_ptr< ofdm_prach_demodulator_factory > ofdm_prach_factory, unsigned dft_size_15kHz, unsigned max_nof_concurrent_requests)
Creates a software based PRACH processor.
std::unique_ptr< resource_grid > srsgnb::create_resource_grid(unsigned nof_ports, unsigned nof_symbols, unsigned nof_subc)
Creates a generic resource grid instance for a number of ports, symbols and subcarriers.
nof_ports Number of ports. nof_symbols Number of OFDM symbols. nof_subc Number of subcarriers. A resource grid object.
std::unique_ptr< resource_grid_pool > srsgnb::create_resource_grid_pool(unsigned nof_sectors, unsigned nof_slots, std::vector< std::unique_ptr< resource_grid >> &&grids)
Creates a generic resource grid pool.
nof_sectors Number of radio sectors. nof_slots umber of slots to be buffered, per sector. grids Resource grids, ownerships are transferred to the pool. A generic resource grid pool.
std::unique_ptr< prach_buffer > srsgnb::create_prach_buffer_long()
Creates a long PRACH sequence buffer.
Long buffers contain 839-element PRACH sequences for up to 4 OFDM symbols.
std::unique_ptr< prach_buffer > srsgnb::create_prach_buffer_short()
Creates a short PRACH sequence buffer.
Short buffers contain 139-element PRACH sequences for up to 12 OFDM symbols.
std::unique_ptr< prach_buffer_pool > srsgnb::create_prach_buffer_pool(std::vector< std::unique_ptr< prach_buffer >> &&elements)
Returns a pool for the given PRACH buffers.
std::shared_ptr< crc_calculator_factory > srsgnb::create_crc_calculator_factory_sw()
std::shared_ptr< ldpc_decoder_factory > srsgnb::create_ldpc_decoder_factory_sw(const std::string &dec_type)
std::shared_ptr< ldpc_encoder_factory > srsgnb::create_ldpc_encoder_factory_sw(const std::string &enc_type)
std::shared_ptr< ldpc_rate_dematcher_factory > srsgnb::create_ldpc_rate_dematcher_factory_sw()
std::shared_ptr< ldpc_rate_matcher_factory > srsgnb::create_ldpc_rate_matcher_factory_sw()
std::shared_ptr< ldpc_segmenter_rx_factory > srsgnb::create_ldpc_segmenter_rx_factory_sw()
std::shared_ptr< ldpc_segmenter_tx_factory > srsgnb::create_ldpc_segmenter_tx_factory_sw(std::shared_ptr< crc_calculator_factory > crc_factory)
std::shared_ptr< polar_factory > srsgnb::create_polar_factory_sw()
std::unique_ptr< short_block_detector > srsgnb::create_short_block_detector()
std::unique_ptr< short_block_encoder > srsgnb::create_short_block_encoder()
std::shared_ptr< channel_modulation_factory > srsgnb::create_channel_modulation_sw_factory()
std::shared_ptr< pbch_encoder_factory > srsgnb::create_pbch_encoder_factory_sw(std::shared_ptr< crc_calculator_factory > crc_factory, std::shared_ptr< pseudo_random_generator_factory > prg_factory, std::shared_ptr< polar_factory > polar_factory)
std::shared_ptr< pbch_modulator_factory > srsgnb::create_pbch_modulator_factory_sw(std::shared_ptr< channel_modulation_factory >, std::shared_ptr< pseudo_random_generator_factory >)
std::shared_ptr< pdcch_modulator_factory > srsgnb::create_pdcch_modulator_factory_sw(std::shared_ptr< channel_modulation_factory >, std::shared_ptr< pseudo_random_generator_factory >)
std::shared_ptr< pdcch_encoder_factory > srsgnb::create_pdcch_encoder_factory_sw(std::shared_ptr< crc_calculator_factory > crc_factory, std::shared_ptr< polar_factory > encoder_factory)
std::shared_ptr< pdcch_processor_factory > srsgnb::create_pdcch_processor_factory_sw(std::shared_ptr< pdcch_encoder_factory > encoder_factory, std::shared_ptr< pdcch_modulator_factory > modulator_factory, std::shared_ptr< dmrs_pdcch_processor_factory > dmrs_factory)
std::shared_ptr< pdsch_encoder_factory > srsgnb::create_pdsch_encoder_factory_sw(pdsch_encoder_factory_sw_configuration &config)
std::shared_ptr< pdsch_modulator_factory > srsgnb::create_pdsch_modulator_factory_sw(std::shared_ptr< channel_modulation_factory >, std::shared_ptr< pseudo_random_generator_factory >)
std::shared_ptr< pdsch_processor_factory > srsgnb::create_pdsch_processor_factory_sw(std::shared_ptr< pdsch_encoder_factory > encoder_factory, std::shared_ptr< pdsch_modulator_factory > modulator_factory, std::shared_ptr< dmrs_pdsch_processor_factory > dmrs_factory)
std::shared_ptr< prach_detector_factory > srsgnb::create_prach_detector_factory_simple(std::shared_ptr< dft_processor_factory > dft_factory, std::shared_ptr< prach_generator_factory > prach_gen_factory)
std::shared_ptr< prach_generator_factory > srsgnb::create_prach_generator_factory_sw(std::shared_ptr< dft_processor_factory > dft_factory)
std::shared_ptr< pusch_decoder_factory > srsgnb::create_pusch_decoder_factory_sw(pusch_decoder_factory_sw_configuration &config)
std::shared_ptr< pusch_processor_factory > srsgnb::create_pusch_processor_factory_sw(pusch_processor_factory_sw_configuration &config)
std::shared_ptr< ssb_processor_factory > srsgnb::create_ssb_processor_factory_sw(ssb_processor_factory_sw_configuration &config)
std::shared_ptr< pseudo_random_generator_factory > srsgnb::create_pseudo_random_generator_sw_factory()
std::unique_ptr< dmrs_pucch_processor > srsgnb::create_dmrs_pucch_processor(const pucch_format &format, const low_papr_sequence_collection *c=nullptr, const pucch_orthogonal_sequence *occ=nullptr)
Creates a generic DMRS for PUCCH instance.
std::unique_ptr< srsgnb::csi_rs_processor > srsgnb::create_csi_rs_processor()
std::shared_ptr< dmrs_pbch_processor_factory > srsgnb::create_dmrs_pbch_processor_factory_sw(std::shared_ptr< pseudo_random_generator_factory > prg_factory)
std::shared_ptr< dmrs_pdcch_processor_factory > srsgnb::create_dmrs_pdcch_processor_factory_sw(std::shared_ptr< pseudo_random_generator_factory > prg_factory)
std::shared_ptr< dmrs_pdsch_processor_factory > srsgnb::create_dmrs_pdsch_processor_factory_sw(std::shared_ptr< pseudo_random_generator_factory > prg_factory)
std::unique_ptr<dmrs_pusch_estimator> srsgnb::create_pusch_estimator_generic(pusch_estimator_generic_configuration &config)
std::shared_ptr< pss_processor_factory > srsgnb::create_pss_processor_factory_sw()
std::shared_ptr< sss_processor_factory > srsgnb::create_sss_processor_factory_sw()
std::unique_ptr< uplink_processor_pool > srsgnb::create_uplink_processor_pool(uplink_processor_pool_config config)
Creates and returns an uplink processor pool.
References srsgnb::uplink_processor_pool_impl_config::num_sectors, srsgnb::uplink_processor_pool_config::num_sectors, srsgnb::uplink_processor_pool_config::ul_processors, srsgnb::uplink_processor_pool_impl_config::procs.
std::shared_ptr< downlink_processor_factory > srsgnb::create_downlink_processor_factory_sw(const downlink_processor_factory_sw_config &config)
Creates a full software based downlink processor factory.
References srsgnb::downlink_processor_factory_sw_config::ldpc_encoder_type.
std::unique_ptr< downlink_processor_pool > srsgnb::create_dl_processor_pool(downlink_processor_pool_config config)
Creates and returns a downlink processor pool.
References srsgnb::downlink_processor_pool_impl_config::num_sectors, srsgnb::downlink_processor_pool_config::num_sectors, srsgnb::downlink_processor_pool_config::dl_processors, srsgnb::downlink_processor_pool_impl_config::procs.
std::unique_ptr< upper_phy_factory > srsgnb::create_upper_phy_factory(std::shared_ptr< downlink_processor_factory > downlink_proc_factory)
Creates and returns an upper PHY factory.
std::unique_ptr< radio_factory > srsgnb::create_radio_factory(std::string driver_name)
constexpr unsigned srsgnb::bs_channel_bandwidth_to_MHz(bs_channel_bandwidth_fr1 bw)
Converts the BS channel bandwidth label into the actual BW value in MHz.
constexpr unsigned srsgnb::get_nsymb_per_slot(const cyclic_prefix cp)
Defines the number of OFDM symbols per slot, according to TS 38.211 Tables 4.3.2-1 and 4.3.2-2.
References srsgnb::cyclic_prefix::EXTENDED.
Referenced by srsgnb::ofdm_symbol_demodulator_impl::get_cp_offset, srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::ofdm_slot_demodulator_impl::get_slot_size, srsgnb::ofdm_slot_demodulator_impl::demodulate, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_slot_modulator_impl::get_slot_size, srsgnb::ofdm_slot_modulator_impl::modulate, srsgnb::phase_compensation_lut::phase_compensation_lut, srsgnb::ssb_processor_impl::process, srsgnb::csi_rs_processor_impl::generate_sequence, srsgnb::csi_rs_processor_impl::map, srsgnb::dmrs_pdcch_processor_impl::c_init, srsgnb::dmrs_pdsch_processor_impl::sequence_generation, srsgnb::dmrs_pucch_processor_format2_impl::c_init, srsgnb::pucch_helper::get_alpha_index.
constexpr du_ue_index_t srsgnb::to_du_ue_index(std::underlying_type_t< du_ue_index_t > idx)
Convert integer to DU UE index type.
Referenced by srsgnb::ue_index_based_ul_executor_mapper::executor, srsgnb::pcell_ul_executor_mapper::executor.
constexpr bool srsgnb::is_du_ue_index_valid(du_ue_index_t ue_idx)
du_cell_index_t srsgnb::to_du_cell_index(std::underlying_type_t< du_cell_index_t > idx)
Convert integer to DU cell index type.
ue_cell_index_t srsgnb::to_ue_cell_index(std::underlying_type_t< ue_cell_index_t > idx)
bool srsgnb::is_srb(lcid_t lcid)
bool srsgnb::is_lcid_valid(lcid_t lcid)
srb_id_t srsgnb::to_srb_id(lcid_t lcid)
lcid_t srsgnb::srb_id_to_lcid(srb_id_t srb_id)
Convert SRB ID to LCID.
Referenced by srsgnb::srs_cu_cp::du_processor::create_srb.
constexpr ldpc_base_graph_type srsgnb::get_ldpc_base_graph(float R, unsigned A)
Returns the LDPC base graph based on the given code rate and transport block size in bytes, as per TS 38.212 section 7.2.2.
R Target code rate. A Size in bytes of the payload.
References A.
std::string srsgnb::to_string(modulation_scheme mod)
constexpr unsigned srsgnb::get_bits_per_symbol(modulation_scheme mod)
Bits per symbol for a given modulation scheme.
mod Modulation scheme. The number of bits per modulated symbol (sometimes referred to as modulation order).
References PI_2_BPSK, MODULATION_MAX_BITS_PER_SYMBOL.
Referenced by srsgnb::sch_mcs_description::get_spectral_efficiency, srsgnb::ldpc_rate_dematcher_impl::init, srsgnb::ldpc_segmenter_impl::compute_rm_length, srsgnb::ldpc_segmenter_impl::segment, srsgnb::short_block_detector_impl::detect, srsgnb::short_block_encoder_impl::encode, srsgnb::demodulation_mapper_impl::demodulate_soft, srsgnb::modulation_mapper_impl::modulate, srsgnb::pdsch_modulator_impl::modulate, srsgnb::pdsch_processor_impl::encode, srsgnb::sib1_scheduler::allocate_sib1.
ofdm_symbol_range srsgnb::sliv_to_ofdm_symbols(uint32_t sliv)
Converts SLIV to OFDM symbol start S and length L.
sliv An index giving a combination (jointly encoded) of start symbols and length indicator (SLIV). symbols Symbol interval as [S, S+L).
References sliv_to_s_and_l, NOF_OFDM_SYM_PER_SLOT_NORMAL_CP.
unsigned srsgnb::to_nof_cces(aggregation_level lvl)
Calculates number of CCEs based on Aggregation Level as per TS38.211 Table 7.3.2.1-1.
Referenced by pdcch_candidates_common_ss_get_lowest_cce.
unsigned srsgnb::to_aggregation_level_index(aggregation_level lvl)
Calculates the index associated to the passed aggregation level.
prb_index_list srsgnb::cce_to_prb_mapping_coreset0(unsigned N_coreset0_start, unsigned N_coreset0_size, unsigned N_symb_coreset, pci_t N_id_cell, unsigned aggregation_level, unsigned cce_index)
Calculates the PDCCH CCE to PRB mapping for a PDCCH transmission in CORESET0.
N_coreset0_start The lowest RB index of the CORESET0 relative to CRB0 (PointA). N_coreset0_size The CORESET0 bandwidth in RBs. N_symb_coreset The number of symbols for the PDCCH transmission. N_id_cell Physical cell identifier. aggregation_level Number of CCE used for the PDCCH transmission. cce_index Initial CCE index for the PDCCH transmision. A list of the resource blocks used by the PDCCH transmission.
Referenced by srsgnb::pdcch_processor_impl::compute_rb_mask.
prb_index_list srsgnb::cce_to_prb_mapping_non_interleaved(unsigned N_bwp_start, const freq_resource_bitmap &freq_resources, unsigned N_symb_coreset, unsigned aggregation_level, unsigned cce_index)
Calculates the PDCCH CCE to PRB mapping for a non-interleaved PDCCH transmission.
N_bwp_start Start of the BWP relative to CRB0 (PointA). freq_resources Indicates the frequency resources active for the CORESET. N_symb_coreset The number of symbols for the PDCCH transmission. aggregation_level Number of CCE used for the PDCCH transmission. cce_index Initial CCE index for the PDCCH transmision. A list of the resource blocks used by the PDCCH transmission.
Referenced by srsgnb::pdcch_processor_impl::compute_rb_mask.
prb_index_list srsgnb::cce_to_prb_mapping_interleaved(unsigned N_bwp_start, const freq_resource_bitmap &freq_resources, unsigned N_symb_coreset, unsigned reg_bundle_size, unsigned interleaver_size, unsigned shift_index, unsigned aggregation_level, unsigned cce_index)
Calculates the PDCCH CCE to PRB mapping for an interleaved PDCCH transmission.
N_bwp_start Start of the BWP relative to CRB0 (PointA). freq_resources Indicates the frequency resources active for the CORESET. N_symb_coreset The number of symbols for the PDCCH transmission. reg_bundle_size Parameter reg-BundleSize. interleaver_size Parameter interleaverSize. shift_index Parameter shiftIndex if available, otherwise $N_{ID}^{cell}$. aggregation_level Number of CCE used for the PDCCH transmission. cce_index Initial CCE index for the PDCCH transmision. A list of the resource blocks used by the PDCCH transmission.
References srsgnb::bounded_bitset< N, reversed >::count.
Referenced by srsgnb::pdcch_processor_impl::compute_rb_mask.
constexpr coreset_id srsgnb::to_coreset_id(unsigned cs_id)
dci_payload srsgnb::dci_1_0_p_rnti_pack(const dci_1_0_p_rnti_configuration &config)
Packs a DCI format 1_0 scrambled by P-RNTI.
References log2_ceil, srsgnb::dci_1_0_p_rnti_configuration::N_rb_dl_bwp, srsgnb::dci_1_0_p_rnti_configuration::short_messages_indicator, srsgnb::dci_1_0_p_rnti_configuration::scheduling_information, srsgnb::bounded_bitset< N, reversed >::push_back, srsgnb::dci_1_0_p_rnti_configuration::short_messages, srsgnb::dci_1_0_p_rnti_configuration::both, srsgnb::dci_1_0_p_rnti_configuration::frequency_resource, srsgnb::dci_1_0_p_rnti_configuration::time_resource, srsgnb::dci_1_0_p_rnti_configuration::vrb_to_prb_mapping, srsgnb::dci_1_0_p_rnti_configuration::modulation_coding_scheme, srsgnb::dci_1_0_p_rnti_configuration::tb_scaling.
dci_payload srsgnb::dci_1_0_si_rnti_pack(const dci_1_0_si_rnti_configuration &config)
Packs a DCI format 1_0 scrambled by SI-RNTI.
References log2_ceil, srsgnb::dci_1_0_si_rnti_configuration::N_rb_dl_bwp, srsgnb::bounded_bitset< N, reversed >::push_back, srsgnb::dci_1_0_si_rnti_configuration::frequency_resource, srsgnb::dci_1_0_si_rnti_configuration::time_resource, srsgnb::dci_1_0_si_rnti_configuration::vrb_to_prb_mapping, srsgnb::dci_1_0_si_rnti_configuration::modulation_coding_scheme, srsgnb::dci_1_0_si_rnti_configuration::redundancy_version, srsgnb::dci_1_0_si_rnti_configuration::system_information_indicator.
dci_payload srsgnb::dci_1_0_ra_rnti_pack(const dci_1_0_ra_rnti_configuration &config)
Packs a DCI format 1_0 scrambled by RA-RNTI.
References log2_ceil, srsgnb::dci_1_0_ra_rnti_configuration::N_rb_dl_bwp, srsgnb::bounded_bitset< N, reversed >::push_back, srsgnb::dci_1_0_ra_rnti_configuration::frequency_resource, srsgnb::dci_1_0_ra_rnti_configuration::time_resource, srsgnb::dci_1_0_ra_rnti_configuration::vrb_to_prb_mapping, srsgnb::dci_1_0_ra_rnti_configuration::modulation_coding_scheme, srsgnb::dci_1_0_ra_rnti_configuration::tb_scaling.
pdcch_candidate_list srsgnb::pdcch_candidates_common_ss_get_lowest_cce(const pdcch_candidates_common_ss_configuration &config)
Generates a PDCCH candidate list for Common SS as per TS38.213 Section 10.1.
Assertion is triggered if: the aggregation level is invalid (srsgnb::aggregation_level::is_valid for more information), the number of CCE in the CORESET is zero, or the number of candidates times the aggregation level exceeds the number of CCE in the CORESET. The resultant list contains the lowest CCE index of the config.nof_candidates.
References to_nof_cces, srsgnb::pdcch_candidates_common_ss_configuration::L, srsgnb::pdcch_candidates_common_ss_configuration::nof_cce_coreset, srsgnb::pdcch_candidates_common_ss_configuration::nof_candidates, PDCCH_MAX_NOF_CANDIDATES_SS.
pdcch_type0_css_coreset_description srsgnb::pdcch_type0_css_coreset_get(min_channel_bandwidth minimum_bandwidth_MHz, subcarrier_spacing ssb_scs, subcarrier_spacing pdcch_scs, uint8_t coreset_zero_index, uint8_t subcarrier_offset)
Get the CORESET configuration for Type0-PDCCH CSS.
The CORESET configuration is retrieved as per TS38.213 Tables 13-1, 13-2, 13-3, 13-4, 13-5, 13-6, 13-7, 13-8, 13-9 and 13-10 depending on the subcarrier combination of the SS/PBCH block and PDCCH, and the minimum channel bandwidth. minimum_bandwidth_MHz Band minimum bandwidth in MHz as per TS38.104 Table 5.3.5-1 for FR 1 and Table 5.3.5-2 for FR2. ssb_scs SS/PBCH block subcarrier spacing. pdcch_scs PDCCH subcarrier spacing. coreset_zero_index Parameter controlResourceSetZero as per TS38.331 PDCCH-ConfigSIB1. subcarrier_offset Offset between the CRB and the beginning of the SS/PBCH block. A valid CORESET description if config is valid. Otherwise, PDCCH_TYPE0_CSS_CORESET_RESERVED.
Referenced by srsgnb::sib1_scheduler::precompute_sib1_n0.
sch_mcs_description srsgnb::pdsch_mcs_get_config(pdsch_mcs_table table, sch_mcs_index index)
Gets the Modulation and Coding Scheme configuration for PDSCH.
Reserved target code rates and spectral efficiencies are indicated with zero. table MCS table. index MCS index. Modulation and Coding Scheme parameters.
References QPSK, QAM16, QAM64, QAM256, qam64, qam256, qam64LowSe.
Referenced by pusch_mcs_get_config, srsgnb::ra_scheduler::fill_rar_grant, srsgnb::sib1_scheduler::fill_sib1_grant.
constexpr U srsgnb::to_sampling_rate_Hz(subcarrier_spacing scs, unsigned dft_size)
Gets the sampling rate from a subcarrier spacing and a DFT size combination.
U Return data type. Must be convertible to unsigned (default: double). scs Subcarrier spacing. dft_size DFT size. The sampling rate in hertz from the given SCS and DFT size.
References scs_to_khz.
Referenced by srsgnb::phase_compensation_lut::phase_compensation_lut.
prach_configuration srsgnb::prach_configuration_get(frequency_range fr, duplex_mode dm, uint8_t prach_config_index)
Gets a PRACH configuration.
Arguments are considered valid if: They are consistent with the TS38.211 Tables 6.3.3.2-2, 6.3.3.2-3 and 6.3.3.2-4, and the combination is implemented. Currently, only long preamble formats for FR1 in FDD mode are implemented. fr Frequency range (see here for more information). dm Duplex mode (see here for more information). prach_config_index PRACH configuration index with range {0, ..., 255}. A valid PRACH configuration if the provided arguments are valid. Otherwise, PRACH_CONFIG_RESERVED.
References FR1, FDD, SUL, PRACH_CONFIG_RESERVED.
uint16_t srsgnb::prach_cyclic_shifts_get(prach_subcarrier_spacing prach_scs, restricted_set_config restricted_set, unsigned zero_correlation_zone)
Calculates the number of cyclic shifts $N_{CS}$ used in the sequence generation as per TS38.211 Section 6.3.3.1.
The number of cyclic shifts $N_{CS}$ is extracted from: TS38.211 Table 6.3.3.1-5 for preambles 0, 1 and 2 TS38.211 Table 6.3.3.1-6 for preamble 3, and TS38.211 Table 6.3.3.1-7 for the remaining preambles. prach_scs PRACH subcarrier spacing (parameter $\Delta f^{RA}$ as defined in TS38.211 Section 6.3.3.1). restricted_set Restricted set (see restrictedSetConfig in TS38.331 Section 6.3.2, Information Element RACH-ConfigCommon). zero_correlation_zone Zero correlation zone (see zeroCorrelationZoneConfig in TS38.331 Section 6.3.2, Information Element RACH-ConfigGeneric). The number of cyclic shifts if the input parameters are valid. Otherwise, PRACH_CYCLIC_SHIFTS_RESERVED.
References PRACH_CYCLIC_SHIFTS_RESERVED.
prach_frequency_mapping_information srsgnb::prach_frequency_mapping_get(prach_subcarrier_spacing prach_scs, subcarrier_spacing pusch_scs)
Gets the PRACH frequency mapping information contained in TS38.211 Table 6.3.3.2-1.
prach_scs_Hz PRACH subcarrier spacing (parameter $\Delta f_{RA}$). pusch_scs_Hz PUSCH subcarrier spacing (parameter $\Delta f$). The requested PRACH frequency mapping information if the combination of input parameters is valid, PRACH_FREQUENCY_MAPPING_INFORMATION_RESERVED otherwise.
References PRACH_FREQUENCY_MAPPING_INFORMATION_RESERVED.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate.
prach_preamble_information srsgnb::get_prach_preamble_long_info(preamble_format format)
Get long PRACH preamble information as per TS38.211 Table 6.3.3.1-1.
An assertion is triggered if the PRACH preamble format is not long. format PRACH preamble format. PRACH preamble information.
References srsgnb::phy_time_unit::from_units_of_kappa.
Referenced by srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::prach_processor_worker::handle_request, srsgnb::prach_detector_simple_impl::detect.
sch_mcs_description srsgnb::pusch_mcs_get_config(pusch_mcs_table table, sch_mcs_index index, bool tp_pi2bpsk_present)
Gets the Modulation and Coding Scheme configuration for PUSCH.
Reserved target code rates and spectral efficiencies are indicated with zero. table MCS table. index MCS index. tp_pi2bpsk_present Set to true if higher layer parameter tp-pi2BPSK is enabled. See TS38.331 Section 6.3.2 Information Element PUSCH-Config for more information. Modulation and Coding Scheme parameters.
References PI_2_BPSK, QPSK, QAM16, QAM64, qam64, qam256, qam64LowSe, pdsch_mcs_get_config, qam64_tp, qam64LowSe_tp.
unsigned int srsgnb::ra_frequency_type1_get_riv(const ra_frequency_type1_configuration &config)
Calculates the resource indication value $RIV$ as per TS38.214 Section 5.1.2.2.2 for Downlink and Section 6.1.2.2 for Uplink.
if $(L_{RB} - 1) \leq \left \lfloor N_{BWP}^{size}/2 \right \rfloor$, then $RIV = N_{BWP}^{size}(L_{RBs}-1)+RB_{start}$ Otherwise, $RIV = N_{BWP}^{size}(N_{BWP}^{size}-L_{RBs}+1)+(N_{BWP}^{size}-1-RB_{start})$.
References srsgnb::ra_frequency_type1_configuration::length_vrb, srsgnb::ra_frequency_type1_configuration::N_bwp_size, srsgnb::ra_frequency_type1_configuration::start_vrb, sliv_from_s_and_l.
Referenced by srsgnb::ra_scheduler::fill_rar_grant, srsgnb::sib1_scheduler::fill_sib1_grant.
ra_frequency_type1_configuration srsgnb::ra_frequency_type1_from_riv(unsigned N_bwp_size, unsigned riv)
Calculates the PRBs from $RIV$ as per TS 38.214 Section 5.1.2.2.2 for Downlink and Section 6.1.2.2 for Uplink.
References srsgnb::ra_frequency_type1_configuration::N_bwp_size, sliv_to_s_and_l, srsgnb::ra_frequency_type1_configuration::start_vrb, srsgnb::ra_frequency_type1_configuration::length_vrb.
unsigned srsgnb::ra_frequency_type1_special_get_riv(const ra_frequency_type1_special_configuration &config)
Calculates the resource indication value $RIV$ for special cases as per TS38.214 Section 5.1.2.2.2 for Downlink and Section 6.1.2.2 for Uplink.
if $(L'_{RB} - 1) \leq \left \lfloor N_{BWP}^{initial}/2 \right \rfloor$, then $RIV = N_{BWP}^{initial}(L'_{RBs}-1)+RB'_{start}$ Otherwise, $RIV = N_{BWP}^{initial}(N_{BWP}^{initial}-L'_{RBs}+1)+(N_{BWP}^{initial}-1-RB'_{start})$. Where $L'_{RB}=L_{RB}/K$, $RB'_{start}=RB_{start}/K$. if $N_{BWP}^{active}>N_{BWP}^{initial}$ then $K$ is the maximum value from set {1,2,4,8} which satisfies $K \leq \left \lfloor N_{BWP}^{active}/ N_{BWP}^{initial}\right \rfloor$; otherwise $K=1$.
References srsgnb::ra_frequency_type1_special_configuration::N_bwp_active, srsgnb::ra_frequency_type1_special_configuration::N_bwp_initial, srsgnb::ra_frequency_type1_special_configuration::start_vrb, srsgnb::ra_frequency_type1_special_configuration::length_vrb, sliv_from_s_and_l.
constexpr std::size_t srsgnb::get_rb_bw_khz(subcarrier_spacing scs)
Compute RB bandwidth in kHz, based on the used numerology.
References NOF_SUBCARRIERS_PER_RB, scs_to_khz.
constexpr std::size_t srsgnb::channel_bw_mhz_to_index(unsigned dl_bw_mhz)
Converts channel bandwidth in MHz to index.
Referenced by get_max_Nprb.
std::size_t srsgnb::get_max_Nprb(unsigned dl_bw_mhz, subcarrier_spacing scs, frequency_range fr)
Computes the maximum transmission bandwidth in number of PRBs for a UE channel. See TS 38.101-1/2, 5.3.2 - Maximum transmission bandwidth configuration.
References is_scs_valid, channel_bw_mhz_to_index, FR1, to_numerology_value.
constexpr bool srsgnb::is_crnti(rnti_t rnti)
Checks whether RNTI value corresponds to a C-RNTI value.
Referenced by srsgnb::mac_ul_ue_manager::add_ue.
constexpr rnti_t srsgnb::to_rnti(std::underlying_type_t< rnti_t > number)
Converts integer to RNTI value.
Referenced by srsgnb::srs_cu_cp::f1ap_du_processor_adapter::on_create_ue, decode_crnti_ce, srsgnb::rnti_allocator::allocate.
unsigned srsgnb::sib1_rtx_periodicity_to_value(sib1_rtx_periodicity periodicity)
Converts the SIB1 periodicity property to its corresponding value in milliseconds.
constexpr void srsgnb::sliv_to_s_and_l(unsigned N, unsigned sliv, Integer &S, Integer &L)
Convert SLIV to start S and length L.
N Max length. sliv An index giving a combination (jointly encoded) of start and length indicator (SLIV). S Start. L Length.
Referenced by sliv_to_ofdm_symbols, ra_frequency_type1_from_riv.
constexpr unsigned srsgnb::sliv_from_s_and_l(unsigned N, unsigned S, unsigned L)
Convert start S and length L into SLIV.
N Max length. S Start symbols. L Length. An index giving a combination (jointly encoded) of start symbols and length indicator (SLIV).
Referenced by ra_frequency_type1_get_riv, ra_frequency_type1_special_get_riv.
slot_point srsgnb::operator+(slot_point slot, Integer jump)
Sum and subtraction operations between slot_point types.
slot_point srsgnb::operator+(uint32_t jump, slot_point slot)
slot_point srsgnb::operator+(int jump, slot_point slot)
slot_point srsgnb::operator-(slot_point slot, uint32_t jump)
slot_point srsgnb::operator-(slot_point slot, int jump)
slot_point srsgnb::max(slot_point lhs, slot_point rhs)
Get maximum of two slot points.
slot_point srsgnb::min(slot_point lhs, slot_point rhs)
Get minimum of two slot points.
slot_point srsgnb::set_slot_numerology(slot_point sl, unsigned new_numerology)
Convert a slot point to another numerology. This function applies a "floor" operation when the new numerology is lower than the old one. E.g. Given two numerologies mu1 and mu2, where m1 < m2, this conversion function "f" will always ensure that, for a slot t1 with m1 numerology, the condition "f(f(t1, mu2), m1) <= t1" is satisfied.
References srsgnb::slot_point::numerology.
Referenced by slot_is_dl.
unsigned srsgnb::ssb_get_l_first(ssb_pattern_case pattern_case, unsigned ssb_idx)
Calculates the first OFDM symbol in a 5ms SS/PBCH block burst.
pattern_case Provides the pattern ssb_idx Provides the SS/PBCH block opportunity index the first OFDM symbol index in a half-frame
References A, B, C, D, E.
Referenced by srsgnb::ssb_processor_impl::process.
unsigned srsgnb::ssb_get_k_first(frequency_range fr, subcarrier_spacing ssb_scs, subcarrier_spacing common_scs, ssb_offset_to_pointA offset_to_pointA, ssb_subcarrier_offset subcarrier_offset)
Calculates the position of the first SS/PBCH block subcarrier relative to Point A.
The result is expressed in units of subcarriers of SS/PBCH block SCS ssb_scs assuming that: the lowest subcarrier of the resource grid overlaps with Point A, and the resource grid SCS matches the SS/PBCH block SCS. In other words, it is not possible to determine an SS/PBCH block position in the grid if the SS/PBCH block subcarrier offset does not match the position of the resource grid subcarriers. Because of this, the parameters must result in an integer subcarrier index of the SS/PBCH block SCS. Assertions are triggered if: the provided SS/PBCH SCS and frequency range combination is invalid, or the result would point to a non-integer subcarrier index. fr Frequency range. ssb_scs SS/PBCH block subcarrier spacing. common_scs Higher layer parameter subCarrierSpacingCommon as per TS38.331 MIB. offset_to_pointA Offset to Point A (see here for more information). subcarrier_offset Subcarrier offset (see here for more information). The index of the lowest subcarrier of the SS/PBCH block.
References is_scs_valid, FR1, scs_to_khz, srsgnb::bounded_integer< Integer, MIN_VALUE, MAX_VALUE >::is_valid, srsgnb::ssb_subcarrier_offset::is_valid, NRE.
Referenced by srsgnb::ssb_processor_impl::process.
ssb_pattern_case srsgnb::ssb_get_ssb_pattern(subcarrier_spacing ssb_scs, unsigned dl_arfcn)
Calculates SSB pattern from SSB subcarrier spacing and DL ARFCN.
uint8_t srsgnb::ssb_get_L_max(subcarrier_spacing ssb_scs, unsigned dl_arfcn)
Calculates L_max, ie max number of SSB occasions per SSB period. Possible values are {4, 8, 64}.
See TS 38.213, Section 4.1. ssb_scs SSB Subcarrier Spacing. dl_arfcn DL ARFCN. L_max value.
crb_interval srsgnb::get_ssb_crbs(subcarrier_spacing ssb_scs, subcarrier_spacing scs_common, ssb_offset_to_pointA offset_to_pA, ssb_subcarrier_offset k_ssb)
Calculate the CRBs (with reference to SCS common grid) where the SSB is allocated.
ssb_scs is the SSB Sub-Carrier Spacing, as per TS 38.213, Section 4.1. scs_common is the Sub-Carrier Spacing of the Initial DL BWP. offset_to_pA is the OffsetToPointA, , as per TS 38.211, Section 4.4.4.2. k_ssb is the SSB subcarrier offset, or k_ssb, as per TS 38.211, Section 7.4.3.1. The CRB interval (with reference to SCS common grid) where the SSB is allocated.
unsigned srsgnb::ssb_periodicity_to_value(ssb_periodicity periodicity)
Converts the SSB periodicity property to its corresponding value in milliseconds.
Referenced by schedule_ssb.
subcarrier_spacing srsgnb::to_subcarrier_spacing(ssb_pattern_case pattern_case)
Returns the subcarrier spacing corresponding to an SS/PBCH block pattern.
References A, B, C, D, E.
Referenced by srsgnb::ofdm_slot_modulator_impl::modulate, srsgnb::ssb_processor_impl::process.
frequency_range srsgnb::to_frequency_range(ssb_pattern_case pattern_case)
Returns the frequency range corresponding to an SS/PBCH block pattern.
References invalid, D, FR1, FR2.
Referenced by srsgnb::ssb_processor_impl::process.
constexpr bool srsgnb::is_scs_valid(subcarrier_spacing scs)
Check if SCS value is valid.
Referenced by get_max_Nprb, ssb_get_k_first, is_scs_valid, scs_to_khz.
constexpr bool srsgnb::is_scs_valid(subcarrier_spacing scs, frequency_range fr)
Checks whether the provided SCSFR pair is valid.
References is_scs_valid, FR2, FR1.
constexpr unsigned srsgnb::to_numerology_value(subcarrier_spacing scs)
Convert SCS to numerology index ( $\mu$).
Referenced by srsgnb::cyclic_prefix::is_valid, srsgnb::cyclic_prefix::get_length, srsgnb::phy_time_unit::to_Ta, get_max_Nprb, scs_to_khz, get_nof_slots_per_subframe, srsgnb::fapi_adaptor::fapi_to_mac_time_msg_translator::on_slot_indication, lower_phy_factory_generic::create, srsgnb::processor_pool_repository< T >::insert, slot_is_dl, srsgnb::cell_resource_allocator::slot_indication, get_msg3_delay.
constexpr unsigned srsgnb::scs_to_khz(subcarrier_spacing scs)
Converts SCS into integer in kHz.
References is_scs_valid, to_numerology_value.
Referenced by srsgnb::sampling_rate::is_valid, srsgnb::sampling_rate::get_dft_size, to_sampling_rate_Hz, get_rb_bw_khz, ssb_get_k_first, srsgnb::srs_du::ssb_freq_position_generator::find_M_raster, srsgnb::srs_du::ssb_freq_position_generator::get_next_ssb_location, srsgnb::ofdm_symbol_demodulator_impl::demodulate, srsgnb::ofdm_symbol_modulator_impl::modulate, srsgnb::ofdm_prach_demodulator_impl::demodulate, srsgnb::phase_compensation_lut::phase_compensation_lut.
constexpr subcarrier_spacing srsgnb::to_subcarrier_spacing(unsigned numerology)
Convert numerology index ( $\mu$) to SCS.
constexpr unsigned srsgnb::get_nof_slots_per_subframe(subcarrier_spacing scs)
Calculates number of slots per subframe.
References to_numerology_value.
Referenced by srsgnb::ofdm_slot_modulator_impl::modulate, srsgnb::phase_compensation_lut::phase_compensation_lut.
constexpr uint16_t srsgnb::to_number(rlc_um_sn_size sn_size)
constexpr uint16_t srsgnb::to_number(rlc_am_sn_size sn_size)
Converts sequence number field to numeric its value.
sn_size sequence number size numeric value of the sequence number field
constexpr uint32_t srsgnb::cardinality(uint16_t sn_size)
Returns the value range of the sequence numbers.
sn_size Length of the sequence number field in bits cardinality of sn_size
Referenced by window_size.
constexpr uint32_t srsgnb::window_size(uint16_t sn_size)
Returns the UM_Window_Size and AM_Window_Size Ref: 3GPP TS 38.322 Sec. 7.2.
sn_size Length of the sequence number field in bits size of the window
References cardinality.
constexpr unsigned srsgnb::to_number(rlc_dc_field dc)
constexpr uint16_t srsgnb::to_number(rlc_si_field si_field)
constexpr uint16_t srsgnb::to_number(rlc_control_pdu_type type)
std::unique_ptr< rlc_entity > srsgnb::create_rlc_entity(const rlc_entity_creation_message &msg)
Creates an instance of a RLC bearer.
search_space_id srsgnb::to_search_space_id(unsigned ss_id)
bool srsgnb::is_search_space_valid(search_space_id ss_id)
constexpr bwp_id_t srsgnb::to_bwp_id(std::underlying_type_t< bwp_id_t > value)
Converts integer value to BWP-Id".
Referenced by srsgnb::ue_cell_configuration::get_dl_search_spaces.
unsigned srsgnb::to_symbol_index(dmrs_typeA_position pos)
prb_bitmap& srsgnb::operator|=(prb_bitmap &prb_bitmap, const prb_interval &grant)
prb_bitmap srsgnb::convert_rbgs_to_prbs(const rbg_bitmap &rbgs, crb_interval bwp_rbs, nominal_rbg_size P)
Converts RBG bitmap to PRB bitmap given a BWP PRB dimensions and the nominal RBG-size. See TS 38.214, Sections 5.1.2.2.1 and 6.1.2.2.1.
References get_rbg_size, srsgnb::interval< T >::length, srsgnb::bounded_bitset< N, reversed >::find_lowest, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::fill.
unsigned srsgnb::to_nominal_rbg_size_value(nominal_rbg_size sz)
nominal_rbg_size srsgnb::get_nominal_rbg_size(unsigned bwp_nof_prb, bool config_1_or_2)
Calculates Nominal RBG size (P) based on the BWP number of PRBs and configuration type. See TS 38.214, Table 5.1.2.2.1-1 and 6.1.2.2.1-1.
unsigned srsgnb::get_nof_rbgs(crb_interval bwp_rb_dims, nominal_rbg_size P)
Calculates the total number of RBGs for a bandwidth part. See TS 38.214, Sections 5.1.2.2.1 and 6.1.2.2.1.
References divide_ceil, srsgnb::interval< T >::length.
Referenced by get_rbg_size.
unsigned srsgnb::get_nof_rbgs(crb_interval bwp_rb_dims, bool config1_or_2)
unsigned srsgnb::get_rbg_size(crb_interval bwp_rbs, nominal_rbg_size P, uint32_t rbg_idx)
Calculates size of indexed RBG in number of RBs. See TS 38.214, Sections 5.1.2.2.1 and 6.1.2.2.1.
References get_nof_rbgs.
Referenced by convert_rbgs_to_prbs.
std::unique_ptr< mac_scheduler > srsgnb::create_scheduler(sched_configuration_notifier &config_notifier)
Create L2 scheduler object.
std::unique_ptr< sdap_entity > srsgnb::create_sdap_entity()
Creates an instance of a SDAP entity interface.
Factories are at a low level point of abstraction, as such, they are the "only" (best effort) objects that depend on concrete class implementations instead of interfaces, intrinsically giving them tight coupling to the objects being created. Keeping this coupling in a single file, is the best, as the rest of the code can be kept decoupled.
Referenced by create_sdap.
std::unique_ptr< sdap_pdu_handler > srsgnb::create_sdap(sdap_sdu_rx_notifier &listener)
Creates an instance of a SDAP interface.
Factories are at a low level point of abstraction, as such, they are the "only" (best effort) objects that depend on concrete class implementations instead of interfaces, intrinsically giving them tight coupling to the objects being created. Keeping this coupling in a single file, is the best, as the rest of the code can be kept decoupled.
References create_sdap_entity.
coro_handle<noop_coroutine_promise> srsgnb::noop_coroutine() noexcept
auto srsgnb::launch_async(Args &&... args) -> typename detail::future_of< FunT >
Creates coroutine frame and launches task if eager.
Referenced by srsgnb::srs_cu_cp::f1ap_cu_impl::handle_ue_context_setup_request, srsgnb::srs_cu_cp::f1ap_cu_impl::handle_ue_context_release_command, srsgnb::srs_cu_cp::f1ap_cu_impl::handle_ue_context_modification, srsgnb::srs_du::f1ap_du_impl::handle_ue_creation_request, srsgnb::srs_du::f1ap_du_impl::handle_ue_context_modification, srsgnb::srs_sched_config_adapter::handle_ue_deletion_request, srsgnb::mac_dl_processor::add_ue, srsgnb::mac_dl_processor::remove_ue, srsgnb::mac_dl_processor::reconfigure_ue.
auto srsgnb::launch_async(FunT &&f) -> typename detail::future_of< FunT >
Creates coroutine frame and launches task if eager.
auto srsgnb::execute_on(TaskExecutor &exec)
Awaiter that switches to execution context provided by given executor.
Referenced by srsgnb::mac_dl_processor::add_ue, srsgnb::mac_dl_processor::remove_ue, srsgnb::mac_dl_processor::reconfigure_ue.
auto srsgnb::defer_to(TaskExecutor &exec)
Awaiter that defers continuation to execution context provided by given executor.
auto srsgnb::offload_to_executor(DispatchTaskExecutor &dispatch_exec, ResumeTaskExecutor &resume_exec, Callable &&callable)
Returns an awaitable that performs a task in a "dispatch_exec" executor, and resumes in "resume_exec" executor. Note: This is a specialization for tasks with non-void return values. dispatch_exec task executor where given task is going to run. resume_exec task executor where coroutine will resume once the task is run. callable task to run. awaitable.
std::enable_if_t<std::is_same<ReturnType, void>::value, async_task<void> > srsgnb::dispatch_and_resume_on(DispatchTaskExecutor &dispatch_exec, CurrentTaskExecutor &return_exec, Callable &&callable)
std::enable_if_t<not std::is_same<ReturnType, void>::value, async_task<ReturnType> > srsgnb::dispatch_and_resume_on(DispatchTaskExecutor &dispatch_exec, CurrentTaskExecutor &return_exec, Callable &&callable)
std::enable_if_t<std::is_trivially_copyable<T>::value && (sizeof(T) <= sizeof(T*))> srsgnb::do_not_optimize(T const &value)
This function forbids the compiler from optimizing away expressions without side-effects.
std::enable_if_t<!std::is_trivially_copyable<T>::value || (sizeof(T) > sizeof(T*))> srsgnb::do_not_optimize(T const &value)
std::enable_if_t<std::is_trivially_copyable<T>::value && (sizeof(T) <= sizeof(T*))> srsgnb::do_not_optimize(T &value)
std::enable_if_t<!std::is_trivially_copyable<T>::value || (sizeof(T) > sizeof(T*))> srsgnb::do_not_optimize(T &value)
bool srsgnb::srsgnb_terminate(const char *fmt, Args &&... args) noexcept
Command to terminate application with an error message, ensuring first that the log is flushed. Attribute noinline is used to signal to the compiler that this path should rarely occur and therefore doesn't need to get optimized.
Referenced by report_fatal_error, srsgnb::low_papr_sequence_generator_impl::r_uv_arg, srsgnb::pucch_helper::compute_group_sequence, prime_greater_than.
void srsgnb::report_fatal_error(const char *reason_fmt, Args &&... args) noexcept
Reports a fatal error and handles the application shutdown. This function is intended to be used for error conditions that aren't neither caught by the compiler nor possible to handle by the application at runtime.
References srsgnb_terminate.
Referenced by get_message_type_str.
std::unique_ptr<task_executor> srsgnb::make_task_executor(task_worker &w)
const char* srsgnb::to_c_str(fmt::basic_memory_buffer< char, N > &mem_buffer)
static constexpr cf_t srsgnb::COMPLEX_J(0, 1)
Defines the complex imaginary unit.
Referenced by srsgnb::low_papr_sequence_generator_impl::cexp.
constexpr unsigned srsgnb::divide_ceil(unsigned num, unsigned den)
Performs an integer division rounding up.
num Provides the numerator. den Provides the denominator. The result of the operation.
Referenced by srsgnb::bounded_bitset< uci_constants::MAX_NOF_HARQ_ACK_BITS >::to_hex, srsgnb::ldpc_segmenter_impl::compute_rm_length, srsgnb::ldpc_segmenter_impl::segment, srsgnb::prach_detector_simple_impl::detect, srsgnb::rx_softbuffer_codeblock_pool::rx_softbuffer_codeblock_pool, srsgnb::vrb_to_prb_mapper::create_interleaved_coreset0, srsgnb::vrb_to_prb_mapper::create_interleaved_common, srsgnb::vrb_to_prb_mapper::create_interleaved_other, get_nof_rbgs, tbs_calculator_table_find_smallest_not_less_than, srsgnb::bit_decoder::advance_bits.
constexpr unsigned srsgnb::pow2(unsigned power)
Calculates the integer power of 2.
power Indicates the power of 2 to calculate. The result of the operation.
Referenced by srsgnb::low_papr_sequence_collection::low_papr_sequence_collection, srsgnb::cyclic_prefix::get_length, srsgnb::phy_time_unit::to_Ta, srsgnb::pusch_demodulator_impl::demodulate, srsgnb::csi_rs_processor_impl::generate_sequence, srsgnb::dmrs_pdcch_processor_impl::c_init, srsgnb::dmrs_pdsch_processor_impl::sequence_generation, srsgnb::dmrs_pucch_processor_format2_impl::c_init, tbs_calculator_pdsch_get_scaling_factor.
constexpr float srsgnb::abs_sq(cf_t x)
Calculates the squared modulus of a complex value.
x Complex value. The squared absolute of the given value, i.e. $\abs{x}^2=x\cdot\conj{x}=\Re(x)^2+\Im(x)^2$.
constexpr Integer srsgnb::log2_ceil(Integer value)
Calculates $\left \lceil log_2(n) \right \rceil$.
Integer Any unsigned integer type. value Parameter $n$. The result of the calculation if value is not zero. Otherwise 0.
Referenced by dci_1_0_p_rnti_pack, dci_1_0_si_rnti_pack, dci_1_0_ra_rnti_pack.
float srsgnb::convert_dB_to_amplitude(float value)
Converts a value in decibels to linear amplitude ratio.
value is in decibels the resultant amplitude ratio
Referenced by srsgnb::pdcch_processor_impl::process, srsgnb::pdsch_processor_impl::modulate, srsgnb::pdsch_processor_impl::put_dmrs, srsgnb::ssb_processor_impl::process.
float srsgnb::convert_dB_to_power(float value)
Converts a value in decibels to linear power ratio.
value is in decibels the resultant power ratio
float srsgnb::convert_amplitude_to_dB(float value)
Converts a linear amplitude ratio to decibels.
value is the linear amplitude the resultant decibels
float srsgnb::convert_power_to_dB(float value)
Converts a linear power ratio to decibels.
value is the linear power the resultant decibels
Referenced by srsgnb::channel_estimate::get_noise_variance_dB, srsgnb::channel_estimate::get_rsrp_dB, srsgnb::channel_estimate::get_epre_dB, srsgnb::channel_estimate::get_snr_dB, srsgnb::prach_detector_simple_impl::detect.
unsigned srsgnb::prime_greater_than(unsigned n)
Finds the smallest prime number greater than n.
Only works for prime numbers not larger than 3299.
References srsgnb_terminate.
unsigned srsgnb::prime_lower_than(unsigned n)
Finds the biggest prime number lesser than n.
Only works for prime numbers not larger than 3299.
Referenced by srsgnb::low_papr_sequence_generator_impl::r_uv_arg_mprb.
uint8_t srsgnb::reverse_byte(uint8_t byte)
Reverses the bits of a given byte.
Referenced by srsgnb::pseudo_random_generator_impl::apply_xor_byte.
constexpr const T& srsgnb::clamp(const T &value, const T &lower_bound, const T &upper_bound, CompareLess comp)
Ensures a value is between the given bounds, according to a specified order relation.
T Class of the value to clamp. A strict order relation (less than) should be definable between elements of class T. CompareLess Class of the comparison object (see below). value The value to clamp. lower_bound Minimum value after clamping. upper_bound Maximum value after clamping. comp Comparison function object implementing an order relation between elements of T. The signature should be equivalent to bool comp(const T& a, const T& b) and should return true if a < b (according to any order relation in T), false otherwise. A reference to lower_bound if value < lower_bound; a reference to upper_bound if upper_bound < value; a reference to value itself otherwise.
Referenced by clamp, srsgnb::fapi_adaptor::phy_to_fapi_results_event_translator::on_new_prach_results.
constexpr const T& srsgnb::clamp(const T &value, const T &lower_bound, const T &upper_bound)
Ensures a value is between the given bounds, according to the default order relation.
See the documentation for the extended form for more information.
References clamp.
size_t srsgnb::compute_host_nof_hardware_threads()
Computes the number of threads that are usable in the given host.
const char * srsgnb::this_thread_name()
Get caller thread name.
Referenced by print_this_thread_priority.
void srsgnb::print_this_thread_priority()
Print caller thread priority.
References this_thread_name.
obj_id_comparator<GetId> srsgnb::make_id_comparator(GetId &&g)
void srsgnb::apply_addmodremlist_diff(const AddModList &src_list, const AddModList &add_diff_list, const RemoveList &rm_diff_list, AddModList &target_list, const GetId &id_func)
Apply toAddModList/toRemoveList changes src_list original list of rrc fields add_diff_list added/modified elements rm_diff_list removed elements target_list resulting list. (Can be same as src_list)
void srsgnb::apply_addmodremlist_diff(AddModList &src_and_dest_list, const AddModList &add_diff_list, const RemoveList &rm_diff_list, const GetId &id_func)
sched_cell_configuration_request_message srsgnb::make_sched_cell_config_req(du_cell_index_t cell_index, const du_cell_config &du_cfg, unsigned sib1_payload_size)
Derives Scheduler Cell Configuration from DU Cell Configuration.
References srsgnb::du_cell_config::dl_cfg_common, srsgnb::du_cell_config::scs_common, srsgnb::du_cell_config::coreset0_idx, srsgnb::du_cell_config::searchspace0_idx.
Referenced by make_mac_cell_config.
mac_cell_creation_request srsgnb::make_mac_cell_config(du_cell_index_t cell_index, const du_cell_config &du_cfg)
Derives MAC Cell Configuration from DU Cell Configuration.
References srsgnb::du_cell_config::scs_common, srsgnb::du_cell_config::cell_barred, srsgnb::du_cell_config::intra_freq_resel, make_sched_cell_config_req.
nr_cell_global_identity srsgnb::cgi_from_asn1(const asn1::f1ap::nrcgi_s &asn1_cgi)
Converts ASN.1 CGI typo into internal struct. It also performs the byte to MCC/MNC conversion.
asn1_cgi The ASN.1 encoded NR-CGI. The CGI converted to flat internal struct.
References ngap_plmn_to_mccmnc, srsgnb::nr_cell_global_identity::mnc, srsgnb::nr_cell_global_identity::plmn, srsgnb::nr_cell_global_identity::nci.
Referenced by srsgnb::srs_cu_cp::f1ap_du_processor_adapter::on_create_ue, srsgnb::srs_cu_cp::du_processor::handle_f1_setup_request, srsgnb::srs_cu_cp::f1ap_cu_impl::handle_initial_ul_rrc_message.
const char* srsgnb::get_cause_str(const asn1::f1ap::cause_c &cause)
Get string with F1AP error cause.
Referenced by srsgnb::srs_du::f1ap_du_setup_procedure::create_f1_setup_result.
const char* srsgnb::get_message_type_str(const asn1::f1ap::f1_ap_pdu_c &pdu)
Extracts message type.
References report_fatal_error.
Referenced by srsgnb::srs_du::f1ap_du_impl::handle_message.
expected<uint8_t> srsgnb::get_transaction_id(const asn1::f1ap::init_msg_s &out)
Extracts transaction id of Initiating message.
Referenced by get_transaction_id, srsgnb::srs_du::f1ap_du_impl::handle_message, srsgnb::srs_du::f1ap_du_impl::handle_successful_outcome, srsgnb::srs_du::f1ap_du_impl::handle_unsuccessful_outcome.
expected<uint8_t> srsgnb::get_transaction_id(const asn1::f1ap::successful_outcome_s &out)
Extracts transaction id of Successful Outcome message.
expected<uint8_t> srsgnb::get_transaction_id(const asn1::f1ap::unsuccessful_outcome_s &out)
Extracts transaction id of Unsuccessful Outcome message.
expected<uint8_t> srsgnb::get_transaction_id(const asn1::f1ap::f1_ap_pdu_c &pdu)
Extracts transaction id of F1AP PDU.
References get_transaction_id.
sched_ue_creation_request_message srsgnb::make_ue_creation_request(const mac_ue_create_request_message &in)
Convert MAC UE Create Request Message to Scheduler UE Create Request.
sched_ue_reconfiguration_message srsgnb::make_ue_reconfiguration_request(const mac_ue_reconfiguration_request_message &in)
Convert MAC UE Reconfiguration Request Message to Scheduler UE Reconfiguration Request.
rnti_t srsgnb::decode_crnti_ce(byte_buffer_view payload)
Decode C-RNTI MAC CE.
References to_rnti.
Referenced by srsgnb::pdu_rx_handler::handle_crnti_ce.
lcg_bsr_report srsgnb::decode_sbsr(byte_buffer_view payload)
Decode Short BSR.
Referenced by srsgnb::pdu_rx_handler::handle_mac_ce.
long_bsr_report srsgnb::decode_lbsr(bsr_format format, byte_buffer_view payload)
Decode Long BSR.
References srsgnb::long_bsr_report::list.
Referenced by srsgnb::pdu_rx_handler::handle_mac_ce.
uint32_t srsgnb::buff_size_field_to_bytes(size_t buff_size_index, bsr_format format)
Converts the buffer size field of a BSR (5 or 8-bit Buffer Size field) into Nof Bytes. buff_size_index The buffer size field contained in the MAC PDU. format The BSR format that determines the buffer size field length. The actual buffer size level in Bytes. Converts the buffer size field of a BSR (5 or 8-bit Buffer Size field) into Bytes. buff_size_index The buffer size field contained in the MAC PDU. format The BSR format that determines the buffer size field length. The actual buffer size level in Bytes.
Referenced by make_sched_lcg_report.
ul_bsr_lcg_report srsgnb::make_sched_lcg_report(const lcg_bsr_report &ul_bsr_ce, bsr_format bsr_format)
Converts BSR MAC CE (See 38.321, 6.1.3.1) to Scheduler UL BSR event type.
References buff_size_field_to_bytes.
Referenced by srsgnb::pdu_rx_handler::handle_mac_ce.
const char* srsgnb::get_cause_str(const asn1::ngap::cause_c &cause)
Get string with NGAP error cause.
const char* srsgnb::get_message_type_str(const asn1::ngap::ngap_pdu_c &pdu)
Extracts message type.
References report_fatal_error.
std::unique_ptr<pdcch_processor> srsgnb::create_pdcch_processor(pdcch_processor_config_t &config)
Creates a generic PDCCH processor.
unsigned srsgnb::get_rg_subc_mask_reference(const bounded_bitset< MAX_RB > &prb_mask)
Helper function to calculate the subcarrier index reference for a resource grid allocation mask.
The lowest subcarrier index of the lowest selected PRB.
References srsgnb::bounded_bitset< N, reversed >::find_lowest, NRE.
Referenced by srsgnb::pdcch_modulator_impl::map, srsgnb::dmrs_pdcch_processor_impl::map, srsgnb::dmrs_pdsch_processor_impl::map.
static_vector<bool, MAX_RB * NRE> srsgnb::get_rg_subc_mask(const bounded_bitset< MAX_RB > &prb_mask, const std::array< bool, NRE > &prb_mask_re)
Helper function to create an allocation mask from a PRB mask and a RE mask.
Creates an allocation where PRB are selected from prb_mask and the RE within the PRB are selected using prb_mask_re. The resultant mask is relative to to the lowest subcarrier of the lowest selected PRB. In other words, the first element of the resultant mask coincides with the lowest subcarrier of the first selected PRB in prb_mask. prb_mask Selected PRB for the transmission. prb_mask_re DMRS pattern within a PRB. The resultant mask. get_rg_subc_mask_reference
References srsgnb::bounded_bitset< N, reversed >::find_lowest, srsgnb::bounded_bitset< N, reversed >::find_highest, NRE, srsgnb::span< T >::subspan, srsgnb::bounded_bitset< N, reversed >::test, srsgnb::span< T >::begin.
Referenced by srsgnb::pdcch_modulator_impl::map, srsgnb::dmrs_pdcch_processor_impl::map, srsgnb::dmrs_pdsch_processor_impl::map.
std::unique_ptr< rx_softbuffer_pool > srsgnb::create_rx_softbuffer_pool(const rx_softbuffer_pool_description &config)
std::unique_ptr< low_papr_sequence_generator > srsgnb::create_low_papr_sequence_generator()
Creates a generic low PAPR sequence generator.
void srsgnb::dmrs_sequence_generate(span< cf_t > sequence, pseudo_random_generator &prg, float amplitude, unsigned reference_point_k_rb, unsigned nof_dmrs_per_rb, const bounded_bitset< MAX_RB > &rb_mask)
Helper function to generate DMRS sequences.
This function generates DMRS sequences based on a pseudo-random sequence generation. It generates nof_dmrs_per_rb for every active resource block given in rb_mask and skips the nof_dmrs_per_rb for every inactive resource block. sequence Provides the destination storage for the generated sequence. prg Provides the pseudo-random generator to use. amplitude Provides the sequence amplitude. reference_point_k_rb Indicates the RB index for reference. nof_dmrs_per_rb Indicates the number of DMRS to generate per active RB. rb_mask Indicates the active resource blocks. It assumes that the pseudo-random generator is initialized. The sequence size must be consistent with the number of active RBs and the number of DMRS per RB.
References srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::test, srsgnb::pseudo_random_generator::advance, srsgnb::pseudo_random_generator::generate, srsgnb::span< T >::first, srsgnb::span< T >::last, srsgnb::span< T >::size.
Referenced by srsgnb::dmrs_pdcch_processor_impl::sequence_generation, srsgnb::dmrs_pdsch_processor_impl::sequence_generation.
bool srsgnb::string_to_mcc(std::string str, uint16_t *mcc)
Convert between string and BCD-coded MCC. Digits are represented by 4-bit nibbles. Unused nibbles are filled with 0xf. MCC 001 results in 0xf001
bool srsgnb::mcc_to_string(uint16_t mcc, std::string *str)
bool srsgnb::bytes_to_mcc(const uint8_t *bytes, uint16_t *mcc)
Convert between array of bytes and BCD-coded MCC. Digits are represented by 4-bit nibbles. Unused nibbles are filled with 0xf. MCC 001 results in 0xf001
bool srsgnb::mcc_to_bytes(uint16_t mcc, uint8_t *bytes)
std::string srsgnb::mcc_bytes_to_string(uint8_t *mcc_bytes)
bool srsgnb::string_to_mnc(std::string str, uint16_t *mnc)
Convert between string and BCD-coded MNC. Digits are represented by 4-bit nibbles. Unused nibbles are filled with 0xf. MNC 001 results in 0xf001 MNC 01 results in 0xff01
bool srsgnb::mnc_to_string(uint16_t mnc, std::string *str)
bool srsgnb::bytes_to_mnc(const uint8_t *bytes, uint16_t *mnc, uint8_t len)
Convert between array of bytes and BCD-coded MNC. Digits are represented by 4-bit nibbles. Unused nibbles are filled with 0xf. MNC 001 results in 0xf001 MNC 01 results in 0xff01
bool srsgnb::mnc_to_bytes(uint16_t mnc, uint8_t *bytes, uint8_t *len)
bool srsgnb::mnc_to_bytes(uint16_t mnc, Vec &vec)
std::string srsgnb::mnc_bytes_to_string(uint8_t *mnc_bytes, uint32_t nof_bytes)
std::string srsgnb::mnc_bytes_to_string(Vec mnc_bytes)
void srsgnb::ngap_plmn_to_mccmnc(uint32_t plmn, uint16_t *mcc, uint16_t *mnc)
Convert PLMN to BCD-coded MCC and MNC. Digits are represented by 4-bit nibbles. Unused nibbles are filled with 0xf. MNC 001 represented as 0xf001 MNC 01 represented as 0xff01 PLMN encoded as per TS 38.413 sec 9.3.3.5
Referenced by cgi_from_asn1.
void srsgnb::ngap_mccmnc_to_plmn(uint16_t mcc, uint16_t mnc, uint32_t *plmn)
Convert BCD-coded MCC and MNC to PLMN. Digits are represented by 4-bit nibbles. Unused nibbles are filled with 0xf. MNC 001 represented as 0xf001 MNC 01 represented as 0xff01 PLMN encoded as per TS 38.413 sec 9.3.3.5
void srsgnb::log_proc_started(srslog::basic_logger &logger, du_ue_index_t ue_index, rnti_t rnti, const char *proc_name)
void srsgnb::log_proc_started(srslog::basic_logger &logger, du_ue_index_t ue_index, const char *proc_name)
void srsgnb::log_proc_completed(srslog::basic_logger &logger, du_ue_index_t ue_index, rnti_t rnti, const char *proc_name)
void srsgnb::log_proc_failure(srslog::basic_logger &logger, du_ue_index_t ue_index, const char *proc_name, const char *cause_fmt="", Args &&... args)
void srsgnb::log_proc_failure(srslog::basic_logger &logger, du_ue_index_t ue_index, rnti_t rnti, const char *proc_name, const char *cause_fmt="", Args &&... args)
void srsgnb::log_proc_event(srslog::basic_logger &logger, du_ue_index_t ue_index, const char *proc_name, const char *cause_fmt, Args &&... args)
void srsgnb::log_ue_event(srslog::basic_logger &logger, const ue_event_prefix &ue_prefix, const char *cause_fmt, Args &&... args)
void srsgnb::log_ue_proc_event(srslog::log_channel &log_ch, const ue_event_prefix &ue_prefix, const char *proc_name, const char *cause_fmt, Args &&... args)
void srsgnb::log_ul_pdu(srslog::basic_logger &logger, du_ue_index_t ue_index, rnti_t rnti, du_cell_index_t cell_index, const char *ch, const char *cause_fmt, Args &&... args)
void srsgnb::log_ul_pdu(srslog::basic_logger &logger, rnti_t rnti, du_cell_index_t cc, const char *cause_fmt, Args &&... args)
constexpr size_t srsgnb::rlc_am_pdu_header_min_size(rlc_am_sn_size sn_size)
constexpr size_t srsgnb::rlc_am_pdu_header_max_size(rlc_am_sn_size sn_size)
bool srsgnb::rlc_am_read_data_pdu_header(const byte_buffer &pdu, const rlc_am_sn_size sn_size, rlc_am_pdu_header *header)
bool srsgnb::rlc_am_write_data_pdu_header(const rlc_am_pdu_header &header, byte_buffer &pdu)
constexpr size_t srsgnb::rlc_um_pdu_header_size_no_so(rlc_um_sn_size sn_size)
constexpr size_t srsgnb::rlc_um_pdu_header_size_with_so(rlc_um_sn_size sn_size)
bool srsgnb::rlc_um_read_data_pdu_header(const byte_buffer_view &pdu, const rlc_um_sn_size sn_size, rlc_um_pdu_header *header)
size_t srsgnb::rlc_um_nr_packed_length(const rlc_um_pdu_header &header)
bool srsgnb::rlc_um_write_data_pdu_header(const rlc_um_pdu_header &header, byte_buffer &pdu)
unsigned srsgnb::nof_slots_per_tdd_period(const tdd_ul_dl_config_common &cfg)
Calculates number of slots, using TDD reference SCS, of the TDD UL-DL configuration.
References srsgnb::tdd_ul_dl_pattern::dl_ul_tx_period_nof_slots.
Referenced by slot_is_dl.
bool srsgnb::slot_is_dl(const tdd_ul_dl_config_common &cfg, slot_point slot)
Checks whether provided slot corresponds to a DL slot.
References nof_slots_per_tdd_period, srsgnb::slot_point::numerology, to_numerology_value, srsgnb::tdd_ul_dl_config_common::ref_scs, set_slot_numerology, srsgnb::tdd_ul_dl_pattern::dl_ul_tx_period_nof_slots, srsgnb::tdd_ul_dl_pattern::nof_dl_slots, srsgnb::tdd_ul_dl_pattern::nof_dl_symbols.
Referenced by slot_is_ul.
bool srsgnb::slot_is_ul(const tdd_ul_dl_config_common &cfg, slot_point slot)
Checks whether provided slot corresponds to an UL slot.
References slot_is_dl.
crb_interval srsgnb::get_carrier_rb_dims(const scs_specific_carrier &carrier_cfg)
Derives Carrier CRB limits from scs-SpecificCarrier.
References srsgnb::scs_specific_carrier::offset_to_carrier, srsgnb::scs_specific_carrier::carrier_bandwidth.
bwp_rb_bitmap srsgnb::operator|(const bwp_rb_bitmap &lhs, const Other &rhs)
unsigned srsgnb::get_msg3_delay(const pusch_time_domain_resource_allocation &pusch_td_res_alloc, subcarrier_spacing pusch_scs)
Get MSG3 Delay. pusch_td_res_alloc PUSCH-TimeDomainResourceAllocation. pusch_scs SCS used by initial UL BWP. Msg3 delay in number of slots.
References to_numerology_value, srsgnb::pusch_time_domain_resource_allocation::k2.
Referenced by srsgnb::ra_scheduler::run_slot, srsgnb::ra_scheduler::schedule_rar, srsgnb::ra_scheduler::fill_rar_grant.
uint16_t srsgnb::get_ra_rnti(const rach_indication_message &rach_ind, bool is_sul=false)
Get RA-RNTI based on PRACH parameters. See 38.321, 5.1.3 - Random Access Preamble transmission
References srsgnb::rach_indication_message::symbol_index, srsgnb::slot_point::slot_index.
subcarrier_spacing srsgnb::ssb_case_to_scs(ssb_pattern_case ssb_case)
Derive SSB Subcarrier Spacing from SSB pattern case.
References A, B, C, D, E.
void srsgnb::schedule_ssb(cell_slot_resource_allocator &slot_allocator, const slot_point &sl_point, const cell_configuration &cell_cfg)
Schedule grant for SSB.
The functions schedules the SSB according to a given periodicity, depending on the frequency and SSB case slot_allocator Slot allocator object with SSB grants and DL PRBs. sl_point Slot point carrying information about current slot. cell_cfg Reference to scheduler cell configuration. This function only works for FR1, or L_max = 4 or 8.
References srsgnb::cell_slot_resource_allocator::result, srsgnb::dl_sched_result::bc, srsgnb::cell_configuration::dl_carrier, srsgnb::carrier_configuration::arfcn, FR1_MAX_FREQUENCY_ARFCN, ssb_periodicity_to_value, srsgnb::ssb_configuration::ssb_period, srsgnb::slot_point::numerology, srsgnb::slot_point::nof_slots_per_subframe, A, C, CUTOFF_FREQ_ARFCN_CASE_A_B_C, CUTOFF_FREQ_ARFCN_CASE_C_UNPAIRED, B, invalid, srsgnb::cell_slot_resource_allocator::dl_res_grid, srsgnb::cell_slot_resource_grid::fill.
Referenced by srsgnb::scheduler_impl::slot_indication.
bool srsgnb::is_pdcch_monitoring_active(slot_point sl, const search_space_configuration &ss_cfg)
Helper function to check whether a SearchSpace PDCCH is monitored by the UE for a given slot.
sl Slot in which the SearchSpace is being monitored. ss_cfg SearchSpace configuration. true if the SearchSpace is being monitored. False, otherwise.
References srsgnb::search_space_configuration::monitoring_slot_period, srsgnb::search_space_configuration::monitoring_slot_offset, srsgnb::search_space_configuration::duration.
Referenced by srsgnb::ra_scheduler::run_slot.
prb_index_list srsgnb::cce_to_prb_mapping(const bwp_configuration &bwp_cfg, const coreset_configuration &cs_cfg, pci_t pci, aggregation_level aggr_lvl, unsigned ncce)
std::unique_ptr< scheduler_policy > srsgnb::create_scheduler_strategy(const scheduler_strategy_params &params)
unsigned srsgnb::prb_to_crb(const bwp_configuration &bwp_cfg, unsigned prb)
Convert PRB within a BWP into a Common RB, which use pointA as reference point. The CRB and PRB are assumed to have the same numerology of the provided BWP configuration. The existence of a CORESET#0 may also affect the rules for CRB<->PRB conversion.
bwp_cfg BWP configuration of the respective PRB. prb PRB to be converted to CRB. Calculated CRB.
References srsgnb::bwp_configuration::crbs, srsgnb::interval< T >::length.
Referenced by srsgnb::pdcch_scheduler_impl::pdcch_slot_allocator::allocate_cce, prb_to_crb.
crb_interval srsgnb::prb_to_crb(const bwp_configuration &bwp_cfg, prb_interval prbs)
Convert PRBs within a BWP into Common RBs, which use pointA as reference point. CRBs and PRBs are assumed to have the same numerology of the provided BWP configuration. bwp_cfg BWP configuration of the respective PRB interval. prbs PRBs to be converted to CRBs. Calculated CRB interval.
References prb_to_crb.
unsigned srsgnb::crb_to_prb(const bwp_configuration &bwp_cfg, unsigned crb)
Convert CRB within a BWP into a PRB. The CRB and PRB are assumed to use the same numerology as reference.
bwp_cfg BWP configuration of the respective CRB. crb CRB to be converted to PRB. Calculated PRB.
References srsgnb::bwp_configuration::crbs, srsgnb::interval< T >::contains.
Referenced by srsgnb::ra_scheduler::fill_rar_grant, srsgnb::sib1_scheduler::fill_sib1_grant, crb_to_prb.
prb_interval srsgnb::crb_to_prb(const bwp_configuration &bwp_cfg, crb_interval crbs)
Convert CRBs to PRBs within a BWP. CRBs and PRBs are assumed to have the same numerology of the provided BWP configuration.
References crb_to_prb.
span<const pusch_time_domain_resource_allocation> srsgnb::get_pusch_time_domain_resource_table(const pusch_config_common &pusch_cfg)
Retrieves the time resource allocation table for PUSCH. See TS 38.214, Section 6.1.2.1.1 - Determination of the resource allocation table to be used for PUSCH.
References srsgnb::pusch_config_common::pusch_td_alloc_list.
Referenced by srsgnb::ra_scheduler::run_slot, srsgnb::ra_scheduler::schedule_rar.
unsigned srsgnb::get_coreset_nof_prbs(const coreset_configuration &cs_cfg)
Computes the number of RBs used to represent the CORESET.
References srsgnb::interval< T >::length, srsgnb::bounded_bitset< N, reversed >::count.
Referenced by get_coreset0_crbs, get_coreset_nof_cces.
unsigned srsgnb::get_coreset_start_crb(const coreset_configuration &cs_cfg)
Computes the lowest RB used by the CORESET.
References srsgnb::bounded_bitset< N, reversed >::to_uint64, find_first_lsb_one.
Referenced by get_coreset0_crbs.
crb_interval srsgnb::get_coreset0_crbs(const pdcch_config_common &pdcch_cfg)
Computes the CRB interval that delimits CORESET#0.
References get_coreset_start_crb, srsgnb::pdcch_config_common::coreset0, get_coreset_nof_prbs.
unsigned srsgnb::get_coreset_nof_cces(const coreset_configuration &cs_cfg)
Calculates number of CCEs in CORESET.
References get_coreset_nof_prbs.
bool srsgnb::search_space_supports_dl_dci_format(const search_space_configuration &ss_cfg, dci_dl_format dci_fmt)
unsigned srsgnb::calculate_nof_dmrs_per_rb(const dmrs_information &dmrs)
Calculates the number of RE used for DMRS per RB in PDSCH and PUSCH transmissions.
Referenced by srsgnb::sib1_scheduler::allocate_sib1.
dmrs_information srsgnb::make_dmrs_info_common(const pdsch_config_common &pdsch_cfg, uint8_t time_resource, pci_t pci, dmrs_typeA_position dmrs_typeA_pos)
Helper factory of a default DM-RS Information object for DCI f1_0 or for when higher layer configuration parameters are not yet available. TODO: generalize to other cases (e.g. mapping type B). See TS 38.214, 5.1.6.2 - DM-RS reception procedure.
References srsgnb::pdsch_config_common::pdsch_td_alloc_list, srsgnb::pdsch_dmrs_symbol_mask_mapping_type_A_single_configuration::typeA_pos.
Referenced by srsgnb::ra_scheduler::fill_rar_grant, srsgnb::sib1_scheduler::allocate_sib1.
pdcch_type0_css_occasion_pattern1_description srsgnb::pdcch_type0_css_occasions_get_pattern1(const pdcch_type0_css_occasion_pattern1_configuration &config)
Get Type0-PDCCH CSS occasions for multiplexing pattern 1 as per TS38.213 Section 13.
The Type0-PDCCH CSS occasions are retrieved from TS38.213 Table 13-11 for FR1 and Table 13-12 for FR2. An assertion is triggered if config is not valid. config Provides the necessary parameters to calculate the occasions. A valid Type0-PDCCH CSS occasion for multiplexing pattern 1.
References srsgnb::pdcch_type0_css_occasion_pattern1_configuration::is_fr2, srsgnb::pdcch_type0_css_occasion_pattern1_configuration::ss_zero_index, srsgnb::pdcch_type0_css_occasion_pattern1_description::start_symbol, srsgnb::pdcch_type0_css_occasion_pattern1_description::MAX_NOF_OCCASIONS_PER_SLOT, srsgnb::pdcch_type0_css_occasion_pattern1_configuration::nof_symb_coreset.
Referenced by srsgnb::sib1_scheduler::precompute_sib1_n0.
pdsch_default_time_allocation_config srsgnb::pdsch_default_time_allocation_default_A_get(cyclic_prefix cp, unsigned row_index, dmrs_typeA_position dmrs_pos)
Determines the default PDSCH time-domain resource allocation A.
The time domain allocation configuration is described in TS38.214 Table 5.1.2.1.1-2 for normal cyclic prefix and TS38.214 Table 5.1.2.1.1-3 for extended cyclic prefix. cp Cyclic prefix. row_index Row index. dmrs_pos DM-RS for mapping Type A position. A valid PDSCH time-domain allocation configuration is the provided parameters are valid. Otherwise, PDSCH_DEFAULT_TIME_ALLOCATION_RESERVED.
References srsgnb::cyclic_prefix::NORMAL, srsgnb::cyclic_prefix::EXTENDED.
Referenced by pdsch_default_time_allocations_default_A_table.
span< const pdsch_time_domain_resource_allocation > srsgnb::pdsch_default_time_allocations_default_A_table(cyclic_prefix cp, dmrs_typeA_position dmrs_pos)
Determines the table of default PDSCH time-domain resource allocation A.
cp Cyclic prefix. dmrs_pos DM-RS for mapping Type A position. A list of valid PDSCH time-domain allocation configurations to choose from.
References pdsch_default_time_allocation_default_A_get, srsgnb::pdsch_default_time_allocation_config::pdcch_to_pdsch_delay, srsgnb::pdsch_default_time_allocation_config::mapping_type, srsgnb::pdsch_default_time_allocation_config::start_symbol, srsgnb::pdsch_default_time_allocation_config::duration, srsgnb::cyclic_prefix::NORMAL.
Referenced by srsgnb::ue_cell_configuration::get_pdsch_time_domain_list.
dmrs_symbol_mask srsgnb::pdsch_dmrs_symbol_mask_mapping_type_A_single_get(const pdsch_dmrs_symbol_mask_mapping_type_A_single_configuration &config)
Calculates the DMRS for PDSCH symbol mask for single duration.
It is implemented as per TS38.211 Table 5.1.2.1.1-2. Any configuration that is not covered in the table triggers an assertion.
References srsgnb::pdsch_dmrs_symbol_mask_mapping_type_A_single_configuration::typeA_pos.
pdsch_prbs_tbs srsgnb::get_nof_prbs(const prbs_calculator_pdsch_config &pdsch_config)
Computes the required number of PRBs necessary to transmit a given payload size.
This function implements the inverse procedure of the TBS calculation procedure (as per TS38.214 Section 5.1.3.2) to derive the number of PRBs from a given payload in bytes. This function only works for payload size <= 478 bytes (3824 bits). If the TBS that corresponds to input payload exceeds the maximum 478 bytes, the function is working outside its range. In that case, the function returns the max num. of PRBs such that the corresponding TBS won't exceed the max value of 478 bytes. Note that this value would not be enough to fit the payload. It is up to the caller to handle this case. pdsch_config is a struct with the PDSCH configuration to compute the num. of PRBs. Returns a struct with the number of PRBs and the corresponding TBS. If the payload_size is greater than 478 bytes (3824 bits), it returns the number of PRBs and TBS corresponding to maximum allowed payload size of 478 bytes.
References srsgnb::prbs_calculator_pdsch_config::payload_size_bytes, tbs_calculator_table_find_smallest_not_less_than, srsgnb::prbs_calculator_pdsch_config::target_code_rate, srsgnb::prbs_calculator_pdsch_config::mod_order, srsgnb::prbs_calculator_pdsch_config::nof_layers, tbs_calculator_pdsch_get_scaling_factor, srsgnb::prbs_calculator_pdsch_config::tb_scaling_field, NOF_SUBCARRIERS_PER_RB, srsgnb::prbs_calculator_pdsch_config::nof_symb_sh, srsgnb::prbs_calculator_pdsch_config::nof_dmrs_prb, srsgnb::prbs_calculator_pdsch_config::nof_oh_prb, tbs_calculator_pdsch_calculate.
Referenced by srsgnb::sib1_scheduler::allocate_sib1.
crb_interval srsgnb::find_next_empty_interval(const prb_bitmap &used_rb_bitmap, size_t start_crb_idx=0, size_t last_crb_idx=MAX_NOF_PRBS)
Finds the next contiguous range of PRBs whose respective bit in provided RB bitmap is set to zero.
used_rb_bitmap Bitmap of RBs, where 1's represent used RBs and 0's empty RBs. start_crb_idx Minimum RB index from where the search is initiated. last_crb_idx Maximum RB index (excluding) that limits the range of RBs where the search is carried out. An interval of contiguous RBs where the respective bits are set to zero. If no interval was found, an empty interval is returned.
References srsgnb::bounded_bitset< N, reversed >::find_lowest, srsgnb::bounded_bitset< N, reversed >::size.
Referenced by find_empty_interval_of_length.
crb_interval srsgnb::find_empty_interval_of_length(const prb_bitmap &used_rb_bitmap, size_t nof_rbs, uint32_t start_crb_idx=0)
Finds a range of contiguous RBs, whose value in the provided RB bitmap is set to zero. The returned range length should be at most "nof_rbs" RBs. If no range with length "nof_rbs" is found, the longest valid range of RBs set to zero in "used_rb_bitmap" is returned.
used_rb_bitmap Bitmap of RBs, where 1's represent used RBs and 0's empty RBs. nof_rbs Maximum range of RBs start_crb_idx Minimum RB index from where the search is initiated. An interval of RBs with maximum length equal to "nof_rbs".
References find_next_empty_interval, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::interval< T >::length.
Referenced by srsgnb::ra_scheduler::schedule_rar, srsgnb::sib1_scheduler::allocate_sib1.
float srsgnb::tbs_calculator_pdsch_get_scaling_factor(unsigned scaling)
Converts TB scaling field into Scaling Factor S (see Table 5.1.3.2-2, TS 38.214).
scaling is the TB scaling field, possible values are {0,1,2}. Scaling factor S corresponding to scaling.
References pow2.
Referenced by get_nof_prbs, tbs_calculator_pdsch_calculate.
unsigned srsgnb::tbs_calculator_table_find_smallest_not_less_than(unsigned nof_info_prime)
Get smallest TBS in bits (from Table 5.1.3.2-1, TS 38.214) greater than or equal to a given value.
nof_info_prime is the quantized intermediate num. of information bits, as per Section 5.1.3.2, TS 38.214. nof_info_prime must not be greater than 3824 bits. The smallest TBS from Table 5.1.3.2-1, TS 38.214 that is greater than or equal to nof_info_prime.
References divide_ceil.
Referenced by get_nof_prbs.
unsigned srsgnb::tbs_calculator_pdsch_calculate(const tbs_calculator_pdsch_configuration &config)
Calculates the TBS for a given PDSCH transmission.
Implemented as per TS38.214 Section 5.1.3.2.
References NOF_SUBCARRIERS_PER_RB, srsgnb::tbs_calculator_pdsch_configuration::nof_symb_sh, srsgnb::tbs_calculator_pdsch_configuration::nof_dmrs_prb, srsgnb::tbs_calculator_pdsch_configuration::nof_oh_prb, srsgnb::tbs_calculator_pdsch_configuration::n_prb, tbs_calculator_pdsch_get_scaling_factor, srsgnb::tbs_calculator_pdsch_configuration::tb_scaling_field, srsgnb::tbs_calculator_pdsch_configuration::tcr, srsgnb::tbs_calculator_pdsch_configuration::modulation_order, srsgnb::tbs_calculator_pdsch_configuration::nof_layers.
Referenced by get_nof_prbs.
constexpr harq_id_t srsgnb::to_harq_id(unsigned h_id)