srslog::metric
Ty srslog::metric< Ty, Name, Units >::value
Value of the metric.
Referenced by srslog::log_formatter::process_element.
static const char* srslog::metric< Ty, Name, Units >::name()
Returns the name of the metric.
Referenced by srslog::log_formatter::process_element.
static const char* srslog::metric< Ty, Name, Units >::units()
Returns the units of the metric.
Referenced by srslog::log_formatter::process_element.
static metric_kind srslog::metric< Ty, Name, Units >::kind()
Returns the formatting kind of the metric.
Referenced by srslog::log_formatter::process_element.