srsgnb::prb_grant
bool srsgnb::prb_grant::alloc_type_0
union srsgnb::prb_grant::alloc_t srsgnb::prb_grant::alloc
srsgnb::prb_grant::prb_grant()=default
Creates an empty interval.
srsgnb::prb_grant::prb_grant(const prb_interval &other) noexcept
Creates a RB grant of allocation type1, i.e. a contiguous range of RBs.
srsgnb::prb_grant::prb_grant(const rbg_bitmap &other) noexcept
Creates a RB grant of allocation type0, i.e. a set of potentially non-contiguous RBGs.
srsgnb::prb_grant::prb_grant(const prb_grant &other) noexcept
Creates a copy of the RB grant.
prb_grant& srsgnb::prb_grant::operator=(const prb_grant &other) noexcept
prb_grant& srsgnb::prb_grant::operator=(const prb_interval &prbs)
prb_grant& srsgnb::prb_grant::operator=(const rbg_bitmap &rbgs)
srsgnb::prb_grant::~prb_grant()
bool srsgnb::prb_grant::is_alloc_type0() const
Checks whether the grant is of type0.
Referenced by is_alloc_type1, rbgs, operator&=.
bool srsgnb::prb_grant::is_alloc_type1() const
Checks whether the grant is of type1.
References is_alloc_type0.
Referenced by prbs.
const rbg_bitmap& srsgnb::prb_grant::rbgs() const
Extracts the RBG bitmap of the grant, in case it is of type0. This function fails if allocation is of type1.
References is_alloc_type0.
rbg_bitmap& srsgnb::prb_grant::rbgs()
const prb_interval& srsgnb::prb_grant::prbs() const
Extracts the PRB interval of the grant, in case it is of type1. This function fails if allocation is of type0.
References is_alloc_type1.
prb_interval& srsgnb::prb_grant::prbs()
prb_grant& srsgnb::prb_grant::operator&=(const prb_interval interv)
Applies to "this" the intersection of "this" with the provided interval.
References is_alloc_type0, srsgnb::bounded_bitset< N, reversed >::size, srsgnb::bounded_bitset< N, reversed >::fill, srsgnb::interval< T >::intersect.