srsgnb::detail::awaiter_memory_storage_t
small_memory_buffer_t<InlineBuffer, alignof(std::max_align_t)> srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::storage
srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::~awaiter_memory_storage_t()
stored_awaiter<Awaitable>* srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::get_storage()
Get stored awaiter object.
void srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::emplace(Awaitable &&a)
Storage Awaitable and respective awaiter.
Referenced by srsgnb::detail::base_coro_frame< detail::promise_of< FunT > >::on_await_call.
void srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::clear()
Clear memory buffer.
Referenced by srsgnb::detail::base_coro_frame< void >::on_await_resume.
stored_awaiter<Awaitable>::awaiter_type& srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::get_awaiter()
Get stored awaiter reference.
Referenced by srsgnb::detail::base_coro_frame< void >::on_await_resume, srsgnb::detail::base_coro_frame< detail::promise_of< FunT > >::on_await_call.
stored_awaiter<Awaitable>::awaitable_type& srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::get_awaitable()
Get stored awaitable reference.
bool srsgnb::detail::awaiter_memory_storage_t< InlineBuffer >::empty() const
Checks whether awaiter is stored in memory buffer.
Referenced by srsgnb::detail::base_coro_frame< void >::is_suspended, srsgnb::detail::coro_frame< FunT >::destroy.