srsgnb::detail::base_coro_frame
using srsgnb::detail::base_coro_frame< Promise >::promise_type = Promise
using srsgnb::detail::base_coro_frame< Promise >::future_type = decltype(std::declval<promise_type>().get_return_object())
Promise& srsgnb::detail::base_coro_frame< Promise >::promise()
Get promise object.
Referenced by srsgnb::base_resumable_procedure< FutureType >::async_return.
const Promise& srsgnb::detail::base_coro_frame< Promise >::promise() const
bool srsgnb::detail::base_coro_frame< Promise >::on_await_call(Awaitable &&awaitable_obj)
called during await operation to save the awaitable/awaiter in mem buffer, and pass resumable as continuation awaitable_obj object that coroutine awaits on true if awaitable is ready and false if the coroutine needs to suspend
Referenced by srsgnb::base_resumable_procedure< FutureType >::async_await.
static base_coro_frame<Promise>* srsgnb::detail::base_coro_frame< Promise >::from_promise(Promise *p)
From promise object, obtain the coroutine frame pointer.
Referenced by srsgnb::coro_handle< promise_type >::from_promise.
void srsgnb::detail::base_coro_frame< Promise >::on_await_suspend(Awaiter &awaiter_obj, std::false_type)
Called on suspension of current coroutine. Two modes are possible depending on the await_suspend return type.
void srsgnb::detail::base_coro_frame< Promise >::on_await_suspend(Awaiter &awaiter_obj, std::true_type)