srsgnb::coro_handle
srsgnb::coro_handle< Promise >::coro_handle()=default
srsgnb::coro_handle< Promise >::coro_handle(detail::base_coro_frame< Promise > *frame_ptr_)
coro_handle<Promise>& srsgnb::coro_handle< Promise >::operator=(detail::base_coro_frame< Promise > *frame_ptr_)
Promise& srsgnb::coro_handle< Promise >::promise()
Get stored promise object.
Referenced by srsgnb::async_task< R >::promise_type::final_awaiter::await_suspend, srsgnb::coro_handle< promise_type >::promise, srsgnb::coro_handle< promise_type >::done.
const Promise& srsgnb::coro_handle< Promise >::promise() const
void srsgnb::coro_handle< Promise >::destroy()
Destroy coroutine frame.
bool srsgnb::coro_handle< Promise >::done() const
Check if coroutine run until final suspension point.
static coro_handle<Promise> srsgnb::coro_handle< Promise >::from_promise(Promise *p)
From promise, extract coroutine handle.