srsgnb::re_pattern
unsigned srsgnb::re_pattern::rb_begin
Resource block where the pattern begins in frequency domain, the range is (0...274).
Referenced by srsgnb::dmrs_type::get_dmrs_pattern, get_inclusion_mask, get_exclusion_mask, srsgnb::re_pattern_list::merge.
unsigned srsgnb::re_pattern::rb_end
Resource block where the pattern ends in frequency domain (excluded), the range is (1...275).
Referenced by srsgnb::dmrs_type::get_dmrs_pattern, get_inclusion_mask, get_exclusion_mask, srsgnb::re_pattern_list::merge.
unsigned srsgnb::re_pattern::rb_stride
Resource block index jump.
Referenced by srsgnb::dmrs_type::get_dmrs_pattern, get_inclusion_mask, get_exclusion_mask, srsgnb::re_pattern_list::merge.
std::array<bool, NRE> srsgnb::re_pattern::re_mask
Resource element mask per resource block. True entries indicate the resource elements affected by the pattern.
Referenced by srsgnb::dmrs_type::get_dmrs_pattern, get_inclusion_mask, get_exclusion_mask, srsgnb::re_pattern_list::merge.
std::array<bool, MAX_NSYMB_PER_SLOT> srsgnb::re_pattern::symbols
Symbol mask. True entries indicate the symbols affected by the pattern.
Referenced by srsgnb::dmrs_type::get_dmrs_pattern, get_inclusion_mask, get_exclusion_mask, srsgnb::re_pattern_list::merge, srsgnb::csi_rs_processor_impl::map.
srsgnb::re_pattern::re_pattern()=default
Default constructor. It allows instantiating the structure without using other constructors.
srsgnb::re_pattern::re_pattern(unsigned rb_begin_, unsigned rb_end_, unsigned rb_stride_, std::array< bool, NRE > re_mask_, std::array< bool, MAX_NSYMB_PER_SLOT > symbols_)
Constructs an RE pattern from parameters.
rb_begin_ Start RB block index. rb_end_ End RB block index (excluded). rb_stride_ RB index jump. re_mask_ RE Mask. symbols_ Symbol mask.
srsgnb::re_pattern::re_pattern(const re_pattern &other)
Copy constructor.
other Provides the reference to other resource element pattern to copy.
void re_pattern::get_inclusion_mask(span< bool > mask, unsigned symbol) const
Include the described resource element pattern in a resource grid symbol mask.
This method sets to true the elements that are described in the pattern for a given symbol index. The mask represents resource elements allocation for a given symbol in a resource grid. mask Provides a mask representing an entire symbol in a resource grid. symbol Indicates the symbol index for the mask to be included. This method expects that the number of elements of mask is equal to or greater than rb_end
References srsgnb::span< T >::size, rb_end, symbols, rb_begin, rb_stride, srsgnb::NRE, re_mask.
Referenced by srsgnb::csi_rs_processor_impl::map.
void re_pattern::get_exclusion_mask(span< bool > mask, unsigned symbol) const
Exclude the described resource element pattern in a resource grid symbol mask.
This method sets to false the elements that are described in the pattern for a given symbol index. The mask represents resource elements allocation for a given symbol in a resource grid. mask Provides a mask representing an entire symbol in a resource grid. symbol Indicates the symbol index for the mask to be excluded. This method expects that the number of elements of mask is equal to or greater than rb_end
References srsgnb::span< T >::size, rb_end, symbols, rb_begin, rb_stride, srsgnb::NRE, re_mask.
Referenced by srsgnb::pdsch_modulator_impl::map_to_contiguous_prb, srsgnb::pdsch_modulator_impl::map_to_prb_other.