srsgnb::timer_manager::timer_handle
timer_manager& srsgnb::timer_manager::timer_handle::parent
const timer_id_t srsgnb::timer_manager::timer_handle::id
Timer identifier. This identifier should remain constant throughout the timer lifetime.
Referenced by srsgnb::unique_timer::id, srsgnb::timer_manager::tick_all.
bool srsgnb::timer_manager::timer_handle::allocated
Whether timer is being used. Writes are protected by backend lock.
std::atomic<uint64_t> srsgnb::timer_manager::timer_handle::state
The current state of timer (e.g. running/expired/stopped) + duratin + timeout Read methods of timer_handle are not mutexed, thus its state updates must be atomic.
Referenced by is_running, has_expired, duration, time_elapsed, srsgnb::timer_manager::tick_all.
unique_function<void(timer_id_t)> srsgnb::timer_manager::timer_handle::callback
Callback triggered when timer expires. Callback updates are protected by backend lock.
Referenced by set, srsgnb::timer_manager::tick_all.
srsgnb::timer_manager::timer_handle::timer_handle(timer_manager &parent, timer_id_t id)
srsgnb::timer_manager::timer_handle::timer_handle(const timer_handle &)=delete
srsgnb::timer_manager::timer_handle::timer_handle(timer_handle &&)=delete
timer_handle& srsgnb::timer_manager::timer_handle::operator=(const timer_handle &)=delete
timer_handle& srsgnb::timer_manager::timer_handle::operator=(timer_handle &&)=delete
srsgnb::timer_manager::timer_handle::~timer_handle()=default
bool srsgnb::timer_manager::timer_handle::is_running() const
Returns true if the timer is currently running, otherwise returns false.
References srsgnb::timer_manager::decode_is_running_flag, state.
Referenced by srsgnb::unique_timer::is_running.
bool srsgnb::timer_manager::timer_handle::has_expired() const
Returns true if the timer has expired, otherwise returns false.
References state.
Referenced by srsgnb::unique_timer::has_expired.
timer_tick_difference_t srsgnb::timer_manager::timer_handle::duration() const
Returns the configured duration for this timer measured in ticks.
References state.
Referenced by is_set, time_elapsed, set, srsgnb::unique_timer::duration.
bool srsgnb::timer_manager::timer_handle::is_set() const
Returns true if the timer duration has been set, otherwise returns false.
References duration.
Referenced by srsgnb::unique_timer::is_set.
timer_tick_difference_t srsgnb::timer_manager::timer_handle::time_elapsed() const
Returns the elapsed time in ticks.
References state, duration, srsgnb::timer_manager::decode_is_running_flag, srsgnb::timer_manager::cur_time.
Referenced by srsgnb::unique_timer::time_elapsed.
void srsgnb::timer_manager::timer_handle::set(timer_tick_difference_t duration)
Configures the duration of the timer.
References duration, srsgnb::timer_manager::mutex.
Referenced by srsgnb::timer_manager::defer_callback, srsgnb::unique_timer::set.
void srsgnb::timer_manager::timer_handle::set(timer_tick_difference_t duration, unique_function< void(timer_id_t)> cb)
Configures the duration of the timer calling the provided callback upon timer expiration.
References duration, srsgnb::timer_manager::mutex, callback.
void srsgnb::timer_manager::timer_handle::run()
Activate the timer to start ticking.
References srsgnb::timer_manager::start_run.
Referenced by srsgnb::timer_manager::defer_callback, srsgnb::unique_timer::run.
void srsgnb::timer_manager::timer_handle::stop()
Stops the timer from ticking. The timer callback is not called.
References srsgnb::timer_manager::stop_timer.
Referenced by srsgnb::unique_timer::stop.
void srsgnb::timer_manager::timer_handle::destroy()
Deallocates the timer from its parent.
References srsgnb::timer_manager::destroy_timer.
Referenced by srsgnb::timer_manager::defer_callback.
void srsgnb::timer_manager::timer_handle::set_impl(timer_tick_difference_t duration)